### ISSUE TITLE
Planned Analysis: Analysis of recurrent fusions

### ISSUE THREAD

**Issue by PichaiRaman** [AlexsLemonade/OpenPBTA-analysis#10]
This should probably be partitioned by cancer type and/or molecular subtype. This could be a **stacked** bar chart (one bar per fusion) for instance with colors representing different cancer types.

**Comment by jharenza** [comment]
Krutika and I would like to work on this analysis. We have already created a workflow for annotating and identifying high-confidence fusions from the two fusion algorithms.

**Comment by jharenza** [comment]
@kgaonkar6 - for this recurrent analysis, we should pay special attention to samples in which we have diagnosis/relapse pairs (#155) or patient/cell line matched data and should separate/plot differently. For example, we can look at cell line results separately (or exclude from this analysis). For patients with more than one RNA sample, I think we should look into how similar/different they are/if this differs by phase of therapy and think about how to describe this data.

**Comment by jharenza** [comment]
@kgaonkar6 - in writing up some comments for @cansavvy for #18, I realize we could use the recurrent fusion list here. Can you possibly create a quick PR to create a **table** of recurrently-fused genes and recurrent fusions by broad cancer type? I think @cansavvy can perhaps start with that for survival analysis.

**Comment by daveagbo733kweku** [comment]
Hi

**Comment by jaclyn-taroni** [comment]
Closing all planned analysis tickets in favor of opening new proposed analysis/updated analysis tickets as needed.
