### ISSUE TITLE
Updated analysis: interaction plots - assess oncogene/TSG co-occurrence/mutual exclusivity

### ISSUE THREAD

**Issue by jharenza** [AlexsLemonade/OpenPBTA-analysis#1001]
#### What analysis module should be updated and why?
interation-plots

We are interested in determining whether:
1. cancer genes co-occur or are mutually exclusive in pediatric brain tumors and if this is true across histologies (eg: if TP53 and H3F3A co-occur in HGAT, do they also co-occur in other histologies?). We may be very limited for this latter point because of our N per group unless we approach this as grouping all histologies together then extracting the specimens and their histologies (as noted below).
2. known cancer genes co-occur with “non” cancer genes

#### What changes need to be made? Please provide enough detail for another participant to make the update.
1. Using the [gene list from fusion-filtering](https://github.com/AlexsLemonade/OpenPBTA-analysis/blob/master/analyses/fusion_filtering/references/genelistreference.txt) as input, rerun the mutational interaction module and export the full results list. 
2. Determine whether any genes annotated as oncogenes/tumor suppressor genes (TSG) co-occur/are mutually exclusive and in what histologies - we could perhaps perform 1. on all samples, then extract the samples making up these groups (eg TP53+oncogene co-occurrence), then create a plot/table based on this data
3. Repeat 2 where only 1/2 genes is an oncogene/TSG

#### What input data should be used? Which data were used in the version being updated?
`pbta-snv-consensus-mutation.maf.tsv.gz` for now to be updated once #819 is completed

#### When do you expect the revised analysis will be completed?
~2 weeks?

#### Who will complete the updated analysis?
someone from CCDL or @kgaonkar6 ?

**Comment by jashapiro** [comment]
With the way the scripts are currently written, there is not currently an option to include a specific gene list for analysis, but that should be straightforward to add as an alternative to the current method, which takes the most mutated N genes (N=50 as currently run). Note that the gene list in fusion-filtering contains ~5000 genes, which will result in 25 million comparisons. The more comparisons we do, the more cautious we have to be about multiple testing. (There is a related issue where different mutation rates among samples can look like cooccurrence.)

As for the sample by mutation plot you are suggesting, would that look a lot essentially like an oncoprint with those genes?

**Comment by jharenza** [comment]
closing this due to time constraints
