### ISSUE TITLE
Updated analysis: Update oncoprint landscape module to use hotspot consensus maf

### ISSUE THREAD

**Issue by cbethell** [AlexsLemonade/OpenPBTA-analysis#1005]
#### What analysis module should be updated and why?

The `oncoprint-landscape` module should be updated to use the hotspot consensus maf file (as noted in https://github.com/AlexsLemonade/OpenPBTA-analysis/issues/968#issue-842260376) once available.

#### What changes need to be made? Please provide enough detail for another participant to make the update.

The `run-oncoprint.sh` script will need to be updated to replace the current `pbta-snv-consensus-mutation.maf.tsv.gz` maf file with the hotspot consensus maf file for implementation, once available.

#### What input data should be used? Which data were used in the version being updated?

`pbta-snv-hotspots-plus-consensus.maf.tsv.gz` (replacing the current `pbta-snv-consensus-mutation.maf.tsv.gz` file being implemented)

#### When do you expect the revised analysis will be completed?

~ 1 day once the hotspot consensus maf file becomes available

#### Who will complete the updated analysis?

Likely @cbethell or someone at the CCDL

**Comment by jharenza** [comment]
Also adding that we should also switch to using the seg file and setting a threshold for amplifications (so gains and amps are not all coded as amp) once #987 is merged

**Comment by jharenza** [comment]
Note: since the consensus and hotspot maf are separate, this would require combining them and removing redundant calls.

**Comment by jharenza** [comment]
closed with #1088
