### ISSUE TITLE
Updated analysis: Neutral region called as losses when compared to ploidy 

### ISSUE THREAD

**Issue by kgaonkar6** [AlexsLemonade/OpenPBTA-analysis#1010]
#### What analysis module should be updated and why?
The CNV analysis specifically 

While creating the consensus seg file in `copy_number_consensus_call` module we bind a df of  *neutral* region in the code here to fill back neutral calls :
https://github.com/AlexsLemonade/OpenPBTA-analysis/blob/84a324790f9cb2848cd9e370832f0f4d0a7610b1/analyses/copy_number_consensus_call/scripts/bed_to_segfile.R#L149-L160

Which adds neutral regions ( that is regions  not called as del/dups in callable region bed) with a copy number = 2 to specify that it is a neutral call. 

However, when we are gathering the status of "loss"," gain" or "neutral" as an intermediate step between the consensus region seg file and gene annotated seg file in `focal-cn-file-preparation` module :
https://github.com/AlexsLemonade/OpenPBTA-analysis/blob/84a324790f9cb2848cd9e370832f0f4d0a7610b1/analyses/focal-cn-file-preparation/01-add-ploidy-cnvkit.Rmd#L43-L52

Along with the actual del/dups we are also comparing the copy number in these *neutral* region which were assigned copy number=2 as part of `copy_number_consensus_call` module. These are now being annotated as "loss" in `focal-cn-file-preparation` when they are compared to 3,4 etc tumor ploidy. I believe the neutral status of these regions should be propagated in `focal-cn-file-preparation` while annotating the region with genes. 

#### What changes need to be made? Please provide enough detail for another participant to make the update.

My suggestions are:

1) Add ploidy as copy number to neutral calls:
Depending on that we are still following this [note on ploidy](https://github.com/AlexsLemonade/OpenPBTA-analysis/blob/master/doc/data-formats.md#a-note-on-ploidy)
Shouldn't the neutral calls that we are back filling in `copy_number_consensus_call` [code](https://github.com/AlexsLemonade/OpenPBTA-analysis/blob/84a324790f9cb2848cd9e370832f0f4d0a7610b1/analyses/copy_number_consensus_call/scripts/bed_to_segfile.R#L149-L160) have copy number == tumor_ploidy to be considered as a copy neutral call instead of 2? 
My understanding is that controlfreec also calls regions as neutral if the copy number== tumor_ploidy for samples >2 ploidy so this would be similar.

2) Add NA as copy number to neutral calls:
In `copy_number_consensus_call` [code](https://github.com/AlexsLemonade/OpenPBTA-analysis/blob/84a324790f9cb2848cd9e370832f0f4d0a7610b1/analyses/copy_number_consensus_call/scripts/bed_to_segfile.R#L149-L160) add copy number ==NA. So that regions with copy.num==NA are removed [here](https://github.com/AlexsLemonade/OpenPBTA-analysis/blob/5201bc951c87852c3b6c38bd7bcaf47b631b3d1f/analyses/focal-cn-file-preparation/02-add-ploidy-consensus.Rmd#L75-L76) before gathering the status of each consensus cnv region. 
Just wanted to note that neutral calls are eventually removed while annotating the region with gene_symbol [here](https://github.com/AlexsLemonade/OpenPBTA-analysis/blob/5201bc951c87852c3b6c38bd7bcaf47b631b3d1f/analyses/focal-cn-file-preparation/03-prepare-cn-file.R#L267-L269) so this would satisfy the condition of removing all neutral calls.

#### What input data should be used? Which data were used in the version being updated?
pbta-cnv-cnvkit.seg.gz
pbta-cnv-controlfreec.tsv.gz
pbta-sv-manta.tsv.gz

#### When do you expect the revised analysis will be completed?
~ 1 day and few days for QC

#### Who will complete the updated analysis?
TBD
tagging @jashapiro @jharenza @jaclyn-taroni  to identify if and how we would want to implement the fixes

**Comment by jharenza** [comment]
I am in favor of 
> Add ploidy as copy number to neutral calls

**Comment by jaclyn-taroni** [comment]
Just popping into say I am going to put the `blocking release` label on this.

**Comment by jaclyn-taroni** [comment]
The discussion so far is missing some important context in my opinion. When we perform the copy number consensus calling, CNVkit copy number = 2 is called as neutral, regardless of whether or not ploidy = 2 as inferred by ControlFreeC. Said a different way: how we handle CNVkit ignores ploidy information. (More background in #501 and some in #486.) 

In the CN consensus module, we require at least two callers (CNVkit, ControlFreeC, and Manta) to agree. So it's possible we are underreporting losses in samples where ControlFreeC-inferred ploidy > 2  because those are "neutral" according to CNVkit. I haven't fully dug into the code for that module, but I assume then that we'd expect cases where we may be underreporting losses would end up in the neutral file where `copy.num = 2` gets assigned in `bed_to_segfile.R`. I suspect that is the rationale for setting things up that way.

All of this to say, an alternative approach would be to include ControlFreeC-inferred ploidy as part of the consensus CN pipeline which is noted in #501.

**Comment by jaclyn-taroni** [comment]
FWIW I like option 2

> Add NA as copy number to neutral calls

because I think it's a better representation of what's happening and the net result is the same.

**Comment by kgaonkar6** [comment]
> The discussion so far is missing some important context in my opinion. When we perform the copy number consensus calling, CNVkit copy number = 2 is called as neutral, regardless of whether or not ploidy = 2 as inferred by ControlFreeC. Said a different way: how we handle CNVkit ignores ploidy information. (More background in #501 and some in #486.)
> 
> In the CN consensus module, we require at least two callers (CNVkit, ControlFreeC, and Manta) to agree. So it's possible we are underreporting losses in samples where ControlFreeC-inferred ploidy > 2 because those are "neutral" according to CNVkit. I haven't fully dug into the code for that module, but I assume then that we'd expect cases where we may be underreporting losses would end up in the neutral file where `copy.num = 2` gets assigned in `bed_to_segfile.R`. I suspect that is the rationale for setting things up that way.
> 
> All of this to say, an alternative approach would be to include ControlFreeC-inferred ploidy as part of the consensus CN pipeline which is noted in #501.

Thanks for bringing this up, I forgot to mention that we would update first make controlfreec copy number as default as we do in #987. So then the underrepresentation of potential losses will be  for calls only called by cnvkit+manta calls. 

Am I thinking this correctly, for tumor samples ploidy >2 a gain occurred in a large portion of the genome so average ploidy increased to say 3, so for regions with copy number 2 the conditions were:
  - after the genome wide gain a loss occurred in that region to now have copy number ==2 ( these regions would be in the criteria of underrepresented losses)
  - OR the region was not involved in any copy number changes and remained in a `neutral` copy number ==2 state 
The only way to find out the events would be with allele specific copy number analysis which is out of the scope of this paper. 

Structural variants are so complicated haha, let me know what would be a good option to update.

**Comment by jharenza** [comment]
@jaclyn-taroni and @kgaonkar6 thanks for the detailed explanations! I think having that context of CNVkit calls is good and I am on board with using NA to denote the neutral changes and using the controlfreec CN as default as noted in #987. Let's see how that works!

**Comment by jaclyn-taroni** [comment]
> Thanks for bringing this up, I forgot to mention that we would update first make controlfreec copy number as default as we do in #987. So then the underrepresentation of potential losses will be for calls only called by cnvkit+manta calls.

You've spent more time with this code/module than I have recently, but my understanding is that `analyses/copy_number_consensus_call/scripts/bed_to_segfile.R` has separate arguments for a CNV file and neutral file and using ControlFreeC as the default will only impact the former. I expect the CNV file only has alterations in it, so you could potentially have false negatives that arise because CNVkit doesn't take into account ploidy that are in the neutral file instead of the CNV file? 

I think you're correct that we'd be most concerned about calls that are only called by CNVkit and Manta (and I don't really know much about Manta to comment on whether or not "ignoring" ploidy matters). I agree with your points about tumor samples with ploidy > 2. All good things to note as potential limitations.

All that being said:

>  I think having that context of CNVkit calls is good and I am on board with using NA to denote the neutral changes and using the controlfreec CN as default as noted in #987. Let's see how that works!

Sounds good to me. 

It's still not clear to me whether or not CNVkit and ControlFreeC _tend to agree_ in their copy number values or if one method tends to be better at estimating copy number from WGS data. It may be the case that setting neutral region copy number values to NA and other downstream choices in `focal-cn-preparation` are more impactful.

**Comment by kgaonkar6** [comment]
@jharenza @jaclyn-taroni  
I compared the following 4 versions of gene annotated consensus cnv calls:
1) NA to denote the neutral changes and using the controlfreec CN as default [here](https://github.com/kgaonkar6/OpenPBTA-analysis/tree/focal-cn-update/analyses/focal-cn-file-preparation)
2) v18 release which denotes neutral changes as 2 and cnvkit as default calls[here](https://github.com/kgaonkar6/OpenPBTA-analysis/tree/master/analyses/focal-cn-file-preparation)
3) cotrolfreec original seg file
4) cnvkit seg file
[change_log.txt](https://github.com/AlexsLemonade/OpenPBTA-analysis/files/6359203/change_log.txt)

Are main interest is to check changes between 1 and 2, here I'm presenting a change in the status and as we see most losses are changed to gains because controlfreec is used as the default copy number
![image](https://user-images.githubusercontent.com/34580719/115733154-a07d1900-a356-11eb-8626-6e0f45644c28.png)

The below plots are simple tile plots for PNOC003 samples and a specific gene list ( we used this subset for simplicity). The `NA` status are actually statuses found in other versions of the gene annotated cnv calls. 

This plot represents calls from the point `1` which is the consensus cnv calls updated to use controlfreec as default and neutral calls have copy number set to `NA`.
status =NA here represents that this gene+sample_id has a non -neutral call in 2,3 or 4 versions.
![image](https://user-images.githubusercontent.com/34580719/115735578-978d4700-a358-11eb-8dcd-0522735dc0c7.png)

This plot represents the v18 release of the consensus cnv calls point `2` which used cnvkit as default and neutral calls had copy number as 2.
status =NA here represents that this gene+sample_id has a non -neutral call in 1,3 or 4 versions.
![image](https://user-images.githubusercontent.com/34580719/115735695-ad027100-a358-11eb-976f-b679ea782650.png)

This plot represents controlfreec original calls point `3`.
status =NA here represents that this gene+sample_id has a non -neutral call in 1,2 or 4 versions.
![image](https://user-images.githubusercontent.com/34580719/115735713-b25fbb80-a358-11eb-96f2-4b6c18155585.png)

This plot represents cnvkit original calls point `4`
status =NA here represents that this gene+sample_id has a non -neutral call in 1,2 or 3 versions.
![image](https://user-images.githubusercontent.com/34580719/115735734-b68bd900-a358-11eb-8bb6-8e32aa1888c6.png)

My understanding from this plot is:
- looks overall cnvkit and controlfreec plots don't agree with each other, that might be because controlfreec uses the ploidy info so the status are accurately gathered but for cnvkit ( which ignores ploidy) the status might be misleading
- the latest update of using neutral calls as NA is the main force behind removing the majority of losses we see in the v18 release. I had previous compared just using controlfreec as default and cnvkit as default and the changes were not that drastic `latest` here is the controlfreec as input and `previous` is the v18 release which used cnvkit as default.
[compare-cn-freec-cnvkit.pdf](https://github.com/AlexsLemonade/OpenPBTA-analysis/files/6359312/compare-cn-freec-cnvkit.pdf)

**Comment by jharenza** [comment]
@kgaonkar6 this is great! It looks like using copy number = NA and ControlFreeC as default CN gives us the cleanest/least artifact-y plots. 

@jaclyn-taroni we also did some internal checking by recoding the PNOC samples using the IDs in the manuscript and found that using number 1 above does give us the CNVs as expected from clinical sequencing. We did this using the consensus seg files (autosomes + sex chr files in order to assess ATRX) and I think that we can now switch the oncoprint back to using the consensus seg file (since the focal files do not have sex chr included - I will add a ticket for that). Therefore, I think we should move forward with number 1.

**Comment by jashapiro** [comment]
Do you have a comparison with what I might call 1b: Leaving  the neutral regions to NA but leaving CNVkit as the default for the CN quantification? I honestly don’t remember exactly why we chose CNVkit as the default for CN, but I feel like it was recommended as the most reliable. Which might not be right!

**Comment by kgaonkar6** [comment]
@jharenza @jashapiro @jaclyn-taroni  In this plot I've reduced the gene list for simplicity and comparing Freec+neutral calls as NA, CNVkit +neutral calls as NA , and V18 release:
![image](https://user-images.githubusercontent.com/34580719/117028631-e5e10500-accb-11eb-92d7-9a2a49497138.png)

status =NA here represents that this gene+sample_id has a non -neutral call in v18 versions.

The main changes between using controlfreec and cnvkit can be seen for the following samples:
**P-02**
1 ) P-02 has a MET gain (published data has MET gain for P-02 ) captured using controlfreec in both P-02 samples (BS_3Z40EZHD and BS_JRFVST47 ) but cnvkit only reported it in 1 (BS_3Z40EZHD) 
2 ) P-02 has a IGF1R gain captured using controlfreec in both P-02 samples (BS_3Z40EZHD and BS_JRFVST47 ) but not cnvkit only reported it in 1 (BS_3Z40EZHD)
3) KIT,KDR and PDGFRA have amplifications in P-02(BS_JRFVST47) in controlfreec but in cnvkit has gains, and for another P-02 sample (BS_3Z40EZHD) cnvkit has amplification and controlfreec has gains 

**P-18**
1) P-18  has EGFR and MET gains captured in both P-18 samples (BS_CBMAWSAR and BS_ZSH09N84 ) in controlfreec but cnvkit reported it in only 1 sample (BS_ZSH09N84)

It seems controlfreec is consistently capturing the same copy changes in the multiple samples per PNOC samples but cnvkit misses out the CNVs in 1 of the 2 samples available here for P-02 and P-18.

**Comment by kgaonkar6** [comment]
Here I'm comparing ( consensus_seg_annotated_cn_autosomes.tsv.gz + consensus_seg_annotated_cn_x_and_y.tsv.gz ) from the following versions of the files
- controlfreec (default for copy number ) + neutral calls as NA
- cnvkit (default for copy number) + neutral calls as NA
- and v18 release 
![image](https://user-images.githubusercontent.com/34580719/117039107-64db3b00-acd6-11eb-97e2-247cb7875451.png)

The changes between using controlfreec and cnvkit are mainly as follows:
- BS_ZSH09N84 and BS_CBMAWSAR are initial samples from the same participant PT_MNSEJCDM, controlfreec calls EGFR and MET gains in both samples, cnvkit only calls in BS_ZSH09N84
- BS_JRFVST47 and BS_3Z40EZHD are initial samples for PT_9GKVQ9QS, controlfreec calls MET gain in both samples , cnvkit only calls for BS_3Z40EZHD
- Other than the above calls being missed, we also see some copy change level changes in KIT,KDR and PDGFRA calls where ,controlfree calls amplification for BS_JRFVST47 and cnvkit shows as gains; for BS_3Z40EZHD cnvkit shows as amplification and controlfreec shows as gains.

My underdstanding is controlfreec helps identifying consistent calls for multiple samples from the same participant ids where as cnvkit seems to be missing the call for 1 of the 2 multiple samples in the participants mentioned above.

**Comment by jharenza** [comment]
I think it is also important to note here that these samples had clinical sequencing performed and the below option has captured these calls more accurately (as noted above when @kgaonkar6 mentions certain calls being missed.
>controlfreec (default for copy number ) + neutral calls as NA

This being said, I think we should go with the above.

**Comment by jharenza** [comment]
@jaclyn-taroni are you ok with using the above?
>controlfreec (default for copy number ) + neutral calls as NA

**Comment by jaclyn-taroni** [comment]
> @jaclyn-taroni are you ok with using the above?
> 
> > controlfreec (default for copy number ) + neutral calls as NA

Yes, seems reasonable

**Comment by jharenza** [comment]
great, thanks. I think we will start merging @kgaonkar6's PRs [here](https://github.com/kgaonkar6/OpenPBTA-analysis/pulls) in that case, so we can get back to #987

**Comment by jharenza** [comment]
Closed with #1066
