### ISSUE TITLE
How were "Panel" experimental strategy samples processed? 

### ISSUE THREAD

**Issue by cansav09** [AlexsLemonade/OpenPBTA-analysis#102]
#### File(s)

`pbta-histologies.tsv` and to a lesser extent, `pbta-snv-strelka2.vep.maf.gz`

#### Release

release-v2-20190809

#### Link to [OpenPBTA-manuscript](https://github.com/AlexsLemonade/OpenPBTA-manuscript/)

[The methods section about data generation](https://github.com/AlexsLemonade/OpenPBTA-manuscript/blob/master/content/03.methods.md#data-generation) is where I would have expected to see information about the "Panel" samples.

#### Question/issue

What does it mean in `pbta-histologies.tsv` when an experimental strategy is "Panel"?

For the entire set of metadata, there appears to be only two samples that are called "Panel". Here is their information: 

Kids_First_Biospecimen_ID | Kids_First_Participant_ID | experimental_strategy | sample_type | composition | tumor_descriptor
-- | -- | -- | -- | -- | --
BS_7KR13R3P | PT_V1HNAC2Q | Panel | Tumor | Solid Tissue | Diagnosis
BS_WHZT48VG | PT_V1HNAC2Q | Panel | Normal | Peripheral Whole Blood | NA

More specifically, there is only one tumor sample in the Strelka2 data that is noted as using this strategy: `BS_7KR13R3P`. The rest of the samples in the Strelka2 data are noted as "WGS" and "WES" which is what I would have expected for all the samples. 

What does "Panel" mean regarding these samples? Is it incorrectly labeled? If the experimental strategy for these two samples is actually different, should it be discarded from the data in general?

**Comment by jharenza** [comment]
@cansav09 thanks for pointing this out - yes, for this one sample, they did not have enough DNA for WES/WGS, so TGEN ran a panel. I will double check, but I think it was run using the WES pipeline and we have to note that in the methods. I created a [ticket](https://github.com/AlexsLemonade/OpenPBTA-manuscript/issues/41) to add this to the manuscript.

**Comment by cansav09** [comment]
So I think I will go ahead remove these from most of my analyses since I'm not sure how to compare it to the others.

**Comment by jharenza** [comment]
Confirmed the panel alignment used the same bed regions as WES, and will have this updated in the methods this sprint.

**Comment by jharenza** [comment]
Updated with PRs in manuscript [here](https://github.com/AlexsLemonade/OpenPBTA-manuscript/pull/46) and [here](https://github.com/AlexsLemonade/OpenPBTA-manuscript/pull/47)
