### ISSUE TITLE
Update CNS_region for HGG

### ISSUE THREAD

**Issue by jharenza** [AlexsLemonade/OpenPBTA-analysis#1025]
#### What data file(s) does this issue pertain to?
`pbta-histologies.tsv`

#### What release are you using?

v18

#### Put a link to the relevant section of the [OpenPBTA-manuscript](https://github.com/AlexsLemonade/OpenPBTA-manuscript/) here.
NA

#### Put your question or report your issue here.
Cassie Kline had done some internal review of pathology reports to update HGG `CNS_regions`, and we will capture these in #867 histologies file. See attached review.
[CNS_region_review_HGG_CK_update.txt](https://github.com/AlexsLemonade/OpenPBTA-analysis/files/6367919/CNS_region_review_HGG_CK_update.txt)

**Comment by kgaonkar6** [comment]
closing since this is updated in base histology creation step https://github.com/d3b-center/D3b-codes/blob/6fd75ef9f870172299ab6ce9dd014d0ecf882fb1/OpenPBTA_v19_20210423/review_updates.Rmd
