### ISSUE TITLE
vardict and lancet variant calls on deck

### ISSUE THREAD

**Issue by jharenza** [AlexsLemonade/OpenPBTA-analysis#103]
#### File(s)

_What data file(s) does this issue pertain to?_

#### Release

_What release are you using?_

#### Link to [OpenPBTA-manuscript](https://github.com/AlexsLemonade/OpenPBTA-manuscript/)

_Put a link to the relevant section of the OpenPBTA manuscript here._

#### Question/issue

_Put your question or report your issue here._
We are currently generating lancet and vardict calls and will release in V5

**Comment by jharenza** [comment]
update on this - we have vardict completed and annotated and 100 more samples to run through lancet + annotation - will have these for v5 release on 09/24/19

**Comment by jaclyn-taroni** [comment]
@jharenza was this closed via #127?

**Comment by jharenza** [comment]
> @jharenza was this closed via #127?

yup, closed!
