### ISSUE TITLE
Updated analysis: molecular subtyping HGG TP53 annotation

### ISSUE THREAD

**Issue by kgaonkar6** [AlexsLemonade/OpenPBTA-analysis#1034]
#### What analysis module should be updated and why?
`10-HGG-TP53-annotation.Rmd` is not added to run script in `molecular_subtyping_HGG`

#### What changes need to be made? Please provide enough detail for another participant to make the update.
just add to run script

```
# Add TP53 annotation
Rscript -e "rmarkdown::render('10-HGG-TP53-annotation.Rmd',clean=TRUE)"
```

#### What input data should be used? Which data were used in the version being updated?
pbta-histologies-base.tsv
pbta-snv-consensus-mutation.maf.tsv.gz
analyses/focal-cn-preparation/results/cnvkit_annotated_cn_autosomes.tsv.gz
analyses/fusion_filyering/results/pbta-fusion-putative-oncogenic.tsv
pbta-cnv-consensus-gistic.zip
analyses/collapse-rnaseq/results/pbta-gene-expression-rsem-fpkm-collapsed.stranded.rds
analyses/collapse-rnaseq/results/pbta-gene-expression-rsem-fpkm-collapsed.polya.rds
analyses/tp53_nf1_score/results/tp53_alteration_status.tsv

#### When do you expect the revised analysis will be completed?
~1/2 day

#### Who will complete the updated analysis?
@kgaonkar6

**Comment by jharenza** [comment]
closed via #1036
