### ISSUE TITLE
Updated analysis: molecular subtyping TP53 scoring to run with base histology file

### ISSUE THREAD

**Issue by kgaonkar6** [AlexsLemonade/OpenPBTA-analysis#1035]
#### What analysis module should be updated and why?
The `tp53_nf1_score` is not updated to be run as part of base subtyping using `pbta-histologies-base.tsv` 
These updates are necessary  for v19 release mainly because of the 2 PNOC sample_id updates which need to propagated to the tp53_nf1_score module if we don’t there will be duplicate subtypes because of incorrectly matched samples for those 2 PNOC samples like we see here:

Kids_First_Biospecimen_ID | Kids_First_Participant_ID | molecular_subtype | integrated_diagnosis
-- | -- | -- | --
BS_P7VR731D | PT_W5GP3F6B | DMG, H3 K28, TP53 loss | Diffuse midline glioma, H3 K28-mutant
BS_P7VR731D | PT_W5GP3F6B | DMG, H3 K28 | Diffuse midline glioma, H3 K28-mutant
BS_QZPGVNBB | PT_RYMG3M91 | DMG, H3 K28, TP53 loss | Diffuse midline glioma, H3 K28-mutant
BS_QZPGVNBB | PT_RYMG3M91 | DMG, H3 K28 | Diffuse midline glioma, H3 K28-mutant

#### What changes need to be made? Please provide enough detail for another participant to make the update.
`analyses/tp53_nf1_score/run_classifier.sh` needs to be updated to have a logic to use base histology when running for subtyping.

#### What input data should be used? Which data were used in the version being updated?
pbta-histologies-base.tsv if running for base subtyping
pbta-histologies.tsv if running otherwise

#### When do you expect the revised analysis will be completed?
~ 1/2 day

#### Who will complete the updated analysis?
@kgaonkar6

**Comment by jharenza** [comment]
closed with #1037
