### ISSUE TITLE
Missing README files in v4

### ISSUE THREAD

**Issue by jashapiro** [AlexsLemonade/OpenPBTA-analysis#105]
#### File(s)

README.md
release-notes.md

#### Release

release-v4-20190909

#### Question/issue

This file does not seem to be present in the S3 bucket at the location specified in `download-data.sh`. Note that the script refers to `release-notes.md`, but the [release notes](https://github.com/AlexsLemonade/OpenPBTA-analysis/blob/e6c94842afd760d2c168bdb558f105eb79768c90/doc/release-notes.md#release-v4-20190909)  suggest it may be named `README.md`. Neither seems to be present, however.

**Comment by jharenza** [comment]
@yuankunzhu

**Comment by yuankunzhu** [comment]
Hi @jashapiro, we have the `CHANGELOG.md` instead of `release-notes.md`, but you are right, there's no README.md in the release-folder. We draft it in the folder structure to follow @cgreene suggestion at #2, but i guess we can remove it as we never compose one.

**Comment by jaclyn-taroni** [comment]
Closed via #107
