### ISSUE TITLE
Proposed Analysis: Compile molecular-subtype+pathology and clinical feedback + pathology_free_text_diagnosis subtypes to a file

### ISSUE THREAD

**Issue by kgaonkar6** [AlexsLemonade/OpenPBTA-analysis#1061]
#### What are the scientific goals of the analysis?
Combine pathology_free_text_diagnosis base subtyping with the existing compiled subtype results to be used as input for `molecular-subtype-integrate`. Tagging @jharenza @jaclyn-taroni for inputs to combined the pathology_free_text_diagnosis updates to `compiled_molecular_subtypes_with_clinical_pathology_feedback_and_report_info.tsv`

#### What methods do you plan to use to accomplish the scientific goals?

For v19 we already had created `analyses/molecular-subtyping-pathology/results/compiled_molecular_subtypes_with_clinical_pathology_feedback_and_report_info.tsv` to include pathology-free-text-diagnosis based meningioma  subtypes in input for `molecular-subtype-integrate`

To me looks like there are 2 types of updates

1. The following subtypes can be directly added to 'analyses/molecular-subtyping-pathology/results/compiled_molecular_subtypes_with_clinical_pathology_feedback_and_report_info.tsv` as well since these subtypes don't have molecular-subtyping results:

File | Logic to include as results |  Description ticket 
 -- | -- | -- 
analyses/molecular-subtyping-pathology/results/cns-lymphoma-subtypes.tsv | Append | #1057  
analyses/molecular-subtyping-pathology/results/juvenile-xanthogranuloma-subtypes.tsv | Append | #1056 
analyses/molecular-subtyping-pathology/results/choroid_plexus_papilloma_subtypes.tsv  | Append | #1065

2. The samples in the files below have molecular-subtyping results which are already part of the compile file `analyses/molecular-subtyping-pathology/results/compiled_molecular_subtypes_with_clinical_pathology_feedback_and_report_info.tsv` so we would have to incorporate some logic to merge these samples correctly. 

File | Logic to include as results | Previous subtype | Description ticket 
-- | -- | -- | -- 
analyses/molecular-subtyping-pathology/results/lgat-pathology-free-text-subtypes.tsv #1060  | Replace existing values | LGAT | #1000 
analyses/molecular-subtyping-pathology/results/cranio_adam_subtypes.tsv #823  | Replace existing values | CRANIO | #994
analyses/molecular-subtyping-pathology/results/glialneuronal_tumor_subtypes.tsv  | Replace existing values | LGAT | #1017 

#### What input data are required for this analysis?
 molecular-subtype+pathology and clinical feedback + pathology_free_text_diagnosis subtypes from molecular-subtyping-* modules in OpenPBTA

#### How long do you expect is needed to complete the analysis? Will it be a multi-step analysis?
~ 1-2 days 
I believe it can be a 2 step process
- code to replace the existing subtypes after 01-compile-subtyping-results.Rmd
- code to add all other histologies from point 1 above after 03-incorporate-pathology-feedback.Rmd

**Comment by jharenza** [comment]
@kgaonkar6 I think this sounds logical, but to maintain consistency, we probably should pull meningioma out of a direct add to `analyses/molecular-subtyping-pathology/results/compiled_molecular_subtypes_with_clinical_pathology_feedback_and_report_info.tsv` and put it in step 1 here.

**Comment by jharenza** [comment]
closed with #1084
