### ISSUE TITLE
Updated analysis: tp53-nf1-score with hotspot mafs and updated consensus cnv calls

### ISSUE THREAD

**Issue by kgaonkar6** [AlexsLemonade/OpenPBTA-analysis#1072]
#### What analysis module should be updated and why?
This needs to be updated with hotspot maf + consensus maf calls to gather all TP53 hotspot + consensus calls for DNA samples for annotation.
Updated consensus cnv methods will also affect the TP53 alteration annotation and so should be re-run and reviewed.

#### What changes need to be made? Please provide enough detail for another participant to make the update.
 - add bind(consensus_maf),hotspot_maf) %>% unique() to gather all TP53 snvs and indels which are hotspots or called by all 3 callers
- add code in bash script to gather most up-to-date consensus seg file with status 
Rscript -e "rmarkdown::render('../focal-cn-file-preparation/02-add-ploidy-consensus.Rmd', clean = TRUE)"
cp ${scratch_dir}/consensus_seg_with_status.tsv ${analysis_dir}/input/consensus_seg_with_status.tsv

#### What input data should be used? Which data were used in the version being updated?
data/pbta-snv-consensus-mutation.maf.tsv.gz
analyses/hotspots-detection/results/pbta-snv-scavenged-hotspots.maf.tsv.gz
consensus_seg_with_status.tsv ( this file is being saved in scratch from `02-add-ploidy-consensus.Rmd` in focal-cn-file-preparation

#### When do you expect the revised analysis will be completed?
~ 1 day

#### Who will complete the updated analysis?
@kgaonkar6

**Comment by jharenza** [comment]
closed with #1073
