### ISSUE TITLE
Updated analysis: LGAT integrated dx for ganglioglioma

### ISSUE THREAD

**Issue by jharenza** [AlexsLemonade/OpenPBTA-analysis#1074]
#### What analysis module should be updated and why?
molecular-subtyping-lgat
Ganglioglioma diagnoses are not captured in integrated dx

#### What changes need to be made? Please provide enough detail for another participant to make the update.
Recode `integrated_diagnosis` for samples with `pathology_diagnosis == "Ganglioglioma"` to become `Ganglioglioma, subtype` rather than `Low-grade glioma/astrocytoma, subtype` to be consistent with new pathology free text subtyping.

#### What input data should be used? Which data were used in the version being updated?
v19, histologies file

#### When do you expect the revised analysis will be completed?
tomorrow or monday

#### Who will complete the updated analysis?
@kgaonkar6

**Comment by kgaonkar6** [comment]
Closing with #1078
