### ISSUE TITLE
Updated analysis: add glialneuronal tumors back to LGAT subtyping

### ISSUE THREAD

**Issue by jharenza** [AlexsLemonade/OpenPBTA-analysis#1086]
#### What analysis module should be updated and why?
molecular-subtyping-LGAT

#### What changes need to be made? Please provide enough detail for another participant to make the update.
revert the glialneuronal tumor removal #1014 , but reannotate these at the end of the module as per [this discussion](https://github.com/AlexsLemonade/OpenPBTA-analysis/pull/1078#pullrequestreview-667309287). We would recode `molecular_subtype, == GNT, subtype`, instead of `LGG, subtype` and update the integrated_diagnosis with the appropriate tumor type. 

This will enable us to keep the subtyping, which should be the same as LGAT subtyping, for these tumors.

#### What input data should be used? Which data were used in the version being updated?
same as currently used

#### When do you expect the revised analysis will be completed?
this week?

#### Who will complete the updated analysis?
@kgaonkar6

**Comment by kgaonkar6** [comment]
Just wanted to mention here that molecular-subtyping-pathology will also need an update to recode for glialneuronal tumor 
 samples. Specifically this code which adds the intgerated_diagnosis for LGG samples:
https://github.com/AlexsLemonade/OpenPBTA-analysis/blob/c0744576ee80914636443b01012168efc2da22a9/analyses/molecular-subtyping-pathology/01-compile-subtyping-results.Rmd#L223-L239

**Comment by jharenza** [comment]
closed with #1097
