### ISSUE TITLE
Updated analysis: pathology feedback for BS_H1XPVS9A needs update 

### ISSUE THREAD

**Issue by kgaonkar6** [AlexsLemonade/OpenPBTA-analysis#1093]
#### What analysis module should be updated and why?
In #1000 we updated the LGAT samples to incorporate the pathology_free_text_diagnosis in integrated_diagnosis. Which should also be updated in the pathology_feedback script for BS_H1XPVS9A which is a PXA

> Pathology confirmed this HGG BRAF V600E mutant tumor, `BS_H1XPVS9A`to be a LGAT (PXA). I updated `molecular_subtype` here based on what it would look like, but this should come through via the LGAT [subtyping](https://github.com/AlexsLemonade/OpenPBTA-analysis/issues/631) ticket.

#### What changes need to be made? Please provide enough detail for another participant to make the update.
Currently the 
integrated_diagnosis  is "Low-grade glioma/astrocytoma, BRAF V600E"
https://github.com/AlexsLemonade/OpenPBTA-analysis/blob/a9f4101d7c8c9cbc181bdbac8359177e28b81b8f/analyses/molecular-subtyping-pathology/03-incorporate-pathology-feedback.Rmd#L179-L225

But should be "Pleomorphic xanthoastrocytoma, BRAF V600E" now

#### What input data should be used? Which data were used in the version being updated?
pbta-histologies-base.tsv

#### When do you expect the revised analysis will be completed?
1/2 day

#### Who will complete the updated analysis?
@kgaonkar6

**Comment by jharenza** [comment]
updated in #1111
