### ISSUE TITLE
Updated analysis: CNV deep deletions

### ISSUE THREAD

**Issue by kgaonkar6** [AlexsLemonade/OpenPBTA-analysis#1099]
#### What analysis module should be updated and why?
update focal-cn-file-preparation
and
rerun ocnoprint-landscape

#### What changes need to be made? Please provide enough detail for another participant to make the update.
Change:
https://github.com/AlexsLemonade/OpenPBTA-analysis/blob/6bf301eea42a7f8812c3b14cee35a961097f8ecf/analyses/focal-cn-file-preparation/04-prepare-cn-file.R#L240-L247

To:
```

# Merge and annotated no X&Y
autosome_annotated_cn <- process_annotate_overlaps(cnv_df = cnv_no_xy,
                                                   txdb_exons = tx_exons) %>%
  # mark possible amplifications and deep loss in autosomes
  dplyr::mutate(status = dplyr::case_when(
    copy_number > (2 * ploidy) ~ "amplification",
    copy_number == 0  ~ "deep loss",
    TRUE ~ status
  ))

```
Change:
https://github.com/AlexsLemonade/OpenPBTA-analysis/blob/6bf301eea42a7f8812c3b14cee35a961097f8ecf/analyses/focal-cn-file-preparation/04-prepare-cn-file.R#L265-L267

To:
```
  sex_chrom_annotated_cn <- process_annotate_overlaps(cnv_df = cnv_sex_chrom,
                                                      txdb_exons = tx_exons) %>%
  # mark possible deep loss in sex chromosome
  dplyr::mutate(status = case_when(
    copy_number == 0  ~ "deep loss",
   TRUE ~ status
  ))
```

#### What input data should be used? Which data were used in the version being updated?
pbta-cnv-consensus.seg.gz v19

#### When do you expect the revised analysis will be completed?
~1 day

#### Who will complete the updated analysis?
@kgaonkar6 

cc @jharenza @jaclyn-taroni  for input

**Comment by jharenza** [comment]
closed with #1101
