### ISSUE TITLE
Planned Analysis: Cosmic Mutational Signatures

### ISSUE THREAD

**Issue by PichaiRaman** [AlexsLemonade/OpenPBTA-analysis#11]
Characterize PBTA with COSMIC Mutational Signatures and correlate back to cancer type, genetic lesions, and pathway activity. Visualization of this would be important as well.

**Comment by jharenza** [comment]
Though in pediatric cancers, these should not be as prevalent, could also consider environmental signatures as reported [here](https://www.cell.com/cell/pdf/S0092-8674(19)30263-6.pdf).

**Comment by cansav09** [comment]
Since I've been getting more comfortable with the variant data, I can also work on setting this analysis up.

**Comment by jharenza** [comment]
@cansav09 great! I have used the [deconstructSigs](https://github.com/raerose01/deconstructSigs) package - super easy and will calculate signatures for each sample individually (some algorithms only look across a group and those are less informative). There are some newer COSMIC signatures with the latest COSMIC release, but I have not had a chance to look into those at all. Can definitely help with feedback along the way!

**Comment by cansav09** [comment]
@jharenza, thanks for that recommendation I will look into it. Meanwhile, if you wanna see how I’m comparing our data to the COSMIC mutations for the first and admittedly rough pass, you can take a look at the documentation I’ve prepared on PR 114.

**Comment by cansavvy** [comment]
So I have mutational signature information for all the samples and made a graph for each sample,  but how would we like this information presented overall?  (Since looking over ~980 graphs is not practical.) How do we feel about something like the graph in [Alexandrov et al, 2018](https://www.biorxiv.org/content/10.1101/322859v2)? In our case we would have the signatures as rows and the histology as columns, then report the median weight for each histology's  signatures as reported by `deconstructSigs::whichSignatures`? 
![Screen Shot 2019-11-04 at 9 30 36 AM](https://user-images.githubusercontent.com/23458084/68128949-af63d780-fee6-11e9-8a10-c68a907dc27a.png)

**Comment by cansavvy** [comment]
Then when we have molecular subtype information we could make a version with that information instead of the histology?

**Comment by cansavvy** [comment]
We can also present the data like this: ![Screen Shot 2019-11-04 at 9 45 17 AM](https://user-images.githubusercontent.com/23458084/68129597-d4a51580-fee7-11e9-8b71-9e0a25f23cb6.png)

**Comment by jaclyn-taroni** [comment]
I think we'll want to do both kinds of charts you've put here @cansavvy. The stacked bar plots contain information about individual tumors, but I often find the _overall picture_ hard to digest when there are many signatures contributing.

**Comment by jharenza** [comment]
I like them both as well!

**Comment by cgreene** [comment]
Agree 💯

**Comment by cansavvy** [comment]
What kind of information should I use for a "proposed etiology" column? I don't think we want to keep the same ones? Or do we want to drop that column all together? Here are some drafts of the plots. Let me know what you think. I will have these made for both COSMIC and Alexandrov et al, 2013 Nature signatures. 

This one is for COSMIC for now. 
![Screen Shot 2019-11-04 at 3 56 07 PM](https://user-images.githubusercontent.com/23458084/68212608-db935d00-ffa7-11e9-9c5b-46ab605c449d.png)

I have one of these kinds of plots for each category of `short_histology`. Let me know if we prefer another category instead. 

![barplot_CNS neuroblastoma_cosmic_mutation_sig](https://user-images.githubusercontent.com/23458084/68212854-63796700-ffa8-11e9-9783-b79c445db6f8.png)

I also have mutation signature plots for each sample, but I think this is less useful but I can drop them into a folder somewhere for peoples' reference if that would be useful.

**Comment by jaclyn-taroni** [comment]
For the bubble heatmap, can we make the size of the points the proportion of the tumors with the signature so it's not telling us about sample size? 

For the stacked bar plot - should we try restricting this to primary tumors using the `independent-specimens` list? You can imagine a situation where two samples from the same participant at different points (`tumor_descriptor`) show the same pattern and it could be misleading.

**Comment by cansavvy** [comment]
I am unsure if I am calculating the number of signature mutations for each sample correctly. [`deconstructSigs::whichSignatures`](https://www.rdocumentation.org/packages/deconstructSigs/versions/1.8.0/topics/whichSignatures) doesn't supply this directly, but supplies `weights`. The weights appear to be a rough proportion of the sample's mutations that align with that signature. So I've been multiplying that proportion back to the sample's total signature mutations as provided by [`deconstructSigs::mut.to.sigs.input`](https://www.rdocumentation.org/packages/deconstructSigs/versions/1.8.0/topics/mut.to.sigs.input). Is this right? Or is there a better way?

**Comment by cansavvy** [comment]
This analysis has mainly been addressed, but will any of it need to be updated when we have all the molecular subtyping labels? If so I will create a new issue for that.

**Comment by cansavvy** [comment]
I think we can close this issue then. I don't *think* it needs further analyses after molecular sub-typing comes in but I don't know.

**Comment by jaclyn-taroni** [comment]
This analysis can be found in [`analyses/mutational-signature`](https://github.com/AlexsLemonade/OpenPBTA-analysis/tree/09477cafa880856de001f4844aec39fb61c73f5e/analyses/mutational-signatures).

**Comment by jharenza** [comment]
@cansavvy and @jaclyn-taroni - [this](https://twitter.com/serenanikzainal/status/1229463472041123841?s=12) is a recent tweetorial of new twist on mutational signatures.
