### ISSUE TITLE
Updated analysis: amplification in XY chr

### ISSUE THREAD

**Issue by kgaonkar6** [AlexsLemonade/OpenPBTA-analysis#1102]
#### What analysis module should be updated and why?
focal-cn-file-preparation to add a condition to annotate `status` as amplification in genes on XY chr

#### What changes need to be made? Please provide enough detail for another participant to make the update.
We are adding "deep loss" status in #1101  so including the changes proposed in that ticket we will update:
https://github.com/AlexsLemonade/OpenPBTA-analysis/blob/6bf301eea42a7f8812c3b14cee35a961097f8ecf/analyses/focal-cn-file-preparation/04-prepare-cn-file.R#L265-L267

to:
```
sex_chrom_annotated_cn <- process_annotate_overlaps(cnv_df = cnv_sex_chrom, 
                                                     txdb_exons = tx_exons)  %>% 
dplyr::mutate(status = dplyr::case_when(
    copy_number > (2 * ploidy) ~ "amplification",
    copy_number == 0  ~ "deep loss",
    TRUE ~ status
  ))
```
                                                  
#### What input data should be used? Which data were used in the version being updated?

pbta-cnv-consensus.seg.gz v19

#### When do you expect the revised analysis will be completed?
1 day

#### Who will complete the updated analysis?
@kgaonkar6  
cc @jaclyn-taroni @jharenza  for input

**Comment by jharenza** [comment]
closing this since the MANTA PASS filter resolved our amp/del issues, see #1113
