### ISSUE TITLE
Typo in 'Adamantinomatous Craniopharyngioma' tables

### ISSUE THREAD

**Issue by afarrel** [AlexsLemonade/OpenPBTA-analysis#1108]
#### What data file(s) does this issue pertain to?

Integrated and harmonized data

#### Put your question or report your issue here.

There is a typo in one of the cancer histologies:
"Adamanti**m**omatous Craniopharyngioma" should be "Adamanti**n**omatous Craniopharyngioma"  in  the integrated and harmonized data.

**Comment by jharenza** [comment]
updated in #1084

**Comment by jharenza** [comment]
closed with #1084
