### ISSUE TITLE
Updated analysis: molecular-subtyping-embryonal sample selection

### ISSUE THREAD

**Issue by kgaonkar6** [AlexsLemonade/OpenPBTA-analysis#1110]
#### What analysis module should be updated and why?
`molecular-subtyping-embryonal`

It seems because the path_dx is slightly updated in v19 to Embryonal Tumor with Multilayered Rosettes (ETMR);Other but the we filter by exact matching to terms here https://github.com/AlexsLemonade/OpenPBTA-analysis/blob/master/analyses/molecular-[…]embryonal/subset-files/embryonal_subtyping_path_dx_strings.json

#### What changes need to be made? Please provide enough detail for another participant to make the update.
Use str_detect() to gather the terms used in json file https://github.com/AlexsLemonade/OpenPBTA-analysis/blob/master/analyses/molecular-[…]embryonal/subset-files/embryonal_subtyping_path_dx_strings.json

#### What input data should be used? Which data were used in the version being updated?
`pbta-histologies.tsv`

#### When do you expect the revised analysis will be completed?
1 day

#### Who will complete the updated analysis?
@kgaonkar6

**Comment by jharenza** [comment]
closed with #1117
