### ISSUE TITLE
Updated analysis: Subset manta FILTER=="PASS" consensus cnv

### ISSUE THREAD

**Issue by kgaonkar6** [AlexsLemonade/OpenPBTA-analysis#1113]
#### What analysis module should be updated and why?
Add a FILTER==PASS for manta calls used in `copy_number_consensus_call`. I think this filter is necessary so that we use a subset of high-confidence broad SVs called by manta. https://github.com/Illumina/manta/blob/master/docs/userGuide/README.md#vcf-format-fields

#### What changes need to be made? Please provide enough detail for another participant to make the update.
Add a filter to only keep calls where FILTER=='PASS' 
`$11 == 'PASS'`
[here](https://github.com/AlexsLemonade/OpenPBTA-analysis/blob/d70158c8945e6cdbd96bc3e68e5a114c394c79ff/analyses/copy_number_consensus_call/Snakefile#L101-L106)

#### What input data should be used? Which data were used in the version being updated?
pbta-sv-manta.tsv.gz

#### When do you expect the revised analysis will be completed?
1day

#### Who will complete the updated analysis?
@kgaonkar6

**Comment by jharenza** [comment]
closed with #1114 #1115 #1116
