### ISSUE TITLE
Updated analysis: regenerate figures using v21 data release

### ISSUE THREAD

**Issue by jharenza** [AlexsLemonade/OpenPBTA-analysis#1132]
#### What analysis module should be updated and why?
Script:
https://github.com/AlexsLemonade/OpenPBTA-analysis/blob/master/figures/generate-figures.sh

#### What changes need to be made? Please provide enough detail for another participant to make the update.
Rerun for current plot figures in order to determine necessary changes for final figures

#### What input data should be used? Which data were used in the version being updated?
v21 data release

#### When do you expect the revised analysis will be completed?
asap?

#### Who will complete the updated analysis?
someone from CCDL or @kgaonkar6 ? cc @jaclyn-taroni

**Comment by kgaonkar6** [comment]
Adding here to track updates:
- copy over figure for sample distribution from sample-distribution-analysis with updated code in #1161

**Comment by jharenza** [comment]
closing this since we have tickets for individual figures now
