### ISSUE TITLE
Updated analysis: oncoprint-landscape

### ISSUE THREAD

**Issue by kgaonkar6** [AlexsLemonade/OpenPBTA-analysis#1141]
#### What analysis module should be updated and why?
oncoprint-lamdscape

#### What changes need to be made? Please provide enough detail for another participant to make the update.
- Update gene list 
- Remove display group and instead replace with cancer group coloring
- Remove right side barplots
- Remove 7316 ids
- Increase size of the CNV boxes? Make a rectangle? 
- Add annotation for sex (using germline sex estimate)

#### What input data should be used? Which data were used in the version being updated?
v20 
pbta-snv-consensus-mutation.maf.tsv.gz
pbta-snv-scavenged-hotspots.maf.tsv.gz
pbta-fusion-putative-oncogenic.tsv
consensus_seg_annotated_cn_autosomes.tsv.gz
consensus_seg_annotated_cn_x_and_y.tsv.gz
independent-specimens.*

#### When do you expect the revised analysis will be completed?
1 day

#### Who will complete the updated analysis?
@kgaonkar6

**Comment by jharenza** [comment]
For the updated gene lists: https://docs.google.com/spreadsheets/d/1md5_49yCRh0gBQrRzL7iHvk3wBlAH9rMocxf0LcGwUM/edit#gid=1974203153 - I put ependymal tumor within the "Other" grouping since it has very few genes - this way, we can have a 4 panel, more balanced figure instead

**Comment by kgaonkar6** [comment]
@jharenza, documenting the PRs, please let me know if I missed anything.

#1143 
Update gene list
Remove right side barplots
Remove 7316 ids

#1147 
Remove display group and instead replace with cancer group coloring
Add annotation for sex (using germline sex estimate)

Pending: 
Increase size of the CNV boxes? Make a rectangle?
I am not sure changing the shape/size is possible in maftools::oncplot(). Looking at the code it seems the size are fixed [here](https://github.com/PoisonAlien/maftools/blob/9719868262f946e0b8eb2e7ec2510ee18c6cafa3/R/oncoplot.R#L643-L666)

**Comment by kgaonkar6** [comment]
This seems to completed with #1143, #1147 and #1164?

**Comment by kgaonkar6** [comment]
I believe the updates from #1164 are 
https://github.com/AlexsLemonade/OpenPBTA-analysis/pull/1164#issuecomment-908393543

**Comment by jharenza** [comment]
Yes!
