### ISSUE TITLE
Updated analysis: update some figures to include annotations by `cancer_group` for manuscript

### ISSUE THREAD

**Issue by jharenza** [AlexsLemonade/OpenPBTA-analysis#1144]
#### What analysis module should be updated and why? What changes need to be made? Please provide enough detail for another participant to make the update.

- [x] interaction-plots - update plotting to be by `cancer_group`
- [x] telomerase-activity-prediction - change `broad_histology` and `short_histology` plots to `cancer_group` for the main figure. Could keep all in the analysis module</s>
- [ ] <s> transcriptomic-dimension-reduction - color by `cancer_group` </s>
- [x] sample-distribution-analysis - add second level with `cancer_group`,  3rd/4th/5th with WGS/WXS/RNA, 7th with tumor descriptor, 8th with sex

#### What input data should be used? Which data were used in the version being updated?
v20

#### When do you expect the revised analysis will be completed?
this and next week

#### Who will complete the updated analysis?
@kgaonkar6 

Note, ticket still a WIP

**Comment by kgaonkar6** [comment]
While working in the interaction plots I've identified some points that I'd like to get clarification on:

1) Do we want to plot coocurrence plot per each cancer_group corresponding to the broad_histology here https://github.com/AlexsLemonade/OpenPBTA-analysis/blob/0f5a7263af2b02f80c6949f9d33730fe006eaab2/analyses/interaction-plots/01-create-interaction-plots.sh#L40-L49 ? Asking because dividing some cancer_groups only have a couple of samples 
```
             broad_histology                        cancer_group   n
1 Low-grade astrocytic tumor      Diffuse fibrillary astrocytoma   7
2 Low-grade astrocytic tumor                       Ganglioglioma   1
3 Low-grade astrocytic tumor                 Gliomatosis cerebri   1
4 Low-grade astrocytic tumor                                 GNG  47
5 Low-grade astrocytic tumor                   Oligodendroglioma   1
6 Low-grade astrocytic tumor               Pilocytic astrocytoma 123
7 Low-grade astrocytic tumor       Pleomorphic xanthoastrocytoma  11
8 Low-grade astrocytic tumor Subependymal Giant Cell Astrocytoma   9
```

And since currently only genes that are mutated in [minimum 5 samples](https://github.com/AlexsLemonade/OpenPBTA-analysis/blob/0f5a7263af2b02f80c6949f9d33730fe006eaab2/analyses/interaction-plots/scripts/02-process_mutations.R#L18)  are kept for plotting we end up erroring out on some of the smaller cancer_groups. So we can either drop them with a cutoff of <n> samples or plot cooccurrence by broad_histology but plot the cancer_group in the barplots?




Or

**Comment by jharenza** [comment]
@kgaonkar6 I was envisioning only the barplot would be changed to cancer group, but the analysis would remain as is.

**Comment by kgaonkar6** [comment]
For transcriptomic-dimension-reduction I get an error saying 
`Error: Insufficient values in manual scale. 58 needed but only 26 provided.`

The manual scale has 26 colors here, do we want to add the 58 colors from the figures palette for cancer_group here?
https://github.com/jaclyn-taroni/OpenPBTA-analysis/blob/1ac140e1d93fcb9615d57265f9a11c55c9f4bc74/analyses/transcriptomic-dimension-reduction/util/dimension-reduction-functions.R#L256-L265

**Comment by jaclyn-taroni** [comment]
@kgaonkar6 do you need to alter the module itself or would be altering the figure generation steps to use an updated palette be sufficient for what you're trying to accomplish (e.g., [in here](https://github.com/alexslemonade/OpenPBTA-analysis/blob/1ac140e1d93fcb9615d57265f9a11c55c9f4bc74/figures/scripts/transcriptomic-overview.R#L100))?

**Comment by kgaonkar6** [comment]
umm good question, I thought we want to update the modules in this ticket and the `figures/` will be recreated in #1132. 
Let me know if I mis-understood.

**Comment by jaclyn-taroni** [comment]
That question _probably wasn't for me_, but I'd say that I don't see any reason to update that module if it's only for display purposes. In fact, keeping `figures/` separate is handy for this kind of tweak as it keeps the final touches of display separate from the analysis which can sometimes be exploratory in nature & is nice to have preserved. 

For interaction plots, the figure is just copied from the module so changing the module is the right call: https://github.com/AlexsLemonade/OpenPBTA-analysis/blob/75c737d980884d3bec8c6fdcbecbe97b617e168d/figures/generate-figures.sh#L60

**Comment by jaclyn-taroni** [comment]
I'll also add: I'm not sure making a scatter plot with a 58 color palette is going to be helpful to or discernible by our readers?

**Comment by kgaonkar6** [comment]
That makes sense @jaclyn-taroni! 

From additional discussions with @jharenza we decided to:
 - update the  `TelomeraseActivities.R` and `transcriptomic-overview.R` in the figures folder itself with the cancer_group update, and if that look too busy then revert back to the original figures. 
- copy over figure for sample distribution from sample-distribution-analysis with updated code in #1161
