### ISSUE TITLE
Updated analysis: tp53 module to add figures for manuscript

### ISSUE THREAD

**Issue by jharenza** [AlexsLemonade/OpenPBTA-analysis#1146]
#### What analysis module should be updated and why?
`tp53_nf1_score`

#### What changes need to be made? Please provide enough detail for another participant to make the update.
Using ggpubr 's `ggtheme = theme_pubr())`, export some figures within the RMD files so they can be used within the manuscript:

- [x] Distribution of scores across tp53 altered status
- [x] Distribution of TP53 expression across tp53 altered status (separate stranded/polyA)
- [ ] Distribution of scores across tp53 altered status by cancer predisposition - export these as separate plots by predisposition so they can be broken up for main/supplement (I have only done this for Li-Fraumeni syndrome as a positive control)
- [ ] Create `broad_histology` pngs with `molecular_subtype`- specific violin plots for TP53 scores as in #1153 
- [ ] As an alternative to the above plot, create heatmap figure of all scores with annotations for `display_group`, `cancer_group`, and label by `molecular_subtype` - possibly mirroring the immune deconv scores heatmaps
- [ ] Update ROC curve plot to unified ggpubr theme. Sample code:

https://github.com/marislab/pptc-pdx-classifier-analysis/blob/f269d6c683432f103f6c31659f22e5ada47c4281/R/classifier-plots-revision.R#L7-L63

#### What input data should be used? Which data were used in the version being updated?
current, v20

#### When do you expect the revised analysis will be completed?
this or next week

#### Who will complete the updated analysis?
<s>@kgaonkar6 and </s> @jharenza and @komalsrathi

**Comment by komalsrathi** [comment]
> * [ ]  As an alternative to the above plot, create heatmap figure of all scores with annotations for `display_group`, `cancer_group`, and label by `molecular_subtype` - possibly mirroring the immune deconv scores heatmaps

For this, if we make the molecular subtype as the y-axis, what would be the x-axis?

**Comment by komalsrathi** [comment]
@jharenza can we close this or are we waiting for additional plots?

**Comment by jharenza** [comment]
Closing with #1152 merged
