### ISSUE TITLE
Updated analysis: update oncoprint panel figure code

### ISSUE THREAD

**Issue by jharenza** [AlexsLemonade/OpenPBTA-analysis#1148]
#### What analysis module should be updated and why?
`figures`: https://github.com/AlexsLemonade/OpenPBTA-analysis/blob/master/figures/scripts/oncoprint-landscape.R

#### What changes need to be made? Please provide enough detail for another participant to make the update.
Update the panel for 4 figures instead of 5, since #1143 combined ependymal tumors into other

#### What input data should be used? Which data were used in the version being updated?
same as current script

#### When do you expect the revised analysis will be completed?
next week?

#### Who will complete the updated analysis?
@kgaonkar6 or @cbethell cc @jaclyn-taroni

**Comment by cbethell** [comment]
I can work on tackling this issue!

**Comment by jharenza** [comment]
thanks so much!
