### ISSUE TITLE
[Figures]: update `figures` README with theme and cancer group info

### ISSUE THREAD

**Issue by jharenza** [AlexsLemonade/OpenPBTA-analysis#1158]
#### What module should be updated and why?
`figures` README needs to be updated to include `cancer_group` info/hex codes now that #1142 is merged and a unified publication theme per #761 

#### What changes need to be made? Please provide enough detail for another participant to make the update.
Add information about theme and color palette for `cancer_group` as well as palette for other one-off panel plots which can be colored by levels (eg #1152 used the "jco" journal theme).

#### What input data should be used? Which data were used in the version being updated?
NA, README update

#### When do you expect the revised analysis will be completed?
next week

#### Who will complete this?
@jharenza

**Comment by jaclyn-taroni** [comment]
Addressed by #1172 and if there are items remaining, I think they are subsumed by #1176 at this point.
