### ISSUE TITLE
Updated analysis: oncoprint update aesthetics

### ISSUE THREAD

**Issue by jharenza** [AlexsLemonade/OpenPBTA-analysis#1165]
#### What analysis module should be updated and why?
`oncoprint-landscape`

#### What changes need to be made? Please provide enough detail for another participant to make the update.

per comment [here](https://github.com/AlexsLemonade/OpenPBTA-analysis/pull/1164#issuecomment-906709011):

- remove titles on each plot (`Altered in*`)
- Move broad histologies titles to be centered above each plot
- Label A,B (top), C,D (bottom)
- Increase gene name font size as much as possible
- Try to make the plots more horizontally condensed for a portrait page 
- Update `germline_sex_estimate` label to `sex` and `cancer_group` to `histology`(?) and make sure they are not cut off in the figures
- Create a unified legend and add to the right side of the plots (I feel like this is a ticket in itself and maybe @kgaonkar6 can tackle - we would maybe have to make color boxes with labels and make them another figure, then put it into this panel - thoughts? (Since there are a lot of samples which are not displayed, some cancer groups in the legend do not have these samples in the plots, so I think we would want to only list those which have samples). It would also be nice to convert these so there are no underscores and the whole words are displayed (eg - `In_Frame_Ins` --> `In-frame insertion`) - honestly, I just made these in excel before (ick) and created a piece of a figure and put it in the final figure, so if this is a huge coding challenge, it can be done like that, as tedious as it is.

#### What input data should be used? Which data were used in the version being updated?
same as current

#### When do you expect the revised analysis will be completed?
next 1-2 weeks?

#### Who will complete the updated analysis?
@kgaonkar6 and/or @cbethell

**Comment by cbethell** [comment]
The following points from above have successfully been addressed in PR #1164:

- remove titles on each plot (`Altered in*`)
- Move broad histologies titles to be centered above each plot
- Label A,B (top), C,D (bottom)
- Increase gene name font size as much as possible
- Try to make the plots more horizontally condensed for a portrait page  -- _although there may room for further improvement here_

**Comment by jaclyn-taroni** [comment]
Based on my read, only the last point about legends was relevant per https://github.com/AlexsLemonade/OpenPBTA-analysis/issues/1165#issuecomment-909384523 and the fact that the labels mentioned don't seem cutoff in the oncoprints in `figures/pngs`. I've filed #1178 with a series of steps to create the unified legend and final figure.
