### ISSUE TITLE
[Discussion] - Manuscript figure for de novo mutational signatures

### ISSUE THREAD

**Issue by jharenza** [AlexsLemonade/OpenPBTA-analysis#1173]
We need to sketch out a manuscript figure for the de novo CNS mutational signatures now that #1100 has been merged.

Some things we should have:
1 - Supplemental excel book of DNA BS_ID + signatures with tabs for (CNS signatures `mean` in `fitted_cns_signature_exposures.RDS`), COSMIC, and Alexandrov
2 - plot of CNS signature proportions by `cancer_group`(?) - can be similar to the COSMIC/Alexandrov or stacked bar?

Some things to consider:
- Current plots could be suitable for the supplement (`https://github.com/AlexsLemonade/OpenPBTA-analysis/blob/master/analyses/mutational-signatures/plots/cns/mean_median_exposure_barplot.png`), but not sure what the colors indicate (histologies?)
- We need some sort of mapping of ABC, etc signature to the underlying mechanism of the signature, if known (eg - which signature is due to MMR or HR deficiency, TMZ treatment, etc?) Do we know this information? Will be important to capture this by cancer type so that we can describe the results and also compare to the COSMIC/Alexandrov signatures as to why this is an improvement. Hoping it shows something cool

cc @jaclyn-taroni

**Comment by jaclyn-taroni** [comment]
Link to the signatures we used and the related reference signatures: https://signal.mutationalsignatures.com/explore/studyTissueType/1-6#

**Comment by jaclyn-taroni** [comment]
I'm going to assign myself to this so I can do a bit of poking around in the existing code before making recommendations. For my own reference, the bubble plots we have are an adaptation of this figure: https://www.nature.com/articles/s41586-020-1943-3/figures/3 (from [Alexandrov et al. 2020](https://doi.org/10.1038/s41586-020-1943-3)).

**Comment by jharenza** [comment]
done per #1220
