### ISSUE TITLE
Updated analysis: GISTIC with ploidy instead of NA

### ISSUE THREAD

**Issue by kgaonkar6** [AlexsLemonade/OpenPBTA-analysis#1180]
#### What analysis module should be updated and why?
run-gistic, errors out with 

```
Running GISTIC on the entire OpenPBTA cohort...
GISTIC version 2.0.23
required parameters:
      base_dir: ../results/pbta-cnv-consensus-gistic
       segfile: ../../../scratch/uncompressed-seg-for-gistic/consensus_seg_file_for_gistic.seg
marker spacing: 10000
   refgenefile: /home/rstudio/gistic_install/refgenefiles/hg38.UCSC.add_miR.160920.refgene.mat
optional_params = 
         array_list_file: []
                cnv_file: []
                   t_amp: 0.1000
                   t_del: 0.1000
       join_segment_size: 2
                     ext: []
               qv_thresh: 0.2500
                remove_X: 0
                 markers: []
      max_marker_spacing: 10000
      run_broad_analysis: 1
        broad_len_cutoff: 0.9800
                   ziggs: [1x1 struct]
                     res: 0.0500
              conf_level: 0.9000
                     cap: 1.5000
          do_gene_gistic: 1
     conserve_disk_space: 0
         save_data_files: 1
            use_segarray: 1
        write_gene_files: 1
           use_two_sided: 1
          do_arbitration: 1
           save_seg_data: 1
                   fname: []
              peak_types: {'robust'}
             genepattern: 1
             arm_peeloff: 1
    gene_collapse_method: 'extreme'
           sample_center: 'median'

Checking inputs...
Making D struct
No markers file specified: generating pseudo-markers!
Reading Seg File '../../../scratch/uncompressed-seg-for-gistic/consensus_seg_file_for_gistic.seg'
Warning: Shortened 17856 segments in '../../../scratch/uncompressed-seg-for-gistic/consensus_seg_file_for_gistic.seg' that overlap by one marker.
> In make_D_from_segseq_data at 122
  In run_gistic2_from_seg at 193
  In gp_gistic2_from_seg at 97 
D = 
               sdesc: {915x1 cell}
                chrn: [317435x1 double]
                 pos: [317435x1 double]
    suppress_history: 1
               islog: 0
                isMB: 0
                 dat: [317435x915 SegArray]

D = 
               sdesc: {915x1 cell}
                chrn: [317435x1 double]
                 pos: [317435x1 double]
    suppress_history: 1
               islog: 0
                isMB: 0
                 dat: [317435x915 SegArray]

Matrix size 317435     915
Removing NaN probes...
Removing 317435 markers with NaNs
Matrix size 0  915
 
GISTIC 2.0 input error detected:
All input data were removed after NaN processing.
updating: pbta-cnv-consensus-gistic/ (stored 0%)
updating: pbta-cnv-consensus-gistic/gistic_inputs.mat (deflated 2%)
Running GISTIC on specific histologies...

```

We believe that the change from 2 to NA might be causing this issue, gistic then removes all the markers marked as NaNs

#### What changes need to be made? Please provide enough detail for another participant to make the update.
Suggested by @jaclyn-taroni  we could try to convert to NA to ploidy as we do in chromotripsis ( OR should we update the consensus cnv file to use ploidy instead of NA ?) 
https://github.com/AlexsLemonade/OpenPBTA-analysis/pull/1127#issuecomment-923254312

#### What input data should be used? Which data were used in the version being updated?
pbta-cnv-consensus.seg.gz

**Comment by runjin326** [comment]
@kgaonkar6, thanks for looking into this! I did some digging and I am pretty sure it is coming from the fact that we change `copy.num=NA` for all the neutral calls. I tried last night to change those back to 2 and it ran just fine. 
I see that previously you did some analyses and `copy.num=NA` gives the least amount of noise in focal CN annotation so I think we can keep that for that module. I was actually thinking maybe we can use a separate seg file just for GISTIC so that the other module would not be affected and either use ploidy or just keep the `copy.num=2`. Any thought, @jaclyn-taroni, @kgaonkar6?

**Comment by kgaonkar6** [comment]
I think as recommended by @jaclyn-taroni,  we should replace the NA with tumor ploidy within an internal step in `run-gistic` as we did for chromothripsis here
https://github.com/AlexsLemonade/OpenPBTA-analysis/blob/d31c927a27813ec0b8032fbe768002f31723636f/analyses/chromothripsis/02-run-shatterseek-and-classify-confidence.R#L67-L76

**Comment by sjspielman** [comment]
Closed by updates here: https://github.com/PediatricOpenTargets/OpenPedCan-analysis/pull/119/files
