### ISSUE TITLE
Updated analysis: oncoprint readme/output to list Ns per group

### ISSUE THREAD

**Issue by jharenza** [AlexsLemonade/OpenPBTA-analysis#1182]
#### What analysis module should be updated and why?
oncoprint-landscape

In writing the manuscript, I need to reference the Ns per group when listing out frequencies, so I think we should either have some output table with this info or an update in the readme - probably easier to do the former in case of any changes. 

#### What changes need to be made? Please provide enough detail for another participant to make the update.
Would be ideal to create a table or notebook with N per total samples listed in A,B,C,D and then Ns per each cancer group.

Also note, there are a lot of samples which are not shown in the oncoprint because they lack mutations, but they should be included in the total N since they are included in the denominator of the frequency.

#### What input data should be used? Which data were used in the version being updated?
primary sample list only, v21

#### When do you expect the revised analysis will be completed?
?

#### Who will complete the updated analysis?
<s>@cbethell ? </s> @kgaonkar6  cc @jaclyn-taroni

**Comment by runjin326** [comment]
@jharenza, sure I will start working on this!
