### ISSUE TITLE
Updated analysis: medullo subtyping misses WGS only samples as To be Classified

### ISSUE THREAD

**Issue by jharenza** [AlexsLemonade/OpenPBTA-analysis#1183]
#### What analysis module should be updated and why?
medulloblastoma-subtyping - missed WGS only samples

```
v21 %>%
  filter(cancer_group == "Medulloblastoma" & sample_type == "Tumor" &
           is.na(molecular_subtype)) %>%
  select(Kids_First_Biospecimen_ID, experimental_strategy, molecular_subtype)

# A tibble: 7 x 3
  Kids_First_Biospecimen_ID experimental_strategy molecular_subtype
  <chr>                     <chr>                 <chr>            
1 BS_3J4T2YYW               WGS                   NA               
2 BS_7F07M7JG               WGS                   NA               
3 BS_AG0BZN6F               WGS                   NA               
4 BS_HZNKSQ17               WGS                   NA               
5 BS_V6HKXX1Z               WGS                   NA               
6 BS_WP9J88EB               WGS                   NA               
7 BS_YYAPSA5P               WGS                   NA        
```

#### What changes need to be made? Please provide enough detail for another participant to make the update.
annotate these samples as to be classified

#### What input data should be used? Which data were used in the version being updated?
v21

#### When do you expect the revised analysis will be completed?
next week, if time?

#### Who will complete the updated analysis?
@komalsrathi 

This is also not a huge deal if not added since they are To be classified, but wanted to track as an issue here

**Comment by komalsrathi** [comment]
Sure, will do. Can you add me as an assignee?

**Comment by jharenza** [comment]
Closing with #1206
