### ISSUE TITLE
Updated analysis: oncoprint landscape missing SMARCB1 for embryonal (ATRT)

### ISSUE THREAD

**Issue by jharenza** [AlexsLemonade/OpenPBTA-analysis#1184]
#### What analysis module should be updated and why?
oncoprint landscape - the embryonal tumor plot for ATRTs is missing SMARCB1, the major driver mutation

#### What changes need to be made? Please provide enough detail for another participant to make the update.
Not sure why this is missing - see this [pedcbio page](https://pedcbioportal.kidsfirstdrc.org/results?cancer_study_list=ped_opentargets_2021&tab_index=tab_visualize&case_set_id=-1&case_ids=ped_opentargets_2021%3A7316-1073_353340%2Bped_opentargets_2021%3A7316-1137_356680%2Bped_opentargets_2021%3A7316-122_110806%2Bped_opentargets_2021%3A7316-1771_366034%2Bped_opentargets_2021%3A7316-1778_366153%2Bped_opentargets_2021%3A7316-1781_366204%2Bped_opentargets_2021%3A7316-2090_407671%2Bped_opentargets_2021%3A7316-2110_407931%2Bped_opentargets_2021%3A7316-2141_446716%2Bped_opentargets_2021%3A7316-2181_425854%2Bped_opentargets_2021%3A7316-2186_425928%2Bped_opentargets_2021%3A7316-2187_425944%2Bped_opentargets_2021%3A7316-2224_431244%2Bped_opentargets_2021%3A7316-2269_445086%2Bped_opentargets_2021%3A7316-2582_463647%2Bped_opentargets_2021%3A7316-2688_485693%2Bped_opentargets_2021%3A7316-386_290215%2Bped_opentargets_2021%3A7316-3890_608200%2Bped_opentargets_2021%3A7316-3937_609496%2Bped_opentargets_2021%3A7316-41_35057%2Bped_opentargets_2021%3A7316-479_347665%2Bped_opentargets_2021%3A7316-525_331640%2Bped_opentargets_2021%3A7316-820_358442%2Bped_opentargets_2021%3A7316-878_344873%2Bped_opentargets_2021%3A7316-918_345552&Action=Submit&gene_list=SMARCB1%250ASMARCA4) - we seem to be missing the variant calls and two homodeletions. It is possible some of the samples in pedcbio do not overlap with the independent specimen list, but we need to investigate this, as missing this key alteration is a red flag. _SMARCB1_ is in the GOI list here:
https://github.com/AlexsLemonade/OpenPBTA-analysis/blob/d31c927a27813ec0b8032fbe768002f31723636f/analyses/oncoprint-landscape/data/embryonal-tumor_goi_list.tsv#L63

#### What input data should be used? Which data were used in the version being updated?
v21

#### When do you expect the revised analysis will be completed?
this week?

#### Who will complete the updated analysis?
@runjin326

**Comment by jharenza** [comment]
> We don’t use the whole GOI list by default and in the publication plots we use the top 20 genes when using a GOI list. Since all embryonal tumors are plotted together, it would not surprise me if the top 20 cutoff is the culprit.
> 
> 
> 
> First step should check the underlying files used for the oncoprints, though.

That's true, but I also see genes mutated in only one sample in those plots, and with there being a few ATRTs in the plot, I would have thought we'd capture some SMARCB1, as we do in pedcbio. I think we also need to check whether the samples in pedcbio harboring the mutations exist in the oncoprint and if so, why aren't they showing up here. I think maybe this is the culprit, but want to be sure so we can explain it.

**Comment by runjin326** [comment]
@jharenza, so I looked into this - and the reason is due to the top20 filter for GOI list. 
- SMARCB1 is present only CNV file, not in fusion or MAF 
- it is still present after first filtering for GOI (`"SMARCB1" %in% filtered_maf_object@data[["Hugo_Symbol"]]` is TRUE)
- However, it got filtered out when selecting the top20 (see attached gene summary)
[gene_sum.txt](https://github.com/AlexsLemonade/OpenPBTA-analysis/files/7347349/gene_sum.txt)
    - One thing to note is that the top20 filter does get a bit tricky since there are 17 genes with `AlteredSamples` >2 and 14 genes with `AlteredSamples` =2. 
    - That means when it selected 20, it just pick the first 3 genes that are alphabetically earlier (`APC`, `CTDNEP1` and `FOXO3` were selected because of this) 

Let me know if there are anything else that you want me to look into.

**Comment by jharenza** [comment]
Thanks for this! We may want to prioritize the genes being shown in this specific plot - let me think about it.

**Comment by jharenza** [comment]
going to close this since these genes are not technically missing
