### ISSUE TITLE
Planned Analysis: Identification of potential causal/driver VUS

### ISSUE THREAD

**Issue by PichaiRaman** [AlexsLemonade/OpenPBTA-analysis#119]
#### Scientific goals

Identify potential variants of unknown significance that may play a role in tumorigenesis. 

#### Proposed methods

Look at frequently recurrent VUS, determine if there is a functional effect on a gene (or it is in a regulatory region), look at VAF and focus on samples without other relevant driver mutations. 

#### Required input data

VCF or MAF files

#### Proposed timeline

2 weeks

#### Relevant literature

https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6359859/

**Comment by jashapiro** [comment]
I am starting to look at this. I will be following the approach in the linked paper of comparison of VUS to GENIE, COSMIC and ExAc to identify known drivers, benign mutations, and previously identified recurrent mutations. If there are other suggestions of sources for known drivers, that will become helpful in later filtering steps.

**Comment by jharenza** [comment]
Hi @jashapiro ! I came across this with the PCAWG pan-cancer paper releases: https://www.nature.com/articles/s41467-019-13929-1#code-availability ([code](https://github.com/smshuai/DriverPower)). I thought I also saw something mentioning MutSigCV cc @jaclyn-taroni but couldn't find. I wonder if it is worth running this algorithm (after lifting over to hg19) with our consensus calls.

**Comment by jaclyn-taroni** [comment]
I think you're thinking of #517 @jharenza

**Comment by jharenza** [comment]
oh yes, thanks!

**Comment by jaclyn-taroni** [comment]
Closing all planned analysis tickets in favor of opening new proposed analysis/updated analysis tickets as needed.
