### ISSUE TITLE
Proposed Analysis: Create tsnes with molecular subtype highlighted for Fig S4

### ISSUE THREAD

**Issue by jharenza** [AlexsLemonade/OpenPBTA-analysis#1198]
#### What are the scientific goals of the analysis?
I drafted some [figures](https://github.com/AlexsLemonade/OpenPBTA-manuscript/blob/12118614c628e2f1d98ba7ab75bd6a3de658e30b/content/images/supplement/Figure-S4.png) for Figure S4 to highlight some relevant subtypes within the tsne plot. This PR should update the tsne or figures code to generate these figures for the paper.

#### What methods do you plan to use to accomplish the scientific goals?
- For this, I removed all "To be classified" subtypes 
- I think we should only look at EPN, MB, HGG, and LGG
- For HGG, add both DMG and HGG samples
- For LGG (panel not shown because I didn't update code for this), we can use all samples subtyped within the LGG module (LGG, GNG, GNT), but remove the prefixes LGG/GNG/GNT and only show subtypes so that we don't have an overload of so many groups. This will allow us to determine if we see clusters by pathway/subtype.
- We could also make the `NA` in the legend be `Other CNS tumor` but still color code it as grey.

#### What input data are required for this analysis?
RNA-Seq stranded, pbta-histologies

#### How long do you expect is needed to complete the analysis? Will it be a multi-step analysis?
?

#### Who will complete the analysis (please add a GitHub handle here if relevant)?
someone at CCDL cc @jaclyn-taroni 

#### What relevant scientific literature relates to this analysis?
NA

**Comment by jharenza** [comment]
@runjin326 can you work on this?

**Comment by runjin326** [comment]
@jharenza , sure! will be able to get to this early next week.

**Comment by jharenza** [comment]
done in #1213
