### ISSUE TITLE
Updated analysis: Add CI to interaction-plots module

### ISSUE THREAD

**Issue by runjin326** [AlexsLemonade/OpenPBTA-analysis#1203]
#### What analysis module should be updated and why?
Add CI to `interaction-plots` module

#### What changes need to be made? Please provide enough detail for another participant to make the update.
Add CIs for the odds ratio calculations.

#### What input data should be used? Which data were used in the version being updated?
N/A

#### When do you expect the revised analysis will be completed?
1-2 days

#### Who will complete the updated analysis?
@runjin326

**Comment by jaclyn-taroni** [comment]
Closed via #1204
