### ISSUE TITLE
Updated analysis: survival analysis generalization

### ISSUE THREAD

**Issue by runjin326** [AlexsLemonade/OpenPBTA-analysis#1210]
#### What analysis module should be updated and why?
survival analysis that is currently in [PR 1208](https://github.com/AlexsLemonade/OpenPBTA-analysis/pull/1208)

#### What changes need to be made? Please provide enough detail for another participant to make the update.
1) Currently the script has non-HGAT and PBTA all commented out - need to add back as a loop function to run the analyses on all data frames
2) When looping across different data frames, the quantiles used for HGAT/PBTA and non-HGAT need to be taken into control
3) Add this function as well for output for table:
```
pairwise_survdiff(formula = Surv(OS_days, OS_status) ~ pheno_0.5, 
                  data = meta_no_hgat, 
                  p.adjust.method = "BH", rho = 0)
```

#### What input data should be used? Which data were used in the version being updated?
```
pbta-histologies.tsv
independent-specimens.rnaseq.primary-plus-stranded.tsv
tp53_altered_status.tsv
TelomeraseScores_PTBAStranded_FPKM.txt
```

#### When do you expect the revised analysis will be completed?
1-2 days.

#### Who will complete the updated analysis?
@runjin326

**Comment by jaclyn-taroni** [comment]
I'm going to close this in favor of what's outlined in https://github.com/AlexsLemonade/OpenPBTA-analysis/pull/1208#issuecomment-996356663
