### ISSUE TITLE
Updated analysis: chromothripsis module - change R^2 to R on scatterplot

### ISSUE THREAD

**Issue by LauraEgolf** [AlexsLemonade/OpenPBTA-analysis#1214]
#### What analysis module should be updated and why?
Chromothripsis module - change R^2 to R on scatterplot of SV vs. CNV breaks (for consistency with other figures/text)

#### What changes need to be made? Please provide enough detail for another participant to make the update.
- Update scatterplot code in analyses/chromothripsis/04-plot-chromothripsis-and-breakpoint-data.Rmd
- Re-run figure generation script (no changes needed) to copy the updated PDF from the chromothripsis module to figures

#### What input data should be used? Which data were used in the version being updated?
Latest release

#### When do you expect the revised analysis will be completed?
Today

#### Who will complete the updated analysis?
@LauraEgolf

**Comment by sjspielman** [comment]
Closed with #1215.
