### ISSUE TITLE
Updated analysis: Figures for mutational signatures fitting

### ISSUE THREAD

**Issue by sjspielman** [AlexsLemonade/OpenPBTA-analysis#1220]
Related to #1173. 

#### What analysis module should be updated and why?

Figures representing the results from `mutational-signatures` analyses need to be formalized and incorporated. The overall conclusions from this analysis module were that i) *de novo* extraction does not converge likely to due small and highly heterogeneous dataset. ii) We can fit any of COSMIC, Alexandrov, and/or the 8 CNS Signal signatures to the data, but the first two (COSMIC and Alexandrov) are highly busy and not as targeted as fitting the 8 CNS.

#### What changes need to be made? Please provide enough detail for another participant to make the update.

The plan is for two finalized figures to be created for the main text, likely to be inserted into figure 2. These figures will focus on _exposures for the 8 adult CNS signatures_. 

The plan:

+ A _quick_ comparison between using `deconstructSigs` and `sigfit` packages for fitting these 8 signatures. If results are highly similar, then the faster approach will be used.
+  Make a bubble plot similar to what has previously been done (#11)
+ Make a barplot showing mutational burden per megabase (#11)
  + OR, make something more specific eg coding mutations per megabase

#### When do you expect the revised analysis will be completed?

1-2 weeks.

#### Who will complete the updated analysis?

@sjspielman

**Comment by jharenza** [comment]
done with #1226 and #1227
