### ISSUE TITLE
Updated analysis: Update immune deconvolution module to include xCell and quanTIseq

### ISSUE THREAD

**Issue by sjspielman** [AlexsLemonade/OpenPBTA-analysis#1238]
#### What analysis module should be updated and why?

Currently, `immune-deconvolution` uses only the `xCell` method. This method reports relative scores without units and only allows for comparisons between samples, but _not_ between cell types (see #1234). 

We may want to have a complementary method, such as `quanTIseq`, which provides absolute scores that can be interpreted as fractions of the sample containing that cell type. Further, these scores can be compared _both_ across samples and cell types. 

#### What changes need to be made? Please provide enough detail for another participant to make the update.

Integrate `quanTIseq` into the `immune-deconvolution` in addition to `xCell`, using the same `immunedeconv` package. 

#### What input data should be used? Which data were used in the version being updated?
`v21`

#### When do you expect the revised analysis will be completed?

1-2 days

#### Who will complete the updated analysis?

@sjspielman

**Comment by jharenza** [comment]
updated in #1243
