### ISSUE TITLE
Updated analysis: Remove xCell heatmap figures

### ISSUE THREAD

**Issue by sjspielman** [AlexsLemonade/OpenPBTA-analysis#1240]
#### What analysis module should be updated and why?

The `immune-deconvolution` module contains several heatmaps of `xCell` scores averaged across groupings, including histologies and molecular subtypes for certain histologies. These plots should be removed because:

+ `xCell` scores cannot be compared across cell types, and heatmaps are misleading because they make it seem like you can compare across either dimension
+ Averaging scores may not be robust given the heterogeneity across samples

#### What changes need to be made? Please provide enough detail for another participant to make the update.

Remove current heatmaps from the `immune-deconvolution` module to make way to updated viz coming in subsequent issues. 

#### What input data should be used? Which data were used in the version being updated?

N/A

#### When do you expect the revised analysis will be completed?

1-2 days

#### Who will complete the updated analysis?

@sjspielman

**Comment by jharenza** [comment]
updated in #1241
