### ISSUE TITLE
update CAVATICA to v21

### ISSUE THREAD

**Issue by jharenza** [AlexsLemonade/OpenPBTA-analysis#1245]
#### What data file(s) does this issue pertain to?
v20, v21 releases

#### What release are you using?

v21

#### Put a link to the relevant section of the [OpenPBTA-manuscript](https://github.com/AlexsLemonade/OpenPBTA-manuscript/) here.
NA

#### Put your question or report your issue here.
Please link v20 and v21 files to https://cavatica.sbgenomics.com/u/cavatica/openpbta

**Comment by jharenza** [comment]
@zhangb1

**Comment by zhangb1** [comment]
Sorry, I missed this ticket. this has been done.

Please check the data in the public project here : https://cavatica.sbgenomics.com/u/cavatica/openpbta/files/#q

**Comment by jharenza** [comment]
thanks @zhangb1 !
