### ISSUE TITLE
Proposed Analysis: investigate whether signatures 3 and 18 also 

### ISSUE THREAD

**Issue by jharenza** [AlexsLemonade/OpenPBTA-analysis#1248]
#### What analysis module should be updated and why?
mutational signatures

Based on the literature below, we hypothesize we would see a similar phenomenon in our cohort. That is, samples with hypermutator phenotypes have signatures associated with high genomic instability (in our CNS signature analysis, those would be RefSigs 3 andd 18) _and_ _TP53_ dysregulation. 

From doi:10.1038/s43018-020-0027-5:
>Signatures with a high level of genomic instability are dependent on TP53 dysregulation.

>Last, driver mutations in TP53 appear to be strongly associated with multiple signatures (Fig. 6b). Unlike other driver–signature relationships, target plots recurrently present a dark right semicircle and light left semicircle across multiple tissues. Thus, most tumors carrying these signatures are TP53-mutated, but the reverse is not true—not all TP53-mutated tumors carry the individual signatures. Many of the associated signatures can create hypermutator phenotypes resulting in noticable genomic instability (RefSig 17, 18, R1, R3 and R5). We therefore postulate that most mutational signatures with hypermutator phenotypes have a dependency on TP53 dysregulation. 
<img width="708" alt="Screen Shot 2022-03-18 at 1 50 45 PM" src="https://user-images.githubusercontent.com/207034/159056772-6f1daf0e-764f-4b1c-ad97-2221bfcaecb2.png">

#### What changes need to be made? Please provide enough detail for another participant to make the update.
1. We previously looked for a relationship between hypermutator samples and the MMR signature, but we should also look at whether there is a relationship with Sig 3 and/or 18. 
2. Do these hypermutator samples also show dysregulated _TP53_? Since there are only 3 hypermutant samples in this cohort (> 10 Mut/Mb) and 4 ultrahyper mutant samples (>100 Mut/Mb) defined in pediatric samples by https://www.cell.com/cell/pdf/S0092-8674(17)31142-X.pdf, possibly, we can explore these separately or maybe in a table?
>Having validated panel-based hypermutation testing, we examined the mutation burden in 2,885 pediatric tumors. Mutation frequency ranged from 0–864 Mut/Mb (Figure 1A), with a mean and median of 6.78 Mut/Mb and 2.50 Mut/Mb, respectively. Using segmented linear regression analysis, we calculated 9.91 and 9.0 Mut/Mb as appropriate thresholds for hypermutation in childhood and adult cancers (Figures S1C and S1D; STAR Methods). For consistency, we use 10 Mut/Mb to define hypermutation in both cohorts. We also note that this coincides with the median mutation burden of patients previously reported to respond to checkpoint inhibition (Bouffet et al., 2016; Diaz and Le, 2015; Johanns et al., 2016; Le et al., 2015; Rizvi et al., 2015; Santin et al., 2016; Snyder et al., 2014; Van Allen et al., 2015).

>Hypermutation was observed in childhood cancer types not typically associated with elevated numbers of mutations, including
sarcomas, germ cell tumors, nephroblastomas, and neuroblastomas. Importantly, across the whole cohort, hypermutant cancers were enriched for defects in mismatch repair pathway genes POLE and POLD1, responsible for synthesis of the leading and lagging strand (p % 2.2 3 1016) (Figure 1B). Ultra-hypermutated (>100 Mut/Mb) pediatric tumors were universally replication repair deficient and included only the three tumor types observed in CMMRD: malignant gliomas, colorectal cancers, and leukemias/lymphomas.

#### What input data should be used? Which data were used in the version being updated?
cns signatures, coding tmb

#### When do you expect the revised analysis will be completed?
?

#### Who will complete the updated analysis?
possibly @sjspielman or @runjin326 ?

**Comment by sjspielman** [comment]
Misc note, as discussed in [this comment](https://github.com/AlexsLemonade/OpenPBTA-analysis/pull/1227#discussion_r829949839) - we might want to move the exploration of signatures 1 and MMR2 into this notebook where we explore 3 and 18. There will be a decent amount of similarities among the comparisons.

**Comment by jaclyn-taroni** [comment]
This was closed by #1263. There are some remaining questions in https://github.com/AlexsLemonade/OpenPBTA-analysis/pull/1263#pullrequestreview-920749859, but those would be separate issues.
