### ISSUE TITLE
Create updated panels for Fig 3

### ISSUE THREAD

**Issue by jharenza** [AlexsLemonade/OpenPBTA-analysis#1253]
Now that Figure 3 is finalized (see [here](https://docs.google.com/presentation/d/1bgaDcMaGgwNEGJl46Lg03FoF4EnS4XLjdp5Ji_ufGsI/edit#slide=id.ge9d4ddd4cc_0_15)), we should save the CNS mutational signatures figure as a panel for Figure 3C in https://github.com/AlexsLemonade/OpenPBTA-analysis/tree/master/figures/pdfs/fig3/panels.

Do we also need a script to create this figure? It isn't immediately clear to me how this is now being done.

**Who will complete this?**

@sjspielman ?

**Comment by sjspielman** [comment]
In this case it's appropriate to just have a line in [this script](https://github.com/AlexsLemonade/OpenPBTA-analysis/blob/master/figures/generate-figures.sh) copying the figure over, since the figure in the module is pub-ready. This will be quick, can do it!

**Comment by sjspielman** [comment]
Closed with #1256
