### ISSUE TITLE
Create additional panels for Figure S3

### ISSUE THREAD

**Issue by jharenza** [AlexsLemonade/OpenPBTA-analysis#1255]
Only the `primary_only_other_supplemental_oncoprint.pdf` panel  is represented [here](https://github.com/AlexsLemonade/OpenPBTA-analysis/tree/master/figures/pdfs/supp), so the two CN landscape and chromothripsis panels should be added per the slide deck [here](https://docs.google.com/presentation/d/1bgaDcMaGgwNEGJl46Lg03FoF4EnS4XLjdp5Ji_ufGsI/edit#slide=id.ge9d4ddd4cc_0_30).

Figures used for panels can be found:
- B: @jaclyn-taroni  and @cansavvy I cannot find this one at the moment - can you help?
- C: https://github.com/AlexsLemonade/OpenPBTA-analysis/blob/master/analyses/chromothripsis/plots/04-breakpoint-data/count_chromothripsis_cnv_breaks_stripchart.png
- D: https://github.com/AlexsLemonade/OpenPBTA-analysis/blob/master/analyses/chromothripsis/plots/04-breakpoint-data/count_chromothripsis_sv_breaks_stripchart.png

Who will complete this?
@sjspielman ?

**Comment by sjspielman** [comment]
Yup, I got it!

**Comment by sjspielman** [comment]
I've tracked down panel B here. It was last run with v20, so we might want to update. - https://github.com/AlexsLemonade/OpenPBTA-analysis/blob/master/analyses/cnv-chrom-plot/plots/cn_status_heatmap.png

**Comment by sjspielman** [comment]
Closed by #1259
