### ISSUE TITLE
Updated analysis: supp tables updates

### ISSUE THREAD

**Issue by jharenza** [AlexsLemonade/OpenPBTA-analysis#1260]
#### What analysis module should be updated and why?
https://github.com/AlexsLemonade/OpenPBTA-analysis/tree/master/tables

#### What changes need to be made? Please provide enough detail for another participant to make the update.
- Remove alexandrov and cosmic mutational signatures from DNA table
- Add new tab for quantiseq immune scores to RNA-Seq file (probably easiest to do column 1 bs_id and 10 colunns for cell types)

#### What input data should be used? Which data were used in the version being updated?
https://github.com/AlexsLemonade/OpenPBTA-analysis/blob/master/analyses/immune-deconv/results/quantiseq_deconv-output.rds

#### When do you expect the revised analysis will be completed?
this week?

#### Who will complete the updated analysis?
@runjin326

**Comment by jaclyn-taroni** [comment]
Was this closed by #1265 @jharenza or did more need to happen?

**Comment by jharenza** [comment]
Yes
