### ISSUE TITLE
Manuscript figures for telomerase

### ISSUE THREAD

**Issue by sjspielman** [AlexsLemonade/OpenPBTA-analysis#1272]
Both the script and figures for telomerase visualizations need to be made publication-ready. 

#### What changes need to be made? Please provide enough detail for another participant to make the update.

Currently there is one script `figures/scripts/TelomeraseActivities.R` that creates main text and supplemental figures. Starting with this script as a baseline, we should:

+ Move code into separate scripts for generate main text and supplemental figures, and remove vestigial code
  + Main text will include a jitter-overlayed boxplot of normextend scores for stranded data, as a panel in figure 5
    + These points should be shaped by (ultra)hypermutator status to match accompanying figure 5 panel described in #1271 
  + Figure S5 should contains two panels (G/H) showing TERT and TERC (respectively) expression across stranded normextend FPKM 
+ Update all code and plots with publication-ready styles

Effectively, these changes will remove the current script and include updated ones. 

Note this relevant issue as well which is going to rearrange some aspects of Figure 5, #1271. A figure 5 script itself may be the most appropriate place to place the telomerase main text figures.

#### When do you expect the revised analysis will be completed?

~1 week

#### Who will complete the updated analysis?

@sjspielman

**Comment by jharenza** [comment]
Oops, I just created #1281, which has some telomerase discussion/questions - we can close and discuss here, although there is one other TP53 panel in #1281 which I do not see mentioned in #1280 so wanted to bring that up as well. Also note, since we are moving up TP53 to figure 4, I moved up TP53/telomerase to be before UMAP panels in S5 now.

**Comment by sjspielman** [comment]
Closed with #1283 and #1280
