### ISSUE TITLE
Proposed Analysis: Copy number consensus calls

### ISSUE THREAD

**Issue by jharenza** [AlexsLemonade/OpenPBTA-analysis#128]
#### Scientific goals

_What are the scientific goals of the analysis?_
Create consensus calls from ControlFreeC and CNVKit

#### Proposed methods

_What methods do you plan to use to accomplish the scientific goals?_
Breakpoints will not perfectly overlap between algorithms, so the analyst will likely have to define a window for overlap of copy number alterations to deem consensus calls.

#### Required input data

_What input data will you use for this analysis?_
SEG files

#### Proposed timeline

_What is the timeline for the analysis?_
2 weeks

#### Relevant literature

_If there is relevant scientific literature, put links to those items here._

**Comment by xiehongbo** [comment]
We will use additional methods to get CNV calls with a balanced sensitivity and specificity for the cohort.

**Comment by jaclyn-taroni** [comment]
Are you planning on tackling this @jharenza and @xiehongbo? If so, I will mark as `in progress`.

**Comment by fingerfen** [comment]
We have a pipeline, count me in as well!

**Comment by xiehongbo** [comment]
Yeah, we are tackling this.

**Comment by jharenza** [comment]
> We have a pipeline, count me in as well!

@fingerfen - great! What is the pipeline and what inputs do you need? We may have to set you up on CAVATICA to run this.

**Comment by xiehongbo** [comment]
let talk about it today during our meeting.

**Comment by jaclyn-taroni** [comment]
Hi @jharenza @xiehongbo @fingerfen,

Do you have an idea of when we should expect the first pull request for this issue? I am also wondering if we know what the format of the output of this analysis will be now that the two callers have different file formats. This information will help us in development for issues like #6 and #186.

**Comment by jharenza** [comment]
Hi @fingerfen and @xiehongbo - we were able to finish the data releases to include the new CNVkit and ControlFreeC files, so now you are able to submit a pull request with your analysis. Is it possible to do this next week? @fingerfen can you also list here the output columns of your final file for @jaclyn-taroni ? Thanks!

**Comment by hongboxie** [comment]
We assume, that sample QC has been done by the sample noisy level.
here is what we did for summarizing consensus CNVs from three predictors of somatic CNs

1) We define two CNVs are the same event if the CNVs overlapping each other >50% reciprocally. We typically use much higher threshold for Germline CNVs (60-80%)
2) We took any CNVs that are identified by >=2 approaches (cnvkit,freec, etc).
currently we only summarize deletions (CN=0,1) or amplifications (CN>2).
3) We listed each consensus CNV by listing their Chromosome, Start Position, End Position, the original CNV identified by each CNV detection method.
4) Currently we took the average of the breakpoints from different methods as our consensus breakpoints of consensus CNVs.
5) We remove any CNVs that majority of the content overlapping centromere , telomere,  IGLL regions , segmental duplications (>50%) (* note, we do not remove by removing them, but mark the fraction of overlapping those blacklist regions)

**Comment by jashapiro** [comment]
> We assume, that sample QC has been done by the sample noisy level.

I do not understand what this is referring to. Looking at [the manuscript](
https://github.com/AlexsLemonade/OpenPBTA-manuscript/blob/master/content/03.methods.md#somatic-copy-number-variant-calling), I am not clear on what QC steps were performed on CNV calls, if any. Are there standard QC steps that should be added to the CNV results, and/or documented in the manuscript? Perhaps @jharenza or @yuankunzhu can provide some insight here?

**Comment by hongboxie** [comment]
@jharenza  I think we had this discussion before. Do you want to remove samples with extra high noisy levels, or keep every sample regardless. If we do want to remove samples with high noisy level, which "noisy sample" refers sample with high SD of Depth of coverage, we can do so. Otherwise, we can report CNVs from ALL samples. Up to your guys. I am fine with either way.

**Comment by hongboxie** [comment]
@jashapiro when you recover CNVs from given samples, do you remove "noisy" samples? If so, what is your practice to do so?

**Comment by jashapiro** [comment]
@hongboxie That makes sense. As I do not have the raw data, I can't see the raw coverage metrics, but after you brought up such QC, I went to look in the manuscript for details, and didn't find them mentioned. This is not my area of expertise, so I do not know what the standard practices are; I am just trying to understand the data as we work on some of the downstream analysis.

**Comment by hongboxie** [comment]
@jashapiro no worries! I am learning this topic from everyone as well. I am open to any suggestions.

**Comment by jharenza** [comment]
@hongboxie sorry just reading this now... We discussed with @fingerfen to remove any samples if they showed whole genome-gain. That was a measure of inaccurate CN calling. I think we also chose to use a cutoff of >2500 segments for noise to follow what the arrays used, but I also may recall that ControlFreeC might not have smoothed their segments as CNVkit did (ie collapse multiple into one), so they may have a larger number of segments than expected and this cutoff may not be good. @yuankunzhu do you remember when we redid the ControlFreeC TSV file, if this is smoothed?

Otherwise, no samples were removed. When I checked out the CNVkit seg, the sample call quality all looked reasonable in IGV, so this may only apply to controlFreeC.

**Comment by hongboxie** [comment]
We are perplexed by the outcome of Manta. There are multiple CNVs overlapping the same region. Currently we decide to merge all CNVs into one single consent event. There are something strange about Manta somatic CNV output.

**Comment by hongboxie** [comment]
We haven't had change to dig into the root of this problem, yet

**Comment by hongboxie** [comment]
We haven't had a chance to dig into the root of the problem.

**Comment by jharenza** [comment]
> We are perplexed by the outcome of Manta. There are multiple CNVs overlapping the same region. Currently we decide to merge all CNVs into one single consent event. There are something strange about Manta somatic CNV output.

@yuankunzhu  - do you have any advice?

**Comment by jharenza** [comment]
@hongboxie @fingerfen - can you please post the outcomes of our discussion Wednesday re: merging manta calls, and attach the slide deck here? Thank you!

**Comment by hongboxie** [comment]
About Manta:
1) we found many CNVs overlapping the same region in Manta's outcome;
2) It seems those should come from PE based CNV detection (I think)
3)Currently our consent is to merge those CNVs into one segment of CNV, and hoping other methods (CNVkit/FreeC) will help to eliminate any false positives.

**Comment by hongboxie** [comment]
About consensus CNV:
1) I think ploidy detection is subjective, based on current approaches, for instance, it is very hard to get a consensus when one predictor predict there are 30 copies of one segment, the other predictor claims a different number of ploidy. 
2) We will present two types of CNVs: Amplification (ploity>2) or Deletion (ploidy<2). We created 3 additional columns where we display original outcome of each method overlapping this region as evidence. The original output of each predictor will carry the information of the ploidy, if it has it.

**Comment by fingerfen** [comment]
[Pipeline_Visual_Example_on_chr7.pptx](https://github.com/AlexsLemonade/OpenPBTA-analysis/files/3865398/Pipeline_Visual_Example_on_chr7.pptx)

@jharenza Attached is the ppt from Wednesday's presentation. Sorry for the delay.

**Comment by jaclyn-taroni** [comment]
Documenting the outcomes of the in person meeting this afternoon (@jaclyn-taroni @jashapiro @hongboxie @fingerfen):

* The first pull request will consist of the python script that parses the different callers files into files for individual biospecimens + sets up the snakemake file. A step running this script will also get added to `.circleci/config.yml`
* A second step running the snakemake pipeline will need to be added to `.circleci/config.yml` **OR** a shell script that 1. runs `merged_to_individual_files.py` and 2. runs the snakemake pipeline will need to get added and be the single entry in `.circleci/config.yml` for this analysis.
* Subsequent pull requests will contain a single python script and the updates to the snakemake file that run that python script. That allows us to test each script in CI. It's also fine to include some of the bedtool steps along side the python script additions in these pull requests so long as the pull requests are not many (400+) lines of code.
* To make the final file that will be included in the data download, we probably want a single file that contains both DEL and DUP events for all biospecimens.

**Comment by jharenza** [comment]
closed via #357 #349 #328 #313 #403 #288 #416
