### ISSUE TITLE
Complete manuscript figures

### ISSUE THREAD

**Issue by sjspielman** [AlexsLemonade/OpenPBTA-analysis#1282]
This Issue tracks status of completing manuscript figure panels and overall figures and adding them to `figures/scripts/`, `figures/pdfs/`, and as compiled panels.

See here: 
https://docs.google.com/spreadsheets/d/1RbHSHvY8IiSatiX2F1IQYgPs5YgMnRzDoVBt5kwaT50/edit?usp=sharing

**Comment by jaclyn-taroni** [comment]
@sjspielman is Fig 5C missing currently? I _think_ we need a `cp` step in `figures/` for this: https://github.com/AlexsLemonade/OpenPBTA-analysis/blob/master/analyses/immune-deconv/plots/cell_types-molecular_subtypes.pdf and, more generally, to run that module in that script. Going to acknowledge is could be in #1286

**Comment by sjspielman** [comment]
Noting Fig 5C is now present

**Comment by sjspielman** [comment]
Initial compilations have been completed. Closing in favor of tracking new changes in #1368 and #1372
