### ISSUE TITLE
Document which analysis modules are in the manscript

### ISSUE THREAD

**Issue by sjspielman** [AlexsLemonade/OpenPBTA-analysis#1287]
As we solidify the manuscript, we should track which analysis modules are actually going to be part of the paper.

To this end, the analyses [README](https://github.com/AlexsLemonade/OpenPBTA-analysis/blob/master/analyses/README.md) should be updated with an additional column to indicate if the module is part of the paper or not.

**Comment by jaclyn-taroni** [comment]
Closed with #1290
