### ISSUE TITLE
WXS.hg38.100bp_padded.bed is not able to opened normally

### ISSUE THREAD

**Issue by cansav09** [AlexsLemonade/OpenPBTA-analysis#130]
#### File(s)

v5 release data, WXS.hg38.100bp_padded.bed 

#### Release

release-v5-20190924

#### Link to [OpenPBTA-manuscript](https://github.com/AlexsLemonade/OpenPBTA-manuscript/)

NA, this is a question about how to use the file as opposed to how the file was made. 

#### Question/issue

I cannot open this bed file even though I have no problems opening the rest of the BED files. It looks like it may be compressed in some way. I tried gunzipping and unzipping it, but this doesn't work: 

```gunzip: data/WXS.hg38.100bp_padded.bed is not a regular file```

This is what WXS.hg38.100bp_padded.bed looks like if I open it. 

![Screen Shot 2019-09-26 at 1 58 58 PM](https://user-images.githubusercontent.com/23458084/65712796-cf8db480-e065-11e9-825e-3b60f68abcf3.png)

The rest of the BED files look as they should be: 
![Screen Shot 2019-09-26 at 1 59 22 PM](https://user-images.githubusercontent.com/23458084/65712818-dc120d00-e065-11e9-9ba9-35bb0b47c8ce.png)

**Comment by jharenza** [comment]
I can confirm this is actually gzipped without the extension. @migbro, can you provide the gunzipped version on S3 and @yuankunzhu, you may have to update md5, thanks

`507b9d8b84e4:Downloads harenzaj$ head -n 3  WXS.hg38.100bp_padded.bed 
?,ˡ-?ɴi?e?`n??`97??????6??V?dv+h+?
?M+d?:?y???Z!~>K?K??N2??:?}?T=Y[?9k?z?fPO??$p?o??hKo???d?&f.??n?,^?0???%??qǖ?x?L???Z2w???fd2wiS???a@+Yտ??uC???cZ?`u?:??W?gX?~?^ʜ?Yv??8??`????7~x?????Ǻ?7?\?ǲ??@?~,?-??y?95[??*r???3?cM??o?ך?????*0֞??6׾?v?z?c,?F?vk<?%X?40???j8-?g???????5?7&?5?X{??>V?SN??T??l{???Ɨu?7??=gYZ}?q????g3?F??ޭs??O??l?????6웞???`j+????
                          ?&+m?'>?????f?9?ZH??<??O?:?򧟦2G?ɴa?gږ??EV?R?{?i?5p???m??????p?(ӈv??V>i-?wL?VX???F?-?6????g1???LhH?a?5[6?'?ټȶԚL?[??:)_t??ɖ??????Q[|?????b??}?[??4???˚	<},A۶???`_+>s?????o???:<YO?
/?6c???,?B9??X?(s?k???Vǭ"???3?Z?g?~????q???`ZŜ%? #Ӱ?m&Ӷ!=i;L?i???J???dږpG?ɜ,?m?
                                                                               ?m(h?A?|Z?
507b9d8b84e4:Downloads harenzaj$ mv WXS.hg38.100bp_padded.bed WXS.hg38.100bp_padded.bed.gz
507b9d8b84e4:Downloads harenzaj$ gunzip WXS.hg38.100bp_padded.bed.gz 
507b9d8b84e4:Downloads harenzaj$ head WXS.hg38.100bp_padded.bed 
chr1	65409	65725
chr1	65731	66073
chr1	68991	70108
chr1	628924	629533
chr1	785700	787772
chr1	817271	818302
chr1	824278	824538
chr1	826106	827622
chr1	841100	842201
chr1	842002	842362`

**Comment by migbro** [comment]
Yup, my mistake.  File and md5 updated.

**Comment by cansav09** [comment]
Yes! It works now! Thanks!
