### ISSUE TITLE
Contact Docker and CircleCI to ask permission to use icons in Figure 1 panel

### ISSUE THREAD

**Issue by jaclyn-taroni** [AlexsLemonade/OpenPBTA-analysis#1300]
I think it's worthwhile to reach out to docker and CI to see if we can use. We have time before we need the _final_ submission version!

_Originally posted by @sjspielman in https://github.com/AlexsLemonade/OpenPBTA-analysis/issues/1292#issuecomment-1092809714_

**Comment by jaclyn-taroni** [comment]
I've reached out to the relevant teams.

**Comment by jaclyn-taroni** [comment]
If I don't hear back by Friday, I will consider that a no and close this.

**Comment by jaclyn-taroni** [comment]
Haven't heard back - closing this!

**Comment by sjspielman** [comment]
Bummer, but fair!
