### ISSUE TITLE
Updated analysis: check tp53 Figure 4B,C Ns

### ISSUE THREAD

**Issue by jharenza** [AlexsLemonade/OpenPBTA-analysis#1307]
#### What analysis module should be updated and why?
scripts for plots in figure 4B, C

First, I think both panels probably should have the same Ns?
Second, panel B Ns add up to more RNA-Seq specimens (1166) than we have in this cohort, so that one is likely wrong. 

#### What changes need to be made? Please provide enough detail for another participant to make the update.
check Ns, plots may need to be remade - should be using stranded only 

#### When do you expect the revised analysis will be completed?
this week

#### Who will complete the updated analysis?
@sjspielman ?

**Comment by sjspielman** [comment]
FYI @jaclyn-taroni , we should address this before you compile Figure 4. I'm going to look into it today.
