### ISSUE TITLE
Deprecate primary-plus oncoprint plots in `figures/` ?

### ISSUE THREAD

**Issue by sjspielman** [AlexsLemonade/OpenPBTA-analysis#1314]
Currently, the script `figures/scripts/fig2-oncoprint-landscape.R` creates plots for _both_ primary-plus and primary-only. However, at this time, it does not appear that any primary-plus plots will be incorporated in the manuscript directly.

Do we want to deprecate these plots? The script has a for-loop over only vs. plus, so the code is very adaptable.

**Comment by sjspielman** [comment]
CC @jaclyn-taroni

**Comment by jaclyn-taroni** [comment]
I think it would be fine either way. The main advantage to removing this would be to avoid confusion when compiling figures.
