### ISSUE TITLE
Update Figure 2 oncoprint panels

### ISSUE THREAD

**Issue by sjspielman** [AlexsLemonade/OpenPBTA-analysis#1315]
The figure 2 oncoprint primary-only panels have a mismatch between legends and panel: Cancer groups seen in legends are not always seen in the oncoprint figures directly. Specifically:

+ Embryonal legend contains Ganglioneuroblastoma, but this cancer group is not in the landscape plot
+ Diffuse astrocytic legend contains Oligodenroglioma, but this cancer group is not in the landscape plot

Other miscellaneous changes to be made to these panels:
+ Update code to address Issue #1314 
+ Remove underscores from `cancer_group` and `germline_sex_estimate` row labels
+ Make plot titles a bit larger
+ If possible, match the cancer group legend font sizes

**Comment by jaclyn-taroni** [comment]
This might be another good reason to address #1314, yea. I suspect this is the root of the issue!

**Comment by jaclyn-taroni** [comment]
> * Remove underscores from `cancer_group` and `germline_sex_estimate` row labels

For what it's worth, I drop these from my version of the compiled figure, which you can see an older version of [here](https://github.com/jaclyn-taroni/OpenPBTA-analysis/blob/f6bcf253ac3ceb242e2557e82ad259ea3eb0f729/figures/pngs/figure2.png). It would not shock me if this was not technically possible.

**Comment by sjspielman** [comment]
> It would not shock me if this was not technically possible.

Indeed, technically not possible -  see https://github.com/AlexsLemonade/OpenPBTA-analysis/pull/1316

**Comment by sjspielman** [comment]
Closed with #1316
