### ISSUE TITLE
Updated analysis: Create HR figures for HGGs

### ISSUE THREAD

**Issue by jharenza** [AlexsLemonade/OpenPBTA-analysis#1323]
#### What analysis module should be updated and why?
survival analysis: tp53/telomerase and immune cells (PR #1264)

#### What changes need to be made? Please provide enough detail for another participant to make the update.
1. From tp53/telomerase analysis, create HR plot for Figure 4 panel F from data used below:
<img width="502" alt="Screen Shot 2022-04-15 at 1 14 07 AM" src="https://user-images.githubusercontent.com/207034/163523875-c5845af1-9eb9-4101-b2ff-338f6285302b.png">
2. From upcoming edits to immune cell PR #1264 , add HR plot from univariate analysis of molecular subtypes for HGG group (HGG including DMGs and DIPG - same grouping as from tp53/telomerase analysis).
This will probably also go into figure 4 as 4G.

#### What input data should be used? Which data were used in the version being updated?
same as previous

#### When do you expect the revised analysis will be completed?
within a week

#### Who will complete the updated analysis?
@sjspielman

**Comment by sjspielman** [comment]
I'm not sure that it will be possible to get a panel G here as we'd discussed above, given updated results in #1264. But, 4F is done with #1325!

**Comment by jharenza** [comment]
completed with #1332 and #1346
