### ISSUE TITLE
Updated analysis: add NGSCheckmate to Table S4

### ISSUE THREAD

**Issue by jharenza** [AlexsLemonade/OpenPBTA-analysis#1327]
#### What analysis module should be updated and why?
generate tables - missing NGSCheckmate, but I am actually not sure if it is captured [here](https://github.com/d3b-center/OpenPBTA-workflows/tree/master/cwl)

#### What changes need to be made? Please provide enough detail for another participant to make the update.
- We may need to add this to the OpenPBTA-workflows repo first, but sent a msg to @migbro about this for when he gets back from vacation, else perhaps @dmiller15 can inform/update.
- Once we have the link, we can add to the table. 

#### What input data should be used? Which data were used in the version being updated?
[semi-manual code curation
](https://github.com/AlexsLemonade/OpenPBTA-analysis/blob/master/tables/output_tables.Rmd)

#### When do you expect the revised analysis will be completed?
this week

#### Who will complete the updated analysis?
@jharenza

**Comment by jharenza** [comment]
Docker is here: https://github.com/migbro/ngs_checkmate_wf and workflow is here: https://github.com/kids-first/ngs_checkmate_wf

@migbro will be adding a copy of this to the [OpenPBTA-workflows](https://github.com/d3b-center/OpenPBTA-workflows).

**Comment by migbro** [comment]
Updated the dockerfile to our d3b repo here: https://github.com/d3b-center/bixtools/blob/master/ngscheckmate/1.3/Dockerfile
Functionally equivalent prod release here: https://github.com/kids-first/ngs_checkmate_wf/tree/1.0.0

Created a PR in the workflows repo: https://github.com/d3b-center/OpenPBTA-workflows/pull/1

**Comment by jharenza** [comment]
NGSCheckmat3 is v1.3

**Comment by jharenza** [comment]
completed in #1334
