### ISSUE TITLE
key resources table

### ISSUE THREAD

**Issue by sjspielman** [AlexsLemonade/OpenPBTA-analysis#1366]
According to the [Cell guidelines](https://www.cell.com/star-supplemental-information), 

> Please note that the key resources table and STAR Methods text are not considered part of the SI.

The key resources table should be renamed from `TableS5-Key-Resources-table.xlsx` to just `Key-Resources-table.xlsx`.

**Comment by jharenza** [comment]
@sjspielman we may have to reach out to the editors because this is in contrast to what I posted the other day that if we go over the KR table limit, then it becomes a supp table

**Comment by jharenza** [comment]
My read of what you have above is that the actual KR table which they provide the template for, and STAR Methods, are not part of the supplement, but per [this](https://github.com/AlexsLemonade/OpenPBTA-analysis/pull/1360#issuecomment-1117732886), if we expand (>10 items within a heading of the table), then we need to make that an official supp table. If you have a different understanding, then I can email the journal quickly to find out.

**Comment by sjspielman** [comment]
Aha! Thanks. What a shame this information is not linked from the other set of information that says Key Resources isn't SI! We can probably ignore all of this then!

**Comment by jharenza** [comment]
💯
