### ISSUE TITLE
Update LGG plots

### ISSUE THREAD

**Issue by sjspielman** [AlexsLemonade/OpenPBTA-analysis#1372]
Certain plots that use LGG will need to be updated as we move towards #1368. 

+ The oncoprint plots will need to be updated and recompiled
  + We may want to retitle the LGG panel for manuscript consistency.
  + There is some wonky text resulting from figure compilation that we missed.
+ UMAP in S6
+ Potentially GSVA and UMAP in Fig 5, if we want to retitle legends with "low grade glioma"

**Comment by jharenza** [comment]
Related to https://github.com/AlexsLemonade/OpenPBTA-analysis/issues/1368

**Comment by sjspielman** [comment]
Closing in favor of #1403
