### ISSUE TITLE
Establish notebook for interaction plots sample sizes

### ISSUE THREAD

**Issue by sjspielman** [AlexsLemonade/OpenPBTA-analysis#1391]
From [this discussion](https://github.com/AlexsLemonade/OpenPBTA-manuscript/pull/262#discussion_r867084046), we need to add a small notebook to the `interaction-plots` module directly reporting relevant sample sizes we discuss in the manuscript.

**Comment by sjspielman** [comment]
@jharenza can you take this?

**Comment by jharenza** [comment]
Yes, will do!
