### ISSUE TITLE
Planned Analysis: Isoform analysis / patterns

### ISSUE THREAD

**Issue by PichaiRaman** [AlexsLemonade/OpenPBTA-analysis#14]
Determine differential isoforms across PBTA or within specific PBTA cancers and correlate back to genomic or phenotypic characteristics.

**Comment by cbethell** [comment]
I am planning to work on the solution to this issue. I have been looking into relevant literature and found a [paper](https://mcr.aacrjournals.org/content/early/2017/06/02/1541-7786.MCR-16-0459.full-text.pdf) on the `IsoformSwitchAnalyzeR` [R package](https://mcr.aacrjournals.org/content/molcanres/suppl/2017/07/12/1541-7786.MCR-16-0459.DC1/175983_2_unknown_upload_4006125_zp2qfk.pdf) that may be useful for this issue. Would there be any objections to the implementation of this tool or arguments to implement a substitute tool or workflow?

**Comment by cbethell** [comment]
I have been looking into a few different packages to assist in tackling this issue and here are the packages I believe may be relevant: 

- I attempted to implement the `IsoformSwitchAnalyzeR` package functions, but it does not seem to be feasible for this particular dataset, given the magnitude of samples. This particular also seems to prefer GTF files as input. See package vignette [here](https://bioconductor.org/packages/devel/bioc/vignettes/IsoformSwitchAnalyzeR/inst/doc/IsoformSwitchAnalyzeR.html) and the literature [here](https://mcr.aacrjournals.org/content/molcanres/early/2017/06/02/1541-7786.MCR-16-0459.full.pdf). 

- I also dug into the `magSigPro` R package vignette [here](https://www.bioconductor.org/packages/release/bioc/vignettes/maSigPro/inst/doc/maSigProUsersGuide.pdf) and the literature [here](https://academic.oup.com/bioinformatics/article/22/9/1096/200371). Although I did get further in the workflow involving this package, it looks to be tailored for microarray data and may not be suitable for this dataset. 

- I also took a look at the `SGSEq` package [here](https://bioconductor.org/packages/devel/bioc/manuals/SGSeq/man/SGSeq.pdf). The issue with this package in the format in which it expects input. As stated in the vignette [here](https://bioconductor.org/packages/devel/bioc/vignettes/SGSeq/inst/doc/SGSeq.html), it requires mapped reads contained with SAM/BAM files with a custom tag ‘XS’ for spliced reads, indicating the direction of transcription. It also looks for the variable `library_size` which is a "numeric vector with the total number of aligned reads for single-end data, or the total number of read pairs for paired-end data" as also stated in the vignette. This variable is mentioned in most of the packages I dug into. 

- After reading [this paper](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3460195/), I thought that it may be useful to give the `DEXSeq` package a try. I have not dove deep into this particular package as yet, but it seems as if it may also have an issue with the given dataset as it expect multiple SAM/BAM files. 

- In this [vignette](https://combine-australia.github.io/RNAseq-R/06-rnaseq-day1.html), the short section entitled "Differential expression with limma-voom" has been helpful with understanding the first part of this analysis. However, designing and fitting a model is a bit unfavorable for the given dataset with the the relatively large number of samples. Perhaps subsetting may be the solution here? 

Overall, I noticed that most,  if not all, of these packages require the `library_size` variable, as well as transcript annotation stored in a `TxDb` object or a `GRanges` object. 

If you have any strong preferences or suggestions for which direction this analysis should go in or which package should be implemented, please feel free to express them here!

**Comment by jaclyn-taroni** [comment]
Thanks for putting all of these thoughts together @cbethell! The library size information should be relatively easy to come by - I am making the assumption that whatever tools want that information and want a matrix instead of SAM/BAM are looking for counts (off the top of my head/without looking, not sure if we have counts from kallisto or TPM). 

This seems like picking a method may be difficult and I think there is other characterizations to be done with the expression data, as well as the other data, that are higher priority. Let’s put this particular issue on hold for now. It should be much easier to pick up in the future now that you’ve included this information 😄

I will remove the in progress label for the moment.

**Comment by jharenza** [comment]
@cbethell and @jaclyn-taroni - was just reading up on this thread and I think we can help here. We can provide a count matrices - let me see if we can include this in the v5 data download.

I also agree with @jaclyn-taroni about prioritizing. It sounds like the initial description was pretty open-ended and it may be better to revisit this once we have a hypothesis (eg we think there may be differential isoform usage of certain genes across medulloblastoma subtypes or between diagnosis and relapse of DIPG).

**Comment by yuankunzhu** [comment]
Hi @jaclyn-taroni @cbethell as for the counts, we have generated them as part of our pipeline, so we have:
- raw gene read counts from `STAR-GeneCounts`
- expected_count from `RSEM`
- raw exon read counts from `RNASeQC`

We could go back and fetch them all from the original task, but ideally, we'd like to know what analysis needs those in what format. After discussing with @jharenza, we are proposing we start with RSEM expected_count as it takes care of the impact of multi-mapped/low-quality reads, and will be more consistency for the primary TPM/FPKM as they are all calculated by RSEM. But I know some tools will only work with Integer raw counts. And I also noticed there is a potential interest of trying `DEXseq` which will requires exon level counts along with a proper hypothesis/comparison design. Again, this will come back to what analysis we want to run and required what type of counts. Please let us know your thoughts around this.

**Comment by jaclyn-taroni** [comment]
Hi @yuankunzhu we've tabled this specific analysis for now. If we're thinking about v5 more generally, I agree that expected_count from RSEM seems like a good place to start.

**Comment by jaclyn-taroni** [comment]
Closing this for V1 of the manuscript.
