### ISSUE TITLE
Where are the WXS samples in the Lancet dataset?

### ISSUE THREAD

**Issue by cansavvy** [AlexsLemonade/OpenPBTA-analysis#145]
#### File(s)

The Lancet MAF file: `pbta-snv-lancet.vep.maf.gz` doesn't appear to have WXS samples. Is this how it is supposed to be?

#### Release

v5 release-v5-20190924

#### Link to [OpenPBTA-manuscript](https://github.com/AlexsLemonade/OpenPBTA-manuscript/)

In the methods section don't see an indication in the methods that Lancet wasn't run on the WXS files, unless I'm missing that. 

https://github.com/AlexsLemonade/OpenPBTA-manuscript/blob/master/content/03.methods.md#somatic-single-nucleotide-variant-calling

#### Question/issue

It looks like there are no WXS samples in the Lancet dataset? Should that be the case? 

```
# Read in this MAF, skip the version number
maf_df <- data.table::fread("data/pbta-snv-lancet.vep.maf.gz", skip = 1, data.table = FALSE)

# Isolate metadata to only the samples that are in the datasets
metadata <- readr::read_tsv("data/pbta-histologies.tsv") %>%
  dplyr::filter(Kids_First_Biospecimen_ID %in% maf_df$Tumor_Sample_Barcode) %>%
  dplyr::distinct(Kids_First_Biospecimen_ID, .keep_all = TRUE) %>%
  dplyr::arrange() %>%
  dplyr::rename(Tumor_Sample_Barcode = Kids_First_Biospecimen_ID) %>%
  readr::write_tsv(metadata_file)

summary(as.factor(metadata$experimental_strategy))
```
Output from above is `WGS 940`.

**Comment by jharenza** [comment]
@bmennis - see this issue as well - looks like the WXS files were missed here.

**Comment by jharenza** [comment]
Update: it looks like WXS samples were not run, so they are being added to the queue ASAP. Related to #135 (also were run for Vardict).

**Comment by jharenza** [comment]
As an update, we have completed this and they will be ready for #146
