### ISSUE TITLE
Table 1 double counts histologies

### ISSUE THREAD

**Issue by jashapiro** [AlexsLemonade/OpenPBTA-analysis#1459]
The code linked below is used to derive Table 1 in the manuscript, but this code double counts samples where there are WGS and RNA-seq biospecimens. 

https://github.com/AlexsLemonade/OpenPBTA-analysis/blob/6071c5fe89afeb656ade29051a9ceeb17a0effb7/tables/output_tables.Rmd#L78-L86

I believe adding a `distinct(broad_histology, molecular_subtype, sample_id)` line to the above before counting should address the issue and return the proper count.

**Comment by sjspielman** [comment]
@jashapiro looks like this should have been closed with #1465, yes?

**Comment by jharenza** [comment]
Closed with #1448
