### ISSUE TITLE
Planned Data Release: v6

### ISSUE THREAD

**Issue by jharenza** [AlexsLemonade/OpenPBTA-analysis#146]
#### File(s)

_What data file(s) does this issue pertain to?_

#### Release
v6
_What release are you using?_

#### Link to [OpenPBTA-manuscript](https://github.com/AlexsLemonade/OpenPBTA-manuscript/)

_Put a link to the relevant section of the OpenPBTA manuscript here._

#### Question/issue

_Put your question or report your issue here._
This will include updates to:

- Lancet and Vardict files (WXS to be added; vardict file to be fixed) Related to: #145 and #135 
- Clinical file (#131); Add missing `sample_id`, `aliquot_id`, RNA `tumor_descriptor` (#156)
- New strelka2 maf (#153)
- Dropping LUMPY ([comment](https://github.com/AlexsLemonade/OpenPBTA-analysis/issues/27#issuecomment-546350911))
- New CN seg files from updated benchmarked runs, to include gain/loss info, p-values for #128 
- Manta file (#157)

**Comment by jaclyn-taroni** [comment]
Is it possible to perform somatic filtering on the LUMPY file as part of the next release? See https://github.com/AlexsLemonade/OpenPBTA-analysis/issues/27#issuecomment-539151307 from @gonzolgarcia

**Comment by jharenza** [comment]
@jaclyn-taroni - looking into this - looks like we have to run SVTyper on the VCFs first, then do the [specific filtering](https://github.com/arq5x/lumpy-sv/issues/268) mentioned in the issue (not sure how standard practice this filtering is). Perhaps this should also be done on Manta to be consistent, but they also seem to have their own filtering as the file is so much smaller (75MB v. 2.7GB). We will have to do some research into these pipelines before we implement so this may need to come in a later release. Will also followup on this comment and ask for suggestions.

**Comment by jashapiro** [comment]
Hoping this release can also address the strelka2 file issue identified in #153

**Comment by jaclyn-taroni** [comment]
Closed via #190
