### ISSUE TITLE
Update CAVATICA project with V22 release data

### ISSUE THREAD

**Issue by jharenza** [AlexsLemonade/OpenPBTA-analysis#1467]
#### What data file(s) does this issue pertain to?
all

#### What release are you using?

v22

#### Put a link to the relevant section of the [OpenPBTA-manuscript](https://github.com/AlexsLemonade/OpenPBTA-manuscript/) here.
NA

#### Put your question or report your issue here.

Please add V22 release to https://cavatica.sbgenomics.com/u/cavatica/openpbta/files/#q  @zhangb1

**Comment by zhangb1** [comment]
Okay , v22 release is in the project : https://cavatica.sbgenomics.com/u/cavatica/openpbta/files/#q?path=release-v22-20220505

I also updated the volume, using the d3b bucket in the release files.

**Comment by jharenza** [comment]
thanks so much!
