### ISSUE TITLE
Updated analysis: Update Table 2 - hypermutators

### ISSUE THREAD

**Issue by jharenza** [AlexsLemonade/OpenPBTA-analysis#1481]
#### What analysis module should be updated and why?
`tables` for manuscript

#### What changes need to be made? Please provide enough detail for another participant to make the update.
For Table 2, `BS_F0GNWEJJ` should be added.

#### What input data should be used? Which data were used in the version being updated?
histology, clinical databases

#### When do you expect the revised analysis will be completed?
next week

#### Who will complete the updated analysis?
@jharenza will add this to open PR #1448

**Comment by jaclyn-taroni** [comment]
I believe this was closed by #1448, so I'm going to close it!
