### ISSUE TITLE
Re-generate OpenPBTA manuscript display items

### ISSUE THREAD

**Issue by sjspielman** [AlexsLemonade/OpenPBTA-analysis#1487]
This Epic is associated with issues that re-generate and/or re-compile manuscript tables and figures for OpenPBTA. This is necessary with V22 data and palette updates.

**Comment by sjspielman** [comment]
All Epic items have been addressed and merged in! Onwards we march!

**Comment by sjspielman** [comment]
Re-opening for #1563

**Comment by jaclyn-taroni** [comment]
All the issues associated with this Epic are closed. I do not see any new issues that belong in this Epic. I'm going to close this.
