### ISSUE TITLE
Re-generate supplemental UMAP figures

### ISSUE THREAD

**Issue by sjspielman** [AlexsLemonade/OpenPBTA-analysis#1496]
UMAP figure panels for Figure S6 need to be updated for V22 by re-running and updating, as needed, this script:  (https://github.com/AlexsLemonade/OpenPBTA-analysis/blob/master/figures/scripts/supp-subtype-umap.R)

**Comment by jharenza** [comment]
@sjspielman do you want me to take this since you assigned yourself the TMB callers plots?
