### ISSUE TITLE
Planned Analysis: Immune/Stroma characterization across PBTA

### ISSUE THREAD

**Issue by PichaiRaman** [AlexsLemonade/OpenPBTA-analysis#15]
Determine immune/stromal composition using software such as xCell and correlate back to genetic and phenotypic characteristics.

**Comment by jharenza** [comment]
A new method, [MIXTURE](https://www.biorxiv.org/content/biorxiv/early/2019/08/07/726562.full.pdf), seems to do a bit better for tumor microenvironment cell deconvolution than previous methods and was validated with flow cytometry. Code here: https://github.com/elmerfer/MIXTURE.App

**Comment by cgreene** [comment]
I read the MIXTURE paper but didn't find the supplement. The supplement seems like it's pretty necessary to understand how well we'd be able to apply this to our own data. I am excited about the potential of the method, but also a bit cautious after reading the details.

I did tweet about the supplement. bioRxiv keeps moving things around on the website, so it's possible I missed it.
https://twitter.com/GreeneScientist/status/1159799316984356866?s=20

**Comment by jharenza** [comment]
Oh good catch - I don't see it either.

**Comment by cgreene** [comment]
The author ( @elmerfer ) provided a link to the supplement in a comment on bioRxiv
https://www.biorxiv.org/content/10.1101/726562v1#comment-4575975402

I haven't gotten to read it yet but it would be good to go through it.

**Comment by komalsrathi** [comment]
I would like to take this on, potentially using `MIXTURE` as well as  [immunedeconv](https://github.com/grst/immunedeconv) which incorporates methods like `CIBERSORT` and `xCell` along with others to estimate immune cell fractions from bulk RNA.

**Comment by jharenza** [comment]
@komalsrathi great! Looking forward to seeing your analysis!

**Comment by jaclyn-taroni** [comment]
Hi @komalsrathi, do you have an estimate of when we can expect the first pull request adding this analysis? This will help us factor in review as we plan our workload. Thank you!

**Comment by komalsrathi** [comment]
@jaclyn-taroni Potentially by next Friday? (it could be earlier but just giving myself some extra time). Does that sound reasonable? Let me know.

**Comment by jaclyn-taroni** [comment]
Yes sounds good - thank you!

**Comment by komalsrathi** [comment]
@jaclyn-taroni @jharenza It looks like I will be able to create a branch and push my existing scripts today but for the actual pull request, it will take a couple days more - cibersort needed me to request access to the source scripts which I just got my hands on. I would like to finish a correlation plot between all methods used and another cell type visualization per histology (boxplot) before I submit the pull request. Let me know what you think.

**Comment by jaclyn-taroni** [comment]
@komalsrathi you can create a pull request for what you have so far and then add the CIBERSORT steps, correlation, and additional plot in a later pull request(s). Generally pull requests with fewer parts are easier to review. Would that work on your end?

**Comment by komalsrathi** [comment]
I think that should be doable - let me see if I can add a branch with at least 1-2 clean scripts. Thanks!

**Comment by jaclyn-taroni** [comment]
Closing all planned analysis tickets in favor of opening new proposed analysis/updated analysis tickets as needed.
