### ISSUE TITLE
Re-generate tables

### ISSUE THREAD

**Issue by sjspielman** [AlexsLemonade/OpenPBTA-analysis#1510]
We will need to re-generate manuscript tables after V22 updates. This has been started in #1448.

When completing these tables, be aware of the following issues - 

#1459, `Table 1 double counts histologies`
#1481, `Updated analysis: Update Table 2 - hypermutators`

#1407, Add missing key resources

**Comment by jaclyn-taroni** [comment]
This was closed by #1448 per https://github.com/AlexsLemonade/OpenPBTA-analysis/pull/1448#issuecomment-1176351134
