### ISSUE TITLE
Strelka2 maf file read counts seem incorrect

### ISSUE THREAD

**Issue by jashapiro** [AlexsLemonade/OpenPBTA-analysis#153]
#### File(s)

pbta-snv-strelka2.vep.maf.gz

#### Release

v5

#### Link to [OpenPBTA-manuscript](https://github.com/AlexsLemonade/OpenPBTA-manuscript/)

https://github.com/AlexsLemonade/OpenPBTA-manuscript/blob/master/content/03.methods.md#vcf-annotation-and-maf-creation

#### Question/issue

In the strelka2 files, the reference and alt counts for indel variants include `.` characters, which I would not expect to occur. The columns at issue are the following, and in particular the `*_ref_count` columns:
`t_depth t_ref_count t_alt_count n_depth n_ref_count n_alt_count`

It would be worth looking at the original vcf files to see if this is an error in the vcf to maf conversion, or if it is a "feature" of strelka. Strelka's description of the read counts in the vcf file is [here](https://github.com/Illumina/strelka/blob/v2.9.x/docs/userGuide/README.md#somatic-variant-allele-frequencies)

**Comment by jashapiro** [comment]
This was a bug in vcf2maf, that has been fixed in the development branch, at least. 
https://github.com/mskcc/vcf2maf/pull/215

It would be good to have this updated, but if it needs to wait for the next release, that would be okay, as long as there is a note that VAF calculations for indels from strelka will be wrong (and may just silently fail depending on how this is handled).

**Comment by jashapiro** [comment]
Note that the methods at https://github.com/AlexsLemonade/OpenPBTA-manuscript/blob/master/content/03.methods.md#vcf-annotation-and-maf-creation will also need to be updated to reflect the use of vcf2maf v1.6.17

**Comment by jharenza** [comment]
> Note that the methods at https://github.com/AlexsLemonade/OpenPBTA-manuscript/blob/master/content/03.methods.md#vcf-annotation-and-maf-creation will also need to be updated to reflect the use of vcf2maf v1.6.17

@migbro, can you update the github production repo to include this new VCF2MAF version and I can link to it/edit the manuscript?

**Comment by migbro** [comment]
Workflow updated, PR made here: https://github.com/AlexsLemonade/OpenPBTA-manuscript/pull/48

**Comment by cansavvy** [comment]
I was just testing whether this problem is resolved in v6. It looks like it is? Here's what I did to test it. 
@jashapiro is this an adequate test? 
```
maf_df <- data.table::fread("data/pbta-snv-strelka2.vep.maf.gz", skip = 1, data.table = FALSE)
apply(maf_df[, 40:45], 2, summary)
```
Which yielded: 
```
            t_depth t_ref_count t_alt_count
Min.        2.00000     0.00000     0.00000
1st Qu.    53.00000    33.00000     7.00000
Median     66.00000    45.00000    13.00000
Mean       67.09007    47.01008    16.08527
3rd Qu.    77.00000    57.00000    23.00000
Max.    78061.00000 75043.00000 25883.00000
            n_depth n_ref_count n_alt_count
Min.        2.00000     0.00000     0.00000
1st Qu.    28.00000    26.00000     0.00000
Median     35.00000    33.00000     0.00000
Mean       35.51381    33.54354     0.19936
3rd Qu.    41.00000    40.00000     0.00000
Max.    70502.00000 66348.00000  2709.00000
```
 I think if the `.` still persisted `summary would have given an error?

**Comment by jashapiro** [comment]
That does look like it is fixed, as it is treating the columns as numeric, not characters.
