### ISSUE TITLE
Figure S3A includes the wrong groups and `n_per_cancer_group.tsv` has two "Other" rows

### ISSUE THREAD

**Issue by jharenza** [AlexsLemonade/OpenPBTA-analysis#1548]
Per this comment:

Hi @sjspielman - in trying to go through these tables for the manuscript, I realized that we have two "Other CNS" oncoprints - one in Figure 2D and one in S3-A. Currently, both have the same oncoprint, but S3 should have one similar with groups similar to [this](https://github.com/AlexsLemonade/OpenPBTA-analysis/blob/b6ae33b3c10651efd3c417d1f3d9172ef894999e/figures/pdfs/supp/figs3/figureS3.pdf). I think some lines are getting crossed with two groupings called "Other". I also noticed (and my bad for not noticing during review), that we have two "Other" rows in the `*n_per_cancer_group.tsv` tables.

_Originally posted by @jharenza in https://github.com/AlexsLemonade/OpenPBTA-analysis/issues/1498#issuecomment-1186651357_

We need to create a new Figure S3. I think this may be related to our updating of the palette when we removed some of the oncoprint labeling starting at line [377 here](https://github.com/AlexsLemonade/OpenPBTA-analysis/commit/f7852f0b267c5ddd39df71a37c9eb1ff2f3064c8). So I _think_, @jaclyn-taroni , this has to go back in, to color the "Other" (other) CNS cancer groups in the supplemental figure?

Below is where I think this should be updated in the figure script:

https://github.com/AlexsLemonade/OpenPBTA-analysis/blob/045e5c6121c35377f7d7acbd2ce94ce25b9e2b90/figures/scripts/fig2-oncoprint-landscape.R#L363

**Comment by jaclyn-taroni** [comment]
Filling in some more details that will help us solve this.

The difference between the current palette file and the palette file at the same time (commit hash) as the correct Fig S3A linked above is the inclusion of `oncoprint_hex` and `oncoprint_include` columns. The color palette for the supplemental oncoprints is set in `figures/scripts/fig2-oncoprint-landscape.R`. We can use a logical column in the palette in `oncoprint_include` to deal with the distinction between main text and supplemental items.

That fix will not necessarily account for the issue in the tables. Here are the two tables @jharenza is talking about:

* https://github.com/AlexsLemonade/OpenPBTA-analysis/blob/7d0073ce4bf1e4f1b3482ac8252a186a79422a7c/analyses/oncoprint-landscape/tables/primary-plus_n_per_cancer_group.tsv
* https://github.com/AlexsLemonade/OpenPBTA-analysis/blob/7d0073ce4bf1e4f1b3482ac8252a186a79422a7c/analyses/oncoprint-landscape/tables/primary_only_n_per_cancer_group.tsv

The script that creates those tables is [`analyses/oncoprint-landscape/01-map-to-sample_id.R`](https://github.com/AlexsLemonade/OpenPBTA-analysis/blob/7d0073ce4bf1e4f1b3482ac8252a186a79422a7c/analyses/oncoprint-landscape/01-map-to-sample_id.R), which was altered in #1478: https://github.com/AlexsLemonade/OpenPBTA-analysis/pull/1478/files#diff-78e8a5f2db7504a880fe081822de01ca5b98cbde09ee887e7abe508a8d69ce09

**Comment by jaclyn-taroni** [comment]
I'm going to remove my assignment at this point.

**Comment by sjspielman** [comment]
@jharenza I'm looking into this now, and I'm having some trouble relating the previous S3A cancer groups to what we see now. Some of the cancer groups that appear in S3A, as shown [here](https://github.com/AlexsLemonade/OpenPBTA-analysis/blob/b6ae33b3c10651efd3c417d1f3d9172ef894999e/figures/pdfs/supp/figs3/figureS3.pdf), are now hard-coded as "Other CNS broad histologies" in the palette file:
https://github.com/AlexsLemonade/OpenPBTA-analysis/blob/d1d7584b7be7eecba69489da1b29b53c7ba5c724/figures/mapping-histology-labels.Rmd#L430-L456
(note the comments here also say "see permalink above" but there isn't one!)

The S3A groups are _all_ contained in that array, which is used to make the "Other CNS" panel - 
+ `Desmoplastic infantile astrocytoma and ganglioglioma`, `Glial-neuronal tumor NOS`, and `Neurocytoma` are in `Neuronal and mixed neuronal-glial tumor` broad histology
+ `Germinoma` is in `Germ cell tumor` broad histology
+ `Metastatic secondary tumors` is in `Metastatic tumors` broad histology
+ `Pineoblastoma` is in `Tumors of pineal region` broad histology
+ `Rosai-Dorfman disease` is in the `Histiocytic tumor` broad histology
+ `Sarcoma` is in `Mesenchymal non-meningothelial tumor`

I think I'm either missing something glaring, or maybe S3A is no longer needed..?

**Comment by sjspielman** [comment]
PR coming shortly to address part of this issue. I've found what I believe is the culprit, or at least _a_ culprit! There is a bug in this oncoprint script:

https://github.com/AlexsLemonade/OpenPBTA-analysis/blob/6097fc7a02f05c1ccdbc8adf5a8b7ca137941309/analyses/oncoprint-landscape/01-map-to-sample_id.R#L361-L364

Because the argument name is the same as the column name, the `dplyr::filter()` isn't actually filtering. Fixing this function argument to be named _not_ `broad_histology` resolves the duplicated "Other". To ensure this goes through properly (_and_ in order to remake the oncoprint figures which require a populated `scratch/`!), I'm going to re-run the whole module with this code change, and then file PR.

**Comment by sjspielman** [comment]
I've created a separate issue #1555 to just track the updated S3A panel.

This issue can be used, going forward, to specifically track fixing the extra "Other" rows.
