### ISSUE TITLE
Incomplete metadata for RNA-seq biospecimens

### ISSUE THREAD

**Issue by jashapiro** [AlexsLemonade/OpenPBTA-analysis#156]
#### File(s)

pbta-histologies.tsv

#### Release

v5

#### Link to [OpenPBTA-manuscript](https://github.com/AlexsLemonade/OpenPBTA-manuscript/)

N/A

#### Question/issue

RNA-seq samples are missing data in the `tumor_descriptor` column. This information can be gleaned by looking at matched WGS samples, but it would be ideal to have this in the row for each of the RNA-seq samples as well. 

For example, WGS sample `BS_K07KNTFY` has the descriptor `Initial CNS Tumor`, but the matched RNA-seq sample `BS_QWNBZ9RJ` (both have `sample_id` `7316-272`) has no descriptor.

Ideally, this could be fixed for v6 (#146)

**Comment by jharenza** [comment]
@jashapiro we can add that!

**Comment by jharenza** [comment]
Done, will be integrated with #146
