### ISSUE TITLE
Missing sample in pbta-sv-manta.tsv

### ISSUE THREAD

**Issue by fingerfen** [AlexsLemonade/OpenPBTA-analysis#157]
#### File(s)

Pertains to "pbta-sv-manta.tsv" file under "Kids.First.Biospecimen.ID.Tumor" column

#### Release

release-v5-20190924

#### Question/issue

I think there are 940 unique 'Kids.First.Biospecimen.ID.Tumor' samples for Cnvkit and ControlFreeC data. However, there are only 939 unique 'Kids.First.Biospecimen.ID.Tumor' samples in the Manta file. The missing sample is named 'BS_HSYF7G2D'. I am just wondering if this is because Manta didn't detect anything for this sample or is it due to something else. 

Thanks,

Nhat Duong

**Comment by jharenza** [comment]
Thanks @fingerfen! It looks like that sample was missed during annotation. We will try to get this fixed in #146 !

**Comment by jharenza** [comment]
Update: this has been completed and will be added to #146.

**Comment by fingerfen** [comment]
Thank you very much for the quick response!
