### ISSUE TITLE
Updated analysis: Remove NF1 from Table 2

### ISSUE THREAD

**Issue by jharenza** [AlexsLemonade/OpenPBTA-analysis#1591]
#### What analysis module should be updated and why?
manuscript tables

#### What changes need to be made? Please provide enough detail for another participant to make the update.
Remove NF1 as a cancer predisposition for the hypermutators in Table 2. A separate, unrelated project discussion with Dr. Kristina Cole brought up the discussion that clinically, patients with CMMRD often are mistaken for having NF1 because of the presence of café-au-lait spots, but this is separate of NF1. See publication [here](https://pubmed.ncbi.nlm.nih.gov/27779754/) for this interesting information.

#### What input data should be used? Which data were used in the version being updated?
same, just remove NF1

#### When do you expect the revised analysis will be completed?
Today

#### Who will complete the updated analysis?
@jharenza 

Updated in #1577

**Comment by sjspielman** [comment]
Missed this issue before, so I now see why NF-1 was removed from in #1577!

**Comment by jharenza** [comment]
completed in #1577
