### ISSUE TITLE
Add script to run analyses not used in figures

### ISSUE THREAD

**Issue by sjspielman** [AlexsLemonade/OpenPBTA-analysis#1593]
This issue emerged from this discussion: https://github.com/AlexsLemonade/OpenPBTA-analysis/pull/1543#discussion_r936705688

We currently have the following scripts to run OpenPBTA in various ways:
- `scripts/generate-analysis-files-for-release.sh`: Runs analyses needed to perform subtyping 
- `scripts/run-for-subtyping.sh`: Runs subtyping
- `scripts/run-analyses-for-figures.sh`: [Pending in #1543]: Runs analyses needed for making figures
- `figures/generate-figures.sh`: Runs figure generation scripts and copies over a few manuscript panels from analyses

What is missing from this list is a script that can re-run analysis modules _after subtyping_ which aren't needed for figure generation. To this end, we should create a new script `scripts/run-analyses-after-release.sh` (feedback for name @jaclyn-taroni?) which will run additional analysis modules that are used in the manuscript but not specifically for figures, and need to be re-run with the subtyping information. From what I can tell, these modules include the following which will need to consume the subtyped histologies file -

- [focal-cn-file-preparation](https://github.com/AlexsLemonade/OpenPBTA-analysis/tree/master/analyses/focal-cn-file-preparation)
- [fusion_filtering](https://github.com/AlexsLemonade/OpenPBTA-analysis/tree/master/analyses/fusion_filtering)
- [run-gistic](https://github.com/AlexsLemonade/OpenPBTA-analysis/tree/master/analyses/run-gistic)

**Comment by jaclyn-taroni** [comment]
Should this be everything that isn't deprecated? Which is more than the three you've listed.

**Comment by sjspielman** [comment]
> Should this be everything that isn't deprecated?

Including or excluding those in `generate-analysis-files-for-release.sh`?

**Comment by jaclyn-taroni** [comment]
That _is the question_. I'm trying to wrap my head around what might be the least confusing at this point.

**Comment by sjspielman** [comment]
Closing in favor of #1595
