### ISSUE TITLE
Script for running analyses after release 

### ISSUE THREAD

**Issue by sjspielman** [AlexsLemonade/OpenPBTA-analysis#1595]
Based on separate conversation with @jaclyn-taroni, we will be using this new (`final.final` 🤞) approach to running analyses/figures. _**This approach displaces #1455.**_

0. When it is time to cut a new data release, run [`scripts/generate-analysis-files-for-release.sh`](https://github.com/AlexsLemonade/OpenPBTA-analysis/blob/master/scripts/generate-analysis-files-for-release.sh). This script runs non-subtyping analysis modules that are needed to generate data for the release.
1. Perform molecular subyping to include in the release by running the script [`scripts/run-for-subtyping.sh`](https://github.com/AlexsLemonade/OpenPBTA-analysis/blob/master/scripts/run-for-subtyping.sh)
    - _At this time, a release is cut_ which includes the relevant results from modules as well as the metadata file `pbta-histologies.tsv` that is generated during subtyping.
    - Locally, one can run [`download-data.sh`](https://github.com/AlexsLemonade/OpenPBTA-analysis/blob/master/download-data.sh) to update to the new data release.
2. Run all analyses that are not deprecated  _and_ are used in the manuscript. A full table of analyses [here](https://github.com/AlexsLemonade/OpenPBTA-analysis/tree/master/analyses#readme) indicates which analyses satisfies these conditions. This table also shows which modules consume results from other modules, which is helpful for ensuring analyses are run in the correct order. This script does not yet exist, but we will create it by modifying [`scripts/run-analyses-for-figures.sh`](https://github.com/AlexsLemonade/OpenPBTA-analysis/blob/master/scripts/run-analyses-for-figures.sh) to run all such analyses, rather than just analyses used for figures. It should also be renamed, something like `run-manuscript-analyses.sh`.
3. The manuscript figure panels can be generated with [`figures/generate-figures.sh`](https://github.com/AlexsLemonade/OpenPBTA-analysis/blob/master/figures/generate-figures.sh). This script assumes that the previous script (`run-manuscript-analyses.sh`) has been locally run and all necessary input files (including some `SQL` databases in `scratch/`!) exist. Checking is not generally performed.

**Comment by sjspielman** [comment]
I think we can also use this opportunity to clean this script up - it shouldn't have to run `collapse-rnaseq` at this point at all so the flag can probably go away. @jaclyn-taroni , eh?

https://github.com/AlexsLemonade/OpenPBTA-analysis/blob/b1d2411c4d7b882ddb3fba122a2ab63c377b1b21/analyses/telomerase-activity-prediction/RUN-telomerase-activity-prediction.sh#L19-L34

**Comment by jaclyn-taroni** [comment]
> it shouldn't have to run `collapse-rnaseq` at this point at all so the flag can probably go away.

Sure

**Comment by sjspielman** [comment]
>  I guess maybe keeping this flag could be the way to go?

After much back-and-forth with myself, I have decided we should keep the flag and leave this script alone!
