### ISSUE TITLE
Updated analysis: count-contributions to include Yang Yang as a module contributor

### ISSUE THREAD

**Issue by jharenza** [AlexsLemonade/OpenPBTA-analysis#1599]
#### What analysis module should be updated and why?
`count-contributions` accounts for @yangyangclover's total contributions, but they are not being captured in the module contributions [here](https://github.com/AlexsLemonade/OpenPBTA-analysis/blob/master/analyses/count-contributions/results/module_contribution_counts.tsv) because the module was renamed from `sv-analysis` to `chromothripsis` following those contributions in [this PR](https://github.com/AlexsLemonade/OpenPBTA-analysis/pull/1069).

#### What changes need to be made? Please provide enough detail for another participant to make the update.
Manually add @yangyangclover as a module contributor in [this script](https://github.com/AlexsLemonade/OpenPBTA-analysis/blob/master/analyses/count-contributions/02-format-contributions.Rmd)

#### Who will complete the updated analysis?
@jaclyn-taroni  or @jharenza ?

**Comment by jashapiro** [comment]
I think the proper solution here is going to be to fix the initial script `01-count-coontributions.sh` to track the renaming. We so not want to be manually modifying the output.

**Comment by jharenza** [comment]
> I think the proper solution here is going to be to fix the initial script `01-count-coontributions.sh` to track the renaming. We do not want to be manually modifying the output.

manual add was suggested by @jaclyn-taroni :)

**Comment by jashapiro** [comment]
Turns out that tracking a file name change gets pretty hacky, it turns out. I retract the correct in favor of the easy.

**Comment by jharenza** [comment]
closed with #1600
