### ISSUE TITLE
Planned Analysis: Primary vs Relapse

### ISSUE THREAD

**Issue by PichaiRaman** [AlexsLemonade/OpenPBTA-analysis#16]
Compare primary samples to relapse samples to determine genomic and transcriptomic differences and identify trends. See (https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5172533/).

**Comment by PichaiRaman** [comment]
I thought I may work on this. @cgreene Let me know if you prefer we wait and do other analyses first.

**Comment by cgreene** [comment]
I believe that the Docker/CI stuff is in a reasonable enough place that it's possible for folks to jump into things more. Getting a set of analyses done will help us continue to improve the instructions for new contributors. I'd be happy to see what comes of this! 👍 

Can you take a look at the new issue template for proposed analyses, and maybe write brief blurbs about this? I'm hoping they will help us also clearly convey the findings in the manuscript:
https://github.com/AlexsLemonade/OpenPBTA-analysis/blob/master/.github/ISSUE_TEMPLATE/propose-an-analysis.md

**Comment by jaclyn-taroni** [comment]
@PichaiRaman are you still working on this issue? It would be great to have you flesh this out a bit more using the [template for proposed analyses](https://github.com/AlexsLemonade/OpenPBTA-analysis/blob/master/.github/ISSUE_TEMPLATE/propose-an-analysis.md) as a guide. This could be particularly helpful if someone else works on the issue, as it will give us more information for what you were upon filing.

**Comment by jharenza** [comment]
@PichaiRaman - from our discussion in person, it sounded like you are not working on this anymore. Are you able to add additional information, per @jaclyn-taroni's request? Thank you!

**Comment by jaclyn-taroni** [comment]
The last table in [this section](https://alexslemonade.github.io/OpenPBTA-analysis/analyses/sample-distribution-analysis/03-tumor-descriptor-and-assay-count.nb.html#disease_type_-_descriptors_pairs) of the notebook added in #213 tells us that there are few instances where we have primary tumor data and recurrence data:

| disease_types | descriptors | n |
|---------------|-------------|---|
Ependymoma | Initial CNS Tumor, Recurrence | 5|
| Low-grade glioma;astrocytoma (WHO grade I/II) | Initial CNS Tumor, Recurrence | 4 |
| Ganglioglioma | Initial CNS Tumor, Recurrence | 2 |
| Low-grade glioma;astrocytoma (WHO grade I/II) | Initial CNS Tumor, Progressive, Recurrence | 2|
| Chordoma | Initial CNS Tumor, Progressive, Recurrence | 1 |
| Meningioma | Initial CNS Tumor, Recurrence | 2|
| Dysembryoplastic neuroepithelial tumor | Initial CNS Tumor, Recurrence | 1 |
| Ependymoblastoma, Medulloblastoma | Initial CNS Tumor, Recurrence | 1 |
| Ewings Sarcoma | Initial CNS Tumor, Recurrence | 1 |
| High-grade glioma;astrocytoma (WHO grade III/IV) | Initial CNS Tumor, Recurrence | 1 |
| Rosai-Dorfman Disease, Sarcoma | Initial CNS Tumor, Recurrence | 1 |

**Comment by jharenza** [comment]
closing this; made with a template in #330
