### ISSUE TITLE
Proposed Analysis: Getting a consensus set of SNV mutations 

### ISSUE THREAD

**Issue by cansavvy** [AlexsLemonade/OpenPBTA-analysis#161]
#### Scientific goals

From the results of the four mutation callers, determine a set of mutations that we believe are reliable and real. 

#### Proposed methods

**Overall steps:** 
1) Get an initial evaluation of each caller (implemented by #117, #118, #125, #126, and  #144). 
2) Compare the callers with each other (in progress but set up by #159)

The [snv-caller  README](https://github.com/AlexsLemonade/OpenPBTA-analysis/tree/master/analyses/snv-callers) explains aspects of this analysis this in more detail. 

#### Required input data

pbta-snv-lancet.vep.maf.gz
pbta-snv-mutect2.vep.maf.gz
pbta-snv-strelka2.vep.maf.gz
pbta-snv-vardict.vep.maf.gz

#### Proposed timeline

The set up for this will be mostly wrapped up this week. If the data are ready, we can run this next sprint. 

#### Relevant literature/information

https://software.broadinstitute.org/cancer/cga/mutect
https://github.com/AstraZeneca-NGS/VarDict
https://github.com/Illumina/strelka
https://github.com/nygenome/lancet

**Comment by cansavvy** [comment]
From in person talk with @jashapiro, plan is to: 

1) Turn distribution sina plots into density plots 
2) Do experiment with increasing VAF cutoffs -> recalculate TMB and determine if this improves TMB correlations across callers. Can we recover VarDict by increasing VAF cutoff? 
3) Turn TMB distribution into facet wrapped plot so it is more easily readable.

**Comment by cansavvy** [comment]
Ran the full v6 data. Will upload and add a report. VarDict could not be run because of out-of-memory issues. Will need to optimize some memory intensive steps and figure out an acceptable VAF cutoff for VarDict to actually be run. That being said the consensus made without VarDict is probably more reliable.

**Comment by cansavvy** [comment]
[consensus_mutation.maf.tsv.zip](https://github.com/AlexsLemonade/OpenPBTA-analysis/files/3797553/consensus_mutation.maf.tsv.zip) I will add a more detailed summary of this to the README.

**Comment by jaclyn-taroni** [comment]
Subsumed by #207? What do you think @cansavvy ?

**Comment by jharenza** [comment]
Should we close this one since this was released with #273 ?

**Comment by jaclyn-taroni** [comment]
This is probably better tracked with #275 as well
