### ISSUE TITLE
New data release to handle EPN fusion encoding

### ISSUE THREAD

**Issue by sjspielman** [AlexsLemonade/OpenPBTA-analysis#1618]
Note that this is not a formal reviewer request, but it is a revision that is necessary to proceed with certain revisions and for re-submission more generally.

This PR from the `PediatricOpenTargets` project ([#440 Updated analysis: fusion-summary: modify ependymoma gene pairs](https://github.com/PediatricOpenTargets/ticket-tracker/issues/440)) identified and addressed an incorrect encoding of the data in the fusion module.

This fix will need to be implemented for OpenPBTA as well, via a new data release.

**Comment by jharenza** [comment]
Closed with #1648
