### ISSUE TITLE
Revision: Tumor purity and transcriptomics exploration

### ISSUE THREAD

**Issue by sjspielman** [AlexsLemonade/OpenPBTA-analysis#1621]
From https://github.com/AlexsLemonade/OpenPBTA-manuscript/issues/377

Add an exploratory notebook that looks at relationship between tumor purity and some results from transcriptomics analyses. For example, we can look at:
- EXTEND scores vs tumor purity
- tp53 scores vs tumor purity

It's not immediately clear to me what we could do with GSVA scores, so tagging in some folks for discussion @jaclyn-taroni @jashapiro @jharenza 

Since this notebook will rely on the output from a couple other modules (`telomerase-activity-prediction` and `tp53_nf1_score` for example), it might be a good idea to go ahead and add a `tumor_purity_exploration` module to hold this notebook.

**Comment by jaclyn-taroni** [comment]
My knee jerk reaction upon reading the relevant reviewer comment was "regress out" tumor purity. To quote [this blog post from Rob Alderman](https://www.rga78.com/blog/2015/9/23/intro-to-regression-part-8-multiple-regression-regressing-on-two-numeric-variables):

> By "regress out", we mean to "remove any correlative influence" of one variable from another, so that we can examine the variable in "isolation", so to speak. We do this by building a simple regression model for the two variables, treating one as the response and the other as the regressor (the one being "regressed out"), then taking the residuals and making some use of them (e.g. correlating them with another variable).
> 
> The residuals represent the "leftover" variance in the response variable after removing (i.e. "accounting for") any correlative relationship with the regressor variable. In other words, the residuals represent the portion of the response variable's variance that is NOT explained by the regressor variable. 

Knee jerk reactions, famously, are not always good.

**Comment by sjspielman** [comment]
It sounds to me like you are proposing (with knee jerk caveat!) something conceptually along these lines - 
`lm(EXTEND ~ histology + tumor purity)`, and then regress out `tumor purity`. What to then do with the resulting residuals?

**Comment by sjspielman** [comment]
Another idea (h/t @envest!) could involve running transcriptomics analyses again but only focusing on samples with >=X % tumor purity. 
If _vibes_ match between all samples and, say, only samples that are >=95% tumor, then we're good.

**Comment by sjspielman** [comment]
I've started (emphasis on started!) a notebook here https://github.com/sjspielman/OpenPBTA-analysis/blob/sjspielman/tumor-purity-transcriptomics/analyses/tumor-purity-exploration/02_tumor-purity-transcriptomics.Rmd

**Comment by envest** [comment]
👍 Does this X% threshold affect all cancer types equally? Or would some cancer types be more affected than others by excluding low purity? (I'm guessing the latter)

**Comment by sjspielman** [comment]
To begin assessing feasibility, I'll explore in #1622 how the overall distributions of cancer groups/broad histologies is affected when a median (or other) threshold is applied.

**Comment by sjspielman** [comment]
Noting that I'm going to be opening a couple other issues to reorganize our approach here. For the time being I'm going to leave this issue open but it may get closed in the shuffle in the not distant future.

**Comment by sjspielman** [comment]
I'm going to go ahead and close this issue to focus on the more granular other issues for revision of each transcriptomics analysis.
