### ISSUE TITLE
Revision: Run and assess GSVA results at threshold

### ISSUE THREAD

**Issue by sjspielman** [AlexsLemonade/OpenPBTA-analysis#1626]
To assess the affects of tumor purity on our results, we should re-run GSVA, considering only samples that have `tumor_fraction>= median tumor fraction` (https://github.com/AlexsLemonade/OpenPBTA-analysis/pull/1622).

We should then assess how well the following results hold up:
- MYC upregulation in HGG, DMG, MB, and ATRT --> upregulation of MYC + E2F targets+  G2M (cell cycle phase following S phase) in MBs, ATRTs, and HGGs. LGGs downregulated here.
  - https://github.com/AlexsLemonade/OpenPBTA-manuscript/blob/b0fdf6f24fe9c021f22e8b7da348708f68877ee5/content/03.results.md?plain=1#L274-L276
- upregulation of cytokines ifn-gamma, il-1, il-6 in Schwannomas and neurofibromas
  - https://github.com/AlexsLemonade/OpenPBTA-manuscript/blob/b0fdf6f24fe9c021f22e8b7da348708f68877ee5/content/03.results.md?plain=1#L277
- upregulation of IFN-alpha and IFN-gamma in LGGs and craniopharyngiomas compared to medulloblastoma and ependymoma which show IFN-alpha downregulation
  - https://github.com/AlexsLemonade/OpenPBTA-manuscript/blob/b0fdf6f24fe9c021f22e8b7da348708f68877ee5/content/03.results.md?plain=1#L279

**Comment by sjspielman** [comment]
@jharenza I wonder if you could weigh in on something really quickly - I'm going through all of these (almost done!!) to see if trends identified in the MS are broadly consistent after tumor purity filtering (preview: so far consistent!). 

But, I realize our wording in this MS sentence might need some clean-up in general since I'm not exactly sure what it's referring to: 
https://github.com/AlexsLemonade/OpenPBTA-manuscript/blob/b0fdf6f24fe9c021f22e8b7da348708f68877ee5/content/03.results.md?plain=1#L279 
> We also observed significant upregulation of pro-inflammatory cytokines IFN$\alpha$ and IFN$\gamma$ in LGGs and craniopharyngiomas compared to medulloblastoma and ependymoma tumors (Bonferroni-corrected p < 0.05), both of which showed significant down-regulation of these cytokines (**Figure {@fig:Fig5}B**).

Is this making a statement _specifically_ about comparing LGG to MB (for example, and so on..), or a broad statement overall LGG comparisons, MB comparisons, etc to any other cancer group?

**Comment by jharenza** [comment]
sure - this is saying:
up in in LGG compared to MB 
up in LGG compared to EPN
up in Cranio compared to MB
up in cranio cpmpared to EPN

based on how i wrote it 😬
