### ISSUE TITLE
Revision: Replace "Ependymal tumor(s)" --> "Ependymoma" in figures

### ISSUE THREAD

**Issue by jharenza** [AlexsLemonade/OpenPBTA-analysis#1652]
#### What analysis module should be updated and why?
Per reviewer comment, harmonize "ependymal tumor" and "ependymoma". We only have a few instances of "Ependymal tumor", so we can replace with "Ependymoma". 

#### What changes need to be made? Please provide enough detail for another participant to make the update.
1. Updates to broad histology display in the palette.
2. Update figures with "Ependymal tumor".
  - Figure 1B
  - Figure 5A
  - Figure S6B
  - Figure S6E

**Comment by sjspielman** [comment]
Noting that this will hopefully "just happen" as part of the final Big Run™️, given changes being made in #1666 (which addresses item 1 in https://github.com/AlexsLemonade/OpenPBTA-analysis/issues/1652#issue-1535779766).

**Comment by sjspielman** [comment]
All set as part of the Big Figure Run™️: https://github.com/AlexsLemonade/OpenPBTA-analysis/pull/1677#issuecomment-1438770171
