### ISSUE TITLE
Revision: Assemble a supplemental figure comprised of tumor purity threshold panels

### ISSUE THREAD

**Issue by jaclyn-taroni** [AlexsLemonade/OpenPBTA-analysis#1665]
We have a number of notebooks exploring transcriptomic analyses with high purity tumors. These are often in whatever module the analysis is performed in. Organizing them in this manner in the code base makes sense, but it does mean it's not that easy to point someone to a single place that captures all of the re-analysis. So we should perform the additional step of assembling these panels into a supplemental figure _regardless of whether or not it ultimately gets included in the manuscript_, which depends on the journal's guidelines.

Here's what I'm thinking (plan devised by looking at main display items in the manuscript):

- [x] **Panel A** distribution of tumor purity by cancer group https://github.com/AlexsLemonade/OpenPBTA-analysis/blob/78e4969b99b4ebbc22915b9d8b58b5b3f6a9cad5/analyses/tumor-purity-exploration/01_explore-tumor-purity.Rmd#L128-L129
- [x] **Panel B** _TP53_ classifier ROC for stranded data (related to: https://github.com/AlexsLemonade/OpenPBTA-analysis/issues/1624)
- [x] **Panel C** _TP53_ Score (#1624) and EXTEND box plots https://github.com/AlexsLemonade/OpenPBTA-analysis/blob/78e4969b99b4ebbc22915b9d8b58b5b3f6a9cad5/analyses/telomerase-activity-prediction/07_EXTEND-at-threshold.Rmd#L126
- [x] **Panel D** remake UMAP with high purity tumors only (I don't think this exists yet? So up for discussion.)
- [x] **Panel E** quanTIseq estimations of immune fractions across cancer groups https://github.com/AlexsLemonade/OpenPBTA-analysis/blob/78e4969b99b4ebbc22915b9d8b58b5b3f6a9cad5/analyses/immune-deconv/03-quantiseq-at-threshold.Rmd#L93

This will probably require alterations to the notebooks that perform the new calculations/re-analysis to either save numerical results or the plots to get copied over to `figures/`.

**Comment by sjspielman** [comment]
> remake UMAP with high purity tumors only (I don't think this exists yet? So up for discussion.)

Indeed, this does not exist yet, but I'm looking into it now. 

We may also want to make new versions of Fig 4 B/C (TP53 scores and TP53 expression, respectively, across TP53 status) - https://github.com/AlexsLemonade/OpenPBTA-analysis/blob/a4266d4312e240987790aa6e051a7adadfc83b27/figures/pdfs/fig4/figure4.pdf
