### ISSUE TITLE
Revision: UMAP at tumor purity threshold

### ISSUE THREAD

**Issue by sjspielman** [AlexsLemonade/OpenPBTA-analysis#1667]
We'll want to re-generate the UMAP at the tumor purity threshold. For this, we'll add functionality to the `transcriptomic-dimension-reduction` module to:

- Generate UMAP for tumor purity filtered data
- Add a notebook to compare that UMAP to the original UMAP made from the full data

**Comment by jaclyn-taroni** [comment]
> * Add a notebook to compare that UMAP to the original UMAP made from the full data

I’m not sure if you have to do that if you can skip right to #1665. Might save us some time.

**Comment by sjspielman** [comment]
Because this is how things work, I am naturally seeing this comment https://github.com/AlexsLemonade/OpenPBTA-analysis/issues/1667#issuecomment-1431960984 right after I finished writing a barebones notebook for this. I think I'll put it into the PR I file for this and during review we can decide to either:
- scrap the notebook and make it a script in `figures/` instead
- have the notebook export a UMAP that can be copied over to `figures/` for the #1665 figure
