### ISSUE TITLE
Revise S7 to include information about RNA-seq batch effects

### ISSUE THREAD

**Issue by jaclyn-taroni** [AlexsLemonade/OpenPBTA-analysis#1691]
Not fully captured by the issue title, but here are the three panels we want to add to what is currently Figure S7:

- [x] **(A)** a bar plot showing distributions of disease type (`cancer_group_display`), broken up by library prep strategy (`RNA_library`) – the objective is to illustrate that disease type is unbalanced between poly-A and stranded datasets, so whatever bar plot strategy we think best communicates this works. 
- [x] **(B)** a UMAP plotting samples from both selection strategies on the same coordinates: https://alexslemonade.github.io/OpenPBTA-analysis/analyses/selection-strategy-comparison/01-selection-strategies.nb.html#raw_clustering
- [x] **(C)** the UMAP plot highlighting sequencing center: https://alexslemonade.github.io/OpenPBTA-analysis/analyses/transcriptomic-dimension-reduction/04-explore-sequencing-center-effects.nb.html#cancer_group_umap

_Current panels_ **A-F** become **(D-I)**: https://github.com/AlexsLemonade/OpenPBTA-analysis/blob/627ec427ad0a8d9d913e614c9db50546c56d8283/figures/generate-figures.sh#L188-L210

Then this needs to be recompiled. 

We may be better served by splitting this up, but best to start somewhere!

**Comment by sjspielman** [comment]
Noting Panel A is now being tracked in #1694.

**Comment by sjspielman** [comment]
S7 has been completed and compiled (#1728). This issue is now all set!
