### ISSUE TITLE
Upload CSVs to Zenodo

### ISSUE THREAD

**Issue by sjspielman** [AlexsLemonade/OpenPBTA-analysis#1727]
This issue is broken out of #1692. Once all CSVs are set, time to send it to Zenodo and get a DOI!

**Comment by jaclyn-taroni** [comment]
Before I go ahead and upload to Zenodo, @sjspielman will do a final quality check first thing tomorrow. @sjspielman, you can find `openpbta-manuscript-figure-data.zip` in the shared CCDL drive in the `OpenPBTA` folder.

I created it with the following command from the `tables/zenodo-upload` directory:

```
zip -r openpbta-manuscript-figure-data.zip . -x '.*'
```

This should prevent the `.DS_Store` files and `.gitignore` from being included. (I thought including `.gitignore` in the Zenodo upload would be more confusing than helpful). 

Please confirm that you are able to unzip properly and that there are no hidden files. I checked locally with `zipinfo` but might as well double-check while you're at it!

**Comment by sjspielman** [comment]
> Please confirm that you are able to unzip properly and that there are no hidden files. 

Confirmed! However, the README is not the most recent version, so that file needs to be replaced.

**Comment by jaclyn-taroni** [comment]
Thanks, @sjspielman. I've remedied that and used the same command to generate a new zip file. I am in the middle of the Zenodo upload right now!
