### ISSUE TITLE
Request metadata: patient age at last followup, smoking history, alcohol usage

### ISSUE THREAD

**Issue by guru-yang** [AlexsLemonade/OpenPBTA-analysis#177]
As discussed in issue #27 , I'd like to request patient age at last followup, smoking history, alcohol usage if available. Thanks.

**Comment by cgreene** [comment]
@guru-yang : I've updated the title. I'm going to guess that smoking history and alcohol usage is going to be unlikely to be available with this study, and also that in many cases here that there would be no smoking history or alcohol usage. Is there a reason that these variables would aid the analysis described in #27?

**Comment by jharenza** [comment]
Hi @guru-yang ! We do not have smoking history or alcohol usage for this patient cohort, but we do have age at last followup. Will just double check that we can share this metadata, as it is not in the DRC, but was used for survival calculations, so hopefully, won't be a problem.

**Comment by guru-yang** [comment]
@cgreene Smoking and alcohol usage are known to contribute to genome instability. @jharenza Good idea. We ended up using SNV signature to measure smoking in a lung cancer study, since self-reported smoking history is somewhat not accurate. Thanks.

**Comment by cgreene** [comment]
@guru-yang : I realize that in other settings smoking and alcohol usage are known to contribute, but these are pediatric cancers. If you look at the `age_at_diagnosis` column of the `pbta-histologies.tsv` file I think you'll see something that suggests that in this population those risk factors are probably not a major driver of genome instability. Does this help?

**Comment by allisonheath** [comment]
It would be interesting if we knew the status of these for the parents - but this is not something we collect at this time. We are working on revamping some of our clinical data collection, so will put a note to include this in the future if possible, but it won't be available for this analysis.

**Comment by guru-yang** [comment]
@cgreene I am fully aware, that's why I was asking about the parents. About one third of the patients in this cohort are teenagers, some of them might use tobacco and alcohol. Measuring by SNV signatures is probably the best way.

**Comment by jharenza** [comment]
Added age at last follow up to #190 , but the rest of the information is not available.
