### ISSUE TITLE
Proposed Analysis: map from SEG file to genes (and broader segments)

### ISSUE THREAD

**Issue by jaclyn-taroni** [AlexsLemonade/OpenPBTA-analysis#186]
#### Scientific goals

We currently have copy number information in the form of SEG files. The goal of this analysis is to generate focal copy number files for consumption in the oncoprint (#6) and co-occurrence/mutual exclusivity modules (#13). In essence we want to know what genes are amplified or deleted in each sample for downstream analysis. ~This will also have an element of determining what thresholds are appropriate to make the focal copy number calls.~ See: https://github.com/AlexsLemonade/OpenPBTA-analysis/issues/186#issuecomment-548345704

The output of this analysis should be data in tabular format:

| gene_symbol | biospecimen_id | label |  seg.mean  |
|:-------------:| :---------------:|:----:|:------------:|
| SMARCB1  | BS_XXXXXXXX | Hem_Deletion | some float |
| ... | ... | ... | ... |
| ... | ... | ... | ... |
| ... | ... | ... | ... |

As @jharenza pointed out [here](https://github.com/AlexsLemonade/OpenPBTA-analysis/pull/182/files#r340587968) on #182, it is not known at this time if we can make homozygous/hemizygous calls.

#### Proposed methods

Here's how we think this work should be broken up into a series of steps (as discussed with @cbethell and @jashapiro in person):

1. Put together code, adapted from [this code](https://github.com/marislab/pptc-pdx-copy-number-and-SVs/blob/0117f5c5ea89f0c364178ab9423807bb1362e66e/R/focal-CN-revision.R) linked by @jharenza, that takes a SEG file as input and produces the tables outlined above. This will most likely make use of the [`GenomicFeatures`](https://bioconductor.org/packages/release/bioc/html/GenomicFeatures.html) package. ~It will use the same, somewhat arbitrarily chosen thresholds introduced in #182.~
~2. An analysis that specifically examines _SMARCB1_ deletions in ATRTs. This will help with choosing thresholds.~
3. An analysis that examines RNA-seq expression levels for genes that are called as homozygous deletions. This could potentially help with cutoffs as well.
4. Moving from single genes to broader segments of the genome. We can use tabular format above + information about how genes are ordered on chromosomes to get an idea of what broader amplifications or deletions are recurrent. Whiteboard sketch capturing the overall idea:
![gene-to-broader](https://user-images.githubusercontent.com/19534205/67873613-17db3f00-fb0a-11e9-9a5e-e192981aae00.jpg)

#### Required input data

For development: `data/pbta-cnv-cnvkit.seg.gz`
In the future, we will want to use consensus calls (#128)

#### Proposed timeline

I expect the first step outlined above will be a few days at maximum.

**Comment by jaclyn-taroni** [comment]
I wanted to note that the first step should go before oncoprint plotting and interaction plots in CI to allow folks to develop off of the output.

**Comment by jharenza** [comment]
Hi! After not releasing the controlfreeC seg file yesterday, we figured out part of the problem was with LRR values and we are going to remove that information (or recalculate properly) in lieu of absolute CN. If you look at the new CNVkit seg file, you can see we added CN and so now this can be used instead of thresholding LRR (0 = homozygous loss, 1 = hemizygous loss, 2 = diploid, 3/4= gain, and some cutoff can be used for amplification - 5,6+ copies?). This will make life much easier, such that just the segments have to be mapped to genes.

Will update with a new controlFreeC bed file today, hopefully, and will create an issue about this/explain this new format in the readme.

**Comment by jaclyn-taroni** [comment]
Okay thank you -- looking forward to getting more information. Do you have an analysis that supports those calls that you can share publicly @jharenza ? 

In that case @cbethell, let's have the tabular output in this format:

| gene_symbol | biospecimen_id | label |  copy_number |
|:-------------:| :---------------:|:----:|:------------:|
| YFG1 | BS_XXXXXXXX | hemizygous_loss | 1 |
| ... | ... | ... | ... |
| ... | ... | ... | ... |
| ... | ... | ... | ... |

**Comment by jharenza** [comment]
Do you mean the pipeline or explanation of the output? I think we pushed that to our github and I can update the link in the manuscript. If not, will do.

**Comment by jaclyn-taroni** [comment]
> I think we pushed that to our github and I can update the link in the manuscript. If not, will do.

Sounds good. I would expect the explanation of the output to be in the issue or README you mentioned above, is that correct?

**Comment by jharenza** [comment]
Yep, I will add to the readme!

**Comment by jharenza** [comment]
Re: missing genes, you can potentially try using [an hg38 GTF file](https://cavatica.sbgenomics.com/public/files/5772b6c5507c1752674486ce/) to create a gene coordinates bed file and use the `bedr` [R package](https://cran.r-project.org/web/packages/bedr/vignettes/Using-bedr.html) to do intersections of genes with segments.

**Comment by jaclyn-taroni** [comment]
This is the Ensembl link for the hg38 GTF linked in Cavatica above: `ftp://ftp.ensembl.org/pub/release-84/gtf/homo_sapiens/Homo_sapiens.GRCh38.84.gtf.gz`

**Comment by jaclyn-taroni** [comment]
@cbethell and I are going to split up the work on this, as there are two main areas where this needs to be worked on.

#### Changes to file preparation
* Using the `bedr` R package and `Homo_sapiens.GRCh38.84.gtf` instead of the R annotation package we currently use - the dependencies were added to the Docker image in #225
* Add functionality to use ControlFreeC input / use ploidy information for CNVkit
* Use `loss` and `gain` broadly where that is not already the case https://github.com/AlexsLemonade/OpenPBTA-analysis/pull/216/files#r341868719

There is currently a draft PR open looking at _SMARCB1_ deletions in ATRT #217 - we want to understand how the new annotation strategy and use of different methods affects these results. 

The output of `01-prepare-cn-file.R` will get updated to be:

| gene_symbol | biospecimen_id | label |  copy_number | ploidy |
|:-------------:| :---------------:|:----:|:------------:|:-----:|
| YFG1 | BS_XXXXXXXX | loss | 1 | 3 |
| ... | ... | ... | ... | ... |
| ... | ... | ... | ... | ... |
| ... | ... | ... | ... | ... |

#### Changes and additions downstream of file preparation
* Look at RNA-seq expression for `loss` calls (use RSEM data) - we probably don't want to rely on this to make definitive total loss calls (https://github.com/AlexsLemonade/OpenPBTA-analysis/pull/216/files#r341875649) but let's see what this looks like, generally speaking
* Use the output of `01-prepare-cn-file.R` in the Oncoprint plotting (#6) 
* The "Moving from single genes to broader segments of the genome" described in the steps above

I will take the file preparation part and @cbethell will take the downstream steps.

**Comment by jashapiro** [comment]
I noticed in initial attempts to integrate CNV calls into #13 that there are a number of genes where CNVkit calls include both gain and loss for the vast majority of samples (see table below, noting that there are only 649 samples in the dataset used). This seems worth a bit of investigation. My initial guess is that most of these are bad calls in repetitive regions, and that restricting calls to exons may reduce this. (That also neatly skirts the strange behavior of `txdb` objects with the `gene()` selector.) I hope that #128 will also take care of many of these cases.

Note also that many of these are also duplicate genes, which is probably making calls harder, but even so, calling in almost all samples as both gain *and* loss seems less than ideal.

|gene_cnv          | mutant_samples|
|:-----------------|--------------:|
|CBS_Gain          |            646|
|CBS_Loss          |            643|
|CBSL_Gain         |            646|
|CBSL_Loss         |            643|
|CRYAA_Gain        |            646|
|CRYAA_Loss        |            643|
|CRYAA2_Gain       |            646|
|CRYAA2_Loss       |            643|
|FAM243A_Gain      |            646|
|FAM243A_Loss      |            642|
|LOC101927050_Gain |            633|
|LOC286297_Loss    |            634|
|MIR8069-2_Gain    |            645|
|MIR8069-2_Loss    |            643|
|SMIM11B_Gain      |            646|
|SMIM11B_Loss      |            642|
|U2AF1_Gain        |            646|
|U2AF1_Loss        |            643|
|U2AF1L5_Gain      |            646|
|U2AF1L5_Loss      |            643|

**Comment by jaclyn-taroni** [comment]
@jashapiro I'll give `GenomicFeatures::exons` a shot and then let's take a look at these specific genes?

**Comment by jashapiro** [comment]
Sounds good. In light of #241, we may want to think about switching over to reading in annotations from a GTF file too.

**Comment by jaclyn-taroni** [comment]
Agreed 👍

**Comment by jaclyn-taroni** [comment]
While I'm working on the changes to file preparation, I think I'll also add in a step that maps from Entrez IDs to cytobands using the `org.Hs.eg.db` package (`org.Hs.egMAP`). I don't think I'm going to put this into the same tabular format outlined above.

**Comment by jaclyn-taroni** [comment]
@jashapiro I followed up on your analysis above, where I counted how many instances of a gene being called as a gain and a loss within the same sample now that we've made the changes in #253. You can see the notebook for that here: https://jaclyn-taroni.github.io/openpbta-notebook-concept/both-gain-and-loss.nb.html

It seems _slightly better_ than before, but it appears to be much less of an issue in ControlFreeC.

**Comment by jashapiro** [comment]
> It seems _slightly better_ than before, but it appears to be much less of an issue in ControlFreeC.

Oh, I think that looks a *lot* better. The secondary concern I had (which this nb does not quite address), is the extent to which certain regions are prone to false calls and/or reference sequences are non-representative of the population. The analysis above came up in my work on #13 because I was investigating the high number of very high frequency calls that were stymying my filters; the multi-call genes started as a secondary observation, but morphed into primary...

**Comment by jaclyn-taroni** [comment]
Discussed in person - now that we have GISTIC broad arm calls, we should come up with a strategy for reconciling the broad arm calls with the annotated results from CNVkit. That is to say that we don't want to report individual genes as gained or lost if it would be more accurate to report a broader event. @cbethell and @cansavvy are going to take a look at this together.

**Comment by cansavvy** [comment]
> That is to say that we don't want to report individual genes as gained or lost if it would be more accurate to report a broader event.

Does this mean we would prefer to remove the genes from the annotated files if it is more accurate to say the whole arm is gained or lost? OR do we want to add an extra column in the annotated files that says whether the arm for each gene reported is in an arm that is gained or lost (I think this second suggestion is more likely)? Part of this question has to do with gaining a better understanding of what the downstream application of the broad arm data would be.

**Comment by jaclyn-taroni** [comment]
I would say that second option makes it easy to achieve the first via filtering downstream.

**Comment by jaclyn-taroni** [comment]
Once #452 lands, we want to make sure we run `analyses/copy_number_consensus_call/results/pbta-cnv-consensus.seg` through the annotation steps in `focal-cn-file-preparation` now that #441 has been merged. This requires the following changes:

- [ ] Adding `analyses/copy_number_consensus_call/results/pbta-cnv-consensus.seg` to the processing in `analyses/focal-cn-file-preparation/00-add-ploidy-cnvkit.Rmd` 
- [ ] Including the annotation of this file in `analyses/focal-cn-file-preparation/run-prepare-cn.sh` (e.g., passing it to `analyses/focal-cn-file-preparation/01-prepare-cn-file.R`)
- [ ] You may want to make GISTIC files _optional_  in `analyses/focal-cn-file-preparation/01-prepare-cn-file.R` because we don't have the GISTIC consensus results yet (tracked here: #453).

**Comment by jaclyn-taroni** [comment]
Closing this - what's left is now tracked in #497 and #485.
