### ISSUE TITLE
Planned Analysis: Molecularly subtype all tumors

### ISSUE THREAD

**Issue by jharenza** [AlexsLemonade/OpenPBTA-analysis#19]
Without methylation data, the goal of this analysis is to best molecularly subtype all brain tumors based on defining features.
- [x] Medulloblastomas (MBs) into SHH, WNT, Group 3, and Group 4 - @PichaiRaman has created a classifier [here](https://github.com/PichaiRaman/MedulloClassifier) and classified the samples with RNA-Seq.
- [ ] ATRTs into SHH, MYC, TYR. See: [1-s2.0-S1535610816300356-main.pdf](https://github.com/AlexsLemonade/OpenPBTA-analysis/files/3387143/1-s2.0-S1535610816300356-main.pdf)
- [ ] Ependymomas into ST-RELA, ST-YAP1, PF-A, and PF-B. Will require some genome-wide copy number examination. See: [0D556E30-D832-4D6F-9F2F-49554F68D56F.pdf](https://github.com/AlexsLemonade/OpenPBTA-analysis/files/3387093/0D556E30-D832-4D6F-9F2F-49554F68D56F.pdf)
- [ ] High-grade gliomas, according to brain region (if known, eg: midline vs hemispheric) and defining lesion (eg H3F3A K27/28M, G34/5R/V, HIST1H3B K27/28M, IDH-mutant, ACVR1-mutant, PDGFRA, and mesenchymal subtypes). See: [WHO 2016 classifications](https://braintumor.org/wp-content/assets/WHO-Central-Nervous-System-Tumor-Classification.pdf) 
- [ ] Non-MB embryonal tumors (old PNET classified tumors) into ETMRs and CNS embryonal NOS
- [ ] Oligodendrogliomas as IDH-mutant and 1p/19q codeleted
- [ ] Chordomas - subtype into poorly differentiated (INI1/SMARCB1 loss)

**Comment by jharenza** [comment]
I prefer to use [this](https://docs.google.com/spreadsheets/d/1Sa0hNX1lje40HdBpWiLUBY6-53UzvQczFLYb3uIm2jw/edit?usp=sharing) as a working list of tumor histologies which we can molecularly subtype. I have gone through and broadly classified each histology based on the WHO 2016 classifications and also classified "Other" tumors based on internal CBTTC data.

**Comment by linneacripe** [comment]
Medulloblastoma- need five subtypes, SHH p53 mutated and SHH p53 wild type

**Comment by jharenza** [comment]
V2 clinical file [here](https://docs.google.com/spreadsheets/d/1gFbA7_9VsqLGXI6SYLT9XoOnOfY0qixLeJmH5DoJ-Ec/edit#gid=1385692882), and will be included with data download V2.

**Comment by syzheng** [comment]
> Without methylation data, the goal of this analysis is to best molecularly subtype all brain tumors based on defining features.
> 
> * [x]  Medulloblastomas (MBs) into SHH, WNT, Group 3, and Group 4 - @PichaiRaman has created a classifier [here](https://github.com/PichaiRaman/MedulloClassifier) and classified the samples with RNA-Seq.
> * [ ]  ATRTs into SHH, MYC, TYR. See: [1-s2.0-S1535610816300356-main.pdf](https://github.com/AlexsLemonade/OpenPBTA-analysis/files/3387143/1-s2.0-S1535610816300356-main.pdf)
> * [ ]  Ependymomas into ST-RELA, ST-YAP1, PF-A, and PF-B. Will require some genome-wide copy number examination. See: [0D556E30-D832-4D6F-9F2F-49554F68D56F.pdf](https://github.com/AlexsLemonade/OpenPBTA-analysis/files/3387093/0D556E30-D832-4D6F-9F2F-49554F68D56F.pdf)
> * [ ]  High-grade gliomas, according to brain region (if known, eg: midline vs hemispheric) and defining lesion (eg H3F3A K27/28M, G34/5R/V, HIST1H3B K27/28M, IDH-mutant, ACVR1-mutant, PDGFRA, and mesenchymal subtypes). See: [WHO 2016 classifications](https://braintumor.org/wp-content/assets/WHO-Central-Nervous-System-Tumor-Classification.pdf)
> * [ ]  Non-MB embryonal tumors (old PNET classified tumors) into ETMRs and CNS embryonal NOS
> * [ ]  Oligodendrogliomas as IDH-mutant and 1p/19q codeleted
> * [ ]  Chordomas - subtype into poorly differentiated (INI1/SMARCB1 loss)

for oliodendroglioma and astrocytoma, you may also consider comparing them with adult cancers.

**Comment by jharenza** [comment]
I will work on this once we have some consensus, summary files!

**Comment by jharenza** [comment]
@syzheng - in what way should we compare oliodendroglioma and astrocytoma to adult cancers? Specific analysis?

**Comment by jaclyn-taroni** [comment]
Should we break each of the current list items into its own ticket with more specific instructions? Then they will be more limited in scope and the work could be more easily distributed _and_ approaches more easily discussed. I imagine the domain knowledge required for each of the items may vary. Getting specific instructions on tickets (including required inputs) would allow potential analysts to get an idea of the amount of effort required. In some situations, it might be appropriate to pair analysts with domain experts (perhaps serving as reviewers) to address items. I think separate tickets will help with that as well.

**Comment by jharenza** [comment]
We can. I typically utilize fusions, CN, and SNVs to determine the subgroups, if possible. There are instances when you can categorize as NOS (not otherwise specified), so I think most of this will be done manually, unfortunately.

**Comment by jaclyn-taroni** [comment]
I'm not proposing an 'automatic' solution (e.g., building classifiers). I think if we can find ways to automatically generate reports that are easily consumed by, say, putting required results in a single place in tabular format, that might help us reach our goals more quickly. It would also allow us to rerun things when data gets updated (and therefore see if the subtype labels change) and probably be a bit more transparent.

**Comment by jaclyn-taroni** [comment]
I should say "see if the information underlying the subtype labels change"

**Comment by jharenza** [comment]
Closing this, as I separated into #244 , #245 , #249 , #250 , and #251

**Comment by syzheng** [comment]
Hi Jo Lynne
We have finished calculating telomerase scores. How should we circulate it?
Email, or upload to the project portal?
Thanks
Siyuan

**Comment by jharenza** [comment]
@syzheng can you create a pull request for the telomerase ticket #148 with the code used to generate scores? If you need some help walking through it, perhaps @jaclyn-taroni and @jashapiro can help via phone or slack. You can join https://www.ccdatalab.org/slack and the `#open-pbta` channel for more discussion!

Thanks so much!

**Comment by jaclyn-taroni** [comment]
Yes, please feel free to reach out with questions @syzheng
