### ISSUE TITLE
Planned Data release: v7

### ISSUE THREAD

**Issue by jharenza** [AlexsLemonade/OpenPBTA-analysis#194]
#### File(s)

_What data file(s) does this issue pertain to?_
ControlFreeC CNV, tumor ploidy estimate, and #155 
#### Release

_What release are you using?_
update v6, adding files

#### Link to [OpenPBTA-manuscript](https://github.com/AlexsLemonade/OpenPBTA-manuscript/)

_Put a link to the relevant section of the OpenPBTA manuscript here._
https://github.com/AlexsLemonade/OpenPBTA-manuscript/issues/49 - to be added
#### Question/issue

_Put your question or report your issue here._

**Comment by jaclyn-taroni** [comment]
What is the timeline for this? That will influence whether or not I go forward with putting the independent samples files on the S3 bucket that has the CI testing data.

**Comment by jaclyn-taroni** [comment]
Are the two SEG files supposed to be different formats? if so, can we please add a note in this section of the README: https://github.com/AlexsLemonade/OpenPBTA-analysis#data-formats ?

**Comment by jharenza** [comment]
> Are the two SEG files supposed to be different formats? if so, can we please add a note in this section of the README: https://github.com/AlexsLemonade/OpenPBTA-analysis#data-formats ?

Yes, they are - I updated CNVkit, but waited for v7 to update controlfreeC. I added links and more info to clarify these; submitting PR now.
