### ISSUE TITLE
Process for CAVATICA access/analysis

### ISSUE THREAD

**Issue by jharenza** [AlexsLemonade/OpenPBTA-analysis#20]
We should flush out this process - giving people access to CAVATICA to analyze data, ability to use virtual notebooks to do analyses, then submission of their code/figures/notebooks to github.

**Comment by cgreene** [comment]
Short summary:
* We will create a CAVATICA user that has access to the PBTA data.
* We will generate an API key.
* We will use that API key in our download scripts to obtain the PBTA data files.

**Comment by cgreene** [comment]
Current instructions from @yuankunzhu
```
curl -s https://pbta-open-access-data.s3.amazonaws.com/downloader.sh | sh # primary download
curl -s https://pbta-open-access-data.s3.amazonaws.com/downloader-or.sh | sh # overwrite download
```

About to convert this into a download script.

**Comment by jharenza** [comment]
> Current instructions from @yuankunzhu
> 
> ```
> curl -s https://pbta-open-access-data.s3.amazonaws.com/downloader.sh | sh # primary download
> curl -s https://pbta-open-access-data.s3.amazonaws.com/downloader-or.sh | sh # overwrite download
> ```
> 
> About to convert this into a download script.

As an FYI for anyone downloading this data, we will be updating the download dataset to include some additional CNV/SV analyses by the end of next week.

**Comment by cgreene** [comment]
@jharenza - what do you think about closing this issue now that we have determined a process and taking a look at #2 and adding additional requirements (if any) in there? Also, are you and @yuankunzhu going to take a stab at putting the download code together?

**Comment by jharenza** [comment]
sure - I think @yuankunzhu will work on this during this sprint!
