### ISSUE TITLE
Consensus Mutation Files Release

### ISSUE THREAD

**Issue by cansavvy** [AlexsLemonade/OpenPBTA-analysis#207]
#### Background:

As documented in #161, I have the first edition of the consensus mutation files. 

I have uploaded them to S3 in a zipped folder that is in their own separate folder `snv-consensus`:
~`https://open-pbta.s3.amazonaws.com/data/snv-consensus/snv-consensus_1112019.zip`~

**UPDATED:** https://open-pbta.s3.amazonaws.com/data/snv-consensus/snv-consensus_11122019.zip see https://github.com/AlexsLemonade/OpenPBTA-analysis/issues/207#issuecomment-553412044 below

**This zipped folder includes:**
- README that explains what these files are, where they came from, and links to information about how they came to be. 
- `consensus_mutations.maf.tsv`:  a "MAF-like" file with all the mutations and their associated mutations. 
- `consensus_mutations.tmb.tsv` - a file with the recalculated tumor mutation burden statistics for each sample (based on the consensus mutation set) 

These files can be used for whatever downstream SNV analyses are planned. I will update them as the data releases are also updated. 

Please file issues and tag me about any concerns with these files or the [methods used to obtain them](https://github.com/AlexsLemonade/OpenPBTA-analysis/tree/master/analyses/snv-callers). 

#### Questions about the protocol for this type of thing:

- Do we want to include these files in the data-download script? 
- How do we want to handle updates to this set? Do we include them in data releases or keep this separate? 
- What information will be needed from me for the manuscript? 

*What about VarDict?*
This first edition was made using the v6 data and dropped the VarDict file. Mostly because of unreliability of its data but also because of technical difficulties of running such a large file (it is 5x as big as the next biggest MAF file). As this pipeline is streamlined and made more efficient (documented by issue #201) I may go back and run VarDict's data just to see what it looks like, however, it is unlikely the VarDict data will be added into this consensus file.

**Comment by cansavvy** [comment]
We should figure out what to do with this consensus file's handling for downstream analyses. Since #239 uses it, I have a temporary set of code to have it download directly from S3, however, this means its not subsetted along with the other files and will clog up CircleCI's tests.

**Comment by jharenza** [comment]
@cansavvy should we add these to the v10 release?

**Comment by cansavvy** [comment]
What do you think, @jaclyn-taroni? We should probably add them to the `create-subset` scripts as well. I don't think #239 will be able to be merged until the file is subset.

**Comment by jaclyn-taroni** [comment]
Adding to v10 and then getting them into `create-subset-files` sounds like a plan to me

**Comment by cansavvy** [comment]
As was noted by issue #262 and addressed by PR #263 , the consensus file needed to have the metadata columns that were appended to it, dropped. These changes have been implemented and both the code (#263) and the files on S3 have been updated.  The up to date zip file loaded to S3 is `snv-consensus_11122019.zip`.

**Comment by jharenza** [comment]
thanks @cansavvy - will add this zip file to #254

**Comment by jharenza** [comment]
Released with #273
