### ISSUE TITLE
Planned release: v8

### ISSUE THREAD

**Issue by jharenza** [AlexsLemonade/OpenPBTA-analysis#219]
#### File(s)

_What data file(s) does this issue pertain to?_
pbta-histologies.tsv and pbta-cnv-controlfreec.tsv.gz
#### Release

_What release are you using?_
v7

#### Link to [OpenPBTA-manuscript](https://github.com/AlexsLemonade/OpenPBTA-manuscript/)

_Put a link to the relevant section of the OpenPBTA manuscript here._

#### Question/issue

_Put your question or report your issue here._
#214 and #216 - fixes `primary_site` column and adds `tumor_ploidy` to the TSV file

**Comment by jaclyn-taroni** [comment]
Sounds like #221 will be addressed in this release as well.

**Comment by jharenza** [comment]
#223 completed
