### ISSUE TITLE
Updated analysis: ssGSEA using collapsed matrix

### ISSUE THREAD

**Issue by jaclyn-taroni** [AlexsLemonade/OpenPBTA-analysis#235]
#### What analysis module should be updated and why?

In #198 code is being added to collapse the RSEM matrix to a set of gene symbols. The intent is to then distribute the collapsed files as part of the data download. 

The [`ssgsea-hallmark`](https://github.com/AlexsLemonade/OpenPBTA-analysis/tree/3ddf4f903758805596fcc941fba90370fea34593/analyses/ssgsea-hallmark) module includes a collapse step currently.

#### Proposed changes

Once the collapsed file is included in the download, we should update the `ssgsea-hallmark` module to use this directly instead of performing the collapse steps. This will help ensure all analyses use a consistent approach. 

It also worth noting that the analysis that is currently in `master` used an outdated file (updated in current version `v9` #232). We also might want to use the FPKM data instead of counts.

This is where the input file is specified: https://github.com/AlexsLemonade/OpenPBTA-analysis/blob/3ddf4f903758805596fcc941fba90370fea34593/analyses/ssgsea-hallmark/01-run-ssgsea.R#L14

This is where the collapse steps start (through line 24):
https://github.com/AlexsLemonade/OpenPBTA-analysis/blob/3ddf4f903758805596fcc941fba90370fea34593/analyses/ssgsea-hallmark/01-run-ssgsea.R#L16

#### Required input data and release version

Collapsed RSEM stranded files in an unknown future release

#### Proposed timeline

~1 day maximum is my estimate

**Comment by jaclyn-taroni** [comment]
When this gets addressed,  this will need to get added back into CI: https://github.com/AlexsLemonade/OpenPBTA-analysis/commit/aac50d7402e0c134868aa1081c4aa7317c7e9d94

**Comment by sjspielman** [comment]
I'm in the process of updating this module with the correct data and without an unnecessary collapse step, as well as some more general code reformatting to match style etc. (PS @jaclyn-taroni if there's another issue associated with updating this analysis module more generally please tag it in, thanks). 

**Very notably**, it appears the specific method employed for scoring was NOT ssGSEA, but was instead GVSA. Line 34 runs the code:
```GeneSetExprsMat <- GSVA::gsva(expData, hallmarkSets, abs.ranking=F, min.sz=1, max.sz=500, parallel.sz=1, mx.diff=F)```

Per `GSVA::gsva` function documentation, a `method` argument would be required to specifically employ the ssGSEA algorithm:
>  method: Method to employ in the estimation of gene-set enrichment
          scores per sample. By default this is set to ‘gsva’
          (Hänzelmann et al, 2013) and other options are ‘ssgsea’
          (Barbie et al, 2009), ‘zscore’ (Lee et al, 2008) or ‘plage’
          (Tomfohr et al, 2005). The latter two standardize first
          expression profiles into z-scores over the samples and, in
          the case of ‘zscore’, it combines them together as their sum
          divided by the square-root of the size of the gene set, while
          in the case of ‘plage’ they are used to calculate the
          singular value decomposition (SVD) over the genes in the gene
          set and use the coefficients of the first right-singular
          vector as pathway activity profile.

Can anyone weight in on how much the algorithm choice here matters and whether I should go ahead and update to actually run ssgsea?

**Comment by jharenza** [comment]
@sjspielman looping in @komalsrathi because she routinely runs GSVA. In the initial [issue for ssGSEA](https://github.com/AlexsLemonade/OpenPBTA-analysis/issues/7), I briefly noted that when we tried ssGSEA for our recent [PDX manuscript](http://bit.ly/pdx-genomics), we didn't get much signal and instead had to group the PDX models by histology/prior before running the analysis. However, @komalsrathi has had better experience with GSVA, so will let her comment.

**Comment by sjspielman** [comment]
Thanks, @jharenza and @komalsrathi  - I'm about to submit a PR that begins updating data AND more generally re-factoring this analysis, will tag you all there. Seems important to clean this analysis up being excessively using it for any downstream analysis e.g. molecular subtyping.

**Comment by komalsrathi** [comment]
@sjspielman I use the following command line which is not different than what you have noted:

```
# default method gsva 
GeneSetExprsMat <- gsva(exprs, gset.idx.list = gset, min.sz = 1, max.sz = 1500, parallel.sz = 1, mx.diff = FALSE)
```

In few of my datasets, I've obtained similar results using both ssgsea and gsva but gsva mostly gave better (or rather expected) results. In those few cases, ssgsea results were pretty noisy. There are a couple benchmarking papers on these methods and gsva seems to be performing better so I stick with that.

Explanation for the parameters that I use:
`max.sz` is dependent on the size of the genesets used, so you could set it to a higher number for genesets > 500 genes. I keep it at 1500 to account for larger genesets. You could also increase `parallel.sz` if you are using the parallel package for multi threading, so entirely dependent on if you are using multiple cores. `mx.diff = FALSE` and `abs.ranking=F` (an approach similar to GSEA) increases the method's sensitivity to return gene sets that are highly enriched in either up or down genes.

**Comment by sjspielman** [comment]
I think we should be able to close this issue after PR #386, @jaclyn-taroni?

**Comment by jaclyn-taroni** [comment]
Agreed!
