### ISSUE TITLE
Proposed Analysis: Molecularly subtype ATRT tumors

### ISSUE THREAD

**Issue by jharenza** [AlexsLemonade/OpenPBTA-analysis#244]
#### Scientific goals

_What are the scientific goals of the analysis?_
Subtype ATRTs into SHH, MYC, TYR. 

#### Proposed methods

_What methods do you plan to use to accomplish the scientific goals?_
Suggestions:
1) In the absence of methylation data, perform t-sne or other clustering of expression data to determine whether the total N of ATRTs is high enough to enable subgroup clustering (See Supplemental Figure 1B in the manuscript below)
2) Review of histologies file, copy number, SV, mutation, and _gene expression data across all ATRT samples_.

Summarize results in a table, which can be added to a notebook, with molecular subtype designated. 

**ATRT TYR**
- most are infratentorial localized 
- broad _SMARCB1_ deletions (most have chr22q loss/monosomy 22)
- Major expression markers: overexpression of melanosomal genes (eg: _TYR_, _MITF_, _DCT_)
  - _TYR_ is over-expressed in every case in this subgroup but not expressed in any other subgroup (biomarker)
- overexpression of _VEGFA_
- overexpression of genes involved in ciliogenesis (eg: _DNAH11_ and _SPEF1_)
  - Explore additional TF targets in Figure 6A in the manuscript below for overexpression if needed

**ATRT SHH**
- infratentorial or supratentorial localized
- focal _SMARCB1_ deletions
- Major expression markers: overexpression of SHH pathway (can be accomplished by looking at single sample GSEA results or expression of SHH pathway genes - eg: _MYCN_, _GLI2_)
- overexpression of _CDK6_
- overexpression of _ASCL1_, _HES5/6_, and _DLL1/3_, indicating active _NOTCH_ signaling
  - _MYC_ is the most commonly overexpressed gene in this subgroup
  - Explore additional TF targets in Figure S6A in the manuscript below for overexpression if needed
- can have _SMARCA4_ loss, but not required
- this group has more total mutations than the other two

**ATRT MYC**
- most are supratentorial localized
- focal _SMARCB1_ deletions
- Major expression markers: overexpression of _MYC_ and _HOX_ gene cluster - eg: _MYC_, _HOTAIR_
  - Explore additional TF targets in Figure S6B in the manuscript below for overexpression if needed 

May be able to determine brain regions using the `primary_site` from pbta_histologies.tsv - [Ref](https://www.ncbi.nlm.nih.gov/books/NBK65903/figure/CDR0000574573__205/):
- infratentorial aka posterior fossa (eg: cerebellum, tectum, fourth ventricle, and brain stem (midbrain, pons, and medulla)
  - more common in first 2 years of life
  - median survival 17 months
  - fewer total mutations, relative to supratentorial tumors
- supratentorial (eg: cerebrum, lateral ventricle and third ventricle, choroid plexus, pineal gland, hypothalamus, pituitary gland, and optic nerve)

#### Required input data

_What input data will you use for this analysis?_
- RNA-Seq
- Copy number
- SV
- Somatic Mutations (eg: nonsense mutations, deleterious mutations)

#### Proposed timeline

_What is the timeline for the analysis?_
1 week

#### Relevant literature

_If there is relevant scientific literature, put links to those items here._
[Link](https://www.cell.com/cancer-cell/fulltext/S1535-6108(16)30035-6) to Atypical Teratoid/Rhabdoid Tumors Are Comprised of Three Epigenetic Subgroups with Distinct Enhancer Landscapes, specifically, Table S3 has a nice summary of genotyping the _SMARCB1_ locus.

**Comment by jaclyn-taroni** [comment]
I'm adding what I think the table summarizing the results would contain here. From a cursory look, there are 30 samples that are classified as ATRT in the histologies file. That is a large enough sample size for what I'll suggest below. I agree that one of the first analyses would be unsupervised clustering or dimension reduction.

### Tabular format

The goal of the table is to summarize all of the information above in a manner that would allow someone with domain expertise to quickly make relatively easy calls and to identify cases where more information is needed. So it should contain everything mentioned above.

| Kids_First_Participant_ID | Kids_First_Biospecimen_ID | age at diagnosis (days) | reported gender | primary site | location summary | _TYR_ expression z-score | ... | ... | SHH ssGSEA score (rank?) | Notch ssGSEA score (rank?) | Focal _SMARCB1_ status | Focal SMARCA4 status | chr22q loss |
|---|---|---|---|---|---|---|---|---|---|---|---|---|---|
| PT_XXXXXXXX | BS_XXXXXXXX | 800 | Female | Cerebellum/Posterior Fossa | infratentorial | 4.235 | ... | ... | 25 | 18 | loss | neutral | ... |
|...|...|...|...|...|...|...|...|...|...|...|...|...|...|

#### Notes on columns
* `age at diagnosis (days)`, `reported gender`, `primary site` can all be obtained from the `pbta-histologies.tsv` file. `location summary` would be a recoding of `primary site` into `infratentorial` or `supratentorial`.
* For any of the genes mentioned in terms of overexpression, a column that contains the z-scores for ATRT samples should be included. This tells us about the expression of that gene in a gene relative to all other ATRT samples.
  * To obtain z-scores, I would expect an analyst to filter an expression matrix to only ATRT samples, `log2(x + 1)` it and then z-score the rows.
* For pathways such as SHH, we can use ssGSEA values but we want to represent them in a way that tells us about the pathway score in a sample relative to all other ATRT samples. Listing a rank or perhaps z-scores again come to mind. 
  * Notch signaling is captured in the hallmark gene sets used in [`analyses/ssgsea-hallmark`](https://github.com/AlexsLemonade/OpenPBTA-analysis/tree/713d2b8549226227b1e73e7440b41954434fad4a/analyses/ssgsea-hallmark), but different gene sets may need to be identified for SHH.
* For focal copy number alterations, the files in [`analyses/focal-cn-file-preparation/results`](https://github.com/AlexsLemonade/OpenPBTA-analysis/tree/713d2b8549226227b1e73e7440b41954434fad4a/analyses/focal-cn-file-preparation/results) can be used. See also: #217 
* To my knowledge, the structural variant data is not yet in an easily consumable format analogous to the focal CN files above.

**Comment by cbethell** [comment]
I am going to begin the work on this analysis by implementing the suggestions above.

**Comment by cbethell** [comment]
> I am going to begin the work on this analysis by implementing the suggestions above.

To be more specific, my plan is as follows: 
- Perform unsupervised hierarchical clustering using `Heatmap`
- Use the `pbta-histologies.tsv` file (filtered for `short_histology` == "ATRT") to obtain `primary_site`, `Kids_First_Participant_ID`, `Kids_First_Biospecimen_ID`, `age_at_diagnosis_days`, and `reported gender`. 
- Use `primary_site` to define values for `location_summary`. These values will be `infratentorial` and `supratentorial`.
- Calculate the z-scores on the expression data and join this with the metadata.
- Use the focal CN files to determine focal SMARCB1 and SMARCA4 status, and add 2 columns denoting the respective status to the existing data.frame with `location_summary` and expression z-scores.
- Obtain the relevant pathway information from the ssGSEA file and calculate the z-scores. Add this information to the existing data.frame.
- Use the SV data to create a column denoting whether or not `chr22q` loss is present.
- Use the consensus mutation files to rank Tumor Mutation burden. 
- Perform PCA and t-SNE

**Comment by jharenza** [comment]
@jaclyn-taroni do you and @cbethell want to see if the results from [cnvkit gistic](s3://kf-openaccess-us-east-1-prd-pbta/data/2019-12-10-gistic-results-cnvkit.zip) `broad_values_by_arm.txt` results make sense with the current _SMARCB1_ deletions found/be good enough for this analysis? If so, we can release these results in the next data release.

**Comment by cbethell** [comment]
> @jaclyn-taroni do you and @cbethell want to see if the results from gistic for CNVkit: `s3://kf-openaccess-us-east-1-prd-pbta/data/2019-12-10-gistic-results-cnvkit.zip` `broad_values_by_arm.txt` results make sense with the current _SMARCB1_ deletions found/be good enough for this analysis? If so, we can release these results in the next data release.

@jharenza yes, I believe the gistic results would be good/useful for this analysis so I would like to see them in the next data release, if possible.

**Comment by jaclyn-taroni** [comment]
My understand of what is left on this ticket:
* Use the `broad_values_by_arm.txt` GISTIC file to obtain the chr22q loss information and add that to the final table.
* Have someone with domain expertise look at the table we have and make tweaks or follow up as needed.

**Comment by jharenza** [comment]
@jaclyn-taroni was just looking at this today as well. Once the table is done, we have a clinician (probably via email) who can check out the data. It may be nice to point him to a notebook of the table with the final subtypes and columns of criteria used.

**Comment by jaclyn-taroni** [comment]
[`molecular-subtyping-ATRT`](https://github.com/AlexsLemonade/OpenPBTA-analysis/tree/master/analyses/molecular-subtyping-ATRT) will need to be rerun with annotated focal consensus calls (#186) and new GISTIC calls (#453).

**Comment by jharenza** [comment]
@cbethell - started going through these results a bit. Can I request that you also add a column for `OS_months`, derived from `OS_days` to the results? Thanks!

**Comment by jharenza** [comment]
@cbethell sorry for the separate comment - would you be able to also include expression of _HES5_, _HES6_, _DLL1_, and _DLL3_ to assess Notch signaling? This is for ATRT SHH group, as noted above.

Looks like the other genes mentioned are all included.

Thanks!

**Comment by jaclyn-taroni** [comment]
> would you be able to also include expression of HES5, HES6, DLL1, and DLL3 and GSEA for http://software.broadinstitute.org/gsea/msigdb/cards/HALLMARK_NOTCH_SIGNALING.html to assess Notch signaling? This is for ATRT SHH group, as noted above. 

I'm going to pick this up right now @jharenza.

**Comment by jharenza** [comment]
Thanks @jaclyn-taroni !

**Comment by jharenza** [comment]
@jaclyn-taroni - I think, if possible, we may want to move `POU3F4, POU3F2, and PBX1` over to the grouping with ATRT SHH genes (from Table S6) and we can also possibly add `MSX2, STAT3, PRRX1, LMX1A, and OTX2` for the TYR subgroup genes (from Figure 6A and Table S6). I think the TYR subtype is pretty easy to delineate with the genes we have, but this will give some extra confidence.

**Comment by jharenza** [comment]
Here is a minimal gene list for expression/GSEA for each subgroup:

| TYR | SHH | MYC |
|--------|------------|----------|
| TYR | MYCN | MYC |
| MITF | GLI2 | HOTAIR |
| DCT | CDK6 | TEAD3 |
| VEGFA | ASCL1 | MYC GSEA |
| DNAH11 | HES5 |  |
| SPEF1 | HES6 |  |
| MSX2 | DLL1 |  |
| STAT3 | DLL3 |  |
| PRRX1 | LHX2 |  |
| LMX1 | TEAD1 |  |
| OTX2 | Notch GSEA |  |

**Comment by jharenza** [comment]
Even using the minimal set of genes, the subtyping is not clear-cut based on these genes' expression, and after discussing with @jaclyn-taroni, I think it would be a better approach to develop a classifier for ATRT subtyping, similar to what we was done for MB [here](https://github.com/d3b-center/medullo-classifier-package). Since this may not make it into the first submission of the paper, I will close this for now.
