### ISSUE TITLE
Proposed Analysis: Add additional subtypes to medulloblastoma tumors

### ISSUE THREAD

**Issue by jharenza** [AlexsLemonade/OpenPBTA-analysis#247]
#### Scientific goals

_What are the scientific goals of the analysis?_
Further classify Medulloblastoma SHH subtype.

#### Proposed methods

_What methods do you plan to use to accomplish the scientific goals?_
Assess _TP53_ mutation status for samples classified as SHH subtype to further classify into SHH,TP53-mutated and SHH,TP53-wildtype. (See WHO book chapter below)

**SHH,TP53-mutated**
-SHH subtype with _TP53_ mutation

**SHH,TP53-wildtype**
-SHH subtype, no _TP53_ mutation

#### Required input data

_What input data will you use for this analysis?_
SNVs for _TP53_ status, copy number, SVs, fusions, RNA expression, histologies file

#### Proposed timeline
_What is the timeline for the analysis?_
1-2 days

#### Relevant literature

_If there is relevant scientific literature, put links to those items here._
[Medulloblastoma WHO 2016 book chapter.pdf](https://github.com/AlexsLemonade/OpenPBTA-analysis/files/3831401/Medulloblastoma.WHO.2016.book.chapter.pdf)

**Comment by jaclyn-taroni** [comment]
@mkoptyra and I will start on this next week.

**Comment by jaclyn-taroni** [comment]
@mkoptyra - @cansavvy is going to pick up this ticket so you can focus on chordoma subtyping (#250)

**Comment by jaclyn-taroni** [comment]
Working on #249 this weekend brought this question up for me - is it _any_ _TP53_ mutation (how the code is currently written) or does this mean “_TP53_ mutations that are likely to be functional?” How do folks usually approach this?

**Comment by jaclyn-taroni** [comment]
Taking a look at the chapter - looks like the _TP53_ are often in exons 4 through 8 and are germline mutations about half the time, which we would not capture here.

**Comment by jharenza** [comment]
@jaclyn-taroni nice catch on this - I think that perhaps we should just leave MB as the 4 subtypes, given we do not have germline data in this cohort and I think we would miss some if we attempted it. @mkoptyra, do you agree?

**Comment by cgreene** [comment]
@jharenza : would the folks writing the germline paper be willing to share the presence/absence of mutations in key genes for subtyping, or would they view that as something that could not be shared?

**Comment by jharenza** [comment]
@cgreene I think the fastest way to get this would be for us to release a limited MAF of variants within the desired genes, filtered by @yiran-guo. Will add a ticket for this and plan to release for v14.

**Comment by jharenza** [comment]
Per our conversation about subjectiveness of germline filtering and potential to miss/over-assign pathogenicity of _TP53_ variants when they are of uncertain significance, @jaclyn-taroni and I decided we should close this ticket (see #431).
