### ISSUE TITLE
Proposed Analysis: Molecularly subtype high-grade glioma tumors

### ISSUE THREAD

**Issue by jharenza** [AlexsLemonade/OpenPBTA-analysis#249]
#### Scientific goals
_What are the scientific goals of the analysis?_
Subtype High-grade gliomas (high-grade astrocytic tumors, HGAT), according to defining histone lesion.

Note: historically, amino acid 1 was not counted in protein nomenclature, thus K27 and G34 mutations noted above really translate to K28 and G35. See:
[ActaNeuropathol.2018Leske.pdf](https://github.com/AlexsLemonade/OpenPBTA-analysis/files/3825553/ActaNeuropathol.2018Leske.pdf)
Our data maps to K28 and G35, consistent with COSMIC and pedcbioportal. 
- Fun fact: this was also the case with BRAF V600E (it was historically called V599E, but the community adapted the current nomenclature).

#### Proposed methods
_What methods do you plan to use to accomplish the scientific goals?_
1) Review of mutation, copy number, and expression data.
2) Render results in tabular form in a notebook.

Any sample that harbors _H3F3A_ K28M, _H3F3A_ G35R/V_, or _HIST1H3B_ K28M, if not classified as a high-grade glioma, should be, as this is a defining lesion. Eg: three former PNET tumors were re-classified as such.

**H3 K28 mutant**
- These tumors contain _H3F3A_ K28M or _HIST1H3B_ K28M mutations
- Co-occurring lesions include: _ACVR1_, _TP53_, _ATRX_ mutations; _PDGFRA_ amplification; _PTEN_ loss
- Mutually-exclusive lesions: _FGFR1_ mutations/fusions (thalamic); _IDH1_ mutations; _BRAF V600E_ (low-grade gliomas)
- Average age of 9 years
- Majority should be midline localized

**H3 G35 mutant**
- These tumors contain _H3F3A_ G35R/V mutations
- Co-occurring lesions include: _ATRX/DAXX_, _TP53_, _SETD2_ mutations, _NTRK_ fusions
- Mutually exclusive lesions: _IDH1_ mutations
- Average age of 20 years

**IDH mutant**
- These tumors contain _IDH1_ R132H mutations
- Co-occurring lesions include: _TP53_ mutations; P73-AS1  promoter methylation and downregulation
- High expression of _FOXG1_ and _OLIG2_
- Mutually exclusive lesions: chr7 gain and chr10 loss

**H3.3 and IDH wildtype**
- High-grade gliomas absent of _H3F3A_ and _IDH_ mutations
- Defining lesions: _MYCN_, _PDGFRA_ amplification, _TP53_ and _TERT_ mutations

**1p/19q co-deleted oligodendrogliomas**
- Co-deletion of chr 1p and 19q (LOH, loss of heterozygosity of both) results in translocation t(1p;19q)
- Nearly all have a co-occurring _IDH1_ mutation (R132 or R172)
- Other co-occurring lesions include: _TERT_ promoter, _CIC_, and _FUBP1_ mutations
- Mutually exclusive of _TP53_ and _ATRX_ mutation
- Typically occurs in adult tumors

#### Required input data
_What input data will you use for this analysis?_
Histologies file (contains brain regions classified for high-grade gliomas as midline, hemispheric, mixed, or other), SNVs, copy number, RNA expression data.

#### Proposed timeline
_What is the timeline for the analysis?_
1 week

#### Relevant literature
_If there is relevant scientific literature, put links to those items here._
[Link](https://braintumor.org/wp-content/assets/WHO-Central-Nervous-System-Tumor-Classification.pdf) to The 2016 World Health Organization Classification of Tumors
of the Central Nervous System: a summary
[Link](https://www.uptodate.com/contents/clinical-features-diagnosis-and-pathology-of-idh-mutant-1p-19q-codeleted-oligodendrogliomas) to Clinical features, diagnosis, and pathology of IDH-mutant, 1p/19q-codeleted oligodendrogliomas

**Comment by jharenza** [comment]
@adamcresnick, @awaanders, @jainpayal022 - do these look like reasonable ways to subtype the high-grade gliomas by lesion?

**Comment by jharenza** [comment]
Got confirmation from @awaanders that these look good. Thanks!

**Comment by jaclyn-taroni** [comment]
> Any sample that harbors H3F3A K28M, H3F3A G35R/V_, or HIST1H3B K28M, if not classified as a high-grade glioma, should be, as this is a defining lesion. Eg: three former PNET tumors were re-classified as such.

For this ticket, the first step should be looking at these lesions in _all_ samples.

**Comment by cbethell** [comment]
I am planning to work on this ticket.
I have made a general workout plan as follows to produce the following information in tabular format:

| Kids_First_Participant_ID | Kids_First_Biospecimen_ID | age at diagnosis (days) | reported gender | glioma brain region | _FOXG1_ expression z-score | ... | ... | Co-occurring lesions | Focal CN status | Chromosomal gain/loss |
|---|---|---|---|---|---|---|---|---|---|---|
| PT_XXXXXXXX | BS_XXXXXXXX | 800 | Female | midline | 4.235 | ... | ... | _ACVR1_, _TP53_ | loss | chr7 gain | ... |
|...|...|...|...|...|...|...|...|...|...|...|

#### Notes on columns
* `age at diagnosis (days)`, `reported gender`, `glioma brain region` can all be obtained from the `pbta-histologies.tsv` file.
* For any of the genes mentioned in terms of overexpression, a column that contains the z-scores for samples should be included. 
  * To obtain z-scores, I would expect an analyst to filter an expression matrix to only ATRT samples, `log2(x + 1)` it and then z-score the rows.
* The co-occurring lesions can be determined using the `data/pbta-snv-consensus-mutation.maf.tsv.gz` file. 
* For focal copy number alterations, the files in [`analyses/focal-cn-file-preparation/results`](https://github.com/AlexsLemonade/OpenPBTA-analysis/tree/713d2b8549226227b1e73e7440b41954434fad4a/analyses/focal-cn-file-preparation/results) can be used. See also: #217 
* To my knowledge, the structural variant data is not yet in an easily consumable format analogous to the focal CN files above.

_Note: As mentioned in the previous comment, the first step will be to look at the lesions in all samples. I will be joining the files mentioned above using the `sample_id` variable from the histologies file._

**Comment by jharenza** [comment]
@cbethell - thanks for working on this! I don't think we need translocations, however there are deletions and duplications in that manta file that may be useful. This file should be annotated for SV type and has a field for gene annotation, so it should be a bit more straightforward to use than the CNV files. Regarding `reported_gender`, I would suggest using `germline_sex_estimate`. While these are annotated for the `Normal` WGS files, we should be able to use this estimate on a patient-level.

**Comment by jaclyn-taroni** [comment]
**Summarizing ongoing efforts and what tasks remain** - initially mentioned in https://github.com/AlexsLemonade/OpenPBTA-analysis/pull/420#issuecomment-573257980. Essentially, each data type requires a number of decisions that are best discussed and documented one data type at a time. Therefore, we've split up the work of cleaning and presenting relevant data in the following way:

1. Subsetting files to tumor samples and using `Kids_First_Biospecimen_ID` to filter rather than `sample_id` (allows us to drop derived cell line samples) - #426 
2. Cleaning copy number data - specifically, annotated CNVkit data and GISTIC `broad_values_by_arm.txt` data - #427 
3. Cleaning mutation data - specifically, consensus mutation data for the 12 genes mentioned above - #428 
4. Cleaning fusion data - _NTRK_ and _FGFR1_ fusions from `pbta-fusion-putative-oncogenic.tsv` file - #429 
5. Cleaning gene expression data - specifically _FOXG1_, _OLIG2_, and, in the absence of methylation data, _TP73-AS1_ for both stranded and poly-A data - *needs to be addressed*
6. Joining all DNA-seq data (copy number, mutation) with relevant clinical data by `Kids_First_Biospecimen_ID` and removing samples with ambiguous `sample_id` that cannot be mapped to RNA-seq data - *needs to be addressed, relies on #427, #428*
7. Joining RNA-seq data (fusion, gene expression) to the DNA-seq/clinical table where possible to produce a final table - *needs to be addressed, depends on everything above*

What is mentioned above, but has not been directly addressed with the Manta data is the translocation t(1p;19q) - for the moment we use the chromosome arm info from GISTIC.

**Comment by jaclyn-taroni** [comment]
[`molecular-subtyping-HGG`](https://github.com/AlexsLemonade/OpenPBTA-analysis/tree/master/analyses/molecular-subtyping-HGG) will need to be rerun with annotated focal consensus calls (#186) and new GISTIC calls (#453).

**Comment by jaclyn-taroni** [comment]
I am going to close this - what is left of what has been discussed is tracked in #499 and #509 as well was the open PR #466.
