### ISSUE TITLE
Planned data release: v10

### ISSUE THREAD

**Issue by jaclyn-taroni** [AlexsLemonade/OpenPBTA-analysis#254]
I am collecting what has been discussed/documented elsewhere, though things on this things on this list may get pushed to a later release:

* Consensus mutation files (#207)
* Standard annotation and reference files (#241)
* Collapsed RNA-seq matrices with unique gene symbols (#248)
* Gene- and transcript-level RSEM TPM values (https://github.com/AlexsLemonade/OpenPBTA-analysis/issues/229#issuecomment-550446782)

**Comment by jashapiro** [comment]
Adding 
* Rerun vcf2maf.pl for all SNV files (#255)

**Comment by jharenza** [comment]
Finalizing all of this today.

**Comment by jharenza** [comment]
completed #273
