### ISSUE TITLE
Variation in MAF formats

### ISSUE THREAD

**Issue by jashapiro** [AlexsLemonade/OpenPBTA-analysis#255]
#### File(s)

pbta-snv-strelka2.vep.maf.gz
pbta-snv-lancet.vep.maf.gz
pbta-snv-mutect2.vep.maf.gz
pbta-snv-vardict.vep.maf.gz

#### Release

v9

#### Link to [OpenPBTA-manuscript](https://github.com/AlexsLemonade/OpenPBTA-manuscript/)

https://github.com/AlexsLemonade/OpenPBTA-manuscript/blob/master/content/03.methods.md#vcf-annotation-and-maf-creation

#### Question/issue

The maf files included in v9 do not have consistent columns. 
In most, there is a `variant_id` and `variant_qual` column (though whether there is any content in those is still variable); but in `pbta-snv-strelka2.vep.maf.gz`, there are instead `vcf_id`, `vcf_qual`, and `vcf_pos`. 

It seems this is likely due to the files being processed with different versions of `vcf2maf.pl`:
https://github.com/mskcc/vcf2maf/commit/051aaaf74d017cc0e7ee49dff2fe1cc1670ced15
Rerunning the current version of vcf2maf.pl on all files should solve this.

**Comment by jharenza** [comment]
updated with #273
