### ISSUE TITLE
Clarification sought on lancet parameters

### ISSUE THREAD

**Issue by jashapiro** [AlexsLemonade/OpenPBTA-analysis#269]
#### What data file(s) does this issue pertain to?

pbta-snv-lancet.vep.maf.gz

#### What release are you using?

v9

#### Put a link to the relevant section of the [OpenPBTA-manuscript](https://github.com/AlexsLemonade/OpenPBTA-manuscript/) here.

https://github.com/AlexsLemonade/OpenPBTA-manuscript/blob/master/content/03.methods.md#snv-and-indel-calling-1

#### Put your question or report your issue here.

From the description in the manuscript, it is somewhat unclear how lancet was run to generate SNV calls. In particular, the methods state:

>For input intervals to Lancet, a reference BED was created by using only the UTR, exome, and start/stop codon features of the GENCODE 31 reference. Per recommendations by the New York Genome Center, the Lancet input intervals were augmented with PASS variant calls from Strelka2 and Mutect2 as validation.

Does this mean that Lancet was set to only make calls in transcribed regions and for specific sites where  mutations had been found by other callers? Or is there some leeway around the augmentation sites where it could make calls?

The net result may be that lancet calls are not directly comparable outside of transcribed regions, so I want to confirm that this is the case.

Thanks!

**Comment by jharenza** [comment]
@migbro, can you respond to this?

**Comment by migbro** [comment]
Hi @jashapiro , I think you've got it right, in that, the calls for lancet are limited to the GENCODE31 CDS plus any additional regions of calls made by mutect and strelka2 following the recommendation here: https://www.biorxiv.org/content/biorxiv/early/2019/04/30/623702.full.pdf.  So in effect, regions used will vary from sample-to-sample.  It is possible to omit the other callers and run it that way, but our benchmarking efforts hint that you might miss a lot of calls.  However, the severity of those "missed" calls, we didn't evaluate, so maybe it's not so bad.  In summary, it's a method meant to balance coverage with run time.  Hope this helps!

**Comment by jashapiro** [comment]
Thanks @migbro. That makes sense. In looking at the results, it seems like lancet makes similar #s of calls to mutect and strelka in transcribed, but it makes many fewer outside. In the article you linked (thanks!), they specify:

>[lancet] is also run on the +/- 250nt regions around non-exonic variants that are called by **only one** of the other callers, to add confidence to such variant. (emphasis mine)

Is that what you did? If so, it seems if a call was made in both mutect and strelka, it would not be in the lancet region file? Is that correct? Or does the region file include all calls from mutect and all calls from strelka?

**Comment by migbro** [comment]
@jashapiro good catch.  I actually went +/300 bp, to make sure the 600bp window at a minimum was met, and included ALL additional strelka2 and mutect2 calls.  So i did deviate slightly from their plan.

**Comment by jashapiro** [comment]
Okay, that actually makes a lot more sense than what they did! It is still a bit concerning that lancet calls outside the transcripts are so much more sparse, but that is probably just be the effect of the tool.

**Comment by jharenza** [comment]
@jashapiro - do you want me to make any edits to manuscript methods based on this discussion, or do you want to suggest edits?
