### ISSUE TITLE
Request for more info/documentation around Manta Annotated TSV

### ISSUE THREAD

**Issue by jaclyn-taroni** [AlexsLemonade/OpenPBTA-analysis#272]
#### What data file(s) does this issue pertain to?

`pbta-sv-manta.tsv.gz`

#### What release are you using?

`release-v9-20191105`

#### Put a link to the relevant section of the [OpenPBTA-manuscript](https://github.com/AlexsLemonade/OpenPBTA-manuscript/) here.

https://alexslemonade.github.io/OpenPBTA-manuscript/#somatic-structural-variant-calling

#### Put your question or report your issue here.

The Manta TSV format is documented here: https://github.com/AlexsLemonade/OpenPBTA-analysis/blob/master/doc/format/manta-tsv-header.md

Manta outputs a VCF file using the 4.1 format ([ref](https://github.com/Illumina/manta/blob/master/docs/userGuide/README.md#manta-vcf-interpretation)) and this has some fields that I would expect to see in a VCF like:
```
7	ID
8	REF
9	ALT
10	QUAL
11	FILTER
12	INFO
13	FORMAT
```

Based on the manuscript section (linked above)

> The somatic DNA workflow for SNV, INDEL, copy number, and SV calling can be found in the KidsFirst Github repository.

I expect there's some annotation step in this repository https://github.com/kids-first/kf-somatic-workflow.

Can someone point me to where the annotation step is described? Preferably we'd also add something to the README of this repository.

**Comment by jharenza** [comment]
Ahh - @kgaonkar6 or @migbro - can you add the AnnotSV workflow to d3b github and share the link, if separate from the somatic WF? I can add this to the methods if not there currently.

**Comment by kgaonkar6** [comment]
Hi, here's the dockerfile and cwl for annotSV : https://github.com/d3b-center/annotSV/tree/master original tool https://lbgi.fr/AnnotSV/

**Comment by jaclyn-taroni** [comment]
Hi @kgaonkar6 - I think that repository may currently be private. I am getting a 404.

**Comment by kgaonkar6** [comment]
ah yes sorry, it's public now

**Comment by jaclyn-taroni** [comment]
Thank you @kgaonkar6

**Comment by jharenza** [comment]
updated with [PR](https://github.com/AlexsLemonade/OpenPBTA-manuscript/pull/58)
