### ISSUE TITLE
Planned Analysis: Somatic Structural Variant and Chromothripsis Analysis

### ISSUE THREAD

**Issue by jharenza** [AlexsLemonade/OpenPBTA-analysis#28]
The goal of this analysis is to identify recurring, putative oncogenic SV lesions/genes with recurrent lesions within and/or across brain tumor subtypes. Coupled to this, investigation of chromothripsis and correlations with survival should be done. See [this paper ](https://www.biorxiv.org/content/10.1101/333617v1)for chromothripsis analysis using WGS.

**Comment by gonzolgarcia** [comment]
Another example studying structural variants and chromothripsis in [our recent paper](https://www.biorxiv.org/content/10.1101/572248v2)
Note: in order to study chromothripsis both CNV calls and Str. variant calls are required

**Comment by kgaonkar6** [comment]
R package used for Chromothripsis analysis https://github.com/parklab/ShatterSeek; used in  [Comprehensive analysis of chromothripsis in 2,658 human cancers using whole-genome sequencing] <https://www.biorxiv.org/content/10.1101/333617v1>

**Comment by gonzolgarcia** [comment]
> R package for Chromothripsis analysis https://github.com/parklab/ShatterSeek; used in [Comprehensive analysis of chromothripsis in 2,658 human cancers using whole-genome sequencing] https://www.biorxiv.org/content/10.1101/333617v1

I have been using this package lately and it is not straight forward. In their manuscript they recognize that eventually it requires visual inspection... Another method implemented as a perl module: https://metacpan.org/release/SGOVIND/Shatterproof-0.13

**Comment by kgaonkar6** [comment]
Ah ok good to know, I've not used the package yet just found it while reading up on SVs.

**Comment by gonzolgarcia** [comment]
I will be running some of the analyses implemented in our [recent paper](https://www.biorxiv.org/content/10.1101/572248v3); including analyses of recurrent SVs and CNVs but also chromothripsis.

**Comment by jharenza** [comment]
merge with and rename #27
