### ISSUE TITLE
Noncoding Genome Analysis

### ISSUE THREAD

**Issue by jharenza** [AlexsLemonade/OpenPBTA-analysis#29]
Should we attempt this for the paper or tackle that in OpenPBTA2? 😄

**Comment by kgaonkar6** [comment]
Annovar does annotate some noncoding calls with known COSMIC noncoding variants and reg_snp https://github.com/linhai86/regsnp_intron annotations

**Comment by jharenza** [comment]
Tabling this for this paper.
