### ISSUE TITLE
Updated analysis: `snv-callers` documentation

### ISSUE THREAD

**Issue by jaclyn-taroni** [AlexsLemonade/OpenPBTA-analysis#296]
#### What analysis module should be updated and why?

The `snv-callers` documentation is out of date.

#### Why should the module be updated?

As far as I can tell, the README doesn't account for the changes as part of the refactor (#201 and related PRs): https://github.com/AlexsLemonade/OpenPBTA-analysis/blob/49acc98f5ffd86853fc70f220623311e13e3ca9f/analyses/snv-callers/README.md

We are also changing the release process with v11 such that the consensus mutation files are no longer included as a zip file and therefore there will not be a README available at `data/snv-consensus-<date>` (see https://github.com/AlexsLemonade/OpenPBTA-analysis/issues/287#issuecomment-558653481 and https://github.com/AlexsLemonade/OpenPBTA-analysis/pull/293#issuecomment-558782828).

#### What changes need to be made? Please provide enough detail for another participant to make the update.

- [x] `snv-callers/README` should be updated to reflect the current state of the analyses
- [x] The main repository README should include information on the consensus files under the `Data Format` header.
  - [x] @jashapiro has documented `pbta-snv-consensus-mutation.maf.tsv.gz` in https://github.com/yuankunzhu/OpenPBTA-analysis/pull/1/files
  - [x] The TMB files need similar documentation

#### What input data should be used? Which data were used in the version being updated?

N/A I am requesting a documentation change.

#### Who will complete the updated analysis?

I am assigning @cansavvy.

**Comment by cansavvy** [comment]
I believe this has been addressed with the merging of #333. Is there anything left that needs more documentation?

**Comment by jaclyn-taroni** [comment]
👍
