### ISSUE TITLE
Generating CI subset files for v11

### ISSUE THREAD

**Issue by cansavvy** [AlexsLemonade/OpenPBTA-analysis#303]
Here's the steps I will take for generating the CI subset files for v11. (Will do this on AWS)

1. Add remote and checkout `yuankunzhu:release/v11` which makes the required changes to the data download step : https://github.com/yuankunzhu/OpenPBTA-analysis/tree/release/v11
2. Run `bash download-data.sh` to obtain the v11 data while on that branch
3. Add origin and checkout this branch `jaclyn-taroni:ci-v11` which contains the required changes to generate the v11 files for CI.
4. Run `./analyses/create-subset-files/create_subset_files.sh`.
5. Snag the files in `data/testing/release-v11-2019122`; they are what we need for CI.

Because we'll be subsetting VarDict, this will need to be run with 128 GB of RAM.

**Comment by jaclyn-taroni** [comment]
We're going to need to take into account `reported_gender` because not taking this into account is causing a failure in the sex prediction from RNA-seq steps: https://circleci.com/gh/AlexsLemonade/OpenPBTA-analysis/1526

**Comment by jaclyn-taroni** [comment]
Closed via #297 and #308
