### ISSUE TITLE
Updated analysis: TMB Coding vs TMB with all mutations

### ISSUE THREAD

**Issue by cansavvy** [AlexsLemonade/OpenPBTA-analysis#305]
#### What analysis module should be updated and why?

snv-caller analysis 

#### Why should the module be updated?

Currently the TMB stats calculated use all mutations, but we should also have a separate TMB stats for coding mutations only. 

This would be handy for downstream analyses like tmb-tcga-compare to be more comparable to TCGA data which is coding only. 

#### What changes need to be made? Please provide enough detail for another participant to make the update.

Change 03-calculate_tmb.R to save two files: `coding_only` and `all_mutations`. 
Use the  `Variant_Classification` MAF field to sort out coding from non-coding mutations. 

#### What input data should be used? Which data were used in the version being updated?

Same consensus file as before, just the very end needs to be split into two TMB calculated files. 

#### When do you expect the revised analysis will be completed?

This week?

#### Who will complete the updated analysis?

@cansavvy

**Comment by jashapiro** [comment]
It might be worth also having a TMB calculation with the strelka-mutect consensus (no lancet). Lancet calls seem to be biased against non-coding regions (likely due to the way its region file was constructed), as indicated by the fact that it has a smaller fraction of non-coding calls than the other callers. 

I would not expect this to affect relative TMB calculations, but the absolute numbers might be a bit different.

**Comment by cansavvy** [comment]
So should both `coding_only` and `all_mutations` versions of the TMB file be made *only* with mutect and strelka? Or do we want `coding_only` made from all three, and `all_mutations` with only strelka and mutect? What is the least confusing way to handle this as far as TMB files?

**Comment by jashapiro** [comment]
I would lean toward the latter:  `coding_only` TMB from the three caller consensus, and `all_mutations` TMB with only strelka and mutect. But I am happy to hear other opinions.

I *think* the `coding_only` TMB would be similar either way, but I might be wrong there.

**Comment by cansavvy** [comment]
> I would lean toward the latter: `coding_only` TMB from the three caller consensus, and `all_mutations` TMB with only strelka and mutect. But I am happy to hear other opinions.

In order to do this, we are going to need to do a little revamping to `02-merge-callers.R`. Do you have a suggestion on the easiest way to obtain the different consensus files for the downstream TMBs without breaking the whole thing? I think ideally we should include an argument that specifies what callers you would like the consensus to be made from but that will involve a little more work than I was previously thinking. Thoughts/suggestions, @jashapiro?

**Comment by jashapiro** [comment]
Hmm... I don't think we need to go that far; probably just pull from the database file for the two-caller consensus. Just make sure to also include the MNV query to get comparable counts.

**Comment by jharenza** [comment]
@jaclyn-taroni - would this be something to add/update with V12 #326 ?

**Comment by jaclyn-taroni** [comment]
@cansavvy are the files ready? I know all of the related pull requests have not gone through, but wasn’t sure if part 3 will be downstream of these files.

**Comment by cansavvy** [comment]
Part 3 is updating the docs for this. I’d just need to run the full file instead of the subsetted files like I was doing to test it. So I can get the updated TMB files today if want them.

**Comment by jaclyn-taroni** [comment]
Sounds good, let’s get them run today.

**Comment by cansavvy** [comment]
The updated TMB and consensus files have been uploaded (using v11 data) and now we have `coding only` and `all` versions of the TMB stats. Once #333 is merged, I will close this issue.
