### ISSUE TITLE
Documentation: focal-cn-file-preparation README 

### ISSUE THREAD

**Issue by jaclyn-taroni** [AlexsLemonade/OpenPBTA-analysis#319]
[`analyses/focal-cn-file-preparation`](https://github.com/AlexsLemonade/OpenPBTA-analysis/tree/master/analyses/focal-cn-file-preparation) does not have a README.  This README should contain a note about the issues with the two methods (e.g., adding ploidy and status to CNVkit) and that we are generating consensus calls #128. When this README gets written, we should also revisit the numbering of the scripts and notebooks.

**Comment by JemanDaNderZ** [comment]
We can copy from Twitter

**Comment by JemanDaNderZ** [comment]
thankz to none but one 

Jaclyn Taroni 

wanna kno how...
