### ISSUE TITLE
Data analysis/format questions for downstream analysts

### ISSUE THREAD

**Issue by jharenza** [AlexsLemonade/OpenPBTA-analysis#32]
CNV
1. We have ControlFreeC and CNVkit. CNVkit output is VCF – do users want raw output for these or should we convert ControlFreeC output to VCF, then annotate all with AnnotSV (which is what we are using for SV annotation) and then provide annotated tab files?

SV
2. Do we want Novobreak as a 3rd algorithm? Have Manta and and will have Lumpy. 

Annotated/Merge Files
3. We ran Strelka2 and Mutect2 for somatic calls. Do we want to use VEP for SNVs (MAFs are currently annotated with this) or SNPeff? We have both, but VEP was provided.
4. Do we want to provide a limited merged tab file in maf format that includes both Mutect2 and Strelka2 variant calls with a column for “Algorithm”? If so, we need to define the fields - Is this better for users?
5. Should we do the same for CNVs and SVs – provide one merge file of all data? Note: these will be large – (22GB +) and won’t be able to be processed locally
6. Should we set up a CAVATICA project for people to work on interactive analyses (R studio/Jupyter notebooks) or do we think they will do that on their own? We can probably provide some cloud credits for this if they want to do on own – maybe we need instructions?
7. Current plan is for CBTTC and PNOC to be separate merge files, but so we want these to remain separate or be merged? If separate, we need instructions for downstream users to merge all files they download, so I prefer merging all from the start.

SNV
8. Do we want only tumor/normal paired samples or should we also include tumor-only samples? If yes to tumor only, what should we use as PON - normal from cross-brain tumors, normal within disease type (if high enough N), non-cancer pediatric normals?

@gonzolgarcia @samesense @Yiran-Guo @gwaygenomics @jpfeil @kgaonkar6 @LauraEgolf @apexamodi @nathankendsersky @afarrel @jaclyn-taroni @PichaiRaman please weigh in. cc: @yuankunzhu

**Comment by cgreene** [comment]
I am just heading out of town so this is really short and not a comprehensive set of answers, and instead some guiding principles:

* Standard file formats are preferred for the initial distribution. This way tooling, to the extent possible, will already work with it. My inclination for your first question (as an example) would be to have both in VCF if that's what's most widely used.
* If we want people to analyze data from both studies together, we should supply them as merged files. Lowers the chance of processing errors downstream leading to analyses that don't work on part of the data.

If you want to keep refining the data that's fine, but we should have a file in a standard file format for each data type that we want to use. This means we'll need to be a bit opinionated, but without that there will be a plethora of files and people may use very different files for, say, gene expression. This will increase the load of what people "need to know" to engage with the project, and then reduce the number of participants.

**Comment by samesense** [comment]
5. For merged files, use gvcf or something similar that provides depth of coverage for non-variants.
6. Less data duplication and updates if you provide notebooks that point to same cloud datasource.
7. Merge at start.
8. Include tumor-only to use as additional evidence when making arguments about somatics.
* As you update data, I'd git-lfs for data version control.

**Comment by cgreene** [comment]
From our experience, git-lfs has significant limitations around file size and transfer that make it unsuitable for a project like this.

I do think that the place it's being distributed from should provide a zip file that unzips with versioned file names, a readme with a version and changelog, file checksums & automated checking in the download script, and ideally symlinks (if we can assume that folks are on platforms w/ symlinks) for non-versioned filenames.

This way we can replace the symlinks on our CI service with ones that point to a subset of the data to test the processing code.

**Comment by jharenza** [comment]
@yuankunzhu ^

**Comment by samesense** [comment]
> From our experience, git-lfs has significant limitations around file size and transfer that make it unsuitable for a project like this.

Good point. I've been working with a custom git-lfs server that talks directly to google cloud storage, and didn't realize the limitations of other implementations.

**Comment by jharenza** [comment]
Thanks for all of the comments!
