### ISSUE TITLE
Therapy Response and Outcome Data

### ISSUE THREAD

**Issue by GeoffLyle** [AlexsLemonade/OpenPBTA-analysis#329]
Is there data on therapies used and patient outcomes for any of the samples?  

I saw the `OS_days` and `OS_status` columns in the `pbta-histologies.tsv`, but I couldn't discover anything related to treatment information in the v11 data release.  Any therapies tried on the derived cell lines and their IC50 values would also be of interest.

**Comment by jharenza** [comment]
Hi @GeoffLyle! Looked at the data we have available - I can add some columns for chemotherapy yes/no, radiation yes/no, chemotherapy drug (many may be "not reported" even if chemo == yes). We don't currently have organized IC50 data for the cell lines, though I will loop in @mkoptyra re: cell line IC50 data. We are planning V12 data release (#326) very soon (late this week/early next week) and can throw throw this data into the clinical file.

**Comment by GeoffLyle** [comment]
@jharenza That's great!  Thanks for the quick turnaround!  Is there data for columns "targeted_therapy" yes/no, "targeted_therapy_drug" <TEXT>?

**Comment by jharenza** [comment]
I see a protocol column, and for most, the drugs are not immediately available - one would have to go back to all of the protocols to determine this. I will check whether this can be publicly shared!

**Comment by jharenza** [comment]
Hi @GeoffLyle! As I was preparing the new clinical file, I ran into quite a few things that are going to preclude me from adding therapy status. The major issue is that the way things were recorded was by specimen level and not patient level, such that if a patient had radiation, there may be one sample that is linked to `yes` radiation and another `no` radiation. Same situation with chemotherapy and drugs. I attempted to collapse all drugs and trials together, but I think it is just too messy and potentially mistake-ridden for distribution right now. The clinical and databasing teams might have to do some additional work on this. cc-ing @allisonheath. I am sorry about this.

**Comment by GeoffLyle** [comment]
@jharenza Thanks for the update!  No worries on updating the clinical data.  I talked with my team and if there is no response data (ex. SD = Stable Disease) to go with the treatment then knowing the drug given is less useful as machine learning information.  However, knowing if a sample is pre or post-treatment would be of interest.  Thanks for your work on this issue!

**Comment by jharenza** [comment]
@GeoffLyle going to close this for the reasons mentioned above. Sorry we couldn't add more information at this time.
