### ISSUE TITLE
Script to generate a subset of the data

### ISSUE THREAD

**Issue by cgreene** [AlexsLemonade/OpenPBTA-analysis#33]
It would be really handy if there was a script that could be run over the input data files to produce files containing data for only a small, specified number of matched participants. I'm imagining that we would use this to produce data files with information for 10 or so participants. We would then use this code via CircleCI to test the analytical code that people contribute without having to run over the full set of input data.

**Comment by jharenza** [comment]
@yuankunzhu ^

**Comment by jaclyn-taroni** [comment]
@cgreene and I discussed this in person as a follow-up to #44. We'll aim for 5 matched participants across all files. They will contain all the data for these 5 participants.

I can generated these subset files and stick them on S3 to facilitate getting CI up and running.

**Comment by jaclyn-taroni** [comment]
Closed via #56.
