### ISSUE TITLE
Proposed Analysis: genomic differences between primary and relapse samples

### ISSUE THREAD

**Issue by jharenza** [AlexsLemonade/OpenPBTA-analysis#330]
#### What are the scientific goals of the analysis?
Compare primary samples to relapse samples to determine genomic and transcriptomic differences. 

#### What methods do you plan to use to accomplish the scientific goals?
Ideas could be:
- assessing number of mutations/TMB between diagnosis/relapse (literature has shown an increase in TMB/somatic mutations upon relapse for a variety of tumor types, but this is underexplored in the pediatric brain tumors literature) - eg simple barplots of the cohort showing dx/relapse pairs
- assessing SVs between primary/relapse (eg circos plots)
- assessing mutation/CNV/fusion landscape between diagnosis/relapse - can be in the form of a co-oncoplot 
- performing GSEA between diagnosis/relapse to determine whether there are changes in oncogenic pathways expressed - this can utilize single-sample data from #133 

#### What input data are required for this analysis?
- See comment [here](https://github.com/AlexsLemonade/OpenPBTA-analysis/issues/16#issuecomment-549360497) for samples with primary and relapse samples
- mutations: consensus MAF files, TMB files
- fusions: prioritized fusion calls
- SVs: manta SV TSV
- CNV: consensus CNV calls

#### How long do you expect is needed to complete the analysis? Will it be a multi-step analysis?
2-4 weeks; yes

#### Who will complete the analysis (please add a GitHub handle here if relevant)?
up for grabs

#### What relevant scientific literature relates to this analysis?
neuroblastoma relapse literature: 
- https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5172533/
- https://www.ncbi.nlm.nih.gov/pubmed/26121087
- https://www.ncbi.nlm.nih.gov/pubmed/26121086
leukemia relapse literature:
- https://www.ncbi.nlm.nih.gov/pubmed/31697823

**Comment by cgreene** [comment]
The sample count here is very limited. That table that you linked (https://github.com/AlexsLemonade/OpenPBTA-analysis/issues/16#issuecomment-549360497) shows that even for the most common histology the samples with matched primary/relapse is 5. I propose that we put the table and the process by which it was derived into the manuscript. As the collection grows (maybe for analysis V2), perhaps the number will increase to the point where it is feasible to do more and this could provide an outline.

**Comment by jharenza** [comment]
Closing this for v1
