### ISSUE TITLE
Missing project details from readme

### ISSUE THREAD

**Issue by quaidmorris** [AlexsLemonade/OpenPBTA-analysis#332]
If you are trying to attract new folks, you need to say front and center more about this project.

Things that people thinking about analyzing these data will be interested in include:

-Number of samples
-What kind of cancer, also primary vs met, treatment status
-Type of sequencing (looks like WGS + Panel, RNAseq)
-Depth, sequencing type: eg 150nt paired end, details on the panel and how it was designed
-Source: fresh frozen versus FFPE

All of this information influences how you do the analysis and folks assessment about whether it is an interesting project to join.

**Comment by jharenza** [comment]
Hi @quaidmorris - great idea! We will add this information in tabular format in the README and clearly label the link to the [manuscript](https://alexslemonade.github.io/OpenPBTA-manuscript/) being created in the [manuscript repository](https://github.com/AlexsLemonade/OpenPBTA-analysis) for the finer method details. I will update this ticket once completed.

**Comment by quaidmorris** [comment]
@jharenza Awesome!

Can I also recommend writing 1-2 paragraphs of the intro to the manuscript, and possibly including that in the README as an introduction to potential new people to the project? Casey told me about your project last night but didn't give many details and it's a bit hard right now to figure out what y'all are up to.

Something like:

"The Open Pediatric Brain Tumor Atlas is a community-driven project to jointly analyze genomic data collected from brain tumors of X volunteers. The goals of this project are ... 
We collected WGS data and RNA-seq data from X donors, sampling their resected [insert type of brain tumor] tumors. For secondary analysis, to identify driver mutations associated with prognosis or treatment response, we deeply sequenced DNA collected using a targeted panel of Y key driver genes [or whatever]. These data were jointly analyzed, using open source tools by a large collection of researchers organized through a Github repository, in order to characterize the landscape of pediatric brain tumors and genomic predictors of clinical response."

**Comment by jaclyn-taroni** [comment]
Suggestion from @jashapiro about where some of this content should go https://github.com/AlexsLemonade/OpenPBTA-analysis/pull/342/files#r358922674

**Comment by jharenza** [comment]
Added some of these details in #361

**Comment by cgreene** [comment]
Hi @quaidmorris : is this new section of the readme that @jharenza added helpful?
https://github.com/AlexsLemonade/OpenPBTA-analysis#data-description

**Comment by quaidmorris** [comment]
Super helpful! This is exactly what I was looking for! Awesome job!
