### ISSUE TITLE
Updated analysis: TMB by Molecular Subtype

### ISSUE THREAD

**Issue by cansavvy** [AlexsLemonade/OpenPBTA-analysis#335]
#### What analysis module should be updated and why?

When all the molecular sub-typing issues have been addressed, will we want to update TMB plots to break things down by subtype? If so, what would this look like and what output would we be looking for? 

Should each short_histology group be broken out into its own graph and color coded by molecular subtype?

**Comment by cansavvy** [comment]
I think this is generally covered by the newer TMB CDF plots which are broken up by histology, so this can be closed?

**Comment by jharenza** [comment]
I don't think this will be necessary - I think the global views by broader histology, compared to TCGA are exactly what we want.
