### ISSUE TITLE
Updated Data Files: Add intersection genome BED files used for TMB to v13 data release

### ISSUE THREAD

**Issue by cansavvy** [AlexsLemonade/OpenPBTA-analysis#351]
#### What data file(s) does this issue pertain to?

The effective genome BED ranges should be added to v13 data release. 
These [files are created in snv-callers for TMB calculations](https://github.com/AlexsLemonade/OpenPBTA-analysis/tree/master/analyses/snv-callers#tumor-mutation-burden-calculation) and [should also be used in `mutational-signatures` calculations](https://github.com/cansavvy/openpbta-notebook-concept/issues/5).  

There are three of them: 
`intersect_exon_WXS.bed`
`intersect_strelka_mutect_WGS.bed`
`intersect_exon_lancet_strelka_mutect_WGS.bed`

I can put them on S3 when we are getting closer to v13.

#### Put a link to the relevant section of the [OpenPBTA-manuscript](https://github.com/AlexsLemonade/OpenPBTA-manuscript/) here.

[This manuscript PR](https://github.com/AlexsLemonade/OpenPBTA-manuscript/pull/66) discusses these files on a conceptual level, but the [SNV-callers README](https://github.com/AlexsLemonade/OpenPBTA-analysis/tree/master/analyses/snv-caller) has more info.

Related [issue](https://github.com/cansavvy/openpbta-notebook-concept/issues/5)

**Comment by jaclyn-taroni** [comment]
@cansavvy - do you have these files available on S3?

**Comment by cansavvy** [comment]
> @cansavvy - do you have these files available on S3?

I do not. Where should I put them on S3?

**Comment by cansavvy** [comment]
Should I add them to the `snv-consensus` folder or also zip them up on in the `snv-consensus` zip file?

**Comment by jaclyn-taroni** [comment]
From discussion in person: Do not include them in the `snv-consensus` zip file

**Comment by cansavvy** [comment]
I've made them their own folder in the `open-pbta` S3 bucket. https://open-pbta.s3.amazonaws.com/data/snv-consensus-bed/

**Comment by jaclyn-taroni** [comment]
Closed via #444
