### ISSUE TITLE
Unknown sample BS_4X8PQ5G6

### ISSUE THREAD

**Issue by jashapiro** [AlexsLemonade/OpenPBTA-analysis#371]
#### What data file(s) does this issue pertain to?

`pbta-gene-counts-rsem-expected_count.stranded.rds`

#### What release are you using?

v12

#### Put your question or report your issue here.

The file `pbta-gene-counts-rsem-expected_count.stranded.rds` contains a column with data for the sample `BS_4X8PQ5G6` which does not appear in other files, and is not described in `pbta-histologies.tsv`

**Comment by jharenza** [comment]
Hi @jashapiro - sorry for all of these mistakes in the v12 files. I think we need to implement a QC process around the files prior to release - we will work on this on our end.

`BS_4X8PQ5G6` should not have made it into any of the files, as it was a newly stranded sequenced RNA, but it was deemed mismatched to its previous polyA RNA sample, hence why it is not in the histologies file. cc-ing @kgaonkar6 and @tkoganti for this - will update for V13.

**Comment by jaclyn-taroni** [comment]
v13 data does not contain this biospecimen:
```r
> "BS_4X8PQ5G6" %in% colnames(`pbta-gene-expression-rsem-fpkm.stranded`)
[1] FALSE
> "BS_4X8PQ5G6" %in% histologies_df$Kids_First_Biospecimen_ID
[1] FALSE
```
Closing this issue.
