### ISSUE TITLE
Propagate medulloblastoma `molecular_subtypes` labels to all biospecimens of the same sample

### ISSUE THREAD

**Issue by cansavvy** [AlexsLemonade/OpenPBTA-analysis#379]
#### What data file(s) does this issue pertain to?

`pbta-histologies.tsv`

#### What release are you using?

release-v12-20191217

#### Put your question or report your issue here.

Related to PR #378 

Molecular subtyping labels have been added for medulloblastoma RNA-seq samples in the `molecular_subtype` column since for medulloblastoma, these `molecular_subtypes` are based on RNA-seq data. 

However,  I *think* it can be assumed `biospecimen`s from the same `sample_id` would have the same `molecular_subtype`. It would be handy to have the medulloblastoma subtype labels in `molecular_subtype` column propagated to other` biospecimen`s of the same `sample` of origin. 

I temporarily got around this issue for #378 by doing a `list` based `dplyr::recode`.

**Comment by jharenza** [comment]
Hi @cansavvy! I think that I didn't do this only because I recall seeing one MB patient with two biospecimens and each had a different subtype. Did you run into this at all?

**Comment by cansavvy** [comment]
@jharenza here are the numbers breakdowns before and after propagating the medulloblastoma label. There are 98 samples (105 - 7) that do not have `molecular_subtype` labels originally but are associated with sample_id 's that have `molecular_subtype` labels.

Before propagating labels: 
```
Group3 Group4    SHH    WNT   NA's 
    15     67     31     11    105 
```
After 
```
Group3 Group4     NA    SHH    WNT 
    26    118      7     57     21 
```

Here's the code where I got these numbers, this is also included in the SHH-TP53 notebook. 
```r
metadata <-
  readr::read_tsv(file.path(data_dir, "pbta-histologies.tsv")) %>%
  dplyr::filter(disease_type_new == "Medulloblastoma")

# Check summary of subtypes here
summary(as.factor(metadata$molecular_subtype))

#Propagate the `molecular_subtype` labels to biospecimens of the same `sample_id`.
#First make a key of molecular subtype to `sample_id`.

key_df <- metadata %>%
  dplyr::filter(!is.na(molecular_subtype)) %>%
  dplyr::select(molecular_subtype, sample_id)

# Make into list form so it can be used in dplyr::recode
key <- key_df$molecular_subtype
names(key) <- key_df$sample_id

# Recode and filter to all `sample_id`s that are `SHH` and have `WGS` or `WXS` data.
recoded_metadata <- metadata %>%
  dplyr::mutate(molecular_subtype = dplyr::recode(sample_id, 
                                                  !!!key, 
                                                  .default = "NA"))
# Check summary after recoding
summary(as.factor(recoded_metadata$molecular_subtype))
````

**Comment by cansavvy** [comment]
I don't believe I ran into biospecimen's with different subtype labels, but I will double check that now.

**Comment by cansavvy** [comment]
> Hi @cansavvy! I think that I didn't do this only because I recall seeing one MB patient with two biospecimens and each had a different subtype. Did you run into this at all?

We shouldn't need the same all a participants' biospecimens to have the same `molecular_subtype` right? What I'm talking about in this issue is propagating labels from the same `sample_id`s not the same `Kids_First_Participant_ID`.

**Comment by jharenza** [comment]
yes, you're right, @cansavvy - in that case, the use of sample_id is perfect

**Comment by jaclyn-taroni** [comment]
Looking at v13, this appears to be resolved and correct:
```r
> histologies_df <- read_tsv("data/pbta-histologies.tsv",
                             col_types = cols(molecular_subtype = col_character()))

> mb_histology_subtype <- histologies_df %>% 
    filter(!is.na(molecular_subtype)) %>% 
    group_by(sample_id, molecular_subtype) %>% 
    count()

> head(mb_histology_subtype)
# A tibble: 6 x 3
# Groups:   sample_id, molecular_subtype [6]
  sample_id molecular_subtype     n
  <chr>     <chr>             <int>
1 7316-1038 SHH                   1
2 7316-1083 Group4                2
3 7316-109  Group4                2
4 7316-1104 SHH                   1
5 7316-1118 Group4                2
6 7316-135  Group3                2

> any(duplicated(mb_histology_subtype$sample_id))
[1] FALSE
```
Closing this issue.
