### ISSUE TITLE
Planned Analysis: Filter and Annotate Fusions

### ISSUE THREAD

**Issue by jharenza** [AlexsLemonade/OpenPBTA-analysis#39]
Here, we will filter potential artifacts, filter fusions observed in normal tissue, retain high-confidence calls, and annotate with several databases to create a final list of putative driver fusions.

**Comment by jharenza** [comment]
@kgaonkar6 and I have created a workflow for this, will update soon!

**Comment by jaclyn-taroni** [comment]
Is this pipeline described in https://github.com/AlexsLemonade/OpenPBTA-manuscript/pull/21?

**Comment by jharenza** [comment]
> Is this pipeline described in [AlexsLemonade/OpenPBTA-manuscript#21](https://github.com/AlexsLemonade/OpenPBTA-manuscript/pull/21)?

It is not yet described there. Do you think we should add it to the methods section or part of the analysis/results section? We created a workflow (and @kgaonkar6 created an R package) to annotate fusion gene partners as TSG, oncogene, kinase, TF, receptor, added expression of each gene, filtered out artifacts, fusions in normal tissues, etc, to come up with a high-confidence list of putative driver fusions. It is probably more of a method, but weren't going to add until this PR was finished - still making tweaks.

**Comment by jaclyn-taroni** [comment]
>  It is probably more of a method, but weren't going to add until this PR was finished - still making tweaks.

Ah, sounds good. This is the order I would expect. Are the `Fusion prioritization` steps described in https://github.com/AlexsLemonade/OpenPBTA-manuscript/pull/21 then upstream, e.g., they have been performed on the fusion TSV files?

**Comment by jharenza** [comment]
They are all post data download of TSV files.

**Comment by syzheng** [comment]
> To clarify, this is very helpful:
> 
> > Here, we will filter potential artifacts, filter fusions observed in normal tissue, retain high-confidence calls, and annotate with several databases to create a final list of putative driver fusions.
> 
> I'm wondering about things like where the fusions observed in normal tissue information is coming from.

it can be from multiple resources. For instance, TCGA normal samples have been analyzed for fusions; but the best source might be GTEx. One issue with using normal sample for filtering is that the normal samples should be analyzed with the same pipeline used for cancer so to minimize tool introduced artifacts.

**Comment by jharenza** [comment]
closed with #294 #300 #277 #267
