### ISSUE TITLE
Discussion: consensus CN files for downstream analyses

### ISSUE THREAD

**Issue by jaclyn-taroni** [AlexsLemonade/OpenPBTA-analysis#392]
**Related to the generation of copy number consensus calls: #128**

Downstream analysis of copy number data, including analysis with GISTIC (#8), often relies on information contained in a SEG file outside of the region, e.g., `seg.mean` from CNVkit. @fingerfen is generating consensus calls from CNVkit, ControlFreeC, and Manta.

From @hongboxie https://github.com/AlexsLemonade/OpenPBTA-analysis/issues/128#issuecomment-555521330:

> We will present two types of CNVs: Amplification (ploity>2) or Deletion (ploidy<2). We created 3 additional columns where we display original outcome of each method overlapping this region as evidence. The original output of each predictor will carry the information of the ploidy, if it has it.

My interpretation of this comment is that some of the required information for downstream analysis will be retained. 

I am filing this ticket to facilitate discussion around how we will use the copy number consensus results for downstream analysis. Because [GISTIC is currently run on the CNVkit data](https://github.com/AlexsLemonade/OpenPBTA-analysis/blob/master/doc/data-formats.md#copy-number-files) (and in my pretty limited experience there seems to be a decent amount of tooling for using CNVkit output), subsetting the CNVkit SEG file to only those regions that have support from the other methods and using that when `seg.mean` values are required is what comes to mind.

I am also tagging @jashapiro who has been reviewing the consensus code and @jharenza.

**Comment by jharenza** [comment]
Hi @jaclyn-taroni - I think this sounds like a reasonable approach for CNVkit results/analyses requiring SEG files. Would be happy to rerun GISTIC once we have these consensus calls.

**Comment by hongboxie** [comment]
@jaclyn-taroni I think it sounds reasonable. Do you have overall plan for downstream analysis of CNV data?

**Comment by jaclyn-taroni** [comment]
@hongboxie broadly speaking, we'll want to run GISTIC (#8) and plot recurrent alterations in an OncoPrint (#6; though this does not require the segment mean values; also somewhat related to #394). I am assuming we probably want to integrate the CNV data with the SV data for visualization purposes. I've found this [UMCCR pipeline code](https://github.com/umccr/rock) that uses Manta and CNVkit output to create circos plots. I bet we can adapt it (or use it to guide something similar) to use the "consensus filtered" CNVkit data mentioned here, the AnnotSV-annotated Manta file, and [`circlize`](https://github.com/jokergoo/circlize).

**Comment by hongboxie** [comment]
@jaclyn-taroni Sure! Typically circular plot will benefit visualizing genomic translocation. If there is a team working on providing translocation, that will be perfect. Long time ago, we clustered CNVs into groups, to see whether certain tumor or tumor+stages. Not sure if those are something in our plan.

**Comment by jaclyn-taroni** [comment]
Closed via #441 and the file release is mentioned on #432.
