### ISSUE TITLE
Proposed Analysis: Chromothripsis analysis with ShatterSeek, SV signatures

### ISSUE THREAD

**Issue by jaclyn-taroni** [AlexsLemonade/OpenPBTA-analysis#393]
I am splitting up #27 into more focused tickets. I am copying some of the information below from the closed pull request #271.

#### What are the scientific goals of the analysis?

>  1. structural variations analysis
>  2. chromothripsis analysis
>  3. decipher signatures of structural variations
>  4. to understand the potential mechanism behind tumors through structural variations analysis

From https://github.com/AlexsLemonade/OpenPBTA-analysis/issues/27#issuecomment-516471524, I expect

> A barplot with the frequency of chromothripsis prevalence by tumor subtype

will be produced as part of this analysis. We also want to make sure the following downstream analyses are supported with the output from this analysis (again from https://github.com/AlexsLemonade/OpenPBTA-analysis/issues/27#issuecomment-516471524):

> association of chromothripsis with other somatic alterations (i.e. TP53 status)
> multivariate [survival] analyses including clinical variables as well as ... chromothripsis.

#### What methods do you plan to use to accomplish the scientific goals?

* ShatterSeek for chromothripsis detection 
* NMF for SV signature analysis

#### What input data are required for this analysis?

`pbta-sv-manta.tsv.gz`
`pbta-cnv-cnvkit.seg.gz`

#### How long do you expect is needed to complete the analysis? Will it be a multi-step analysis?

Based on #271 (see also: https://github.com/yangyangclover/OpenPBTA-analysis/tree/048e5f6576795330a75ac3b91f51246ec84d36cf/analyses/structural-variation-signature), I expect that this is at least a four step analysis.

#### Who will complete the analysis (please add a GitHub handle here if relevant)?

@yangyangclover has contributed the first part (#283; processing Manta file for use with ShatterSeek) so far. Also tagging @guru-yang.

#### What relevant scientific literature relates to this analysis?

Cortés-Ciriano et al. Comprehensive analysis of chromothripsis in 2,6  58 human cancers using whole-genome sequencing. _bioRxiv._ 2018. DOI: [10.1101/333617
](https://doi.org/10.1101/333617)

**Comment by jaclyn-taroni** [comment]
Hi @yangyangclover, we are looking to wrap up the analyses for this within the next couple of weeks. Do you have an idea of when you will be able submit the next pull request for this analysis?

**Comment by yangyangclover** [comment]
Hi @jaclyn-taroni, sorry about the late reply, I just came back from my vacation. I will upload the result soon. Happy new year to you!

**Comment by jaclyn-taroni** [comment]
@yangyangclover happy new year to you as well! Sounds good -- looking forward to it!

**Comment by jaclyn-taroni** [comment]
Hi @yangyangclover, based on your [README for `sv-analysis`](https://github.com/AlexsLemonade/OpenPBTA-analysis/blob/master/analyses/sv-analysis/README.md) and pull requests you've submitted in the past, I expect that you will be adding some plots to this module. It would also be great to address https://github.com/AlexsLemonade/OpenPBTA-manuscript/issues/75 so others have a better understanding of your methodology and can readily use your results. What is your time line for pull request submission?

Thank you, let me know if you need any help getting started with the manuscript writing in particular!

**Comment by yangyangclover** [comment]
Hi @jaclyn-taroni , I am glad to add some plots to this module, such as "the percentage of chromothripsis sample across different tumor type", "genome chromothripsis events", or others?

I do have some figures locally and I can send them to you, then you can see what you need, and I can upload the codes and figures.

I hope I can finish the manuscript this week.

**Comment by jaclyn-taroni** [comment]
Hi @yangyangclover – thanks for the quick reply! It'd be great have you share the plots you have locally. If you zip them up or if the individual plots are PNGs, you are able to drag and drop them into a comment here. Thanks!

**Comment by yangyangclover** [comment]
**chromothripsis  event in one patient**
![BS_1M63B97V_1_2_4_5_6_7_8_11_15_16_17_18_consensus](https://user-images.githubusercontent.com/7209877/74545833-2ad61b80-4f0f-11ea-90cd-b9ec2c57fb8f.jpeg)

**the percentage of chromothripsis sample across different tumor type**
![image](https://user-images.githubusercontent.com/7209877/74546069-98824780-4f0f-11ea-90de-129d1e1f41ec.png)

**association between chromothripsis and  other info**
![image](https://user-images.githubusercontent.com/7209877/74546147-bbacf700-4f0f-11ea-8fdf-088654776f15.png)

**distribution of SV**
[SV Number_PBTA.pdf](https://github.com/AlexsLemonade/OpenPBTA-analysis/files/4205219/SV.Number_PBTA.pdf)
[SV Percent_PBTA.pdf](https://github.com/AlexsLemonade/OpenPBTA-analysis/files/4205220/SV.Percent_PBTA.pdf)

**Comment by jharenza** [comment]
This was completed with #1106 #1098 #1083
