### ISSUE TITLE
Proposed Analysis: chromosomal instability burden, recurrently altered genes

### ISSUE THREAD

**Issue by jaclyn-taroni** [AlexsLemonade/OpenPBTA-analysis#394]
I am breaking up #27 into more focused issues.

#### What are the scientific goals of the analysis?

Integrated analysis of CNV and structural variant data. This issue covers readouts/output described in https://github.com/AlexsLemonade/OpenPBTA-analysis/issues/27#issuecomment-516471524 that are not captured by #393, specifically (paraphrasing):

* Generating a measure of chromosomal instability (CIN) burden that can be plotted by tumor type
* Identify recurrently altered genes to be included in the OncoPrint (#6)
  - Amplification/tandem-duplication
  - Deep deletion/deletion
  - Other Structural variation: Inversion, translocations

#### What methods do you plan to use to accomplish the scientific goals?

From  https://github.com/AlexsLemonade/OpenPBTA-analysis/issues/27#issuecomment-516471524:

> In order to integrate CNV calls and SV calls we focus on breakpoint co-locallization, more details in the manuscript: https://www.biorxiv.org/content/10.1101/572248v3

@gonzolgarcia do you have additional guidance you can provide outside of what you included on #27 such that someone else can complete this analysis? Links to source code would be ideal. Thank you!

#### What input data are required for this analysis?

`pbta-cnv-cnvkit.seg.gz` - though we ultimately may want to use a consensus filtered file (related: #128 #392)
`pbta-sv-manta.tsv.gz`

#### How long do you expect is needed to complete the analysis? Will it be a multi-step analysis?

Unknown; the scope of this will need to be refined.

#### Who will complete the analysis (please add a GitHub handle here if relevant)?

@cansavvy is going to start digging into this a bit.

#### What relevant scientific literature relates to this analysis?

Lopez et al. Somatic structural variation targets neurodevelopmental genes and identifies SHANK2 as a tumor suppressor in neuroblastoma. _bioRxiv._ 2019. DOI: [10.1101/572248](https://doi.org/10.1101/572248)

**Comment by cansavvy** [comment]
Does anyone know anything about [CINdex](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5761903/)?  I don't see any indication of it using SV data though, only CNV data.

**Comment by jaclyn-taroni** [comment]
From @jharenza (paraphrasing) - the first point (CIN burden) could be measured by "breakpoint density" which was used in the PPTC PDX paper. Here is the relevant code: https://github.com/marislab/pptc-pdx-copy-number-and-SVs/blob/1bc5bbbc6e88daee0b0b5654203a5d5c31caf96b/R/sv_figure.R The number of breakpoints was calculated by using 10% copy number change between breaks from SNP _arrays_.

High Breakpoint Density (HBD) was used as a surrogate for measuring chromothripsis, but we have WGS for this project. We could consider using the ShatterSeek output (#393) instead of breakpoint density.

**Comment by jaclyn-taroni** [comment]
Package from @gonzolgarcia: https://github.com/gonzolgarcia/svcnvplus

**Comment by gonzolgarcia** [comment]
Hi,
I would like to share my brand new R package that implements analytical and visualization tools proposed in this issue: 
[https://github.com/gonzolgarcia/svcnvplus](https://github.com/gonzolgarcia/svcnvplus)

The package include many tools for the analyses of CNV and SV data:

1. Integrated CNV and SV analyses

- **percent.genome.changed** per sample measure of genome instability; calculates what percentage the genome’s copy number log2-ratio != 0.
- **seg.breaks** identifies segment breaks based on ΔCNV  (the fold change of the CN between contiguous segments) threshold. In addition, ‘seg.breaks’ and ‘sv.breaks’ measure per sample breakpoint burden.
- **cnv.freq.plot** aggregates segments which copy number log-ratio != 0 and plots a genome wide map of gain/lost frequencies (Fig 1a).
- **match.breaks** evaluates the colocalization of breakpoints from CNV segmentation data and SV calls for a set of common samples. 
- **gene.cnv** obtains gene-level CNV matrix from segmentation data from which amplifications and deep-deletions can be queried.
- **cnv.break.annot** and ‘sv.break.annot’ evaluate whether breakpoints overlap with known genes and their upstream regions. Produces gene level variant association reports.

2. Chromosome shattering analyses: 

- **shattered.regions** combines CNVs and SV calls into a map of genomic regions with high breakpoints density (HBD) regions as candi-dates of chromothripsis or chromoplexia. The definition of HBD regions is highly parametrizable; by default: 
- **shattered.region.cnv** identifies shattered regions using CNV segmen-tation data only. Parameters derived from CNVs are used: num-ber of breakpoints, 
- **shattered.map.plot** generates a genome wide map of regions with chromosome shattering (Fig. 1b)
- **circ.chromo.plot** is a wrapper of circlize (Gu, et al., 2014) function-alities for circus plotting. And produce CNV and SV visualiza-tions with shattered chromosomes (Fig 1b). In addition, ‘circ.wg.plot’ generates whole genome CNV and SV links circos plots.

There is a complete vignette in the github page.

**Comment by cansavvy** [comment]
Thanks, @gonzolgarcia , for this nice summary of the package. I've been looking through your code a bit after @jaclyn-taroni pointed me to it. Thanks for sending the link.

**Comment by gonzolgarcia** [comment]
@cansavvy I have just updated the latest commit at [svcnvplus](https://github.com/gonzolgarcia/svcnvplus). I would really appreciate any feedback.

**Comment by cansavvy** [comment]
@gonzolgarcia , here are the output plots from the code that I have queued up as a pull request on #419. Would you be able to take a look at these plots and let me know if there is anything missing from these plots that would help aid your interpretation of the data? Secondly, is median number of breakpoints an acceptable value to present for grouped tumor-type data or would you suggest a different summary stat? 

*Heatmap of breakpoints for individual samples:*
[breaks-heatmaps.zip](https://github.com/AlexsLemonade/OpenPBTA-analysis/files/4072417/breaks-heatmaps.zip)

*Breakpoint data grouped by tumor-type:* 
[tumor-type.zip](https://github.com/AlexsLemonade/OpenPBTA-analysis/files/4072418/tumor-type.zip)

You can see the rendered notebook here for more details and context: https://cansavvy.github.io/openpbta-notebook-concept/chromosomal-instability/chromosomal-instability.nb.html

**Comment by cansavvy** [comment]
### Summary of recurrent breakpoint genes tentative plan: 
For identifying genes that have recurrent breakpoints, my tentative plan is to report number of exonic breakpoints per gene. I'll subdivide this by breakpoint types (Amplification/Deletion and the categories of `SVtypes`). And I think these data should also be reported in proportion to exonic gene length (per kb exon length or something like that). Does anyone have comments or suggestions?

**Comment by gonzolgarcia** [comment]
@cansavvy I have a few comments on the #419.
1.  Regarding the common breaks, I think you are using a different approach compared to what I have implemented in [svcnvplus](https://github.com/gonzolgarcia/svcnvplus/). Specifically, the function [match.breaks](https://github.com/gonzolgarcia/svcnvplus#co-localization-of-breakpoints) looks at the intersection (as opposed to the union) between CNVs and SV calls. The idea is that both approaches are orthogonal and that breaks that appear in both data types are the most reliable. However,  SVs that do not involve a copy number dosage change (e.g. inversions and some translocations) won't appear in the CNV profile; so CNV and SV are also complementary. In other datasets I have looked into, 20%-40% of breakpoints are in the common set. I think that'd be a good quality control test for this datasets.
2. I looked at the heatmaps and it seems that there are genomic regions with high density of breakpoints across all tumors; my guess is that those brakpoints come from the CNV data an my impression is that those are mostly artifacts. This often happens in low coverage regions (e.g centromeres and sub-telomeric regions). I would recommend filtering out those regions or applying filters for repetitive CNV segments that appear across many tumors. This is also implemented 
3. For the representation of chromosomal instability I would recommend using the same as tumor mutational burden plots. See an  
![example](https://user-images.githubusercontent.com/17988364/72628582-98952480-391c-11ea-8c2f-0005b55e81c2.png) based on TCGA. I will include the code in the package vignette. One way to be stringent about this is to consider only common breaks (as explained in comment 1)

Finally, note that svcnvplus has not a stable version yet, I have been updating and I got my code audited and my hope is to publish v1.0 by the end of next week.

**Comment by cansavvy** [comment]
> Specifically, the function match.breaks looks at the intersection (as opposed to the union) between CNVs and SV calls.

Thanks for this advice. I will definitely switch it to an intersection, that sounds like a good call. 

> I looked at the heatmaps and it seems that there are genomic regions with high density of breakpoints across all tumors; my guess is that those brakpoints come from the CNV data an my impression is that those are mostly artifacts.  

We suspect this too, but the data you see here will be finalized a bit more when we switch to our consensus CNV data. Hopefully this dataset has less of the calls that seem like false positives. After we get that data switched in we'll be able to take a more realistic look.

**Comment by jaclyn-taroni** [comment]
I am marking this as blocked by #438 per https://github.com/AlexsLemonade/OpenPBTA-analysis/pull/419#pullrequestreview-344903979

**Comment by jaclyn-taroni** [comment]
Moving this over from: https://github.com/AlexsLemonade/OpenPBTA-analysis/issues/245#issuecomment-576710898

Discussed in person with @cansavvy: the chromosomal instability info is typically displayed like TMB but we need to revisit the "effectively surveyed region of the genome" BED files (#440) and because chromosome instability measures will eventually use the _consensus_ and we want to filter out artifacts due to low coverage per https://github.com/AlexsLemonade/OpenPBTA-analysis/issues/394#issuecomment-575706453, we will want to take into account the blacklist used as part of `copy_number_consensus_calls`: https://github.com/AlexsLemonade/OpenPBTA-analysis/blob/master/analyses/copy_number_consensus_call/ref/bad_chromosomal_seg_updated_merged.bed (related to #438).

**Comment by cansavvy** [comment]
My plan for the next PRs for this issue: 

1) Reconfigure the scripts for the BED files: https://github.com/AlexsLemonade/OpenPBTA-analysis/pull/461
2) Add consensus CNV file and BED and re-run (THis can be done whenever #457 is ready. Should not be a big PR. 
3) Add a [plot like described in the comment above](https://github.com/AlexsLemonade/OpenPBTA-analysis/issues/394#issuecomment-575706453). 
4) Add notebook for recurrent genes analysis for CNV data. 
5) Add notebook for recurrent genes analysis for SV data. 

I think these 5 PRs should address everything and then we can close this issue.

**Comment by cansavvy** [comment]
Now that I have the GISTIC gene `amp` and `del` data wrangled, I need more input on what kind of output we are looking for this recurrent genes analysis for Oncoprint. So far, I took the `amp` and `del` genes from the `_genes.conf_90.txt` files from GISTIC and reformatted it in a way that's useable. Are we looking for just gene lists? 

The _genes.conf_90 files have these fields: 
| gene | wide_peak_boundaries | cytoband | q_value | residual_q_value |

**Comment by jaclyn-taroni** [comment]
Because GISTIC is run on the whole cohort and therefore I expect the q-values in that table also reflect the entire cohort, I think you may want to use the output of `focal-cn-file-preparation` to essentially count how often an alteration occurs: 1) within a histology/subtype/<your favorite category here> 2) across the cohort - you can maybe plan to cross reference the results from number 2 with the GISTIC table?

**Comment by cansavvy** [comment]
So do we want genes that are included in broad arm changes to be included in these results or should be they be included with some sort of asterisk?

**Comment by cansavvy** [comment]
The remaining aspects of this issue have been moved to their own places #488 #487
