### ISSUE TITLE
Proposed Analysis: visualization of CNV and SV data with Circos plot

### ISSUE THREAD

**Issue by jaclyn-taroni** [AlexsLemonade/OpenPBTA-analysis#397]
Related to the following: #393, #394, https://github.com/AlexsLemonade/OpenPBTA-analysis/issues/392#issuecomment-570332277, and https://github.com/AlexsLemonade/OpenPBTA-analysis/issues/27#issuecomment-516471524

#### What are the scientific goals of the analysis?

To generate circular plots that integrate CNV and SV data. Specifically, it might be useful for the following cases:

* Display examples of chromothripsis per https://github.com/AlexsLemonade/OpenPBTA-analysis/issues/27#issuecomment-516471524
* There are some subtype tickets that would benefit from such a visualization (e.g., "[ST-EPN-YAP1] Focal 11q most frequent CNA, with rest of genome stable" #245)
* Likely most useful to examine translocations

The implementation should focus on _flexibility and extensibility_ because we don't know what "final" output will be required for the project.

#### What methods do you plan to use to accomplish the scientific goals?

Here I'm including links to code that could potentially be used to guide this analysis, rather than a specific _method_. 

From https://github.com/AlexsLemonade/OpenPBTA-analysis/issues/392#issuecomment-570332277:

> I've found this [UMCCR pipeline code](https://github.com/umccr/rock) that uses Manta and CNVkit output to create circos plots. I bet we can adapt it (or use it to guide something similar) to use the "consensus filtered" CNVkit data mentioned here, the AnnotSV-annotated Manta file, and [`circlize`](https://github.com/jokergoo/circlize).

Relevant functions from @gonzolgarcia's package mentioned in https://github.com/AlexsLemonade/OpenPBTA-analysis/issues/394#issuecomment-570589012:

* https://github.com/gonzolgarcia/svcnvplus/blob/ea43a5dbd7ae38f1b26520a31af1daddadbaf5dd/R/circ.chromo.plot.r
* https://github.com/gonzolgarcia/svcnvplus/blob/ea43a5dbd7ae38f1b26520a31af1daddadbaf5dd/R/circ.wg.plot.r

#### What input data are required for this analysis?

* SEG file, most likely the "consensus filtered" file #392 (related: #128)
* `pbta-sv-manta.tsv.gz`

#### How long do you expect is needed to complete the analysis? Will it be a multi-step analysis?

~1 week is my rough estimate

#### Who will complete the analysis (please add a GitHub handle here if relevant)?

Unknown/unassigned at this time

**Comment by cansavvy** [comment]
Since I've been working with the CNV and SV data a bit and have made circos plots before, I'm going to work on this ticket.

**Comment by cansavvy** [comment]
My general plan I'm starting on is to make a general purpose circos plotting function. What data would like to be able to be processed into a circos plot? Secondly what kinds of features will we want on these circos plots? 

**Data  types to map:** 
- Chromosomal breakpoint data
- SV seg file
- CNV seg file
- SNV data???

**Features to include**:
- gene annotation for peaks? 
- filter by subtype or histology (perhaps make subtypes each their own track)?

**Comment by cansavvy** [comment]
Some [circos plotting functions and examples of how to use them](https://github.com/AlexsLemonade/OpenPBTA-analysis/blob/master/analyses/chromosomal-instability/01b-visualization-cnv-sv.Rmd) have been added. What's left for this issue is to decide what we want to be plotted.

**Comment by jaclyn-taroni** [comment]
As @cansavvy stated, we have some functionality for generating Circos plots in the [`chromosomal-instability`](https://github.com/AlexsLemonade/OpenPBTA-analysis/tree/master/analyses/chromosomal-instability) module. I am going to close this in favor of opening more specific issues for what, if any, specific plots should be generated.
