### ISSUE TITLE
Proposed Analysis: Fusion files specifically for consumption by molecular subtyping analyses

### ISSUE THREAD

**Issue by jaclyn-taroni** [AlexsLemonade/OpenPBTA-analysis#398]
Related to this thread: https://github.com/AlexsLemonade/OpenPBTA-analysis/pull/315#issuecomment-563425021

#### What are the goals of the analysis?

To generate files that contain information about the _presence or absence_ of specific fusions or genes participating in fusions to be used in generating subtype labels for:

* Ependymoma tumors #245 
* Non-MB/ATRT embryonal tumors #251 

#### What input data are required for this analysis?

We can use the putative oncogenic fusion file for this: `pbta-fusion-putative-oncogenic.tsv`

#### What is the expected output?

I think output here will be most useful if it is divided into two files in tabular format: 1) fusions relevant for ependymoma tumors and 2) non-MB/ATRT embryonal tumors.

Below I include what I think the files should contained based on my understanding of #245 and #251, where columns with a name that consists of a _single gene_ will indicate if that gene is included in _any_ fusion event.

##### Ependymoma

Toy example:

| Kids_First_Biospecimen_ID | RELA | C11orf95--YAP1 | YAP1--MAMLD1 | YAP1--MAMLD2 | YAP1--FAM118B | C11orf95--MAML2 |  PTEN--TAS2R1 | C11orf95--RELA | LTBP3--RELA |
|----|----|----|----|----|----|----|----|----|----|
| BS_XXXXXXXX | 1 | 0 | 0 | 0 | 0 | 0 | 1 | 1 | 1 |

##### Non-MB/ATRT embryonal tumors 

#251 states:

> [ETMR, C19MC-altered] tumors have focal amplification of the miRNA cluster on chr19 (denoted C19MC) and often have gene fusions involving TTYH1 and chr19 miRNA cluster genes.

Side note, I think this is the relevant publication for that: [Kleinman et al. _Nature Genetics_. 2014.](https://doi.org/10.1038/ng.2849)

Because it seems that this cluster would contain over 40 gene symbols ([Wikipedia](https://en.wikipedia.org/wiki/C19MC_miRNA_cluster)), I propose listing which, if any, fusions with _TTYH1_ are present in a sample.

Here's a toy example:

| Kids_First_Biospecimen_ID | TTYH1_fusions | MN1 | MN1--BEND2 | MN1--CXXC5 | FOXR2 | CIC-NUTM1 |
|----|----|----|----|----|----|----|
| BS_XXXXXXXX | TTYH1--`<Gene X>`, `<Gene Y>`--TTYH1 | 1 | 0 | 1 | 0 | 0
| BS_XXXXXXXX | NA | 0 | 0 | 0 | 1 | 0

I don't understand from #251 that the orientation of the MN1--BEND2 and MN1--CXXC5 fusions matters, so I believe BEND2--MN1 and CXXC5--MN1 count.

#### How long do you expect is needed to complete the analysis? Will it be a multi-step analysis?

1-2 days

#### Who will complete the analysis (please add a GitHub handle here if relevant)?

Unassigned. Whoever picks this up, please double check the molecular subtyping tickets and ensure that you agree with my summary!

#### What relevant scientific literature relates to this analysis?

See subtyping tickets.

**Comment by dmiller15** [comment]
I can take this.

**Comment by jaclyn-taroni** [comment]
Hi @dmiller15, thank you and welcome to the project! Please see [our contributing guidelines](https://github.com/AlexsLemonade/OpenPBTA-analysis/blob/master/CONTRIBUTING.md) and the [Implementing an Analysis](https://github.com/AlexsLemonade/OpenPBTA-analysis#implementing-an-analysis) and [How to Add an Analysis ](https://github.com/AlexsLemonade/OpenPBTA-analysis#how-to-add-an-analysis) sections of the README for more information before you implement this analysis.

You may also find this documentation about the putative oncogenic fusion file helpful: https://github.com/AlexsLemonade/OpenPBTA-analysis/blob/master/doc/data-formats.md#derived-fusion-files

If you have any questions, please let us know! Thanks again!

**Comment by jaclyn-taroni** [comment]
Closed via #410
