### ISSUE TITLE
Planned Analysis: MultiPLIER LVs + Survival & Variant Analysis

### ISSUE THREAD

**Issue by cgreene** [AlexsLemonade/OpenPBTA-analysis#4]
We plan to produce a MultiPLIER LV matrix. We then plan to use that analysis to identify LVs associated with survival as well as those associated with samples that contain alterations in selected genes. This issue is for more fully fleshing out the analysis.

**Comment by jaclyn-taroni** [comment]
I will get started on the MultiPLIER LV matrix this week in [this Docker container](https://github.com/greenelab/multi-plier#dependencies) to start. First steps include filtering to remove low variance LVs.

**Comment by jaclyn-taroni** [comment]
This should wait on #198

**Comment by jaclyn-taroni** [comment]
Closing all planned analysis tickets in favor of opening new proposed analysis tickets as needed.
