### ISSUE TITLE
Update GISTIC data format information

### ISSUE THREAD

**Issue by jharenza** [AlexsLemonade/OpenPBTA-analysis#417]
#### What data file(s) does this issue pertain to?
GISTIC zip file

#### What release are you using?

v12

#### Put a link to relevant section of repo here:
https://github.com/AlexsLemonade/OpenPBTA-analysis/blob/master/doc/data-formats.md#copy-number-files

#### Put your question or report your issue here.
Update GISTIC output file information.

**Comment by cbethell** [comment]
In support of this ticket, here is a [notebook](https://cbethell.github.io/open-pbta-output/GISTIC-missing-samples.nb.html) cross-checking that the samples 'missing' from the GISTIC `broad_values_by_arm.txt` file (implemented in PR #414) are the samples denoted to not be included based on the information recorded in the GISTIC `sample_seg_counts.txt` file.

**Comment by jharenza** [comment]
closed via #507
