### ISSUE TITLE
Proposed Analysis: Filter germline variants for MB subtyping

### ISSUE THREAD

**Issue by jharenza** [AlexsLemonade/OpenPBTA-analysis#431]
#### What are the scientific goals of the analysis?
Filter germline variants for deleterious variants within _TP53_, _SUFU_, and _PTCH1_ to enable #247 

#### What methods do you plan to use to accomplish the scientific goals?
Using Annovar annotations,
- keep those with sequencing depth DP > 10
- keep those with alternative allele depth AD > 0.25 * sum of all AD's. E.g. assuming the vcf FORMAT field is GT:AD:DP, if the sample sequencing data is 0/1:19,9:28 then keep this variant; if 0/1:19,6:25 then discard this variant.
- keep those with AAChange.refGene not being .
- keep those with allele frequency < 0.01 in the gnomAD datasets. There are three frequencies gnomad211_exome_AF=, gnomad211_genome_AF= and gnomad30_genome_AF=, and make sure the smallest among them are less than 0.01.

#### What input data are required for this analysis?
germline VCFs, controlled access

#### How long do you expect is needed to complete the analysis? Will it be a multi-step analysis?
1 week

#### Who will complete the analysis (please add a GitHub handle here if relevant)?
@yiran-guo

#### What relevant scientific literature relates to this analysis?
[Medulloblastoma.WHO.2016.book.chapter.pdf](https://github.com/AlexsLemonade/OpenPBTA-analysis/files/4055344/Medulloblastoma.WHO.2016.book.chapter.pdf)

**Comment by jharenza** [comment]
@jaclyn-taroni I only looked through this briefly, but looks like the above are the 3 major genes we want?

**Comment by jharenza** [comment]
@yiran-guo, below are the normal IDs for the samples included in OpenPBTA:
[OpenPBTA-allnormal-BSids.txt](https://github.com/AlexsLemonade/OpenPBTA-analysis/files/4059462/OpenPBTA-allnormal-BSids.txt)

**Comment by cansavvy** [comment]
@jharenza , according to the book chapter you attached, those seem to be the three genes we should look for.

**Comment by jharenza** [comment]
Per our conversation about subjectiveness of germline filtering and potential to miss/over-assign pathogenicity of _TP53_ variants when they are of uncertain significance, @jaclyn-taroni and I decided we should close this ticket, as well as #378 and #451.
