### ISSUE TITLE
Updated analysis: Re-calculate coding TMB with Lancet WXS BED file update

### ISSUE THREAD

**Issue by cansavvy** [AlexsLemonade/OpenPBTA-analysis#440]
#### What analysis module should be updated and why?

`snv-callers` [where coding TMB is calculated](https://github.com/AlexsLemonade/OpenPBTA-analysis/blob/1a8a35954a09c6a64ae38f2b885867420da4b1d0/analyses/snv-callers/run_caller_consensus_analysis.sh#L73)

#### Why should the module be updated?
Because the current WXS BED file is not accurate for the Lancet data and will be updated. It was a 100bp that needed to be run and a 300bp window was run. 

#### What changes need to be made? Please provide enough detail for another participant to make the update.

- If the Lancet file is updated then the whole pipeline will need to be re-ran with the updated data
- Need to reconfigure the coding WXS TMB to include the new BED file. 

#### What input data should be used? Which data were used in the version being updated?
I think this update will be in v13.

#### When do you expect the revised analysis will be completed?
We can have in revised for v14

#### Who will complete the updated analysis?
@cansavvy

**Comment by jharenza** [comment]
correct, will release this bed with #373

**Comment by jaclyn-taroni** [comment]
@jharenza there is a little confusion on our end. The methods section of the manuscript reported that for WXS samples, Lancet was run with a 100 bp padded bed file. It was in fact run with a 300 bp padded file. You are planning on releasing the WXS BED with 300 bp padding now, but there will be no underlying changes to the Lancet data (e.g., you will not be rerunning it with 100 bp). Is that correct?

**Comment by jharenza** [comment]
Correct. I think the intersect for WXS should stay similar anyway, since there is an intersect with CDS regions.

**Comment by jaclyn-taroni** [comment]
https://github.com/AlexsLemonade/OpenPBTA-analysis/pull/444#discussion_r367643169

**Comment by jaclyn-taroni** [comment]
This was blocked by the v13 release, which went out yesterday in #444 so I am removing the blocked label.

**Comment by cansavvy** [comment]
This issue has been addressed. The results have been uploaded to S3.
*Changes to S3 files:*
- The updated intersection BED files that were used 
     - https://open-pbta.s3.amazonaws.com/data/snv-consensus-bed/intersect_cds_lancet_strelka_mutect_WGS.bed
     - https://open-pbta.s3.amazonaws.com/data/snv-consensus-bed/intersect_cds_lancet_WXS.bed
- updated zip file `snv-consensus-20200121.zip` (Note the only file of the three files within here that has changed is `pbta-snv-consensus_snv_tmb_coding_only.tsv`, but for consistency's sake, I uploaded the data in the same way and format that the other editions were. 
      - https://open-pbta.s3.amazonaws.com/data/snv-consensus/snv-consensus-20200121.zip

**Comment by jaclyn-taroni** [comment]
Closed via #459.
