### ISSUE TITLE
Proposed Analysis: Assess batch effects in RNA-Seq data

### ISSUE THREAD

**Issue by srp33** [AlexsLemonade/OpenPBTA-analysis#448]
#### What are the scientific goals of the analysis?

Batch effects are commonly observed in RNA expression data. Such effects are likely less pronounced in RNA-Seq data than microarray data. However, batch effects may bias conclusions of studies that do not account for these effects. We wish to evaluate the level to which batch effects are present in the RNA-Seq data from this study and create alternative versions of the data that have been adjusted for batch effects.

#### What methods do you plan to use to accomplish the scientific goals?

We propose to use the BatchQC tool to evaluate the data for batch effects. BatchQC provides various visualization tools for evaluating batch effects. We will use these and prepare a summary based on our findings. ComBat is a widely used method that uses empirical Bayes methods for correcting batch effects. Currently, we are unsure whether batch is known for these samples. If batch is known, we will adjust for it using ComBat. If not, we will use SVA to identify surrogate variables and plot those against variables that may have a confounding effect.

#### What input data are required for this analysis?

RNA-Seq data. We will start with gene-summarized values but may also work with transcript-level data.

#### How long do you expect is needed to complete the analysis? Will it be a multi-step analysis?

10-20 hours. It will require at least two steps (examining the data using MultiQC and applying ComBat/sva).

#### Who will complete the analysis (please add a GitHub handle here if relevant)?

@nathanmella and @srp33

#### What relevant scientific literature relates to this analysis?

https://www.ncbi.nlm.nih.gov/pubmed/20838408
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5167063/
https://www.ncbi.nlm.nih.gov/pubmed/22257669

**Comment by jaclyn-taroni** [comment]
Hi @srp33 and @nathanmella, welcome and thank you for proposing this analysis! 

Before you get started implementing this analysis, we ask that you read the documentation in the [`README`](https://github.com/AlexsLemonade/OpenPBTA-analysis/blob/master/README.md) and [contributing guidelines](https://github.com/AlexsLemonade/OpenPBTA-analysis/blob/master/CONTRIBUTING.md) in full. In addition, you may find more information about the data in [`doc/data-formats.md `](https://github.com/AlexsLemonade/OpenPBTA-analysis/blob/master/doc/data-formats.md) and [`doc/data-files-description.md`](https://github.com/AlexsLemonade/OpenPBTA-analysis/blob/master/doc/data-files-description.md), with a history of data releases in [`doc/release-notes.md`](https://github.com/AlexsLemonade/OpenPBTA-analysis/blob/master/doc/release-notes.md).

Regarding 

> Currently, we are unsure whether batch is known for these samples. If batch is known, we will adjust for it using ComBat. 

We do not have information about _batch_ per se, but I wanted to make you aware of the following columns in the `pbta-histologies.tsv` file: `seq_center` and `cohort` which indicate the sequencing center that processed the samples and the scientific cohort, respectively. I can imagine that these differences might introduce some technical variation.

We've also separated out the poly-A and (ribodepleted) stranded RNA-seq samples due to findings captured in this notebook: https://alexslemonade.github.io/OpenPBTA-analysis/analyses/selection-strategy-comparison/01-selection-strategies.nb.html (from the [`selection-strategy-comparison`](https://github.com/AlexsLemonade/OpenPBTA-analysis/tree/master/analyses/selection-strategy-comparison) module). 

I would suggest making sure you have the most recent data release (`release-v13-20200116`) that went out yesterday (#444), as it resolved some known issues with the v12 RNA-seq data (#373, #374).

If you have questions as you implement this analysis, please feel free to ask them here or [file a data question issue](https://github.com/AlexsLemonade/OpenPBTA-analysis/issues/new?assignees=&labels=data&template=data-question.md&title=). For real-time help with things like git or filing a pull request, we have the Cancer Data Science Slack which you can join by following this [link](http://ccdatalab.org/slack). The **#open-pbta** channel is the best place to get started there. 

Thank you!

**Comment by jaclyn-taroni** [comment]
I think the correct handle is @natemella based on a recent fork of the repository 😄

**Comment by natemella** [comment]
We are actively working on this. Do we need to update status with this anywhere?

**Comment by jaclyn-taroni** [comment]
Hi @natemella - if you have an idea of when you expect to file a first pull request, posting that timeline can help us plan out the review workload. You should also feel free to comment here with interim results if you'd like to discuss!

**Comment by natemella** [comment]
Okay, this week I have finished up the analysis. Sorry for the lack of responses lately. Here's the time line for the remaining work:

1) Feb 20th, upload graphs and brief interpretation of results
2) Feb 22nd, upload robust interpretation of results, along with the methods.
3) Feb 24th, (assuming that we are in agreement with the results, the methods, and the interpretation) submit a pull request.

**Comment by natemella** [comment]
Here's how I broke up the analysis:

I tested for batch effects in three different areas:
1) Batch = Sequencing Center
2) Batch = Cohort
3) Batch = polyA vs Stranded

Within each of theses analysis I looked at the rsem and kallisto files

Within each rsem and kallisto file, I looked at polyA files and stranded files

**The null hypothesis is that there are no batch effects in the data**

**RESULTS**:
1.  **Batch = Sequencing Center**
    a) **kallisto**
       i) polyA: Reject null hypothesis
       ii) stranded: Reject null hypothesis
    b) **rsem**
       i) polyA: Reject null hypothesis
       ii) stranded: Reject null hypothesis
2.  **Batch = Cohort**
    a) **kallisto**
       i) polyA: Reject null hypothesis
       ii) stranded: Fail to reject null hypothesis
    b) **rsem**
       i) polyA: Reject null hypothesis
       ii) stranded: Fail to reject null hypothesis
3.  **Batch = polyA vs Stranded**
    a) **kallisto**
        i) Reject null hypothesis
    b) **rsem**
        ii) Reject null hypothesis
    
![image](https://user-images.githubusercontent.com/33582671/75011796-b97df780-543d-11ea-834e-35c47a3de759.png)

Attached are two graphs for each section 1) the distribution of P-values and 2) the PCA plot
[kallisto_polya_sequence_pca.pdf](https://github.com/AlexsLemonade/OpenPBTA-analysis/files/4234680/kallisto_polya_sequence_pca.pdf)
[rsem_stranded_sequence_pca.pdf](https://github.com/AlexsLemonade/OpenPBTA-analysis/files/4234681/rsem_stranded_sequence_pca.pdf)
[kallisto_polyA_sequence.pdf](https://github.com/AlexsLemonade/OpenPBTA-analysis/files/4234682/kallisto_polyA_sequence.pdf)
[rsem_stranded_sequence.pdf](https://github.com/AlexsLemonade/OpenPBTA-analysis/files/4234683/rsem_stranded_sequence.pdf)
[kallisto_polyA_cohort.pdf](https://github.com/AlexsLemonade/OpenPBTA-analysis/files/4234684/kallisto_polyA_cohort.pdf)
[kallisto_polyA_cohort_pca.pdf](https://github.com/AlexsLemonade/OpenPBTA-analysis/files/4234685/kallisto_polyA_cohort_pca.pdf)
[rsem_method.pdf](https://github.com/AlexsLemonade/OpenPBTA-analysis/files/4234686/rsem_method.pdf)
[rsem_polyA_sequence_pca.pdf](https://github.com/AlexsLemonade/OpenPBTA-analysis/files/4234687/rsem_polyA_sequence_pca.pdf)
[kallisto_method.pdf](https://github.com/AlexsLemonade/OpenPBTA-analysis/files/4234688/kallisto_method.pdf)
[kallisto_stranded_cohort_pca.pdf](https://github.com/AlexsLemonade/OpenPBTA-analysis/files/4234689/kallisto_stranded_cohort_pca.pdf)
[Kallisto_stranded_sequence.pdf](https://github.com/AlexsLemonade/OpenPBTA-analysis/files/4234690/Kallisto_stranded_sequence.pdf)
[rsem_method_pca.pdf](https://github.com/AlexsLemonade/OpenPBTA-analysis/files/4234691/rsem_method_pca.pdf)
[rsem_polya_cohort_pca.pdf](https://github.com/AlexsLemonade/OpenPBTA-analysis/files/4234692/rsem_polya_cohort_pca.pdf)
[rsem_stranded_cohort_pca.pdf](https://github.com/AlexsLemonade/OpenPBTA-analysis/files/4234693/rsem_stranded_cohort_pca.pdf)
[kallisto_method_pca.pdf](https://github.com/AlexsLemonade/OpenPBTA-analysis/files/4234694/kallisto_method_pca.pdf)
[rsem_stranded_cohort.pdf](https://github.com/AlexsLemonade/OpenPBTA-analysis/files/4234695/rsem_stranded_cohort.pdf)
[rsem_polyA_sequence.pdf](https://github.com/AlexsLemonade/OpenPBTA-analysis/files/4234696/rsem_polyA_sequence.pdf)
[rsem_polyA_cohort.pdf](https://github.com/AlexsLemonade/OpenPBTA-analysis/files/4234697/rsem_polyA_cohort.pdf)
[kallisto_stranded_cohort.pdf](https://github.com/AlexsLemonade/OpenPBTA-analysis/files/4234698/kallisto_stranded_cohort.pdf)
[kallisto_stranded_sequence_pca.pdf](https://github.com/AlexsLemonade/OpenPBTA-analysis/files/4234699/kallisto_stranded_sequence_pca.pdf)

**Comment by jaclyn-taroni** [comment]
Thanks for this analysis and posting your update @natemella! I would suggest that you submit your pull request at the same time that you write up the methods and interpretation of results. Our pull request template (which you can view [here](https://github.com/AlexsLemonade/OpenPBTA-analysis/blob/master/.github/PULL_REQUEST_TEMPLATE.md)) is designed to help with reporting methods and results. It is helpful for reviewers to have the methods, code, and results all in one "place" during review in our experience.

I am also curious if you checked if the batches were confounded with histologies or disease types? We can discuss and look into this more when you file your PR.

If you need any help with pull request submission, please let us know!

**Comment by natemella** [comment]
Hi @jaclyn-taroni. I'm still working on getting everything ready for the pull request. Thank you for sending the template.

To answer your question regarding confounding variables, I have not explicitly checked to see if the batches correlate with diseases or histologies. With the tool I'm using (batchqc), I can check to see how well certain covariates correlate with batches. A correlation should only happen though if patients of a certain disease were only sent to one sequencing center or cohort. But I can definitely check to make sure that this isn't confounding the results.

**Comment by natemella** [comment]
I'm submitting a merge request today. But first I'm going to upload the results of testing for batch effects after running combat. This way the results can easily be stored within these comment boxes 
[rsem_stranded_sequence_combat_pca.pdf](https://github.com/AlexsLemonade/OpenPBTA-analysis/files/4325809/rsem_stranded_sequence_combat_pca.pdf)
[rsem_stranded_sequence_combat.pdf](https://github.com/AlexsLemonade/OpenPBTA-analysis/files/4325810/rsem_stranded_sequence_combat.pdf)
[rsem_polya_sequence_combat_pca.pdf](https://github.com/AlexsLemonade/OpenPBTA-analysis/files/4325811/rsem_polya_sequence_combat_pca.pdf)
[rsem_polya_sequence_combat.pdf](https://github.com/AlexsLemonade/OpenPBTA-analysis/files/4325812/rsem_polya_sequence_combat.pdf)
[rsem_polya_cohort_combat_pca.pdf](https://github.com/AlexsLemonade/OpenPBTA-analysis/files/4325813/rsem_polya_cohort_combat_pca.pdf)
[rsem_polya_cohort_combat.pdf](https://github.com/AlexsLemonade/OpenPBTA-analysis/files/4325814/rsem_polya_cohort_combat.pdf)
[rsem_method_combat_pca.pdf](https://github.com/AlexsLemonade/OpenPBTA-analysis/files/4325815/rsem_method_combat_pca.pdf)
[kallisto_stranded_sequence_combat_pca.pdf](https://github.com/AlexsLemonade/OpenPBTA-analysis/files/4325816/kallisto_stranded_sequence_combat_pca.pdf)
[rsem_method_combat.pdf](https://github.com/AlexsLemonade/OpenPBTA-analysis/files/4325817/rsem_method_combat.pdf)
[kallisto_stranded_sequence_combat.pdf](https://github.com/AlexsLemonade/OpenPBTA-analysis/files/4325818/kallisto_stranded_sequence_combat.pdf)
[kallisto_polya_sequence_combat_pca.pdf](https://github.com/AlexsLemonade/OpenPBTA-analysis/files/4325819/kallisto_polya_sequence_combat_pca.pdf)
[kallisto_polya_sequence_combat.pdf](https://github.com/AlexsLemonade/OpenPBTA-analysis/files/4325820/kallisto_polya_sequence_combat.pdf)
[kallisto_method_combat_pca.pdf](https://github.com/AlexsLemonade/OpenPBTA-analysis/files/4325821/kallisto_method_combat_pca.pdf)
[kallisto_method_combat.pdf](https://github.com/AlexsLemonade/OpenPBTA-analysis/files/4325822/kallisto_method_combat.pdf)

**Comment by natemella** [comment]
[kallisto_polya_cohort_combat.pdf](https://github.com/AlexsLemonade/OpenPBTA-analysis/files/4328136/kallisto_polya_cohort_combat.pdf)
[kallisto_polya_cohort_combat_pca.pdf](https://github.com/AlexsLemonade/OpenPBTA-analysis/files/4328137/kallisto_polya_cohort_combat_pca.pdf)

**Comment by natemella** [comment]
Hi @jaclyn-taroni, thank you for the feedback on the pull request. We ran some PCA plots where you can visually see batches as shapes and histology as color. 

Our conclusion is that using **method (ribodepleted vs. polyA) as the batch is indeed confounded with histology.** But the other batches (seq_center and cohort) don't visually infer that they are confounded.

We can quantitatively show whether they are confounded by looking at euclidean distances. But we wanted to check in with you before doing anything else. (Attached are the PCA plots
![kallisto_method_batch-adjusted-histology](https://user-images.githubusercontent.com/33582671/78911814-17918900-7a44-11ea-9305-c518d40361bf.png)
![kallisto_method_histology](https://user-images.githubusercontent.com/33582671/78911816-18c2b600-7a44-11ea-90a7-95c194ca7ad8.png)
![kallisto_polya_sequence_batch-adjusted-histology](https://user-images.githubusercontent.com/33582671/78911819-195b4c80-7a44-11ea-9c24-9d14476c97a5.png)
![kallisto_polya_sequence_histology](https://user-images.githubusercontent.com/33582671/78911820-19f3e300-7a44-11ea-9b94-ca55125880fa.png)
![kallisto_stranded_sequence_batch-adjusted-histology](https://user-images.githubusercontent.com/33582671/78911822-19f3e300-7a44-11ea-8c38-4f3ae9ecf718.png)
![kallisto_stranded_sequence_histology](https://user-images.githubusercontent.com/33582671/78911823-1a8c7980-7a44-11ea-8725-3cc44c94181a.png)
![rsem_method_batch-adjusted-histology](https://user-images.githubusercontent.com/33582671/78911824-1a8c7980-7a44-11ea-92d0-dd6404c54570.png)
![rsem_method_histology](https://user-images.githubusercontent.com/33582671/78911826-1b251000-7a44-11ea-9b20-c8a8a5deec72.png)
![rsem_poly_cohort_batch-adjusted-histology](https://user-images.githubusercontent.com/33582671/78911827-1b251000-7a44-11ea-9d2e-a8d53604a8ff.png)
![rsem_poly_cohort_histology](https://user-images.githubusercontent.com/33582671/78911828-1b251000-7a44-11ea-83b1-c5b722105e3a.png)
![rsem_polya_sequence_batch-adjusted-histology](https://user-images.githubusercontent.com/33582671/78911829-1bbda680-7a44-11ea-9713-9ee4266e7af3.png)
![rsem_polya_sequence_histology](https://user-images.githubusercontent.com/33582671/78911830-1bbda680-7a44-11ea-9ea6-986e486a8532.png)
![rsem_stranded_sequence_batch-adjusted-histology](https://user-images.githubusercontent.com/33582671/78911832-1bbda680-7a44-11ea-9711-f6c8b864d704.png)
![rsem_stranded_sequence_histology](https://user-images.githubusercontent.com/33582671/78911833-1c563d00-7a44-11ea-90ea-126b53eec129.png)













)

**Comment by jaclyn-taroni** [comment]
Hi @natemella, 

Thanks for following up and adding these plots! If I were to revisit the project or someone were to come to the project for the first time, I expect it would be helpful for an analysis looking at confounding by histology to come _first_ in a `batch-effects` analysis module.

Before I make specific recommendations about moving forward, a couple questions:

* There were a few instances where the same function or a similar function was used in your open pull request (#628) - would the analysis looking at histology use any of these similar utilities (e.g., cleaning or transposing expression data)?
* Are you familiar with [R Notebooks](https://rmarkdown.rstudio.com/lesson-10.html) or, more generally, [R Markdown](https://rmarkdown.rstudio.com/)? This seems like it would be a good analysis to have your conclusions and some descriptions around the results along side the plots.

In general, my inclination is to structure the analysis module such that the first analysis looks just at potential confounding and then those results can inform any "downstream" batch correction.

Thank you!

**Comment by natemella** [comment]
April 21, 2020 Meeting with Jaclyn Taroni and Nathan Mella

Next steps for me will be to do the following:
1. Put anything that will be needed into the Docker File
2. Make an R markdown file for my graphs with the information needed prior to batch correction
3. Make a .util directory with all of my reused functions

On further pull requests, I will include any batch correction that we deem necessary. I will also include the figures generated from batchQC which further solidfy the need for batch correction.

**Comment by jaclyn-taroni** [comment]
Given the length of the discussion here, we thought it might be helpful to file a new issue with the next steps front and center. That new issue is #919. I am going to close this.
