### ISSUE TITLE
install shatterseek package in Dockerfile

### ISSUE THREAD

**Issue by yangyangclover** [AlexsLemonade/OpenPBTA-analysis#450]
I tried to submit a new [shatterseek PR](https://github.com/AlexsLemonade/OpenPBTA-analysis/pull/449), but the Dockerfile test failed on the step of shatterseek installation ([https://circleci.com/gh/AlexsLemonade/OpenPBTA-analysis/2621?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link](https://circleci.com/gh/AlexsLemonade/OpenPBTA-analysis/2621?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link)).

My commend is 
`RUN R -e  “remotes::install_github('parklab/ShatterSeek'), dependencies = TRUE”`

I ran the below command in Kitematic, it worked
`withr::with_envvar(c(R_REMOTES_NO_ERRORS_FROM_WARNINGS="true"),remotes::install_github('parklab/ShatterSeek'))`

Here is some information about Shatterseek Package, hope it will help:
[parklab/ShatterSeek](https://github.com/parklab/ShatterSeek)

**Comment by jaclyn-taroni** [comment]
Hi @yangyangclover I will take a look now

**Comment by jaclyn-taroni** [comment]
See: https://github.com/AlexsLemonade/OpenPBTA-analysis/pull/449/files#r368123129 

If that change fixes it, we can close this issue.

**Comment by jaclyn-taroni** [comment]
Fixed with https://github.com/AlexsLemonade/OpenPBTA-analysis/commit/d7cc2759c1b27b8d7c306ab2ef190b19b58de149
