### ISSUE TITLE
Germline Mutation Data

### ISSUE THREAD

**Issue by yangyangclover** [AlexsLemonade/OpenPBTA-analysis#451]
#### What data file(s) does this issue pertain to?
germline mutation data/SNP

#### What release are you using?

V12

#### Put your question or report your issue here.
I am trying to perform an association study between SV signature cluster and germline gene mutation. However, it seems the SNP data is controlled. I am wondering if I can access those data or if there are some processed files about germline gene mutation statistics across patients.

**Comment by jharenza** [comment]
Hi @yangyangclover! The germline data is controlled and as such, we cannot release it on a public platform. However, if there are a minimal number of variants you are looking for, and/or specific SNPs you are interested in, we can determine whether we can pre-filter and release just those specific variants. For example, with #431 we will release a binary matrix of whether or not putative deleterious germline variants exist in _TP53_, SUFU, and/or _PTCH1_ in medulloblastoma patients.

Do you have some more information on exactly what variants you are interested in or would this be more of a discovery effort? If discovery, you are more than welcome to request access to these data via the CBTTC [here](https://cbttc.org/scientific-projects-data/), but this may also be beyond the scope the OpenPBTA paper, in which we are largely focusing on somatic variation across the pediatric brain tumors. Either way, happy to help!

**Comment by yangyangclover** [comment]
Thank you @jharenza , if it possible to release BRCA1, BRCA2, TP53 germline mutation data? We found some SV mutation may be related to defective homologous recombination-based DNA damage repair, so we wanna see if BRCA1/BRCA2 is the cause.

**Comment by jharenza** [comment]
@yangyangclover - Per our conversation about subjectiveness of germline filtering and potential to miss/over-assign pathogenicity of _TP53_ variants when they are of uncertain significance, @jaclyn-taroni and I decided to not filter/release the germline data with our lack of expertise in this area. I think in your analysis, you can instead use the mutational signatures and look for mutational signature 3 in those patients.
