### ISSUE TITLE
Missing cnvkit data

### ISSUE THREAD

**Issue by jashapiro** [AlexsLemonade/OpenPBTA-analysis#472]
#### What data file(s) does this issue pertain to?

`pbta-cnv-cnvkit.seg.gz`

#### What release are you using?

v13

#### Put your question or report your issue here.

This file seems to be missing data for specimen `BS_NMJPX8VQ`, which is present in the other cnv and sv calling files.

**Comment by jharenza** [comment]
cc: @yuankunzhu and @migbro for #432 (v14 release)

**Comment by jharenza** [comment]
Noting that this data is located [here](https://cavatica.sbgenomics.com/u/kfdrc-harmonization/sd-bhjxbdqk-08/tasks/bc099946-1356-4acd-8d4a-e3d983ff8ec3/).

**Comment by jharenza** [comment]
Updated and sent @jashapiro the new seg file - will update that, consensus calls, gistic out, and consensus seg for #432.

**Comment by jharenza** [comment]
closed via #507
