### ISSUE TITLE
Updated analysis: Use TCGA SNV consensus calls to get mutational signatures

### ISSUE THREAD

**Issue by cansavvy** [AlexsLemonade/OpenPBTA-analysis#481]
#### What analysis module should be updated and why?
[`mutational-signatures`](https://github.com/AlexsLemonade/OpenPBTA-analysis/tree/master/analyses/mutational-signatures)

#### Why should the module be updated?
We now have TCGA SNV caller data and will soon have TCGA consensus calls (#257) that were gotten through the same way our PBTA consensus calls were. 

#### What changes need to be made? Please provide enough detail for another participant to make the update.

Once #257 is completed, we can apply the same mutational-signatures analysis we used for the PBTA samples to the TCGA consensus. 

#### What input data should be used? Which data were used in the version being updated?
When it is ready, the file in `snv-callers/results/consensus/tcga-snv-consensus-snv.maf.tsv` will have the data needed for calculating the mutational signatures. 

#### When do you expect the revised analysis will be completed?
Part of this is dependent on how long it takes @cansavvy to complete #257, but after that hopefully not long since an example mutational-signatures analysis already exists (for PBTA samples).  https://github.com/AlexsLemonade/OpenPBTA-analysis/tree/master/analyses/mutational-signatures

**Comment by cansavvy** [comment]
This issue is put on pause due to low sample numbers we have for TCGA currently (https://github.com/AlexsLemonade/OpenPBTA-analysis/issues/257#issuecomment-573094811)  However, since there may be more TCGA samples being added, I'll revisit this issue when those samples are added in the next release #601.

**Comment by jharenza** [comment]
@cansavvy ok to close this?
