### ISSUE TITLE
Updated analysis: Recurrently Altered Genes CNV and SV data

### ISSUE THREAD

**Issue by cansavvy** [AlexsLemonade/OpenPBTA-analysis#488]
## What analysis module should be updated and why?
This needs to be added on to `chromosomal-instability`. Originally discussed on . #394
This issue and #487 are the remaining issues from the #394 ticket. 

#### Why should the module be updated?
This analysis will be used to determine what genes should be displayed on the Oncoprint.

#### What changes need to be made? Please provide enough detail for another participant to make the update.

Will make separate gene lists for each type of alteration: 
  - Amplification/tandem-duplication
  - Deep deletion/deletion
  - Other Structural variation: Inversion, translocations

#### What input data should be used? Which data were used in the version being updated?
Use the annotated CN file from `focal-cn-file-preparation` module. 
The SV data to be used is will be the manta file: pbta-sv-manta.tsv.gz ?  

#### When do you expect the revised analysis will be completed?
It is currently in progress. 

#### Who will complete the updated analysis?
@cansavvy

**Comment by cbethell** [comment]
This has been closed with PR #686 🎉
