### ISSUE TITLE
Data: Add RSEM RDS file to md5sum.txt

### ISSUE THREAD

**Issue by jaclyn-taroni** [AlexsLemonade/OpenPBTA-analysis#49]
With the additions in #45, all the data files will need to be represented in the `md5sum.txt` file. This issue pertains to `rsem.fpkm.rds`, first mentioned here: https://github.com/AlexsLemonade/OpenPBTA-analysis/pull/43/files#diff-04c6e90faac2675aa89e2176d2eec7d8R125

This will need to be added to `md5sum.txt`.

**Comment by jharenza** [comment]
@jaclyn-taroni - done!
