### ISSUE TITLE
Updated analysis: Do HGAT samples with BRAF V600E mutations cluster with LGAT samples?

### ISSUE THREAD

**Issue by jaclyn-taroni** [AlexsLemonade/OpenPBTA-analysis#499]
#### What analysis module should be updated and why?

Context is https://github.com/AlexsLemonade/OpenPBTA-analysis/pull/435#discussion_r373808742

During the course of the HGAT subtyping effort (#249), we identified tumor samples that were originally labeled as HGAT, had no defining histone mutations, and had _BRAF_ V600E mutations.

#### What changes need to be made? Please provide enough detail for another participant to make the update.

From @jharenza 

> Can we add a visualization to highlight [the HGAT samples without histone mutations that have _BRAF_ V600E mutations] in a tsne or umap clustering of all of the data by broad histology? If they cluster with the LGAT, then I think we can re-categorize them.

This should be included in a notebook in the [`molecular-subtyping-HGG`](https://github.com/AlexsLemonade/OpenPBTA-analysis/tree/master/analyses/molecular-subtyping-HGG) module.  Specifically, this should be a notebook prefixed with `09` because of #435 (`07`) and #466 (`08`).

#### What input data should be used? Which data were used in the version being updated?

We can use 
* `analyses/molecular-subtyping-HGG/results/HGG_molecular_subtype.tsv` that's going in as part of #435 -- the samples of interest we want to highlight `BRAF V600E` in the `molecular_subtyping` column.
* The request is to color the points by `broad_histology` from `pbta-histologies.tsv`
* Results from [`analyses/transcriptomic-dimension-reduction/results`](https://github.com/AlexsLemonade/OpenPBTA-analysis/tree/master/analyses/transcriptomic-dimension-reduction/results) (log transformed FPKM data) -- these have be run with v13 data.

#### When do you expect the revised analysis will be completed?

1-2 days

#### Who will complete the updated analysis?

Someone from the CCDL team

**Comment by cbethell** [comment]
I am going to begin the work on this ticket today.

**Comment by jaclyn-taroni** [comment]
Closed via #534
