### ISSUE TITLE
Add histologies file to md5sum.txt

### ISSUE THREAD

**Issue by cgreene** [AlexsLemonade/OpenPBTA-analysis#50]
This file will also need to be added since #45 has landed.

**Comment by jaclyn-taroni** [comment]
This is blocking #33

**Comment by jharenza** [comment]
@yuankunzhu - can you add md5sum for the histologies file?

**Comment by jharenza** [comment]
This has been completed.

**Comment by cgreene** [comment]
Can confirm. Download via script now includes this file 👍
