### ISSUE TITLE
AnnotSV output data and getting translocation coordinates

### ISSUE THREAD

**Issue by cansavvy** [AlexsLemonade/OpenPBTA-analysis#503]
#### What data file(s) does this issue pertain to?
pbta-sv-manta.tsv.gz

#### What release are you using?
v13

#### Put your question or report your issue here.

Related to #484 Circos plotting. 

I've been trying to find where both sets of coordinates for translocations are for plotting purposes but it seems like I've only been able to find single base breakpoints. I have been able to get the pairs of breakpoints matched by their ids by following [@yangyangclover 's processing of the SV files](https://github.com/AlexsLemonade/OpenPBTA-analysis/pull/283/files#r354535923)

After looking at the [AnnotSV documentation](https://www.lbgi.fr/AnnotSV/Documentation/README.AnnotSV_1.1.pdf), I *think* this is implying that both sets of coordinates are not in the AnnotSV output file. From page 20 in [AnnotSV README](https://www.lbgi.fr/AnnotSV/Documentation/README.AnnotSV_1.1.pdf)
```
BED format doesn’t allow inter-chromosomal feature definitions (e.g. inter-chromosomal translocation). A
new file format (BEDPE) is proposed in order to concisely describe disjoint genome features but it is not yet
supported by AnnotSV.
However, breakpoints of such features can be annotated by AnnotSV. In this way, breakpoints positions
should be stored in a BED file as follow:
1. chrom - The name of the chromosome (e.g. 3, Y, …) - Preferred without “chr”.
2. breakpointStart - The breakpoint position in the chromosome. The first base in a chromosome is
numbered 0.
3. breakpointEnd - Equal to “breakpointStart + 1” (The chromEnd base is not included in the display of
the feature).
```
Is there a way we can get both sets of coordinates for SV translocation data? If so, how much effort would this take?

**Comment by jharenza** [comment]
Going to loop in @kgaonkar6, since she worked on this previously - she will be back in later today.

**Comment by kgaonkar6** [comment]
Hi @cansavvy , as much as I know only a set of breakend mates can be matched using the components of the IDs (first 7 as specified here https://github.com/Illumina/manta/blob/master/docs/developerGuide/ID.md) like you've mentioned above. The coordinates can as be identified from the SV_start, SV_end and ALT columns per row.

Also just wanted to mention that the ID column comes from Manta and AnnotSV is only used to add annotation. I tried to look for documentation in manta that can help get both sets of breakpoints of a translocation together but didn't find any.

**Comment by cansavvy** [comment]
I've never worked with this kind of data before so I'm trying to figure out how we represent this on a chord diagram and my original thought was that the translocation data upon matching the mates would include 4 points that would be the start and end of the segments translocated, but after rearrangement, all the starts and ends appear to be single bases. 

> The coordinates can as be identified from the SV_start, SV_end and ALT columns per row.

I'm assuming you are referring to `SV.start` and `SV.end`. The coordinates included in the ALT column are identical to the matching breakend coordinates. From the little I understand, this is just to understand the orientation of the break end.

> Also just wanted to mention that the ID column comes from Manta and AnnotSV is only used to add annotation. I tried to look for documentation in manta that can help get both sets of breakpoints of a translocation together but didn't find any.

Do people do this kind of analysis with another type of file from a different program then? Or am I supposed to assume that the entire length of the chromosome arm beyond the break end is included in the translocation? But then, what if two breakpoints are in the same chromosome? How do we interpret that?

**Comment by kgaonkar6** [comment]
When plotting circos plots I would remove BND lines because of the difficulty in formatting them for circos link plots. 

> all the starts and ends appear to be single bases
>

I think this is expected format to not have length or end position format for BND SV type in manta vcf as per vcf 4.1 format in AnnotSV however since the output is bed format it adds the SV.end which is a single basepair apart from SV.start. I am no expert but I think the way SVs are represented in general in vcf format and specifically in vcf4.1 format http://samtools.github.io/hts-specs/VCFv4.1.pdf in manta vcf only allow us to match the breakpoint mates like here:

<img width="413" alt="Screen Shot 2020-02-04 at 7 14 26 AM" src="https://user-images.githubusercontent.com/34580719/73757059-97def980-4736-11ea-9120-18ef6b44c85d.png">

<img width="652" alt="Screen Shot 2020-02-04 at 7 14 21 AM" src="https://user-images.githubusercontent.com/34580719/73757061-99102680-4736-11ea-8fd0-70d39a74602e.png">

**Comment by cansavvy** [comment]
Thanks for this information, @kgaonkar6 . I think this issue has been resolved since it turned out to be an information gathering issue.
