### ISSUE TITLE
Updated analysis: Backfill seg.mean into neutral segments

### ISSUE THREAD

**Issue by jashapiro** [AlexsLemonade/OpenPBTA-analysis#504]
#### What analysis module should be updated and why?

This proposed analysis follows discussion in #486  about updating the `copy_number_consensus_call` analysis to backfill `seg.mean` calls from cnvkit into the "neutral" segments that are included in `pbta-cnv-cnvkit.seg.gz` as part of the #476 update. These seg.mean calls may be useful for plotting and for examining calls in situations where the tumor ploidy is not 2. 

#### What changes need to be made? Please provide enough detail for another participant to make the update.

To perform this analysis, the CNVkit segments that correspond to each neutral segment in the final call set will need to be extracted and their seg.mean values integrated as weighted means into the final seg.mean value. 

#### What input data should be used? Which data were used in the version being updated?

The input data from this will be the same as `copy_number_consensus_call` : 
* pbta-cnv-cnvkit.seg.gz
* pbta-cnv-controlfreec.tsv.gz
* pbta-sv-manta.tsv.gz

Though it will likely start from some of the intermediate files of that analysis.

#### When do you expect the revised analysis will be completed?

In the next two weeks (~2 days of work)

#### Who will complete the updated analysis?

@jashapiro

**Comment by jharenza** [comment]
closed via #476 and #507
