### ISSUE TITLE
Updated analysis: add more detail to the `molecular-subtyping-embryonal` README

### ISSUE THREAD

**Issue by jaclyn-taroni** [AlexsLemonade/OpenPBTA-analysis#514]
#### What analysis module should be updated and why?

`analyses/molecular-subtyping-embryonal/README.md` could use more detail about the steps that are documented in the notebook.

#### What changes need to be made? Please provide enough detail for another participant to make the update.

The following should be reviewed and relevant details should be written up in the README:

* The notebooks in `analyses/molecular-subtyping-embryonal` 
* https://github.com/AlexsLemonade/OpenPBTA-analysis/pull/401
* https://github.com/AlexsLemonade/OpenPBTA-analysis/pull/443
* https://github.com/AlexsLemonade/OpenPBTA-analysis/pull/447
* https://github.com/AlexsLemonade/OpenPBTA-analysis/pull/458
* The original issue: #251 

We should probably include a table of contents that links to the rendered version of the notebooks as well.

#### When do you expect the revised analysis will be completed?

~1 week

**Comment by cbethell** [comment]
I am going to be working on this ticket.

**Comment by jaclyn-taroni** [comment]
Closed via #538
