### ISSUE TITLE
Updated analysis: Immune deconvolution

### ISSUE THREAD

**Issue by jainpayal022** [AlexsLemonade/OpenPBTA-analysis#519]
#### What changes need to be made? Please provide enough detail for another participant to make the update.
For the correlation plot (CIBERSORT)- update the colors so that text on the deep blue circles are visible
For both the hearmaps, separate the brain tumor from non-brain tumor rows (histiocytic and lymphoma) so as to see how brain tumors immune landscape is different. 

#### What input data should be used? Which data were used in the version being updated?
same as before

#### When do you expect the revised analysis will be completed?
Unsure

#### Who will complete the updated analysis?
Komal

**Comment by jharenza** [comment]
@komalsrathi can you work on these minor updates when you have a chance? Thanks!

**Comment by komalsrathi** [comment]
@jharenza sure

**Comment by komalsrathi** [comment]
@jainpayal022 @jharenza I am slightly wary of this approach as the sample sizes of the non-brain tumors are pretty small - 1 for lymphomas and 5 for histiocytic tumors. I have still submitted a pull request and working on some minor changes that Jaclyn suggested.

**Comment by jharenza** [comment]
@komalsrathi good catch - I think perhaps then we should remove lymphomas (and perhaps add a minimum N for histologies plotted in such figures). The histiocytic tumors are a good positive control (could possibly go in a supplement).

**Comment by jharenza** [comment]
closed via #536
