### ISSUE TITLE
Add MATLAB Runtime and the relevant MATLAB programs to project Docker container

### ISSUE THREAD

**Issue by jaclyn-taroni** [AlexsLemonade/OpenPBTA-analysis#529]
We currently run GISTIC upstream of the project. It would be great to include the GISTIC steps in the project repository, as that would give us a better opportunity to document and encapsulate the entire CNA _analysis file_ pipeline and give us more flexibility for how GISTIC is run (e.g., on individual histologies with larger sample sizes, different parameters for a broad change) if desired. Notably, we may also want to use something like MutSigCV (#517) and that would have similar constraints (more on that below). 

To include the GISTIC or MutSigCV steps within the project, we will need to install these on the project Docker container. Both of these programs appear to have executable versions that can be run if the MATLAB Compiler Runtime libraries are installed.

From the GISTIC `README.txt`:

> The executable is the gene pattern module 'gp_gistic2_from_seg'. This
module depends on the libraries in the MATLAB Compiler Runtime (MCR)
version 8.3 (R2014a).

And from the [MutSig documentation](https://software.broadinstitute.org/cancer/cga/mutsig_run):

> If you do not have a license for Matlab, you can run the compiled version of MutSigCV using the free Matlab MCR:
>
> `run_MutSigCV.sh <path_to_MCR> mutations.maf coverage.txt covariates.txt output.txt`

At least GISTIC comes with an MCR Installer, but the size of that installation is non-negligible (~0.5 GB), so we should plan to install it _once_ and symlink it to the individual tools' folders.

Here is an example Dockerfile for MCR: https://hub.docker.com/r/usuresearch/matlab-runtime/dockerfile (H/T @cgreene)

**Comment by jaclyn-taroni** [comment]
I am going to look into this today.

**Comment by jaclyn-taroni** [comment]
@jharenza - relevant to this issue but also more generally - what is the markers file used here: https://github.com/d3b-center/OpenPBTA-workflows/blob/cb87a2b725d0e41d34a88436492830802c40f7f0/bash/run-gistic.sh#L16

**Comment by jaclyn-taroni** [comment]
It seems like it might be optional?

**Comment by jharenza** [comment]
@jaclyn-taroni yes- markers are the original SNP markers used in the SNP array, and is optional - the program generates psuedo-markers, so I really should not have that in the command. Same with the array file - optional, that is to list which samples you want to run, rather than creating a seg each time.I had used in the past but never took that out of the command. Interestingly, GISTIC doesn't care if you have these extra commands (just sloppy), but hollers if you have many other issues in your files!

**Comment by jaclyn-taroni** [comment]
@jharenza can you take a gander at #535? I believe I have all the parameters the same as the other runs with the extra commands removed.

**Comment by jaclyn-taroni** [comment]
Closing this – the GISTIC portion was addressed in #535 and anything else we've considered adding (so far) is subsumed by #545 and #546.
