### ISSUE TITLE
Data: Fusion TSV files are not tab-delimited

### ISSUE THREAD

**Issue by jaclyn-taroni** [AlexsLemonade/OpenPBTA-analysis#53]
While working on #33, I read the Arriba file into R like so (removing the full path info for simplicity):

```R
arriba <- readr::read_tsv("pbta-fusion-arriba.tsv.gz")
```
And the output in the console was:
```
Parsed with column specification:
cols(
  `gene1 gene2 strand1.gene.fusion. strand2.gene.fusion. breakpoint1 breakpoint2 site1 site2 type direction1 direction2 split_reads1 split_reads2 discordant_mates coverage1 coverage2 confidence closest_genomic_breakpoint1 closest_genomic_breakpoint2 filters fusion_transcript reading_frame peptide_sequence read_identifiers tumor_id` = col_character()
)
```

Running

```R
arriba <- readr::read_delim("pbta-fusion-arriba.tsv.gz", delim = " ")
```
yields

```
Parsed with column specification:
cols(
  .default = col_character(),
  split_reads1 = col_double(),
  split_reads2 = col_double(),
  discordant_mates = col_double(),
  coverage1 = col_double(),
  coverage2 = col_double()
)
See spec(...) for full column specifications.
1 parsing failure.
  row col   expected     actual                                   file
37269  -- 25 columns 24 columns '../../data/pbta-fusion-arriba.tsv.gz'
```
and 
```R
> dim(arriba)
[1] 54279    25
```

Also checked by gunzipping the file and using `less -U`. I get a similar pattern with `pbta-fusion-starfusion.tsv.gz`. 

---

I would expect files with a `tsv.gz` extension to be tab-delimited. Is it possible to change these files to be TSV files in the interest of smoothing the way for folks using a TSV parser on them? 

**EDIT**: If this is a limitation of the upstream tools, ~I would suggest changing the extension to `txt.gz` and noting the format in https://github.com/AlexsLemonade/OpenPBTA-analysis#data-formats + possibly adding something to `docs/format`.~ 

Someone noted in person that changing the files with something like `sed /s/ /\t/g` might be preferrable for downstream analysts over making the documentation change.

**Comment by jharenza** [comment]
@jaclyn-taroni - we noticed this and updated the files, but looks like they were not updated in S3 - stand by. cc: @yuankunzhu

**Comment by yuankunzhu** [comment]
yea, sorry i missed it as it was on our internal github issue comment, we just edit the old comments by replace the new data file and that didn't send out notifications. i just picked the file and updated s3 links. it should be tab delimited now. sorry updated the md5 checksum accordingly.

**Comment by jaclyn-taroni** [comment]
Thanks for fixing this @yuankunzhu. After rerunning `bash download-data.sh`, I can confirm that the fusion files are tab-delimited.
