### ISSUE TITLE
Updated analysis: Update kinase reference gene list for fusion filtering 

### ISSUE THREAD

**Issue by kgaonkar6** [AlexsLemonade/OpenPBTA-analysis#530]
#### What analysis module should be updated and why?
Kinase reference list from http://kinase.com/human/kinome/tables/ needs to be updated. 

#### What changes need to be made? Please provide enough detail for another participant to make the update.
This will be updated using Kinase domain location form pfam (http://hgdownload.soe.ucsc.edu/goldenPath/hg38/database/ucscGenePfam.txt.gz) overlapped with gene locations to identify kinase proteins. 

Genes with the following domain names will be considered Kinase genes and added 
names(table(pfam[grep(“kinase”,pfam$X4),“X4"]))
 [1] “AA_kinase”       “Alpha_kinase”    “APS_kinase”      “Carb_kinase”     “Choline_kinase”  “DAG_kinase_N”   
 [7] “Flavokinase”     “Fucokinase”      “GHMP_kinases_C”  “GHMP_kinases_N”  “Hexokinase_1”    “Hexokinase_2"   
[13] “NAD_kinase”      “P-mevalo_kinase” “PI3_PI4_kinase”  “Pkinase”         “Pkinase_C”       “Pkinase_Tyr”  

Genes will be added to https://github.com/AlexsLemonade/OpenPBTA-analysis/blob/master/analyses/fusion_filtering/references/genelistreference.txt in correct format.

#### What input data should be used? Which data were used in the version being updated?
v14 version
pbta-fusion-starfusion.tsv.gz
pbta-fusion-arriba.tsv.gz

#### When do you expect the revised analysis will be completed?
1 day

#### Who will complete the updated analysis?
@kgaonkar6

**Comment by jaclyn-taroni** [comment]
Closed via #539. The update of these files in a data release is tracked in #543.
