### ISSUE TITLE
Updated analysis: CNV seg.mean heatmap

### ISSUE THREAD

**Issue by cansavvy** [AlexsLemonade/OpenPBTA-analysis#533]
#### What analysis module should be updated and why?
`chromosomal-instability` or `cnv-consensus`?

#### What changes need to be made? Please provide enough detail for another participant to make the update.
Need to make a heatmap that shows the samples' seg.means or copy numbers

#### What input data should be used? Which data were used in the version being updated?
pbta-cnv-consensus.seg.gz
pbta-cnv-controlfreec.tsv.gz
pbta-cnv-cnvkit.tsv.gz

#### When do you expect the revised analysis will be completed?
Should take less than a day since the heatmap function and data wrangling for CNV data has been completed in other places. 

#### Who will complete the updated analysis?
@cansavvy

**Comment by cansavvy** [comment]
I think we've decided against this and are instead going with a CNV status heatmap, as noted by #594. If so, should we close this issue?

**Comment by jaclyn-taroni** [comment]
Sure, closing this. We can always reopen if need be!
