### ISSUE TITLE
Proposed Analysis: comparison of GISTIC results (specific histology versus entire cohort)

### ISSUE THREAD

**Issue by cbethell** [AlexsLemonade/OpenPBTA-analysis#547]
#### What are the scientific goals of the analysis?

To determine whether or not the GISTIC results are in agreement when we compare those of a specific histology to those of the entire PBTA cohort.

For context, we found that there are some histologies in the PBTA cohort that contain more samples than others (ie. LGAT). This means that histologies with higher n samples may be driving the results of our analyses. This comparison analysis will help us decide whether or not we should handle our downstream analyses in a histology specific manner.

#### What methods do you plan to use to accomplish the scientific goals?

In `analyses/run-gistic/results` there are four zip files. One contains the GISTIC results for the entire cohort, and the other three contain the GISTIC results for three individual histologies (LGAT, HGAT, and medulloblastoma).

The plan for this analysis is to: 
1. Visualize the agreement/disagreement in the `scores.gistic` files for each of the individual histologies compared to that for the entire cohort by adapting the code in [`analyses/cnv-chrom-plot/gistic_plot.Rmd`](https://github.com/AlexsLemonade/OpenPBTA-analysis/blob/56f82b9f23d369a5e208c7564ce8fc22fa0b64dd/analyses/cnv-chrom-plot/gistic_plot.Rmd#L132). 
2. Use a Venn diagram to visualize the agreement/disagreement in the lists of amplified and deleted genes for each of the individual histologies compared to that for the entire cohort.
3. Use appropriate visualizations to observe the degree of agreement between each of the GISTIC result files that the individual histologies have in common with the entire cohort.

This will also be represented in a R notebook.

#### What input data are required for this analysis?

The input data required for this analysis include:
- `analyses/run-gistic/results/pbta-cnv-consensus-gistic.zip`
- `analyses/run-gistic/results/pbta-cnv-consensus-hgat-gistic.zip`
- `analyses/run-gistic/results/pbta-cnv-consensus-lgat-gistic.zip`
- `analyses/run-gistic/results/pbta-cnv-consensus-medulloblastoma-gistic.zip`

#### How long do you expect is needed to complete the analysis? Will it be a multi-step analysis?

~2 days (rough estimate)

#### Who will complete the analysis (please add a GitHub handle here if relevant)?

@cbethell

**Comment by jaclyn-taroni** [comment]
Closed via the linked pull requests – subsequent analyses are tracked in #560
