### ISSUE TITLE
Updated analysis: Fusion Filtering

### ISSUE THREAD

**Issue by kgaonkar6** [AlexsLemonade/OpenPBTA-analysis#552]
#### What analysis module should be updated and why?
1) During project specific filtering I mistakenly removed "other" fusions while filtering on column Fusion_Type for putative-oncogene fusion list. 
2) There is also a spelling mistake in the run_script 
3) IGH-@,IGH@ , IGL-@ and IGL@ need to be added to reference list as oncogenic genes. 

#### What changes need to be made? Please provide enough detail for another participant to make the update.
1) During project specific filtering I mistakenly removed "other" fusions while filtering on column Fusion_Type for putative-oncogene fusion list. 
In this chunk: https://github.com/AlexsLemonade/OpenPBTA-analysis/blob/87386d2a7a37a8cf9fd131ce74caa79cbaf142e3/analyses/fusion_filtering/04-project-specific-filtering.Rmd#L110 we shouldn't remove dplyr::filter(Fusion_Type != "other") and gather all putative_oncogene fusions at this step.

At this step to scavenge back recurrent inframe/frameshift non-oncogenic fusions use dplyr::filter(Fusion_Type != "other")
https://github.com/AlexsLemonade/OpenPBTA-analysis/blob/87386d2a7a37a8cf9fd131ce74caa79cbaf142e3/analyses/fusion_filtering/04-project-specific-filtering.Rmd#L143

2) There is also a spelling mistake in the run_script https://github.com/AlexsLemonade/OpenPBTA-analysis/blob/87386d2a7a37a8cf9fd131ce74caa79cbaf142e3/analyses/fusion_filtering/run_fusion_merged.sh#L54
$stranded_starfusion_file should be $standard_starfusion_file 

3) IGH-@,IGH@ , IGL-@ and IGL@ need to be added to reference list as oncogenic genes. 

#### What input data should be used? Which data were used in the version being updated?
v14 version
pbta-fusion-starfusion.tsv.gz
pbta-fusion-arriba.tsv.gz

#### When do you expect the revised analysis will be completed?
1 day

#### Who will complete the updated analysis?
@kgaonkar6

**Comment by jaclyn-taroni** [comment]
We should keep an eye on if this changes the output of `fusion-summary` (my intuition suggests not, but I'm not sure) and if so, those changes will need to get propagated to: 1) the data download 2) `molecular-subtyping-embryonal` 3) `molecular-subtyping-EPN`

**Comment by kgaonkar6** [comment]
I looked into ^, I reran the fusion-summary analysis and the files seem to be unchanged.

`md5sum data/fusion_summary_embryonal_foi.tsv `
dd9970e8d64ce7665c6c3983d8d34e98  data/fusion_summary_embryonal_foi.tsv
`md5sum analyses/fusion-summary/results/fusion_summary_embryonal_foi.tsv `
dd9970e8d64ce7665c6c3983d8d34e98  analyses/fusion-summary/results/fusion_summary_embryonal_foi.tsv

`md5sum data/fusion_summary_ependymoma_foi.tsv `
c93c681aadd9ec3e132bf39379b7053c  data/fusion_summary_ependymoma_foi.tsv
` md5sum analyses/fusion-summary/results/fusion_summary_ependymoma_foi.tsv `
c93c681aadd9ec3e132bf39379b7053c  analyses/fusion-summary/results/fusion_summary_ependymoma_foi.tsv

**Comment by jaclyn-taroni** [comment]
Thanks for checking that out @kgaonkar6, looking at your PR (#553) now!

**Comment by jaclyn-taroni** [comment]
Closed via #553
