### ISSUE TITLE
OK to use non-MRAN packages?

### ISSUE THREAD

**Issue by hbeale** [AlexsLemonade/OpenPBTA-analysis#563]
Is there any restriction on adding packages to the Rstudio docker? I noticed that only libraries in the pinned MRAN repository can be installed without changing the repo manually.  I change the repo manually :)

**Comment by jaclyn-taroni** [comment]
Hi @hbeale, in general I would say if you can tie things to a specific version (e.g., if you're using `remotes::install_github` in R, you make use `ref = <specific commit>`), then you are welcome to add that package to `Dockerfile`. The MRAN snapshot has generally helpful for transitive R dependencies in my experience. I might be able to give you a better/clearer answer if we get into the specifics 😄  or please feel free to file a pull request and we can discuss there!

**Comment by hbeale** [comment]
Thanks, @jaclyn-taroni. 

I looked at the Dockerfile, but I can't build a new image based on the old one. Here's the error I get. It might be due to an expired security certificate, because when I try to visit the URL in chrome, I get a message: "Your connection is not private...NET::ERR_CERT_DATE_INVALID".  I've [posted](https://social.technet.microsoft.com/Forums/en-US/f731d10a-252b-467d-a37c-5b0c69757d5c/unable-to-access-index-for-mran-repository?forum=ropen) to the MS R support forum as well. Is there another troubleshooting step you suggest? Thanks!

command:
```
cd /Users/hbeale/downloads/OpenPBTA-analysis 
version_tag=v0.1-alpha
docker build -t hbeale/open-pbta:${version_tag} .
```

Std out
```
...
Warning: unable to access index for repository https://mran.microsoft.com/snapshot/2019-07-05/src/contrib:
  cannot open URL 'https://mran.microsoft.com/snapshot/2019-07-05/src/contrib/PACKAGES'
Error: packages ‘gdalUtils’, ‘leafem’, ‘lwgeom’, ‘stars’, ‘leafpop’, ‘plainview’, ‘sf’, ‘mapview’ are not available (for R version 3.6.0)
In addition: Warning message:
packages ‘gdalUtils’, ‘leafem’, ‘lwgeom’, ‘stars’, ‘leafpop’, ‘plainview’, ‘sf’, ‘mapview’ are not available (for R version 3.6.0) 
The command '/bin/sh -c apt-get update -qq && apt-get -y --no-install-recommends install     && install2.r --error     --deps TRUE     gdalUtils     leafem     lwgeom     stars     leafpop     plainview     sf     mapview' returned a non-zero code: 1
```

**Comment by jashapiro** [comment]
Well, I just tweeted the expired cert out into the void. We'll see if that gets us anywhere.
https://twitter.com/jashapiro/status/1233103722181472267?s=20

**Comment by jaclyn-taroni** [comment]
In the interim, have you tried pulling the current image and then adding to the Dockerfile so some of the layers are cached locally?

**Comment by jaclyn-taroni** [comment]
That will not help if you are adding an R package haha. Don't mind me!

**Comment by jashapiro** [comment]
> Well, I just tweeted the expired cert out into the void. We'll see if that gets us anywhere.
> https://twitter.com/jashapiro/status/1233103722181472267?s=20

First step of success! https://twitter.com/revodavid/status/1233104425553498112?s=20

**Comment by jashapiro** [comment]
And fixed! https://twitter.com/revodavid/status/1233131001901023232?s=21

Try again @hbeale ?

**Comment by hbeale** [comment]
works for me. Thanks!

**Comment by hbeale** [comment]
Building the docker still fails (full msg below):
ERROR: dependency ‘BSgenome.Hsapiens.UCSC.hg19’ is not available for package ‘deconstructSigs’

Even though I've pulled the latest image, Docker still wants to build each layer.
Dockerfile
```
FROM ccdlopenpbta/open-pbta:latest
WORKDIR /rocker-build/

# rna-seq-composition
RUN R -e "devtools::install_github("sfirke/janitor", ref="be3b29b", dependencies = TRUE)"

WORKDIR /rocker-build/
```

```
Step 36/67 : RUN apt-get update -qq && apt-get -y --no-install-recommends install     && install2.r --error     --deps TRUE     deconstructSigs     qdapRegex
 ---> Running in f2c3aa458f99
Reading package lists...
Building dependency tree...
Reading state information...
0 upgraded, 0 newly installed, 0 to remove and 52 not upgraded.
Warning: dependency ‘BSgenome.Hsapiens.UCSC.hg19’ is not available
trying URL 'https://mran.microsoft.com/snapshot/2019-07-05/src/contrib/deconstructSigs_1.8.0.tar.gz'
Content type 'application/octet-stream' length 211160 bytes (206 KB)
==================================================
downloaded 206 KB

trying URL 'https://mran.microsoft.com/snapshot/2019-07-05/src/contrib/qdapRegex_0.7.2.tar.gz'
Content type 'application/octet-stream' length 149638 bytes (146 KB)
==================================================
downloaded 146 KB

ERROR: dependency ‘BSgenome.Hsapiens.UCSC.hg19’ is not available for package ‘deconstructSigs’
* removing ‘/usr/local/lib/R/site-library/deconstructSigs’
* installing *source* package ‘qdapRegex’ ...
** package ‘qdapRegex’ successfully unpacked and MD5 sums checked
** using staged installation
** R
** data
*** moving datasets to lazyload DB
** inst
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
** building package indices
** testing if installed package can be loaded from temporary location
** testing if installed package can be loaded from final location
** testing if installed package keeps a record of temporary installation path
* DONE (qdapRegex)

The downloaded source packages are in
	‘/tmp/downloaded_packages’
Error: installation of package ‘deconstructSigs’ had non-zero exit status
In addition: Warning message:
In install.packages(pkgs, ...) :
  installation of package ‘deconstructSigs’ had non-zero exit status
The command '/bin/sh -c apt-get update -qq && apt-get -y --no-install-recommends install     && install2.r --error     --deps TRUE     deconstructSigs     qdapRegex' returned a non-zero code: 1
```

**Comment by jaclyn-taroni** [comment]
Hm, that is strange considering the step right before that installs `BSgenome.Hsapiens.UCSC.hg19`. 

https://github.com/AlexsLemonade/OpenPBTA-analysis/blob/b1b73fe321a97fa82d85c86d20bd85635aabba25/Dockerfile#L153

I am wondering if the `BSgenome.Hsapiens.UCSC.hg19` is failing with a _warning_ instead of an error which allows the build to keep on going without success. I may be wrong but [we've run into something similar in refine.bio with an earlier version of bioconductor](https://github.com/AlexsLemonade/refinebio/blob/f795b9bb95c11ec043675da08f53e259fbb48368/workers/affymetrix_dependencies.R#L1).

What if we tried changing the build step before the one where it fails to:
```
RUN R -e "options(warn = 2); BiocManager::install(c('BSgenome.Hsapiens.UCSC.hg19', 'BSgenome.Hsapiens.UCSC.hg38'))" 
```

**Comment by jaclyn-taroni** [comment]
I'm going to try building locally and see if I'm getting the same thing, too.

**Comment by jaclyn-taroni** [comment]
I am not seeing an issue with the `deconstructSigs` install locally (starting from `Step 27/66`), so I am curious if raising warnings to errors gives us more information.

**Comment by hbeale** [comment]
Whoa, now the whole dockerfile works for me! So exciting. Now I can ask the question I originally thought would be the hard one: 

Below are the lines I added to the dockerfile. They include installing tidyr from CRAN so that I can get tidyr 1.0 (The MRAN snapshot version is 0.83).  However, I think you don't want to be pulling code from CRAN. I was unable to install it from github after several tries, but that might be an option with more effort. My greatest concern is that updating tidyr will break other people's code. Alternately, I could install it inside my R notebook file. Thoughts?

```
# Packages required for rna-seq-composition
RUN apt-get update -qq && apt-get -y --no-install-recommends install \
    && install2.r --error \
    --deps TRUE \
    EnvStats \
    janitor 

RUN R -e "install.packages(c('rlang', 'vctrs', 'tidyr'), repos = c(CRAN = 'https://cran.rstudio.com'))" 
RUN R -e "devtools::install_github('sfirke/janitor', ref='be3b29b1c55e171b334a38ad2fb73975f3c5fb30', dependencies = TRUE)"
RUN R -e "devtools::install_github('thomasp85/patchwork', ref = 'c67c6603ba59dd46899f17197f9858bc5672e9f4')"
```

**Comment by jaclyn-taroni** [comment]
Hi @hbeale, if we were going to update the Docker image to `tidyr 1.0`, we'd do it by bumping the versioned `rocker/tidyverse` image we pull from (#400). Does one of the packages listed above (`janitor`, `patchwork`) rely on `tidyr v1.0`?

**Comment by hbeale** [comment]
Hi @jaclyn-taroni, No other packages rely on it. I've used commands that were introduced in tidyr v1.0 (e.g. pivot_longer and unnest_wider). I can probably work around that if necessary.

**Comment by jaclyn-taroni** [comment]
Gotcha! If you don't mind working with other (potentially uglier) solutions and adding some TODOs into your code, so if we do end up tackling #400 and bumping the version of the Docker image we have some notes on what can be improved, I think that's the best path forward for now. If that sounds good, please feel free to close this issue. Thanks for your flexibility! 

If you'd like to bounce any ideas about workarounds off of folks, please feel free to post here or pop over to Slack. It seems @sjspielman has probably had to use workarounds for this project, too 🙂

**Comment by sjspielman** [comment]
There's a general recommendation [here](https://tidyr.tidyverse.org/articles/in-packages.html#tidyr-v0-8-3---v1-0-0) for dealing with `tidyr` version conflicts - maybe there is somewhere at the top of the pipeline we can pop this code and everything will just fall cleanly into place (said no one ever)

**Comment by hbeale** [comment]
Great resource. Thanks!

**Comment by jaclyn-taroni** [comment]
Because you've opened #596 with the current Docker image, I am going to go ahead and close this @hbeale.
