### ISSUE TITLE
Updated analysis: bedtools creation of bed files for TMB

### ISSUE THREAD

**Issue by cansavvy** [AlexsLemonade/OpenPBTA-analysis#564]
#### What analysis module should be updated and why?
@yuankunzhu mentioned that the BED files used for TMB denominators seemed too big. 

One issue is that bedtools' intersections when more than two bed files are being intersected do this pairwise. https://bedtools.readthedocs.io/en/latest/content/tools/intersect.html So if A B and C are being intersected, A and B are intersected and then A and C. This is not exactly what we want. Another issue is we may need to do a bedtools merge

#### What changes need to be made? Please provide enough detail for another participant to make the update.
This section where bedtools is being used to make the bed files needs to be fixed: https://github.com/AlexsLemonade/OpenPBTA-analysis/blob/b1b73fe321a97fa82d85c86d20bd85635aabba25/analyses/snv-callers/run_caller_consensus_analysis.sh#L52

This may include doing some merging and/or using different options.

#### What input data should be used? Which data were used in the version being updated?
Same data, different steps. 

#### When do you expect the revised analysis will be completed?
Today? 

#### Who will complete the updated analysis?
@cansavvy

**Comment by cansavvy** [comment]
Okay, I *think* this will give us more what we need: https://github.com/cansavvy/OpenPBTA-analysis/blob/81a806e376e9040877368ca39fa3ec0808cffaab/analyses/snv-callers/run_caller_consensus_analysis.sh#L52

I've switched to doing intersections one step at a time and then sorts and merges on all BED files. This yields bed sizes that seem more reasonable: 
![Screen Shot 2020-02-27 at 11 04 53 AM](https://user-images.githubusercontent.com/23458084/75461836-54506780-5951-11ea-9a43-7657e5225d48.png)

**Comment by yuankunzhu** [comment]
I have also created one for this at #565, but can close that and move the discussion here.

**Comment by yuankunzhu** [comment]
@cansavvy or can also share your TCGA liftover'd BED? Or you are just using the one from V14: `release-v14-20200203/gencode.v19.basic.exome.hg38liftover.bed`

**Comment by jaclyn-taroni** [comment]
Hi @yuankunzhu - this is the BED that is included as part of #562 and I believe is what you are looking for: https://github.com/AlexsLemonade/OpenPBTA-analysis/blob/bd22c5d5e6db700bfb927153eb4cbc5a98547e7f/analyses/snv-callers/ref_files/gencode.v19.basic.exome.hg38liftover.bed

@cansavvy correct me if I'm wrong.

**Comment by cansavvy** [comment]
> Hi @yuankunzhu - this is the BED that is included as part of #562 and I believe is what you are looking for: https://github.com/AlexsLemonade/OpenPBTA-analysis/blob/bd22c5d5e6db700bfb927153eb4cbc5a98547e7f/analyses/snv-callers/ref_files/gencode.v19.basic.exome.hg38liftover.bed
> 
> @cansavvy correct me if I'm wrong.

Yes. That's the one.

**Comment by yuankunzhu** [comment]
Thanks @jaclyn-taroni @cansavvy. we think that BED file might just be the whole exome region for gencode v19, so are trying to find the right WXS bait kit for the TCGA BAM. we might need to use that and re-calculate the TMB

**Comment by jaclyn-taroni** [comment]
@cansavvy was this closed via #566?

**Comment by cansavvy** [comment]
Yes except I don’t think it’s been merged. And there will be more BED files changes according to #568
