### ISSUE TITLE
TCGA BED file used for variant calling

### ISSUE THREAD

**Issue by jharenza** [AlexsLemonade/OpenPBTA-analysis#568]
#### What data file(s) does this issue pertain to?
`gencode.v19.basic.exome.hg38liftover.100bp_padded.bed`

#### What release are you using?

V15

#### Put your question or report your issue here.
We had used the file noted by the GDC [here](https://gdc.cancer.gov/about-data/publications/mc3-2017) for TCGA variant calling for which we are releasing MAFs in #543. However, upon inspection of the BAM file headers, @tkoganti, @yuankunzhu, and I found that their capture kit metadata did not match this BED file. More details to come today after we summarize this data more fully, but I am creating this issue so I can link it in #543 .

**Comment by jashapiro** [comment]
The investigation of this issues seems to be continuing, according to https://github.com/AlexsLemonade/OpenPBTA-analysis/pull/570#issuecomment-594091210

@tkoganti 
>We are tracking this issue here (https://github.com/d3b-center/D3b-codes/blob/feat/openpbta-tmb-analysis/OpenPBTA_TMB_analysis/README.ipynb) and when we have organized all the files that need to be pushed to OpenPBTA, we will create a new PR for TMB

While it is good to have this analysis proceeding, I think it would be good if we could keep all of the discussion and analysis in this repository as much as possible. To that end, each of the steps outlined in the readme referenced above would make a good PR here: 

1. Identification of the correct bed file
2. Testing that the bed file is correct
3. New somatic caller results
4. New TMB calculations 

1 and 2 could potentially be a single PR, but keeping them separate does have some advantages, in terms of continued communication and conversation.

**Comment by jharenza** [comment]
Thanks @jashapiro - I think @yuankunzhu and @tkoganti plan to submit 1 and 2 as a new PR tomorrow.

**Comment by jaclyn-taroni** [comment]
I'm going to close this - I think anything left is covered by #657.
