### ISSUE TITLE
[Transition plan] Publication-ready figures that don't have publication-ready content

### ISSUE THREAD

**Issue by jaclyn-taroni** [AlexsLemonade/OpenPBTA-analysis#571]
The CCDL data science team (@cbethell @cansavvy @jashapiro and @jaclyn-taroni) has other commitments that require us to wind down the phase of the project where we are _actively analyzing data_ and move to maintenance and review. We plan to use our next sprint (March 2-13) to make this transition.

Specifically, our goal is to get publication-ready figures added to the manuscript repository  that may not have the publication-ready content (e.g., the underlying data or gene lists are subject to change) and to do so in a manner where it is easy to update figures as the underlying data changes.

To this end, we will:

1. Write code to produce publication-ready multi-panel plots using a unified color palette and plot theme (#510)
2. Add a shell script that is designed to run _all steps_ required to get from the data download to the publication-ready figures either to the root of the repository or to `scripts`
3. Add a markdown file that documents the process to generate the figures including requirements (e.g., recommended RAM)
4. File a series of pull requests to the manuscript repository ([`AlexsLemonade/OpenPBTA-manuscript`](https://github.com/AlexsLemonade/OpenPBTA-manuscript/)) that use links to the figure PNGs in the `master` branch of this repository so that any changes committed back to this repo are automatic propagated to the manuscript repository.

### Figures we will prepare

* Sample distribution (from [`sample-distribution-analysis`](https://github.com/AlexsLemonade/OpenPBTA-analysis/tree/master/analyses/sample-distribution-analysis)) and GitHub contributions (#572); see: https://github.com/AlexsLemonade/OpenPBTA-manuscript/blob/9b65cd00cef2b59bad7059f0f96b483b7354b8e4/content/images/figure_sketches/fig1-proposed-sketch.png
* Tumor mutation burden (from [`snv-callers`](https://github.com/AlexsLemonade/OpenPBTA-analysis/tree/master/analyses/snv-callers)) and mutational signatures (bubble plot from [`mutational-signatures`](https://github.com/AlexsLemonade/OpenPBTA-analysis/tree/master/analyses/mutational-signatures)): https://github.com/AlexsLemonade/OpenPBTA-manuscript/blob/9b65cd00cef2b59bad7059f0f96b483b7354b8e4/content/images/figure_sketches/fig2-proposed-sketch.png
* Interaction plots ([`interaction-plots`](https://github.com/AlexsLemonade/OpenPBTA-analysis/tree/master/analyses/interaction-plots)); see: https://github.com/AlexsLemonade/OpenPBTA-manuscript/blob/9b65cd00cef2b59bad7059f0f96b483b7354b8e4/content/images/figure_sketches/occurrence-fig-sketch.jpg
* Oncoprint plot(s) ([`oncoprint-landscape`](https://github.com/AlexsLemonade/OpenPBTA-analysis/tree/master/analyses/oncoprint-landscape)); see:https://github.com/AlexsLemonade/OpenPBTA-manuscript/blob/master/content/images/figure_sketches/oncoprint-proposed-sketch.png
  * The oncoprint code already accepts lists of genes of interest. We should generate lists of mutations of interest as @jashapiro modifies `interaction-plots` and also come up with lists of genes with copy number alterations that we should represent. 
    * To get CNA gene lists, we need to make an attempt at the cytoband/arm values via bedtools intersect (#497) -> get lists of the "most focal unit" (WIP PR #485) -> recurrent copy number alterations (#488) 
* Copy number status heatmap which will be an adapted version of the breakpoint plots in [`chromosomal-instability`](https://github.com/AlexsLemonade/OpenPBTA-analysis/tree/master/analyses/chromosomal-instability)
* "Transcriptomic overview", which I'm thinking will contain plots from: UMAP ([`transcriptomic-dimension-reduction`](https://github.com/AlexsLemonade/OpenPBTA-analysis/tree/master/analyses/transcriptomic-dimension-reduction)), GSVA scores ([`gene-set-enrichment-analysis`](https://github.com/AlexsLemonade/OpenPBTA-analysis/tree/master/analyses/gene-set-enrichment-analysis)) and possibly [`immune-deconv`](https://github.com/AlexsLemonade/OpenPBTA-analysis/tree/master/analyses/immune-deconv)?

### Next steps

The CCDL team will break up the figures above into their own focused issues. These issues should include information around what intermediate steps need to be run to produce a figure (e.g., we need to run the SNV consensus steps to generate TMB).

**Comment by sjspielman** [comment]
A strategy like this was suggested to me for color palette. Use an existing smaller color palette that is colorblind friendly and reasonable to distinguish, and then have different gradients. This would work out well if we have some kind of _higher level grouping_ for subtypes? https://stackoverflow.com/questions/50163072/different-colors-with-gradient-for-subgroups-on-a-treemap-ggplot2-r/50164882#50164882

**Comment by jaclyn-taroni** [comment]
We have completed all figures mentioned above and inserted them into the manuscript. The script to generate all figures, as well as documentation around palettes and a summary of the figures are in [`figures`](https://github.com/AlexsLemonade/OpenPBTA-analysis/tree/master/figures).
