### ISSUE TITLE
Figure panel: GitHub contributions

### ISSUE THREAD

**Issue by jaclyn-taroni** [AlexsLemonade/OpenPBTA-analysis#572]
As part of the overview figure/Figure 1 of the manuscript, we would like to include panels that contain information about how the process worked on GitHub. Below is a subset of the sketch of Figure 1 in the manuscript repository.

![gh-fig](https://user-images.githubusercontent.com/19534205/75585077-4d078780-5a3f-11ea-958c-02ea3e74e2dd.png)

Some possible metrics to include:
* Lines over time (tricky because we've got a bunch of data files)
* Commits over time
* Some measure that quantifies _comments_ and _pull request reviews_ because it's not just about the commits!

I'm going to ask some of the CCDL devs if they have ideas of how to approach this.

**Comment by jaclyn-taroni** [comment]
@davidsmejia is going to take a look at generating flat files for contributions over time + comments on issues/pull requests. The idea is that we will set this up such that we can regenerate the flat files -> figure panel at the time of submission.

**Comment by jharenza** [comment]
@jaclyn-taroni is this still a plan for figure 1?

**Comment by jaclyn-taroni** [comment]
> @jaclyn-taroni is this still a plan for figure 1?

Yea, this would be of interest to readers IMO.

**Comment by jharenza** [comment]
I agree!

**Comment by jaclyn-taroni** [comment]
This is not reflected in the Google slides version of figure drafts, so I am going to close it.
