### ISSUE TITLE
Data: MAF files have samples that do not have metadata

### ISSUE THREAD

**Issue by cansav09** [AlexsLemonade/OpenPBTA-analysis#58]
### Problem

13 samples that have data in the MAF files (`pbta-snv-mutect2.vep.maf.gz` and `pbta-snv-strelka2.vep.maf.gz`) are missing from the metadata. I am using data `release-v2-20190809` and downloaded it via the bash script this morning. 

### Samples that are missing metadata but have data reported in the MAF files. 
```r
"BS_0BA5TZND" 
"BS_0HYD1VHH" 
"BS_0PQGSCJA" 
"BS_3GSGMV4T" 
"BS_3RJ3CDE6" 
"BS_AH51BZ8D" 
"BS_BF95AEXC" 
"BS_D0T6V861" 
"BS_KVPJVJR7" 
"BS_TC8R5HY4" 
"BS_TKF4H7CZ" 
"BS_V1DPR5TD"
"BS_X2G3JMM1"
```

Here are the steps I took to obtain this list of samples were missing from the metadata. Let me know if there is something I missing or misunderstanding. 
```
# Read in the metadata
metadata <- readr::read_tsv(file.path("..", "..", "data", "pbta-histologies.tsv"))

# Read in Mutect2 data
mutect2 <- maftools::read.maf(file.path("..", "..", "data", "pbta-snv-mutect2.vep.maf.gz"))

# Read in Strelka2 data
strelka <- maftools::read.maf(file.path("..", "..", "data", "pbta-snv-strelka2.vep.maf.gz"))

# Find out what samples don't have data in the metadata
missing_mutect2_samples <- mutect2@data %>% 
  dplyr::filter(!(Tumor_Sample_Barcode %in% metadata$Kids_First_Biospecimen_ID)) %>%
  dplyr::distinct(Tumor_Sample_Barcode, .keep_all = TRUE) %>%
  dplyr::pull(Tumor_Sample_Barcode)

missing_mutect2_samples <- strelka2@data %>% 
  dplyr::filter(!(Tumor_Sample_Barcode %in% metadata$Kids_First_Biospecimen_ID)) %>%
  dplyr::distinct(Tumor_Sample_Barcode, .keep_all = TRUE) %>%
  dplyr::pull(Tumor_Sample_Barcode)

# These are the same 13 samples in both datasets
sort(intersect(missing_mutect2_samples, missing_strelka2_samples))
```

## Next steps:

Were these samples supposed to be removed from the MAF files? (And if so, why?) 
OR 
Where is the metadata for these 13 samples and how do we get it?

**Comment by jharenza** [comment]
Will look into this. Thanks for the catch!

**Comment by yuankunzhu** [comment]
I didn't see those IDs in the MAF files. What i did is below:
1. for `BS_0BA5TZND`, search in entire maf
```
(base) ➜  release-v2-20190809 zgrep -c BS_0BA5TZND pbta-snv-mutect2.vep.maf.gz
0
(base) ➜  release-v2-20190809 zgrep -c BS_0BA5TZND pbta-snv-strelka2.vep.maf.gz
0
```

2. extract the tumor/normal barcode and search all BS IDs
```
zcat pbta-snv-mutect2.vep.maf.gz | cut -f16,17 | sort -u > bar-code-mutect2
zcat pbta-snv-strelka2.vep.maf.gz | cut -f16,17 | sort -u > bar-code-strelka

grep -w BS_0BA5TZND bar-code-*
grep -w BS_0HYD1VHH bar-code-*
grep -w BS_0PQGSCJA bar-code-*
grep -w BS_3GSGMV4T bar-code-*
grep -w BS_3RJ3CDE6 bar-code-*
grep -w BS_AH51BZ8D bar-code-*
grep -w BS_BF95AEXC bar-code-*
grep -w BS_D0T6V861 bar-code-*
grep -w BS_KVPJVJR7 bar-code-*
grep -w BS_TC8R5HY4 bar-code-*
grep -w BS_TKF4H7CZ bar-code-*
grep -w BS_V1DPR5TD bar-code-*
grep -w BS_X2G3JMM1 bar-code-*
```

**Comment by cansav09** [comment]
Okay. I re-downloaded and refreshed and I think things are good. This was a false alarm. Sorry about that. 

Second question though, why did those 13 samples get removed in this latest data edition when they were in the previous? I'm going to go ahead and close this comment since the original issue is not a problem.

**Comment by jharenza** [comment]
No worries. We had a handful of samples that were removed due to QC/consent issues.

**Comment by yuankunzhu** [comment]
No problem. I briefly described it a little bit in the [release-notes](https://github.com/AlexsLemonade/OpenPBTA-analysis/blob/master/doc/release-notes.md) also.
