### ISSUE TITLE
Proposed Analysis: CN status heatmap

### ISSUE THREAD

**Issue by cansavvy** [AlexsLemonade/OpenPBTA-analysis#594]
#### What are the scientific goals of the analysis?
Create a visualization that can show the CN copy number status across samples.
This would be much like the heatmaps in [chromosomal-instability](https://github.com/AlexsLemonade/OpenPBTA-analysis/blob/master/analyses/chromosomal-instability/02a-plot-chr-instability-heatmaps.Rmd) except this heatmap would be samples x copy number status across the genome (three colors - amp, neutral, del). 

#### What methods do you plan to use to accomplish the scientific goals?
I plan to mainly use the code I developed in [chromosomal-instability](https://github.com/AlexsLemonade/OpenPBTA-analysis/blob/master/analyses/chromosomal-instability/02a-plot-chr-instability-heatmaps.Rmd) but adapt it for copy number status.

#### What input data are required for this analysis?
`pbta-cnv-consensus.seg` from the data release. 

#### How long do you expect is needed to complete the analysis? Will it be a multi-step analysis?
A day?

#### Who will complete the analysis (please add a GitHub handle here if relevant)?
@cansavvy 

#### What relevant scientific literature relates to this analysis?
I don't know of any.

**Comment by cansavvy** [comment]
What I need to figure out more specifically is what the unit of columns for this heatmap will be. Do we want: 
- each pixel is a cytoband? 
- each pixel is a gene? 
- each pixel is a particular bin of width of the genome (which requires me to make a summary call for each bin) - this is probably the least easily interpretable idea.

I think cytoband makes the most sense, so I'll go with that unless someone weighs in differently.

**Comment by cansavvy** [comment]
The pixel is a gene form of this heatmap did not turn out to be useful. After consulting @jaclyn-taroni and @jashapiro , we decided to . move to a window approach where binned portions of the genome are called as a loss, gain or amplification based on the number of bp that are called as each. Will also require a certain (percent of bases?) threshold to avoid calling a whole window as gained/loss if only a few bases were involved in that call.

**Comment by jaclyn-taroni** [comment]
@cansavvy can we close this? I believe any updates you want to make are tracked elsewhere. If that is the case, can you post where they are tracked and close this issue please.

**Comment by cansavvy** [comment]
What's left to be done for the CNV status plot is tracked here: https://github.com/cansavvy/openpbta-notebook-concept/issues/7
