### ISSUE TITLE
Planned Analysis: Oncoprint showing landscape of genetic lesions across PBTA.

### ISSUE THREAD

**Issue by PichaiRaman** [AlexsLemonade/OpenPBTA-analysis#6]
This figure typically focuses on a set of high frequency and cancer associated lesions (mutations / CNV) and will typically have corresponding phenotypic data so as to visualize associations. See Figure 1 (https://www.biorxiv.org/content/10.1101/656587v1.full) for an example.

**Comment by jharenza** [comment]
I imagine this analysis would make use of consensus SNV calls (#30), consensus CNV calls (#128), and filtered/prioritized fusion calls (#39 and #10) currently tied to multiple PRs. I can work on this after a grant submission Nov 15, but if anyone would like to work on this earlier, I have created some [code](https://github.com/marislab/create-pptc-pdx-oncoprints) for this for a recent manuscript that can be adapted.

**Comment by cbethell** [comment]
> I imagine this analysis would make use of consensus SNV calls (#30), consensus CNV calls (#128), and filtered/prioritized fusion calls (#39 and #10) currently tied to multiple PRs. I can work on this after a grant submission Nov 15, but if anyone would like to work on this earlier, I have created some code for this for a recent manuscript that can be adapted.

I can begin working on this issue now, while keeping in mind that this analysis will need to be rerun once the aforementioned upstream issues are completed.

**Comment by jharenza** [comment]
Thanks, @cbethell !

**Comment by jaclyn-taroni** [comment]
The code in [`oncoprint-landscape`](https://github.com/AlexsLemonade/OpenPBTA-analysis/tree/master/analyses/oncoprint-landscape) is largely in good shape. But we will want to update the data displayed in the plots to account for the following:

* We have consensus copy number calls. GISTIC needs to be rerun with the consensus SEG file (#453) and focal vs. broad losses need to be reconciled per https://github.com/AlexsLemonade/OpenPBTA-analysis/issues/186#issuecomment-574214014.
* We should identify recurrently altered genes that can be used to guide the display. 
  * This is included as part of #394 regarding amplification, deep deletion, and other SVs.
  * We have `pbta-fusion-recurrently-fused-genes-byhistology.tsv` now included as part of the data download that can be used to guide the display of fusions.

**Comment by jaclyn-taroni** [comment]
Closing all planned analysis tickets in favor of opening new proposed analysis/updated analysis tickets as needed.
