### ISSUE TITLE
'Brainstem glioma- Diffuse intrinsic pontine glioma' diagnosis based on RNAseq?

### ISSUE THREAD

**Issue by jainpayal022** [AlexsLemonade/OpenPBTA-analysis#606]
#### What data file(s) does this issue pertain to?
RNAseq data from these samples specifically:
BS_1D6PZNKN
BS_30VC3R2Q
BS_5965SFPZ
BS_6DCSD5Y6
BS_7GJT4A6A
BS_9CA93S6D
BS_B1C6GZ84
BS_F0JB4EAK
BS_G3NN392N
BS_MKM0EEN1
BS_NB9XXBW6
BS_PZVHMSYN
BS_W4DB5RP1
BS_W7MFJZ5A
BS_YDEVMD24

#### What release are you using?

V15 

#### Put a link to the relevant section of the [OpenPBTA-manuscript](https://github.com/AlexsLemonade/OpenPBTA-manuscript/) here.
In relation to molecularly-based reclassification of DIPG/HGG tumors to DMGs. 

#### Put your question or report your issue here.
For the samples mentioned above, there is only RNAseq data analysis and we don't know if these are H3K27M mutant. If we could run these through Strelka (@kgaonkar6), would it be possible to help assign K27M mutant status to these, and subsequently re-classify these cases as DMGs (or not)?

**Comment by kgaonkar6** [comment]
Strelka has an experimental mode to call variant calls for transcribed genes here :
https://github.com/Illumina/strelka/blob/master/docs/userGuide/README.md#rna-seq

**Comment by jaclyn-taroni** [comment]
If using Strelka with RNA-seq is not a regular part of a pipeline that has been benchmarked, I would consider it to be beyond the scope of the initial version of a manuscript.

**Comment by jharenza** [comment]
closing, as beyond the scope of v1
