### ISSUE TITLE
Updated analysis: chordoma subtyping

### ISSUE THREAD

**Issue by jharenza** [AlexsLemonade/OpenPBTA-analysis#608]
#### What analysis module should be updated and why?
We should add the "poorly differentiating" subtype

#### What changes need to be made? Please provide enough detail for another participant to make the update.
We have a data [table](https://github.com/AlexsLemonade/OpenPBTA-analysis/blob/master/analyses/molecular-subtyping-chordoma/results/chordoma_smarcb1_status.tsv) of SMARCB1 copy number information and RNA expression, but this should be reviewed by a pathologist or chordoma expert for final determination of the poorly differentiating subtype. I was also reading that [IHC](https://www.ncbi.nlm.nih.gov/pubmed/29483606) can inform/distinguish this, so if possible, they should also review histology imaging for confirmation. 

#### What input data should be used? Which data were used in the version being updated?
This [table](https://github.com/AlexsLemonade/OpenPBTA-analysis/blob/master/analyses/molecular-subtyping-chordoma/results/chordoma_smarcb1_status.tsv) and histology images available on KidsFirst.

#### When do you expect the revised analysis will be completed?
?

#### Who will complete the updated analysis?
?
D3b to pull IHC images and coordinate with a disease expert.

cc @yuankunzhu @allisonheath

**Comment by jharenza** [comment]
CC @stefankies for coordination

**Comment by jaclyn-taroni** [comment]
I'm going to label this as `blocked` because this is external to analyses contained within the repository.

**Comment by jharenza** [comment]
I will coordinate with pathology to get these reviewed.

**Comment by jharenza** [comment]
After my some pathology report translations by Laura Scolaro, my pathology report review, CN inspection, and discussion with pathologist, Mariarita Santi, I have the following to report:

| Kids_First_Participant_ID | Kids_First_Biospecimen_ID_RNA | Kids_First_Biospecimen_ID_DNA | pathology_diagnosis      | sample_id | tumor_descriptor  | focal_SMARCB1_status | SMARCB1_expression | Path report inspection                                                                               | Poorly differentiated? Comments                              |
|---------------------------|-------------------------------|-------------------------------|--------------------------|-----------|-------------------|----------------------|--------------------|------------------------------------------------------------------------------------------------------|--------------------------------------------------------------|
| PT_F1086Z0A               | BS_P4D8Y3S8                   | BS_BWZTMWTM                   | Chordoma                 | 7316-1101 | Initial CNS Tumor | loss                 | 7.1                | INI1 negative; poorlydifferentiated per pathology report                                             | yes                                                          |
| PT_HFQNKP5X               | BS_YB07VF1X                   | BS_9GN1QA3Q                   | Chordoma                 | 7316-2935 | Progressive       | neutral              | 14.29              | poorly differentiated per pathology report; INI1 negative                                            | yes                                                          |
| PT_HFQNKP5X               | BS_EJ9JKM1C                   | BS_6F49F7WH                   | Chordoma                 | 7316-3295 | Recurrence        | loss                 | 3.89               | INI1 retained in 50% of cells                                                                        | likely yes with immunostain being wrong - repeat immunostain |
| PT_WTMSD2WB               | BS_67PX06P3                   | BS_JTBM5TSE                   | Chordoma                 | 7316-3632 | Initial CNS Tumor | loss                 | 15.68              | INI1 not mutated                                                                                     | no - tumor is ploidy 4 and loss with chr22 CN of 3           |
| PT_HFQNKP5X               | BS_DBDXCXT5                   | BS_5B6XZ7YP                   | Chordoma                 | 7316-4062 | Progressive       | loss                 | 18.66              | poorly differentiated per autopsy report                                                             | yes                                                          |
| PT_HFQNKP5X               | BS_GFM6EA61                   | BS_FBJ516WW                   | Chordoma                 | 7316-921  | Initial CNS Tumor | neutral              | 20.87              | loss of INI1 immunostain; no deletion or duplication of SMARB1 or coding mutation                    | likely no with immunostain being wrong - repeat immunostain  |
| PT_3WA7SBQ6               | BS_0VRSD9V3                   | BS_HN8DE43A                   | Choroid plexus carcinoma | 7316-2248 | Initial CNS Tumor | neutral              | 113.08             | no mention of INI1; recurrent tumor one year later (7316-3135) notes preserved INI1 nuclear staining | no (remove, not chordoma)                                    |
| PT_41BCPB7R               | BS_64HCD9K3                   | NA                            | Choroid plexus carcinoma | 7316-406  | Initial CNS Tumor | NA                   | 33.73              | INI1 positive                                                                                        | no (remove, not chordoma)                                    |
| PT_7TRGHZBK               | BS_W36RZSFA                   | BS_XEVMEYFS                   | Choroid plexus carcinoma | 7316-431  | Initial CNS Tumor | neutral              | 53.15              | INI1 positive                                                                                        | no (remove, not chordoma)                                    |
| PT_YZ8A8A36               | BS_GSVCN2XC                   | BS_59FR1NC2                   | Choroid plexus carcinoma | 7316-723  | Initial CNS Tumor | neutral              | 43.79              | INI1 normal                                                                                          | no (remove, not chordoma)                                    |

I am not certain we will have immunostains on the two samples in question, so we could make those `To be classified` for now to get this updated and merged.

**Comment by jharenza** [comment]
Forgot to add this CN image:
![BS_JTBM5TSE_CNV](https://user-images.githubusercontent.com/207034/107826701-54f53000-6d53-11eb-846f-d6a9b4d133bd.png)

**Comment by kgaonkar6** [comment]
Just wanted to add a note from slack discussion, we will add the above subtypes to molecular-subtyoing-pathology once we have a 3rd type called dedifferentiated also identified and annotated for chordoma samples.

**Comment by jharenza** [comment]
Pasting here email correspondence from Mariarita Santi

>Dear Jo Lynne,
>
>Thank you for your enquire; however it is difficult to answer your questions without looking at the morphology:
>
>
>These are some elements that I can give to you:
>
> **Classic chordoma/ conventional** are defined from soft tissue tumor  WHO classification 2020  as positive for S-100-,cytokeratin, EMA and brachyury and in majority of cases retained INI-1.  Now there are reports of conventional chordoma with loss of INI-1 immunostain.  Case 7316-921 is reported as chordoma with loss of INI-1 expression; however you mentioned that no alteration/mutation of INI-1/SMARCB1 were found.  Probably the immunostain was wrongly interpreted, if you think that the genetic test you did was correct , here there is a discrepancy between immunostains and genetic result.  You should run again on unstained section the INI-1 immunostain.  In addition a test done from the contributor 7316-921 cytogenetic mentioned that no INI-1 mutation/abnormality is found.  Putting everything together I would say that the immunostain was wrong, this is probably a chordoma, but  I cannot be completely sure without looking at the morphology and correlating everything together.
>
> **Poorly differentiated chordoma** are characterized by loss of INI-1/SMARCB1 loss; these are brachyury positive.  Therefore yes 7316-3295 may be a poorly differentiated if you see deletion/mutation of SMACB1 gene.  Again what does it mean loss of immunostains in 50% of the cells. It is impossible to judge without looking.  Again you should repeat immunostains.
>
>Remember there is a third category of **dedifferentiated chordoma**  that is conventional chordoma plus sarcoma, with brachyury negative but no loss of INI-1
>
>I think that for this chordoma study you should request unstained FFPE from each contributor and repeat the immunostains here in the core lab if there is no correlation between immunostains and genetic finding
>
>I have another curiosity, what you mean when you write focal SMARCB1 gene loss? Mosaic situation
>
>Thanks
>
>I hope this help
>
>mariarita

**Comment by jharenza** [comment]
@kgaonkar6 I realized that the two samples in question were from one patient for which we have 4 samples, so going back through the timeline of the tumor, I added the most likely subtypes and this is ready for a PR:

| Kids_First_Biospecimen_ID_RNA | Kids_First_Biospecimen_ID_DNA | pathology_diagnosis      | sample_id | tumor_descriptor  | focal_SMARCB1_status | SMARCB1_expression | Path report inspection                                                                                                        | Poorly differentiated? Comments                              | molecular_subtype           |
|-------------------------------|-------------------------------|--------------------------|-----------|-------------------|----------------------|--------------------|-------------------------------------------------------------------------------------------------------------------------------|--------------------------------------------------------------|-----------------------------|
| BS_P4D8Y3S8                   | BS_BWZTMWTM                   | Chordoma                 | 7316-1101 | Initial CNS Tumor | loss                 | 7.1                | INI1 negative; poorlydifferentiated per pathology report                                                                      | yes                                                          | CHDM, poorly differentiated |
| BS_YB07VF1X                   | BS_9GN1QA3Q                   | Chordoma                 | 7316-2935 | Progressive       | neutral              | 14.29              | poorly differentiated per pathology report; INI1 negative                                                                     | yes                                                          | CHDM, poorly differentiated |
| BS_EJ9JKM1C                   | BS_6F49F7WH                   | Chordoma                 | 7316-3295 | Recurrence        | loss                 | 3.89               | INI1 retained in 50% of cells; in areas, tumor is more solid and less differentiated than previous resection                  | likely yes with immunostain being wrong - repeat immunostain | CHDM, poorly differentiated |
| BS_DBDXCXT5                   | BS_5B6XZ7YP                   | Chordoma                 | 7316-4062 | Progressive       | loss                 | 18.66              | poorly differentiated per autopsy report                                                                                      | yes                                                          | CHDM, poorly differentiated |
| BS_GFM6EA61                   | BS_FBJ516WW                   | Chordoma                 | 7316-921  | Initial CNS Tumor | neutral              | 20.87              | loss of INI1 immunostain; no deletion or duplication of SMARB1 or coding mutation                                             | likely no with immunostain being wrong - repeat immunostain  | CHDM, conventional          |
| BS_67PX06P3                   | BS_JTBM5TSE                   | Chordoma                 | 7316-3632 | Initial CNS Tumor | loss                 | 15.68              | morphological and immunohistochemistry results ( AE1/AE3 +, Cam5.2+, EMA+,S100+, INI-1 not mutated) consistent with chordoma. | no - tumor is ploidy 4 and loss with chr22 CN of 3           | CHDM, conventional          |
| BS_0VRSD9V3                   | BS_HN8DE43A                   | Choroid plexus carcinoma | 7316-2248 | Initial CNS Tumor | neutral              | 113.08             | no mention of INI1; recurrent tumor one year later (7316-3135) notes preserved INI1 nuclear staining                          | no (remove, not chordoma)                                    |                             |
| BS_64HCD9K3                   | NA                            | Choroid plexus carcinoma | 7316-406  | Initial CNS Tumor | NA                   | 33.73              | INI1 positive                                                                                                                 | no (remove, not chordoma)                                    |                             |
| BS_W36RZSFA                   | BS_XEVMEYFS                   | Choroid plexus carcinoma | 7316-431  | Initial CNS Tumor | neutral              | 53.15              | INI1 positive                                                                                                                 | no (remove, not chordoma)                                    |                             |
| BS_GSVCN2XC                   | BS_59FR1NC2                   | Choroid plexus carcinoma | 7316-723  | Initial CNS Tumor | neutral              | 43.79              | INI1 normal                                                                                                                   | no (remove, not chordoma)                                    |                             |

**Comment by kgaonkar6** [comment]
cool, adding a PR for this

**Comment by kgaonkar6** [comment]
Are there integrated_diagnosis terms attached with each of the subtypes below?
 sample_id | molecular_subtype
-- | --
7316-1101 |	CHDM, poorly differentiated
7316-2935 |	CHDM, poorly differentiated
7316-3295 |	CHDM, poorly differentiated
7316-4062 |	CHDM, poorly differentiated
7316-921 |	CHDM, conventional
7316-3632	| CHDM, conventional

**Comment by jharenza** [comment]
closed with #951
