### ISSUE TITLE
Proposed Analysis: Investigate integrated diagnosis vs pathology diagnosis

### ISSUE THREAD

**Issue by jharenza** [AlexsLemonade/OpenPBTA-analysis#609]
#### What are the scientific goals of the analysis?
1. To determine via pathology reports, slides, images whether the molecular (`integrated_diagnosis`) was something missed, could be explained by pathology, and/or was not suggested by pathology. 
2. To determine whether therapy would have been different given the `integrated_diagnosis`.
3. If 2 is `yes, different`, to investigate clinical outcomes/survival. 

#### What methods do you plan to use to accomplish the scientific goals?
Manual inspection of pathology reports, IHC images, slides, clinical data, etc.

#### What input data are required for this analysis?
Table from #607, pathology reports, IHC images, slides, clinical data, etc. (available on [KidsFirst](kidsfirstdrc.org)).

#### How long do you expect is needed to complete the analysis? Will it be a multi-step analysis?
~2-4 weeks (beginning the week of March 9 with CHOP pathology)

#### Who will complete the analysis (please add a GitHub handle here if relevant)?
CHOP pathologists Maria Rita Santi and Angela Viaene
@taylordm

#### What relevant scientific literature relates to this analysis?
NA

cc: @yuankunzhu @allisonheath @stefankies @jvlilly

**Comment by jvlilly** [comment]
Looping in the PMs

Jena V. Lilly MS CCRC
Director of Operations & Strategic Planning
Center for Data Driven Discovery in Biomedicine
Children’s Brain Tumor Tissue Consortium
The Roberts Center for Pediatric Research
12th floor, 12473
2716 South Street.
Philadelphia, PA 19146
M: (609) 922-1092
lillyj@email.chop.edu<mailto:lillyj@email.chop.edu> ● d3b.center<http://d3b.center/>

[cid:image002.jpg@01D3E787.6D25A060]
CBTTC.org <http://cbttc.org/>  Kidsfirstdrc.org <http://kidsfirstdrc.org/>  PNOC.us<applewebdata://38657B7D-0294-4061-912A-1C2E4CE8110E/pnoc.us> Cavatica.org<http://cavatica.org/>

**Comment by jharenza** [comment]
Sent Mariarita and Angela the following files, but they had requested us to write up findings in paragraph form. @adamcresnick to determine who will do this.


[2020-02-28-OpenPBTA-differential-dx.xlsx](https://github.com/AlexsLemonade/OpenPBTA-analysis/files/4318453/2020-02-28-OpenPBTA-differential-dx.xlsx)
[2020-02-28-hgg-molecular-lesions.txt](https://github.com/AlexsLemonade/OpenPBTA-analysis/files/4318458/2020-02-28-hgg-molecular-lesions.txt)
[2020-02-28-emb-molecular-lesions.txt](https://github.com/AlexsLemonade/OpenPBTA-analysis/files/4318461/2020-02-28-emb-molecular-lesions.txt)

**Comment by jharenza** [comment]
Updated feedback from Rita:

| ﻿Kids_First_Biospecimen_ID | glioma_brain_region | sample_id | aliquot_id | Kids_First_Participant_ID | experimental_strategy | pathology_diagnosis                              | integrated_diagnosis                     | Notes from Path inspection                                                                  | Action                                                                                 | Given to Rita 3/13/20                                                                                      | short_histology | broad_histology                                                          | broad_composition | Notes                                                                 | cancer_predispositions | molecular_subtype   |
|---------------------------|---------------------|-----------|------------|---------------------------|-----------------------|--------------------------------------------------|------------------------------------------|---------------------------------------------------------------------------------------------|----------------------------------------------------------------------------------------|------------------------------------------------------------------------------------------------------------|-----------------|--------------------------------------------------------------------------|-------------------|-----------------------------------------------------------------------|------------------------|---------------------|
| BS_C6ZZ3FY5               | hemispheric         | 7316-1105 | 470017     | PT_X71D7G5S               | RNA-Seq               | Supratentorial or Spinal Cord PNET               | High-grade glioma                        | No path report available                                                                    | reviewed - OK with new dx                                                              | 1 slide, pathology report                                                                                  | HGAT            | Diffuse astrocytic and oligodendroglial tumor                            | tumor             | Updated via OpenPBTA subtyping                                        | None documented        | HGG, H3 G35         |
| BS_P8WN8XEQ               | hemispheric         | 7316-1105 | 549712     | PT_X71D7G5S               | WGS                   | Supratentorial or Spinal Cord PNET               | High-grade glioma                        | No path report available                                                                    | reviewed - OK with new dx                                                              | 1 slide, pathology report                                                                                  | HGAT            | Diffuse astrocytic and oligodendroglial tumor                            | tumor             | Updated via OpenPBTA subtyping                                        | None documented        | HGG, H3 G35         |
| BS_23M72ABG               | NA                  | 7316-523  | 588343     | PT_AQWDQW27               | RNA-Seq               | Meningioma                                       | </s>Ependymoma</s> Meningioma                   | No path report available                                                                    | reviewed - keep as meningioma                                                          | 2 slides, pathology report; email request for radiology                                                    | tumor           | <s>Ependymal tumor</s>                                                          | tumor             |                                                                       | None documented        | <s>ST-EPN-YAP</s>          |
| BS_5JM573JC               | hemispheric         | 7316-2255 | 717166     | PT_6Q0NPVP3               | RNA-Seq               | Ganglioglioma                                    | Diffuse midline glioma                   | Path report ganglioglioma with extensive chondroid metaplasia                               | need to review radiology report; if not diffuse, ganglioglioma, H3 mut - cannot review | pathology report (no slides - from Pitt); email request for radiology - will not receive in the short term | HGAT            | Diffuse astrocytic and oligodendroglial tumor                            | tumor             | Updated via OpenPBTA subtyping                         | None documented        | DMG, H3 K28         |
| BS_E5H6CFYT               | hemispheric         | 7316-2255 | 711134     | PT_6Q0NPVP3               | WGS                   | Ganglioglioma                                    | Diffuse midline glioma                   | Path report ganglioglioma with extensive chondroid metaplasia                               | need to review radiology report; if not diffuse, ganglioglioma, H3 mut - cannot review | pathology report (no slides - from Pitt); email request for radiology - will not receive in the short term | HGAT            | Diffuse astrocytic and oligodendroglial tumor                            | tumor             | Updated via OpenPBTA subtyping                         | None documented        | DMG, H3 K28         |
| BS_BFDEZK1C               | other               | 7316-1102 | 549714     | PT_5BWZA0NT               | WGS                   | Supratentorial or Spinal Cord PNET               | Diffuse midline glioma                   | No path report available                                                                    | reviewed - OK with new dx                                                              | 3 slides, pathology report                                                                                 | HGAT            | Diffuse astrocytic and oligodendroglial tumor                            | tumor             | Updated via OpenPBTA subtyping                                        | None documented        | DMG, H3 K28         |
| BS_MB7WN0ZB               | other               | 7316-1102 | 470031     | PT_5BWZA0NT               | RNA-Seq               | Supratentorial or Spinal Cord PNET               | Diffuse midline glioma                   | No path report available                                                                    | reviewed - OK with new dx                                                              | 3 slides, pathology report                                                                                 | HGAT            | Diffuse astrocytic and oligodendroglial tumor                            | tumor             | Updated via OpenPBTA subtyping                                        | None documented        | DMG, H3 K28         |
| BS_H1XPVS9A               | hemispheric         | 7316-1106 | 549575     | PT_T8V9ES93               | RNA-Seq               | High-grade glioma/astrocytoma (WHO grade III/IV) | <s>High-grade glioma</s> Low-grade glioma       | No path report available                                                                    | reviewed - OK with new dx (PXA/LGG)                                                    | 2 slides, pathology report                                                                                 | HGAT            | <s>Diffuse astrocytic and oligodendroglial tumor</s> Low-grade astrocytic tumor | tumor             | Updated via OpenPBTA subtyping                                        | None documented        | LGG, BRAF V600E          |
| BS_J4E9SW51               | hemispheric         | 7316-1106 | 549708     | PT_T8V9ES93               | WGS                   | High-grade glioma/astrocytoma (WHO grade III/IV) | <s>High-grade glioma</s> Low-grade glioma       | No path report available                                                                    | reviewed - OK with new dx (PXA/LGG)                                                    | 2 slides, pathology report                                                                                 | HGAT            | <s>Diffuse astrocytic and oligodendroglial tumor</s> Low-grade astrocytic tumor | tumor             | Updated via OpenPBTA subtyping                                        | None documented        | LGG, BRAF V600E          |
| BS_J8VX4D17               | mixed               | 7316-506  | 588299     | PT_7E3V3JFX               | RNA-Seq               | Ependymoma                                       | <s>Diffuse midline glioma</s> Ependymoma        | Path report posterior fossa ependymoma                                                      | reviewed - keep EPN with H3 mut- rare                                                  |                                                                                                            | HGAT            | <s>Diffuse astrocytic and oligodendroglial tumor</s> Ependymal tumor            | tumor             | Updated via OpenPBTA subtyping                                        | None documented        | <s>DMG, H3 K28</s>         |
| BS_G16NM5WJ               | mixed               | 7316-506  | 588011     | PT_7E3V3JFX               | WGS                   | Ependymoma                                       | <s>Diffuse midline glioma</s> Ependymoma        | Path report posterior fossa ependymoma                                                      | reviewed - keep EPN with H3 mut- rare                                                  |                                                                                                            | HGAT            | <s>Diffuse astrocytic and oligodendroglial tumor</s> Ependymal tumor            | tumor             | Updated via OpenPBTA subtyping                                        | None documented        | <s>DMG, H3 K28</s>         |
| BS_KSKZ9J7J               | NA                  | 7316-765  | 470731     | PT_80NVYCBS               | RNA-Seq               | Ependymoma                                       | CNS Embryonal Tumor                      | Path report anaplastic ependymoma                                                           | reviewed - OK with new dx                                                              |                                                                                                            | Embryonal Tumor | Embryonal tumor                                                          | tumor             | Updated via OpenPBTA subtyping                                        | None documented        | CNS HGNET-MN1       |
| BS_K07KNTFY               | NA                  | 7316-272  | 588001     | PT_00G007DM               | WGS                   | Medulloblastoma                                  | Embryonal tumor with multilayer rosettes | Path report had "medulloblastoma" handwritten, but final dx ETMR with multilayer rosettes   | reviewed - OK with new dx                                                              |                                                                                                            | ETMR            | Embryonal tumor                                                          | tumor             | Updated via OpenPBTA subtyping                                        | None documented        | ETMR, C19MC-altered |
| BS_QWNBZ9RJ               | NA                  | 7316-272  | 588287     | PT_00G007DM               | RNA-Seq               | Medulloblastoma                                  | Embryonal tumor with multilayer rosettes | Path report had "medulloblastoma" handwritten, but final dx ETMR with multilayer rosettes   | reviewed - OK with new dx                                                              |                                                                                                            | ETMR            | Embryonal tumor                                                          | tumor             | Updated via OpenPBTA subtyping                                        | None documented        | ETMR, C19MC-altered |
| BS_P39SQPTS               | NA                  | 7316-447  | 588300     | PT_01MZ62KG               | RNA-Seq               | Pineoblastoma                                    | Embryonal tumor with multilayer rosettes | Path report PNET/pineoblastoma; "there are scattered true rosettes (Flexner-Wintersteiner)" | reviewed - OK with new dx                                                              |                                                                                                            | ETMR            | Embryonal tumor                                                          | tumor             | Updated via OpenPBTA subtyping                                        | None documented        | ETMR, C19MC-altered |
| BS_TE8QFF7T               | NA                  | 7316-447  | 588012     | PT_01MZ62KG               | WGS                   | Pineoblastoma                                    | Embryonal tumor with multilayer rosettes | Path report PNET/pineoblastoma; "there are scattered true rosettes (Flexner-Wintersteiner)" | reviewed - OK with new dx                                                              |                                                                                                            | ETMR            | Embryonal tumor                                                          | tumor             | Updated via OpenPBTA subtyping                                        | None documented        | ETMR, C19MC-altered |
| BS_N6N147BY               | NA                  | 7316-238  | 232096     | PT_X648RVMK               | RNA-Seq               | High-grade glioma/astrocytoma (WHO grade III/IV) | Embryonal tumor with multilayer rosettes | Path report handwritten "high grade glioma"; final dx infiltrating glioneuronal neoplasm    | reviewed - OK with new dx (ETMR original tumor 7316-2975 and this one consistent)      |                                                                                                            | ETMR            | Embryonal tumor                                                          | tumor             | Updated via OpenPBTA subtyping                                        | None documented        | ETMR, C19MC-altered |
| BS_5P1TN10Z               | hemispheric         | 7316-158  | 746061     | PT_9BZETM0M               | RNA-Seq               | Supratentorial or Spinal Cord PNET               | High-grade glioma                        | Path report PNET                                                                            | reviewed - OK with new dx grade III-IV                                                 |                                                                                                            | HGAT            | Diffuse astrocytic and oligodendroglial tumor                            | tumor             | from PNET to HGG due to H3F3A mutation;Updated via OpenPBTA subtyping | None documented        | HGG, H3 G35         |
| BS_STNH7YSX               | hemispheric         | 7316-158  | 746056     | PT_9BZETM0M               | WGS                   | Supratentorial or Spinal Cord PNET               | High-grade glioma                        | Path report PNET                                                                            | reviewed - OK with new dx grade III-IV                                                 |                                                                                                            | HGAT            | Diffuse astrocytic and oligodendroglial tumor                            | tumor             | from PNET to HGG due to H3F3A mutation;Updated via OpenPBTA subtyping | None documented        | HGG, H3 G35         |
| BS_TV5B86ZD               | hemispheric         | 7316-158  | 150593     | PT_9BZETM0M               | RNA-Seq               | Supratentorial or Spinal Cord PNET               | High-grade glioma                        | Path report PNET                                                                            | reviewed - OK with new dx grade III-IV                                                 |                                                                                                            | HGAT            | Diffuse astrocytic and oligodendroglial tumor                            | tumor             | from PNET to HGG due to H3F3A mutation;Updated via OpenPBTA subtyping | None documented        | HGG, H3 G35         |

cc @baileyckelly @jaclyn-taroni 

Two notes:
1. `PT_7E3V3JFX` specimens were consistent with the original EPN dx, so pathology would call this a rare EPN, H3 K28 mutated tumor, rather than DMG.
2. `PT_AQWDQW27` specimen was consistent with meningioma, even though it has a hallmark EPN fusion, so pathology would also call this a rare meningioma with a _YAP1_ fusion.
3. Because 1 is a rare tumor (maybe first seen), the logic of searching for all H3 K28 mutations in [HGG subtyping](https://github.com/AlexsLemonade/OpenPBTA-analysis/issues/249) would convert this sample by default - how to handle this? 
4. Pathology confirmed this HGG BRAF V600E mutant tumor, `BS_H1XPVS9A` [https://cbethell.github.io/open-pbta-output/09-HGG-with-braf-clustering.nb.html#identify_sample_that_clusters_with_lgat), to be a LGAT (PXA). I updated `molecular_subtype` here based on what it would look like, but this should come through via the LGAT [subtyping](https://github.com/AlexsLemonade/OpenPBTA-analysis/issues/631) ticket. How should we add this info?

**Comment by jaclyn-taroni** [comment]
> Because 1 is a rare tumor (maybe first seen), the logic of searching for all H3 K28 mutations in HGG subtyping would convert this sample by default - how to handle this?

My inclination would be to handle these specimens in their own section of  `07-HGG-molecular-subtyping-combine-table.Rmd` and document why we're doing that.

**Comment by jaclyn-taroni** [comment]
I think this is closed by the linked issues and pull requests and the presence of [`molecular-subtyping-pathology`](https://github.com/AlexsLemonade/OpenPBTA-analysis/tree/master/analyses/molecular-subtyping-pathology).
