### ISSUE TITLE
Add cell line composition type to pbta-histologies.tsv

### ISSUE THREAD

**Issue by jharenza** [AlexsLemonade/OpenPBTA-analysis#610]
#### What data file(s) does this issue pertain to?
pbta-histologies.tsv

#### What release are you using?

V15

#### Put your question or report your issue here.
There are sometimes more than two cell lines derived from the same patient tumor. Add a `composition_type` or other column descriptor to describe the manner of growth of these lines. A = adherent, S = suspension. Below are the cell lines and their growth characteristics.

| Kids_First_Participant_ID | Kids_First_Biospecimen_ID | cell_line_composition | sample_id | aliquot_id |
|---------------------------|---------------------------|------------------|-----------|------------|
| PT_3AWKWXEV               | BS_QYPHA40N               | S                | 7316-85   | 740010     |
| PT_3AWKWXEV               | BS_59ZJWJTF               | A                | 7316-85   | 740007     |
| PT_4347ZBEX               | BS_8ZD6J47V               | S                | 7316-913  | 739932     |
| PT_4347ZBEX               | BS_M8EA6R2A               | A                | 7316-913  | 739931     |
| PT_C2D4JXS1               | BS_0RQ4P069               | A                | 7316-1746 | 739942     |
| PT_C2D4JXS1               | BS_PNYN0AYD               | S                | 7316-1746 | 739941     |
| PT_HNZNZ635               | BS_GXTFW99H               | A                | 7316-2151 | 740006     |
| PT_JNEV57VK               | BS_BWBDH9GM               | A                | 7316-3058 | 739934     |
| PT_JNEV57VK               | BS_2A162JH9               | S                | 7316-3058 | 739933     |
| PT_JSFBMK5V               | BS_40MP5BWR               | S                | 7316-1769 | 740009     |
| PT_VAJN5QP8               | BS_5GNQC2FF               | A                | 7316-2176 | 739936     |
| PT_VTM2STE3               | BS_PGK832G2               | A                | 7316-2189 | 740008     |
| PT_Y5KY6KN9               | BS_MX23ZY0Y               | S                | 7316-195  | 739938     |
| PT_Y5KY6KN9               | BS_P9JP6JFA               | A                | 7316-195  | 739937     |
| PT_Z4PJA6KT               | BS_DRY58DTF               | A                | 7316-1763 | 739940     |
| PT_Z4PJA6KT               | BS_E60JZ9Z3               | S                | 7316-1763 | 739939     |
| PT_3AWKWXEV               | BS_CZRA594T               | A                | 7316-85   | 739824     |
| PT_3AWKWXEV               | BS_ERAWW3H7               | S                | 7316-85   | 739827     |
| PT_4347ZBEX               | BS_FJEZ3ASV               | S                | 7316-913  | 739829     |
| PT_4347ZBEX               | BS_PKZ1HWNB               | A                | 7316-913  | 739828     |
| PT_C2D4JXS1               | BS_68TZMZH1               | A                | 7316-1746 | 739839     |
| PT_C2D4JXS1               | BS_AFBPM6CN               | S                | 7316-1746 | 739838     |
| PT_HNZNZ635               | BS_TX8C5VAJ               | A                | 7316-2151 | 739823     |
| PT_JNEV57VK               | BS_QWM9BPDY               | A                | 7316-3058 | 739831     |
| PT_JNEV57VK               | BS_HM5GFJN8               | S                | 7316-3058 | 739830     |
| PT_JSFBMK5V               | BS_RXP2ZRQT               | S                | 7316-1769 | 739826     |
| PT_VAJN5QP8               | BS_M659G06J               | A                | 7316-2176 | 739833     |
| PT_VTM2STE3               | BS_ERFMPQN3               | A                | 7316-2189 | 739825     |
| PT_Y5KY6KN9               | BS_XMP9XNR9               | A                | 7316-195  | 739834     |
| PT_Y5KY6KN9               | BS_JGKRN7NA               | S                | 7316-195  | 739835     |
| PT_Z4PJA6KT               | BS_853PNV7P               | A                | 7316-1763 | 739837     |
| PT_Z4PJA6KT               | BS_TF5TTEXH               | S                | 7316-1763 | 739836     |

cc  @baileyckelly @chris-s-friedman @yuankunzhu @allisonheath @mkoptyra

**Comment by baileyckelly** [comment]
We are starting on this.

**Comment by jaclyn-taroni** [comment]
I was working on #509 yesterday and ran into some difficulties that I think are related to this issue. Let's take a look at the cell lines with the `sample_id` `7316-195` as an example (full table [here](https://github.com/jaclyn-taroni/OpenPBTA-analysis/blob/f37ea59562d5639546af24184413ff2068f7df4e/analyses/molecular-subtyping-HGG/results/HGG_molecular_subtype.tsv)):

Kids_First_Participant_ID | sample_id | Kids_First_Biospecimen_ID_DNA | Kids_First_Biospecimen_ID_RNA | composition | molecular_subtype
-- | -- | -- | -- | -- | --
PT_Y5KY6KN9 | 7316-195 | BS_JGKRN7NA | BS_MX23ZY0Y | Derived Cell Line | DMG, H3 K28
PT_Y5KY6KN9 | 7316-195 | BS_JGKRN7NA | BS_P9JP6JFA | Derived Cell Line | DMG, H3 K28
PT_Y5KY6KN9 | 7316-195 | BS_XMP9XNR9 | BS_MX23ZY0Y | Derived Cell Line | DMG, H3 K28
PT_Y5KY6KN9 | 7316-195 | BS_XMP9XNR9 | BS_P9JP6JFA | Derived Cell Line | DMG, H3 K28

Using `Kids_First_Participant_ID`, `sample_id` and `composition` is insufficient to unambiguously map between RNA-seq and DNA-seq samples. Looking at the table above:

> PT_Y5KY6KN9 	BS_MX23ZY0Y 	S 	7316-195 	739938
> PT_Y5KY6KN9 	BS_P9JP6JFA 	A 	7316-195 	739937
> PT_Y5KY6KN9 	BS_XMP9XNR9 	A 	7316-195 	739834
> PT_Y5KY6KN9 	BS_JGKRN7NA 	S 	7316-195 	739835

We can not use `aliquot_id` to help us (in this particular case anyway). Is it okay to assume that the adherent cell line biospecimens that have different `experimental_strategy` but share a `Kids_First_Participant_ID` and `sample_id` are paired?

**Comment by baileyckelly** [comment]
@jaclyn-taroni Just to confirm I'm understanding correctly - Are you trying to identify the RNA/DNA cell line pairs?

**Comment by jaclyn-taroni** [comment]
Marking this as blocking #509 for now.

**Comment by mkoptyra** [comment]
@jaclyn-taroni anything else we need to help solving with this (other the including in the new release I guess)?

**Comment by jaclyn-taroni** [comment]
@mkoptyra in regards to this https://github.com/AlexsLemonade/OpenPBTA-analysis/issues/610#issuecomment-603210320 - can I assume that the adherent cell line biospecimens that have different `experimental_strategy` but share a `Kids_First_Participant_ID` and `sample_id` are paired?

Here's an example (same sample as above) - `BS_P9JP6JFA` is RNA-seq, `BS_XMP9XNR9` is DNA-seq

> PT_Y5KY6KN9 BS_P9JP6JFA A 7316-195 739937
> PT_Y5KY6KN9 BS_XMP9XNR9 A 7316-195 739834

Would it be appropriate to combine the DNA data (e.g., mutation calls) and RNA data (e.g., fusion calls) for this pair of biospecimens because they share `Kids_First_Participant_ID` and `sample_id` and are both marked as adherent?

**Comment by kgaonkar6** [comment]
I believe that matching with `Kids_First_Participant_ID`, `sample_id` and `parent_aliquot_id` (removing the .WGS and .RNA-Seq suffix) we will be able to fix this issue @jaclyn-taroni . Thoughts @mkoptyra ? 

Kids_First_Participant_ID | sample_id | parent_aliquot_id | Kids_First_Biospecimen_ID_DNA | Kids_First_Biospecimen_ID_RNA | molecular_subtype
-- | -- | -- | -- | -- | --
PT_Y5KY6KN9 | 7316-195 | 7316-195-T-202630 | BS_AYPBAHJ6 | BS_4QW2S1Q8 | DMG, H3 K28
PT_Y5KY6KN9 | 7316-195 | 7316-195-T-202952 | BS_XMP9XNR9 | BS_P9JP6JFA | DMG, H3 K28
PT_Y5KY6KN9 | 7316-195 | 7316-195-T-203029 | BS_JGKRN7NA | BS_MX23ZY0Y | DMG, H3 K28

**Comment by baileyckelly** [comment]
Yes. The Sample ID is actually our "Event ID" here. It's all the same surgical event/tumor - but different aliquots to do different things with (Cell Line, DNA, RNA, etc).  They could be different tissue chunks (different parent aliquot IDs). The parent aliquot id means different biobank tubes - but we dont necessarily know the reason the same surgical event got multiple biobank tubes (ie didnt fit in one tube or truly different regions, etc)

**Comment by jharenza** [comment]
leaving this out of the histologies file since it went into #796
