### ISSUE TITLE
Updated analysis: Fusions found in more than 4 histologies in putative oncogene fusion list

### ISSUE THREAD

**Issue by kgaonkar6** [AlexsLemonade/OpenPBTA-analysis#620]
#### What analysis module should be updated and why?
module: fusion_filtering
background:  
We had previously implemented filtering in 04-project-specific-filtering.Rmd as a last step to remove potential false calls, for example if fusion reading-frame could not be determined by the callers (Fusion_Type=="other") we removed them if the fusion is a local-rearrangement according to FusionAnnotator we removed them as potential read-throughs. 
isuue:
However in v14 and v15 we have gradually REMOVED the above filtering from putative oncogene fusions to capture some of the edge cases where a known fusion like IGH-MYC had reading-frame other , CAPZ2-MET is annotated as local-rearrangement. This removal of filtering lets us gather fusion calls known in oncogenic genes per histologies but also adds a lot of fusions which @jaclyn-taroni @jharenza and I would like to discuss here.

I've plotted some figures to help us discuss methods/conditions to filter these fusions found in more than 4 broad_histologies to tackle the issue above. (We have decided morethan 4 here because we have seen that some known fusions like  EWSR1−−FLI1 is seen is 4 different broad_histologies in our current clinical file)

plots/fusionNames can be found here:
https://github.com/d3b-center/D3b-codes/blob/fusion_v15_QC/OpenPBTA_v15_release_QC/QC_putative_onco_fusion_dustribution.pdf

#### What changes need to be made? Please provide enough detail for another participant to make the update.
In https://github.com/AlexsLemonade/OpenPBTA-analysis/blob/master/analyses/fusion_filtering/04-project-specific-filtering.Rmd we need to implement a condition to remove putative oncogene fusions if they are found in more than 4 broad_histologies. 

This will also need edits to recurrent fusion/fused genes script https://github.com/AlexsLemonade/OpenPBTA-analysis/blob/master/analyses/fusion_filtering/05-recurrent-fusions-per-histology.R . We would need to remove any filtering done here https://github.com/AlexsLemonade/OpenPBTA-analysis/blob/7963db0abf1ccbce98159c93627103ed315e1007/analyses/fusion_filtering/05-recurrent-fusions-per-histology.R#L82-L89

#### What input data should be used? Which data were used in the version being updated?
v15
pbta-fusion-starfusion.tsv.gz : aggregated starfusion calls; a column tumor_id with the samples BS ID is added to each sample files
pbta-fusion-arriba.tsv.gz : aggregated arriba calls; a column tumor_id with the samples BS ID is added to each sample files ; a column annots is added from running FusionAnnotator
pbta-gene-expression-rsem-fpkm.polya.rds : aggregated polya samples fpkm data
pbta-gene-expression-rsem-fpkm.stranded.rds : aggregated stranded fpm data

#### When do you expect the revised analysis will be completed?
1-2days

#### Who will complete the updated analysis?
@kgaonkar6

**Comment by jaclyn-taroni** [comment]
I consider this closed via #621
