### ISSUE TITLE
Proposed Analysis: Identify CNS Ewing Sarcomas

### ISSUE THREAD

**Issue by jharenza** [AlexsLemonade/OpenPBTA-analysis#623]
#### What are the scientific goals of the analysis?
- Confirm/identify all samples with Ewings Sarcoma hallmark fusions are classified as such in `integrated_diagnosis`.
- Remove `CNS EFT-CIC` from `short_histology` for these samples, as these are distinct tumors with different transcriptional regulation and fusion alterations.

#### What methods do you plan to use to accomplish the scientific goals?
**PR 1:**
1. Survey _**all**_ samples for the following fusions:
2. Create 1,0 matrix fusion summary file for ewings (add [here](https://github.com/AlexsLemonade/OpenPBTA-analysis/tree/master/analyses/fusion-summary/results))  --> `fusion_summary_ewings_foi.tsv`

**PR2**
3. Use 2. above to identify samples which should be categorized as Ewings sarcoma:
- **Ewings Sarcoma** (`integrated_diagnosis`) and `EWS` (`short_histology`)
  - Fusions are one of: _EWSR1‐FLI1_, _EWSR1‐ERG_, _EWSR1‐PATZ1_, or _FUS‐ERG_ 

#### What input data are required for this analysis?
`putative_oncogenic_fusions.tsv` 

#### How long do you expect is needed to complete the analysis? Will it be a multi-step analysis?
1-2 days

#### Who will complete the analysis (please add a GitHub handle here if relevant)?
@kgaonkar6 

#### What relevant scientific literature relates to this analysis?
[ijms-21-01818.pdf](https://github.com/AlexsLemonade/OpenPBTA-analysis/files/4314625/ijms-21-01818.pdf)
[Specht, et al, 2014
](https://www.ncbi.nlm.nih.gov/pubmed/?term=Distinct+transcriptional+signature+and+immunoprofile+of+CIC-DUX4+fusion-positive+round+cell+tumors+compared+to+EWSR1-rearranged+Ewing+sarcomas%3A+further+evidence+toward+distinct+pathologic+entities.)

**Comment by jaclyn-taroni** [comment]
Closed via #635 and #640.
