### ISSUE TITLE
Updated analysis: ependymoma subtyping lesions table update

### ISSUE THREAD

**Issue by jharenza** [AlexsLemonade/OpenPBTA-analysis#626]
#### What analysis module should be updated and why?
[ependymoma subtyping
](https://github.com/AlexsLemonade/OpenPBTA-analysis/tree/master/analyses/molecular-subtyping-EPN)
#### What changes need to be made? Please provide enough detail for another participant to make the update.
Per [this comment ](https://github.com/AlexsLemonade/OpenPBTA-analysis/issues/245?email_token=ANLQX4X7E6YAX7R3ATHPRDLQ64GJHA5CNFSM4JKY3XAKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEJQCO7Q#issuecomment-596709627) and the associated publication, we should perform a first step of pulling any sample with a `YAP1--FAM118B` or `YAP1-MAMLD1` fusion in our dataset, even if not diagnosed as ependymoma, and add those to the molecular lesions table, as these fusions have been reported to be unique to ST-EPN-YAP1 tumors.

> Although neither YAP1-MAMLD1 nor YAP1-FAM118B fusions have been reported in other types of cancer, it is considered likely that these constitute the oncogenic drivers of infant ST-EPNs based on high frequency of YAP1 fusions in this type of cancer. 

See HGG subtyping for an example of how we searched all samples for histone mutations first, then added all remaining HGGs to the table.

#### What input data should be used? Which data were used in the version being updated?
fusion_summary_embryonal_foi.tsv 

#### When do you expect the revised analysis will be completed?
1 day

#### Who will complete the updated analysis?
@tkoganti

**Comment by jharenza** [comment]
Temporary time out on this - the pathologists would like to review the one patient whose dx would change in doing this. They will do this week.

**Comment by jaclyn-taroni** [comment]
I'm going to label this as `blocked` because this is external to analyses contained within the repository.

**Comment by jharenza** [comment]
Closing this issue - from CHOP pathology after reviewing slides and pathology report, it seems like there can be very rare cases of non-EPN samples with what were considered "EPN-specific fusions", so we should not use this fusion to re-classify as EPN.

Final dx:

> Meningioma  with YAP-FAM fusion, clinical significance difficult to determine
