### ISSUE TITLE
[Discussion] What is the best way to annotate histologies in figures?

### ISSUE THREAD

**Issue by jharenza** [AlexsLemonade/OpenPBTA-analysis#627]
We have multiple columns of with histology type and molecular subtype information, and as we are creating figures, we should decide which columns to use for figures to aid in disease expert/audience interpretability.

For example, in reviewing the figures in [this comment](https://github.com/AlexsLemonade/OpenPBTA-analysis/pull/611#issuecomment-596617098), it could be confusing having medulloblastomas listed as `Embryonal tumor-SHH`,  `Embryonal tumor-WNT`,  `Embryonal tumor-Group3`,  `Embryonal tumor-Group4`. 

However, in an oncoprint, we could have tracks for `broad_histology/short_histology`, `integrated_diagnosis`, and `molecular_subtype`, which would enable the viewer to see all of the information. 

Should we try to create tracks for all figures, or create a standard of disease nomenclature for those samples which have subtypes if we want only one label for the disease on a figure?

**Comment by jharenza** [comment]
Related to #571

**Comment by jharenza** [comment]
@jaclyn-taroni @jashapiro @cansavvy 

I have created an _amateur_ (:grinning:) notebook [here](https://jharenza.github.io/openPBTA-notebooks/plot-labels.nb.html) to discuss around a histologies label concept.

Of note (and at the end of the notebook):
- The 833 remaining NAs are the normal specimens.
- The CNS EFT-CIC will become CNS Ewings sarcoma via #624 .
- We have a standalone BRAF V600E subtype, but this is HGG only, and should be labeled as such (will create an update HGG analysis ticket).
- We probably want to label LGAT as BRAF fusion, BRAF V600E, or LGG BRAF WT (I can create a subtyping ticket and I think @kgaonkar6 can work on that).

**Comment by jashapiro** [comment]
I'm going to suggest that we create a **high level histology** list that we can then use for figures. This does not need to be recorded in `pbta_histologies.tsv` but can be a separate table that we keep in the repo directly that serves as a dictionary to map `harmonized_diagnosis` and/or `broad_histology` to some subset of plotable categories. For color reasons, we should strive to have this set of categories be on the order of 10-15 labels. 

At the moment, `broad_histology` has about 24 categories, but many of these only have a few samples, so it would seem likely these could be combined with others for plotting.

I don't feel comfortable generating this list, but  perhaps @jharenza or @kgaonkar6 would like to take a crack at it? Then we could modify `figures/palettes/histology_color_palette.tsv` to use this list. In the future we can update this file separately from the histologies file without requiring a full release.

**Comment by sjspielman** [comment]
This has been taken care of with #1174 and #1176.
