### ISSUE TITLE
Figure Panel: Sample distribution across histologies plot

### ISSUE THREAD

**Issue by cbethell** [AlexsLemonade/OpenPBTA-analysis#629]
As a part of [figure 1 of the manuscript](https://github.com/AlexsLemonade/OpenPBTA-manuscript/blob/master/content/04.results.md#the-open-pediatric-brain-tumor-atlas). The Github contributions figure mentioned in ticket #572 is not yet available, I will therefore be working on the following subset of this panel: 
<img width="1003" alt="Screen Shot 2020-03-13 at 12 37 11 PM" src="https://user-images.githubusercontent.com/43576623/76641075-64f30700-6527-11ea-9570-9806fa9e036a.png">

- Two options for representing the sample distribution will be provided: a barplot and a treemap.
- Then a separate script for putting these plots in a figure panel will be created (setting this script up to accept the other figures that will later be a part of this panel as seen in the [sketch](https://github.com/AlexsLemonade/OpenPBTA-manuscript/blob/master/content/04.results.md#the-open-pediatric-brain-tumor-atlas).

**Comment by jaclyn-taroni** [comment]
Closed via #633 - if any changes should be made, I think a new ticket is appropriate (notes to self: update a figure issue template could be helpful).
