### ISSUE TITLE
Contributor friendliness: make project approachable for newcomers

### ISSUE THREAD

**Issue by jaclyn-taroni** [AlexsLemonade/OpenPBTA-analysis#64]
In service of making the project more approachable for new contributors, I'm creating this issue to discuss the use of our _issue labels_.

From the [Planned Analysis section](https://github.com/AlexsLemonade/OpenPBTA-analysis#planned-analyses) of the README:
> We have tagged a [subset of these with the label "good first issue"](https://github.com/AlexsLemonade/OpenPBTA-analysis/issues?q=is%3Aissue+is%3Aopen+label%3A%22good+first+issue%22). These "good first issues" are ones that have a limited scope, that can be done with the software already present on the Docker container, and that we expect to have few dependencies with other issues.

We do not currently have a 'fleshed-out' Docker image. As a result, I've untagged all issues that were labeled as `good first issue` for the moment. When we have the container building and ready for use, we should focus on making limited-in-scope issues and tagging those.

I've also recently added the [`blocked` label](https://github.com/AlexsLemonade/OpenPBTA-analysis/labels/blocked), which is meant to indicate that an issue is blocked by something that is external to or upstream of this project. We should apply this label to existing issues where appropriate.

Another consideration: should we use issues to indicate priority?

**Comment by jharenza** [comment]
Sounds good. We can perhaps change `assigned` to `in progress` - I quickly added that to denote people are working on it/ it has been claimed, but also don't want to give the impression that if people want to work on it they can't since it has been assigned. Thoughts? Or, we could tag the ones not being worked on with `help-needed`.

Not sure we need priority tags. It's kind of all high-priority :P

**Comment by jaclyn-taroni** [comment]
Okay, made the change from `assigned` -> `in progress` and added a description: https://github.com/AlexsLemonade/OpenPBTA-analysis/labels

What do you think?

**Comment by jharenza** [comment]
Looks good!

**Comment by jaclyn-taroni** [comment]
I am going to close this. I think once we've started to wrap up the active analysis phase and the Docker image is relatively mature, it does make sense to use the `good first issue` in the way that it was originally (but not currently) described in the README.
