### ISSUE TITLE
Figure Panel: Oncoprint Landscape

### ISSUE THREAD

**Issue by cbethell** [AlexsLemonade/OpenPBTA-analysis#641]
As depicted in the sketch of [the landscape of genomic alterations figure in the manuscript](https://github.com/AlexsLemonade/OpenPBTA-manuscript/blob/master/content/04.results.md#landscape-of-genomic-alterations), the oncoprint figure found in `analyses/oncoprint-landscape/plots` should be updated and made publication ready. (Related to: #571)

Updating/making this figure publication ready will consist of:
-  Incorporating the list of genes in the `gene_disease_top50.tsv` generated and saved in the `results` directory of `analyses/interaction-plots` to filter to genes with mutations of interest interest that should be represented on the oncoprint
- Incorporating a list of CNA genes that should be represented on the oncoprint (after PR #617 is merged, lists of the "most focal unit" generated (WIP PR #485) and recurrent copy number alterations determined (#488)
- Updating the script to use the most recent consensus files where applicable (consensus CN files)
- Updating the script to use the color palettes generated in PR #510
- Creating a separate script for putting the oncoprint in a figure panel

I plan to work on this sometime this sprint.

**Comment by jaclyn-taroni** [comment]
I'm going to call this closed by #666 and subsumed by #706.
