### ISSUE TITLE
Proposed Analysis: Survival plots HGG subtypes

### ISSUE THREAD

**Issue by kgaonkar6** [AlexsLemonade/OpenPBTA-analysis#648]
#### What are the scientific goals of the analysis?
As per @jharenza suggestions:
Identify the difference in survival 
- between molecular subtypes. 
- between samples with fusions (recurrent/known fusion which might be included in molecular subtypes like in EPN with RELA and YAP fusions but in high grade glioma we find REV3L-FYN and recurrent MET fusions these can be explored as well) . 
- between presence and absence of fusions in subgroups (I'm just thinking aloud should this also include presence and absence of SV changes? )
I've also just realized a lot of this was discussed as part of #18 :D 

#### What input data are required for this analysis?
method:
https://github.com/AlexsLemonade/OpenPBTA-analysis/blob/master/analyses/survival-analysis/util/survival_models.R by @cansavvy 
file selection:
initial tumor samples (if multiple choose randomly) for Overall survival plots 
files: 
pbta-histologies.tsv for molecular-subtype information 
fusion-summary files for known/recurrent fusions
pbta-fusion-putative-oncogene.tsv for fusion presence and absence

#### How long do you expect is needed to complete the analysis? Will it be a multi-step analysis?
1 week
Yes it is a multi-step analysis
1 ) Subset and format clinical data to get molecular subgroups, fusion file for presence-absence
2 ) Run survival code for each subgroup 
 
#### Who will complete the analysis (please add a GitHub handle here if relevant)?
I can work on this using @cansavvy notebook for survival 

#### What relevant scientific literature relates to this analysis?
[DIPG subgroups](https://user-images.githubusercontent.com/34580719/77652488-aaaac900-6f44-11ea-8385-b4d8b0e7202f.png)
[ more glioma survival plots](https://www.cell.com/cms/10.1016/j.ccell.2017.08.017/attachment/3551e2c1-9f69-450c-bda7-040543dcfc9b/mmc1)

**Comment by jaclyn-taroni** [comment]
@kgaonkar6 I think we should pick one of these areas that is the most straightforward to implement so we can kick the tires of `survival-analysis`. HGG subtypes might be a good starting point because, based on your comment, it seems like we can compare our results to previous literature. What do you think?

**Comment by kgaonkar6** [comment]
Sounds good to me! 
Yeah I think KM plots for HGG/DIPG subtypes could be compared to plots from https://www.cell.com/cancer-cell/fulltext/S1535-6108(17)30362-8

**Comment by sjspielman** [comment]
Note for survival analysis: `NA` as upper CI bound is not uncommon in skewed analyses like some of ours, and in fact the `NA` really means `Inf`. Not ideal, but so it is. https://github.com/AlexsLemonade/OpenPBTA-analysis/pull/674#issuecomment-638233796

**Comment by jaclyn-taroni** [comment]
I believe this was closed via #674
