### ISSUE TITLE
Updated analysis: add CNV alterations to evaluate tp53, nf1 classifier  

### ISSUE THREAD

**Issue by kgaonkar6** [AlexsLemonade/OpenPBTA-analysis#653]
#### What analysis module should be updated and why?
Tp53 and nf1 classifier by Greg Way was used to get TP53 and NF1 inactivation scores 
https://github.com/AlexsLemonade/OpenPBTA-analysis/issues/165
As you might know we only used SNVs to get tp53/nf1 altered status for evaluating the classifier results, should we add CNV calls as well to identify tp53/nf1 deletion inactivation status of samples as per https://github.com/AlexsLemonade/OpenPBTA-analysis/issues/165#issuecomment-572823015 ?

#### What changes need to be made? Please provide enough detail for another participant to 
extend https://github.com/AlexsLemonade/OpenPBTA-analysis/blob/master/analyses/tp53_nf1_score/00-tp53-nf1-alterations.R to include CNV deletion (amplification as well?) calls to analyses/tp53_nf1_score/results/TP53_NF1_snv_alteration.tsv which will then be used to evaluate the classifier results https://github.com/AlexsLemonade/OpenPBTA-analysis/blob/master/analyses/tp53_nf1_score/02-evaluate-classifier.py.

#### What input data should be used? Which data were used in the version being updated?
data/consensus_seg_annotated_cn_autosomes.tsv.gz maybe ?

#### When do you expect the revised analysis will be completed?
1 week

#### Who will complete the updated analysis?
@kgaonkar6

**Comment by kgaonkar6** [comment]
Hi @jaclyn-taroni ! To gather the copy number alterations I’m using consensus_seg_annotated_cn_autosomes.tsv.gz  since it looks like is being used for certain subtyping analysis and is also annotated with gene_symbol. When I look at the status column there's loss, gain and amp 
`cnvConsesus$status %>% unique()`
`[1] “loss”          “gain”          “amplification”`
I used the all "loss" data in the evaluation step and it seems it's not a good match to evaluate looking at the ROC curve for stranded data here: 
![stranded_TP53](https://user-images.githubusercontent.com/34580719/78585076-3c4ced00-7807-11ea-9dff-03d2131e572f.png)
![stranded_NF1](https://user-images.githubusercontent.com/34580719/78585534-0825fc00-7808-11ea-8adf-04284a63c1b4.png)

I went back to the discussion https://github.com/AlexsLemonade/OpenPBTA-analysis/pull/385#issuecomment-572673315 which mentions using only deep deletions. So should I be using a different file or should I probably apply a logic using the copy_number and ploidy column to get deep deletion alterations for NF1 and TP53

**Comment by jaclyn-taroni** [comment]
@kgaonkar6 I can think about this a bit more but my knee-jerk reaction is to look at instances where copy number = 0

**Comment by kgaonkar6** [comment]
> @kgaonkar6 I can think about this a bit more but my knee-jerk reaction is to look at instances where copy number = 0

I did look at that, there was only 1 entry for copy number==0
`cnvConsesus[which(cnvConsesus$copy_number == 0 & cnvConsesus$gene_symbol  %in% c("TP53","NF1")),]`
`1:    BS_ZV21J6YW   loss           0      2 ENSG00000141510        TP53  17p13.1`

**Comment by jaclyn-taroni** [comment]
@kgaonkar6 my understanding of what's happening to get the gene symbols in that file is that we're just looking at _any overlap_ between a segment and exons from a particular gene (you can take a look at the function that does the work [here](https://github.com/AlexsLemonade/OpenPBTA-analysis/blob/203319b32a8893345c071f6275ee90e4909f168c/analyses/focal-cn-file-preparation/04-prepare-cn-file.R#L61); it uses [mergeByOverlaps](http://web.mit.edu/~r/current/arch/i386_linux26/lib/R/library/IRanges/html/findOverlaps-methods.html)). So I might expect that there are a lot of results that get "let in" that don't have any consequences that we'd see at the transcriptomic level. 

There are some results in [this document](https://github.com/AlexsLemonade/OpenPBTA-analysis/blob/203319b32a8893345c071f6275ee90e4909f168c/analyses/focal-cn-file-preparation/display-plots.md) that support that idea. (That document is looking at the impact of CNA in a gene on its expression level, which I suspect depends on things like how highly a gene is expressed in general, etc.)

**Comment by kgaonkar6** [comment]
Should I look into maybe bs_ids which overlap between cnvConcensus and manta then? 

I got 8 BS_Ids when I checked manta  for TP53 deletion
`manta_bs_ids_tp53<-manta %>% filter(grepl("[/]TP53[$|/]",manta$Gene.name) & SV.type=="DEL" & FILTER=="PASS") %>% select(Kids.First.Biospecimen.ID.Tumor) %>% unique()`

overlapping with cnvConcensus I get:
cnvConsesus %>% filter(biospecimen_id %in% manta_bs_ids_tp53$Kids.First.Biospecimen.ID.Tumor & gene_symbol=="TP53")
|  biospecimen_id |status| copy_number| ploidy     |    ensembl | gene_symbol|  cytoband
|--- |--- |---|---| ---| ---| ---
BS_3NX3RBCX |  loss   |        1  |   2 | ENSG00000141510    |    TP53 | 17p13.1
BS_79SYEHY3  | loss    |      2    | 4 | ENSG00000141510      |  TP53  | 17p13.1
BS_96S0VQBN |  loss   |        2  |  4 | ENSG00000141510      |  TP53  | 17p13.1
BS_EJV0N3BX  | loss    |       1    | 2 | ENSG00000141510       | TP53  | 17p13.1
BS_H8NWA41N |  loss   |        2  |   3 | ENSG00000141510      |  TP53  | 17p13.1

**Comment by jaclyn-taroni** [comment]
The consensus SEG file (`pbta-cnv-consensus.seg.gz`) that is used to generate `consensus_seg_annotated_cn_autosomes.tsv.gz` takes Manta calls into account but doesn't take ploidy into account in the same way as `focal-cn-file-preparation` (where `consensus_seg_annotated_cn_autosomes.tsv.gz` is generated). A bit more background:

* https://github.com/AlexsLemonade/OpenPBTA-analysis/tree/203319b32a8893345c071f6275ee90e4909f168c/analyses/copy_number_consensus_call#methods
* https://github.com/AlexsLemonade/OpenPBTA-manuscript/pull/93
* https://alexslemonade.github.io/OpenPBTA-analysis/analyses/focal-cn-file-preparation/02-add-ploidy-consensus.nb.html
* And the `04-prepare-cn-file.R` part of this: https://github.com/AlexsLemonade/OpenPBTA-analysis/tree/203319b32a8893345c071f6275ee90e4909f168c/analyses/focal-cn-file-preparation#scripts-and-notebooks

How are you handling the fact that copy neutral segments are not in `consensus_seg_annotated_cn_autosomes.tsv.gz`? That has been a point of friction for other analyses.

**Comment by kgaonkar6** [comment]
Thanks for the background, I'll read up.. that's helpful!  
> How are you handling the fact that copy neutral segments are not in `consensus_seg_annotated_cn_autosomes.tsv.gz`? That has been a point of friction for other analyses.

Good point to discuss I think I'll just put in a PR with what I have for now . 
Right now if I don't find a TP53 loss I have added it to the "No_TP53_NF1_alt" condition like in https://github.com/AlexsLemonade/OpenPBTA-analysis/blob/203319b32a8893345c071f6275ee90e4909f168c/analyses/tp53_nf1_score/00-tp53-nf1-alterations.R#L94

**Comment by jaclyn-taroni** [comment]
Filing a PR so we can take a look sounds good, thanks!

**Comment by kgaonkar6** [comment]
subsumed by #837 where we discussed CNV filter and TP53 domain region of overlap
