### ISSUE TITLE
Updated analysis: Cleaning BRAF fusions for LGAT subtyping 

### ISSUE THREAD

**Issue by kgaonkar6** [AlexsLemonade/OpenPBTA-analysis#665]
#### What analysis module should be updated and why?
**molecular-subtyping-LGAT**
In the LGAT subset we see known KIAA1549--BRAF fusion and some other BRAF fusions as you can see in FusionName column here:
https://github.com/AlexsLemonade/OpenPBTA-analysis/blob/master/analyses/molecular-subtyping-LGAT/results/lgat_cleaned_all_table.tsv

So @jaclyn-taroni  and I want to discuss here if **any** BRAF fusions found in LGAT sample should be included in molecular_subtype== "LGG,BRAF fusion" or would the fused BRAF need to satisfy other conditions like kinase domain retention and overexpression as mentioned in for the oncogenic KIAA1549--BRAF fusion
https://www.frontiersin.org/articles/10.3389/fonc.2015.00054/full 
"The constitutive kinase activity of KIAA1549:BRAF fusion oncoprotein is due to the loss of the BRAF N-terminal auto-inhibitory domain which usually regulates BRAF activity (15, 28). Lin et al. demonstrated that the KIAA1549:BRAF fusion is transcribed from the KIAA1549 gene promoter and thus is expressed at higher levels than wild-type BRAF, so the fusion oncoprotein is not only constitutively active but also over expressed giving two mechanisms of aberrant activity (27)."

A example of other BRAF fusion can be seen in this sample: has no BRAF V600E mutation but does have two fusions (BRAF--RNF130_, RNF130--BRAF):
```
BS_9X9E86DY	No	PT_20ZM6THA	7316-3629	BS_E94QRJDW	BRAF--RNF130, RNF130--BRAF
```

Here I've plotted the breakpoints for BRAF gene in each fusion to show the differences in kinase domain retention status per fusion
RNF130--BRAF is a cosmic fusion https://cancer.sanger.ac.uk/cosmic/fusion/overview?fid=199318&gid=296121. In-frame fusion and also retains the kinase domain because the breakpoint is before the kinase domain
![image](https://user-images.githubusercontent.com/34580719/78035805-95b0aa00-7337-11ea-8d49-264e4eb92022.png)
BRAF--RNF130 is the reciprocal frame-shift fusion that doesn't fully retain the kinase domain as you can see the breakpoint is within the kinase domain
![image](https://user-images.githubusercontent.com/34580719/78036026-d3adce00-7337-11ea-8715-08805109f274.png)

#### What changes need to be made? Please provide enough detail for another participant to make the update.
Should we add a notebook/script before 01-make-lgat-final-table.Rmd 
- that annotates each Fusion found in a sample with kinase domain retention status and overexpression status of BRAF in the fusion
- filters for the following condition:
          a) kinase domain retention == "Yes"
          b) Fusion_Type=="in-frame" ( so that if kinase domain is retained its coded in the fusion transcript?)
          c) overexpression of BRAF == "Yes"
- and outputfile will have column names compatible with pbta-fusion-putative-oncogenic.tsv to be able to run through 01-make-lgat-final-table.Rmd successfully.

#### What input data should be used? Which data were used in the version being updated?
- pbta-fusion-putative-oncogenic.tsv from v16
- external data from pfam and biomart will need to be added and modified to get domain level information and coordinates

#### When do you expect the revised analysis will be completed?
1 week

#### Who will complete the updated analysis?
@kgaonkar6

**Comment by kgaonkar6** [comment]
I looked into the zscores  using this function `source(file.path("..","focal-cn-file-preparation","util", "rna-expression-functions.R"))` for expression scores for all BRAF fusion in lgat samples:
![image](https://user-images.githubusercontent.com/34580719/78948697-3705d180-7a97-11ea-8ac9-6853756ff7bf.png)

Doesn't look like the overexpression of BRAF is consistent across the BRAF fusions.

**Comment by jainpayal022** [comment]
Can help address by Friday

**Comment by kgaonkar6** [comment]
https://www-sciencedirect-com.proxy.library.upenn.edu/science/article/pii/S1535610820301513?via%3Dihub
they've looked into KIAA1549--BRAF fusion with different breakpoints ( exon16 -> exon9) ,(exon15 -> exon10) and (exon15 -> exon9) and briefly discussed that non-KIAA1549 BRAF fusions occurred exclusively in adolescents with no progression events

>Because of the large number of tumors, we could sub-stratify the BRAF fusions into subgroups based on their breakpoints (Figure S4A). The most common KIAA1549-BRAF fusion involved exon 16 in KIAA1549 and exon 9 in BRAF (16:09). Like all KIAA1549-BRAF fusions, 16:09 was significantly enriched in pilocytic astrocytoma (n = 73/83, 88%, p < 0.0001, Fisher's exact test) and in cerebellar tumors (n = 60/83, 72%, p < 0.0001, Fisher's exact test) (Figures S4B and S4C). Interestingly, the only KIAA1549-BRAF fusion seen in hemispheric tumors was 15:09 (Figure S4B). 15:09 was also the primary fusion seen in tumors with extensive dissemination (n = 5, 83%, p < 0.0001, Fisher's exact test). 15:09 fusions were associated with a worse PFS (p = 0.0003, log rank test, Figure S4D), with a 5-year PFS of 59% as compared with 77%–100% for other fusion subtypes. BRAF fusions not involving KIAA1549 occurred exclusively in adolescents with no progression events (median follow-up = 3.7 years), while 15:11 was only observed in two infants who rapidly experienced tumor progression and died (Figures S4D and S4E). Identifying the specific fusion breakpoints of KIAA1549-BRAF will be important to properly ascertain their propensity for certain clinical features and impact on outcome.

**Comment by jharenza** [comment]
@kgaonkar6 let's revisit this with #790, in which I am adding additional BRAF fusions as another subtype. I think the point you raise about the kinase domain retention is a great one, and we should consider this.

**Comment by jharenza** [comment]
closing this as #790 will cover this
