### ISSUE TITLE
Updated analysis: Include EPN subtyping in `molecular-subtyping-pathology`

### ISSUE THREAD

**Issue by jaclyn-taroni** [AlexsLemonade/OpenPBTA-analysis#667]
#### What analysis module should be updated and why?

`molecular-subtyping-pathology` was established before the completion of #245 (Related PR: #555), but ultimately it will need to be included.

#### What changes need to be made? Please provide enough detail for another participant to make the update.

1. Add EPN table to the compilation of all the molecular subtyping/classification results https://github.com/AlexsLemonade/OpenPBTA-analysis/blob/65180c183c0828dd093dd99a47b689ff3a76999f/analyses/molecular-subtyping-pathology/01-compile-subtyping-results.Rmd#L190

2. Context is https://github.com/AlexsLemonade/OpenPBTA-analysis/pull/663#discussion_r401712388. There was an EPN sample that was reclassified via the defining lesion criteria in `molecular-subtyping-HGG`, but this sample should remain EPN based on pathology feedback. So we should check this sample for the features outlined in #245. 

Relevant section starts here:
https://github.com/AlexsLemonade/OpenPBTA-analysis/blob/65180c183c0828dd093dd99a47b689ff3a76999f/analyses/molecular-subtyping-pathology/02-incorporate-pathology-feedback.Rmd#L124

#### What input data should be used? Which data were used in the version being updated?

Final table with subtyping labels I anticipate will be located in `analyses/molecular-subtyping-EPN/results` - this likely relies on the current data release (`release-v15-20200228`).

#### When do you expect the revised analysis will be completed?

Blocked by #245/#555 - but ~1 day after that

#### Who will complete the updated analysis?

@jaclyn-taroni

**Comment by jharenza** [comment]
>So we should check this sample for the features outlined in #245.

It looks like this sample was somehow missed in the selection for the EPN module, so I think this should be added back there first.

**Comment by jharenza** [comment]
added with #854
