### ISSUE TITLE
Updated analysis: TCGA TMB BED files update v16

### ISSUE THREAD

**Issue by cansavvy** [AlexsLemonade/OpenPBTA-analysis#668]
### What analysis module should be updated and why?
`snv-callers`
TCGA TMB calculations need to be updated now that we have a new set of BED files that more accurately show the target regions. 

#### What changes need to be made? Please provide enough detail for another participant to make the update.

Now that BED files are not just assigned by WGS or WXS sample designations, we need to make a way to supply a BED files to sample ID key so we know which sample's TMB should be calculated with which target region BED file.

#### What input data should be used? Which data were used in the version being updated?
v16 data

#### When do you expect the revised analysis will be completed?
This week.

#### Who will complete the updated analysis?
@cansavvy

**Comment by cansavvy** [comment]
I'll be working on setting this up today. I think my plan for this issue is to add an option to the [`03-calculate_tmb.R` script](https://github.com/AlexsLemonade/OpenPBTA-analysis/blob/65180c183c0828dd093dd99a47b689ff3a76999f/analyses/snv-callers/scripts/03-calculate_tmb.R#L69) and [`calculate_tmb` function](https://github.com/AlexsLemonade/OpenPBTA-analysis/blob/65180c183c0828dd093dd99a47b689ff3a76999f/analyses/snv-callers/util/tmb_functions.R#L94) that allows you to pass in a column of the BED file names that correspond to each biospecimen IDs. 

Currently, its set up to use BED files based on whether a sample is WGS or WXS. The question is do I switch everything to the column strategy?  Or do I add the "provide a column strategy" while maintaining the specify BED files for all WGS and all WXS strategy?

**Comment by jashapiro** [comment]
I would switch to providing a table of sample/bed pairs. I don't think maintaining four different options is worthwhile.

**Comment by jaclyn-taroni** [comment]
Just wanted to note that some of the changes in https://github.com/AlexsLemonade/OpenPBTA-analysis/pull/670/commits/c9675fda5b9e638b117dbd308383cf8e163fc761 and https://github.com/AlexsLemonade/OpenPBTA-analysis/pull/670/commits/94e6e255c0a33715c8583d85f036b7db87bff8ac need to be undone when this gets addressed.

**Comment by cansavvy** [comment]
The BED files for TCGA have been updated and the analysis re-run completely. The TMB values for TCGA are slightly higher, and now we have some outliers show up, but it's still not able to overcome the inherent WGS vs WXS difference we have confounding our PBTA vs TCGA comparison. 
Updated: 
![tmb-cdf-pbta-tcga](https://user-images.githubusercontent.com/23458084/79135953-2a76c700-7d7e-11ea-8a31-7965169e31ef.png)

Old version for comparison: 
![old-tmb-cdf-pbta-tcga](https://user-images.githubusercontent.com/23458084/79135980-32cf0200-7d7e-11ea-95bc-05c33a6ab939.png)

**Comment by jaclyn-taroni** [comment]
@cansavvy was this closed by #671?

**Comment by cansavvy** [comment]
Yes.
