### ISSUE TITLE
`d3r` causing CI failures

### ISSUE THREAD

**Issue by sjspielman** [AlexsLemonade/OpenPBTA-analysis#684]
#### What analysis module should be updated and why?

The analysis module `sample-distribution-analysis` uses CRAN package `d3r` to create sunburst plots. Recently CI builds are failing related to `d3r` deprecated usage of `tidyselect::one_of`. This issue will require more sleuthing, but for now PR #683 does a temporary fix of commenting out the package.

**Comment by jashapiro** [comment]
Fixed by #689. Closing.
