### ISSUE TITLE
Planned Analysis: Single-Sample Enrichment Analysis and visualization of pathway scores 

### ISSUE THREAD

**Issue by PichaiRaman** [AlexsLemonade/OpenPBTA-analysis#7]
The idea here is calculate pathway scores on each of the samples and summarize via a visualization to demonstrate associations of different pathways with phenotypic or genetic elements. This visualization be in the form of a clustered heatmap and should include some sort of statistical analysis when identifying "strong" associations.

**Comment by jharenza** [comment]
As a comment on this, it may be noisy using ssGSEA (we just had the issue with the PPTC paper), so instead, you can use molecular subytpes for this analysis.

**Comment by PichaiRaman** [comment]
@jharenza what if we focused on the Hallmark sets?

**Comment by jharenza** [comment]
Can't hurt to try! @jainpayal022 is interested in seeing some of this for some PNOC samples, so if we can get some signal here, that would be awesome.

**Comment by jharenza** [comment]
@jpfeil let me know that he is 

> developing a Bayesian nonparametric approach for subtyping within homogenous disease groups. I think this would complement the GSEA analysis because the GSEA analysis will say what is different between groups and my other analysis will tell you what is differentially expressed within the groups. Here is a [link](https://github.com/jpfeil/hydra) to the source code.

**Comment by jaclyn-taroni** [comment]
@PichaiRaman laid the groundwork for this in #133, but mentioned this should be revisited with finer granularity https://github.com/AlexsLemonade/OpenPBTA-analysis/pull/133#issuecomment-538597315, e.g., molecular subtypes (#19). I am labeling this with `updated analysis`. The analysis can be found at [`analyses/ssgsea-hallmark/`](https://github.com/AlexsLemonade/OpenPBTA-analysis/tree/master/analyses/ssgsea-hallmark).

**Comment by sjspielman** [comment]
My plan is to make eight heatmaps, combinatorial of:
1. Either mean GSVA across `short_histology` or  `disease_type_new` 
2. GSVA calculated from either polyA or stranded libraries. The polyA plots are sure to be very boring. 
3. All GSVA score comparisons or just those that are significant across pathways

This will all be wrapped into a function for users to customize should more heatmaps be desired. 
Any other variations people want to see at this stage and/or visualization preferences (i.e. pathway on X or Y axis, show both/neither/one of col/row dendrograms, color palette..)?

**Comment by jaclyn-taroni** [comment]
Closing all planned analysis tickets in favor of opening new proposed analysis/updated analysis tickets as needed.
