### ISSUE TITLE
Proposed Analysis : Investigate top tp53_nf1_classifier scoring samples without TP53 alterations

### ISSUE THREAD

**Issue by kgaonkar6** [AlexsLemonade/OpenPBTA-analysis#713]
#### What are the scientific goals of the analysis?
Investigate top tp53_nf1_classifier scoring samples without TP53 alterations ("false-positives") to see if they fall into certain tumor types, have certain mutations, or have other evidence of TP53 loss. As per @cgreene's  [comment](https://github.com/AlexsLemonade/OpenPBTA-analysis/pull/673#issuecomment-635058769)

#### What methods do you plan to use to accomplish the scientific goals?

- Use top scoring samples (tp53_score) and tp53_status==0 to find the sample set
- plot broad_histology distribution
- plot other alterations (need a genelist ? look into CNV data ?)

#### What input data are required for this analysis?
pbta-snv-consensus-mutation.maf.tsv.gz
pbta-gene-expression-rsem-fpkm-collapsed.stranded.rds
pbta-gene-expression-rsem-fpkm-collapsed.polya.rds
(maybe also ? ) consensus_seg_annotated_cn_autosomes.tsv.gz

#### How long do you expect is needed to complete the analysis? Will it be a multi-step analysis?
2 days

#### Who will complete the analysis (please add a GitHub handle here if relevant)?
@kgaonkar6

**Comment by jharenza** [comment]
going to close this, as step 5 of #837 will cover this
