### ISSUE TITLE
Updated analysis: molecular subtyping HGG

### ISSUE THREAD

**Issue by kgaonkar6** [AlexsLemonade/OpenPBTA-analysis#721]
#### What analysis module should be updated and why?
- I believe there is a typo here https://github.com/AlexsLemonade/OpenPBTA-analysis/blob/6c877839435e7bdc3b3a32df79c5f2692429a940/analyses/molecular-subtyping-HGG/07-HGG-molecular-subtyping-combine-table.Rmd#L514-L515 which misses adding the subtyping to associated RNAseq sample

- I also wonder if we missed out Derived Cell Line and Panel samples or was it decided to exclude these samples in the molecular subtyping analysis?

#### What changes need to be made? Please provide enough detail for another participant to make the update.
https://github.com/AlexsLemonade/OpenPBTA-analysis/blob/6c877839435e7bdc3b3a32df79c5f2692429a940/analyses/molecular-subtyping-HGG/07-HGG-molecular-subtyping-combine-table.Rmd#L514-L515 should be edited to:

```
select(Kids_First_Participant_ID, sample_id,
         Kids_First_Biospecimen_ID_DNA, Kids_First_Biospecimen_ID_RNA)
```

#### What input data should be used? Which data were used in the version being updated?
pbta-snv-consensus-mutation.maf.tsv.gz
analyses/focal-cn-preparation/results/cnvkit_annotated_cn_autosomes.tsv.gz
pbta-fusion-putative-oncogenic.tsv
pbta-cnv-consensus-gistic.zip
pbta-gene-expression-rsem-fpkm-collapsed.stranded.rds
pbta-gene-expression-rsem-fpkm-collapsed.polya.rds

**Comment by kgaonkar6** [comment]
@jaclyn-taroni I also noticed that HGAT Derived Cell Lines are not being molecular subtyped does that need to be updated?

**Comment by jaclyn-taroni** [comment]
That's tracked in #509 and may be blocked by #610. There's no answer to my outstanding question about using the adherent/suspension label to distinguish between "duplicates" https://github.com/AlexsLemonade/OpenPBTA-analysis/issues/610#issuecomment-605951267.

**Comment by kgaonkar6** [comment]
thanks for the links , I was under the impression matching Kids_First_Participant_ID and sample_id  was enough for cell-lines as well. I can check and get back to you.

**Comment by kgaonkar6** [comment]
Reposting here from #610 

Matching by Kids_First_Participant_ID, sample_id and parent_aliquot_id (For PNOC003 samples we will have to remove the .WGS and .RNA-Seq suffix) to fix the issue: 
Kids_First_Participant_ID | sample_id | parent_aliquot_id | Kids_First_Biospecimen_ID_DNA | Kids_First_Biospecimen_ID_RNA | molecular_subtype
-- | -- | -- | -- | -- | --
PT_Y5KY6KN9 | 7316-195 | 7316-195-T-202630 | BS_AYPBAHJ6 | BS_4QW2S1Q8 | DMG, H3 K28
PT_Y5KY6KN9 | 7316-195 | 7316-195-T-202952 | BS_XMP9XNR9 | BS_P9JP6JFA | DMG, H3 K28
PT_Y5KY6KN9 | 7316-195 | 7316-195-T-203029 | BS_JGKRN7NA | BS_MX23ZY0Y | DMG, H3 K28
