### ISSUE TITLE
Updated analysis: filter to only non-synonymous mutations for TMB

### ISSUE THREAD

**Issue by jashapiro** [AlexsLemonade/OpenPBTA-analysis#726]
#### What analysis module should be updated and why?

`snv-callers`, specifically   
https://github.com/AlexsLemonade/OpenPBTA-analysis/blob/master/analyses/snv-callers/scripts/03-calculate_tmb.R   
and   
https://github.com/AlexsLemonade/OpenPBTA-analysis/blob/master/analyses/snv-callers/util/tmb_functions.R

#### What changes need to be made? Please provide enough detail for another participant to make the update.

Currently, the TMB we are using for comparisons includes *all* mutations in coding regions (with the caveat that there currently a bug as described in #724). To better conform with emerging standards, as implemented in #725, we should update our TMB calculations to use only the following *non-synonymous* changes: 
`Missense_Mutation`
`In_Frame_Del`
`Nonsense_Mutation`
`In_Frame_Ins`
`Frame_Shift_Del`
`Frame_Shift_Ins`

One note, is that this list of non-synonymous mutation types is slightly shorter than the one used in MAFtools, and implemented here: https://github.com/AlexsLemonade/OpenPBTA-analysis/blob/5b38033f25b64654b7a663b1b8c06398205a973c/analyses/interaction-plots/scripts/02-process_mutations.R#L263-L274

We should probably standardize these two.

This change can be implemented by adding a `dplyr::filter()` step here: https://github.com/AlexsLemonade/OpenPBTA-analysis/blob/5b38033f25b64654b7a663b1b8c06398205a973c/analyses/snv-callers/util/tmb_functions.R#L133
It is likely that we will want to make this optional in the enclosing function.

#### What input data should be used? Which data were used in the version being updated?

Input data is the same as previously.

#### When do you expect the revised analysis will be completed?

The actual changes are small and should be quick. Downstream consequences may take longer to sort out.

#### Who will complete the updated analysis?

TBD; could be implemented alongside the changes to fix #724, as both will require updating of downstream analyses, and we may not want to do that more than once!

**Comment by cansavvy** [comment]
Now that #728 and #739 have been merged, I think this can be closed.
