### ISSUE TITLE
Exploratory Side Analysis: `Variant_Classification` breakdown

### ISSUE THREAD

**Issue by cansavvy** [AlexsLemonade/OpenPBTA-analysis#729]
#### What are the scientific goals of the analysis?
There's a few questions we want to explore in regards to the `Variant_Classification` breakdowns. 

1) How different are the synonymous vs nonsynonymous mutation counts? 

2) How often do these: `Translation_Start_Site`, `Nonstop_Mutation` or `Splice_Site` come up? (These are not included in the FoCR definitions, but are included in `maftools` definition. 

Related: https://github.com/AlexsLemonade/OpenPBTA-analysis/pull/728#discussion_r454401088
Related: https://github.com/AlexsLemonade/OpenPBTA-analysis/pull/728#pullrequestreview-448164485
Related: https://github.com/AlexsLemonade/OpenPBTA-analysis/pull/725#issuecomment-657575733

#### What methods do you plan to use to accomplish the scientific goals?
I'll plan on making two small notebooks that will probably just consist of some exploratory plots: 

1) A notebook that runs the `calculate_tmb.R` script with and without `--nonsynfilter` and creates some plots to get visualizes on how the participant data changes with filters. 

2) A second small notebook that looks at how often the discrepant mutation categories come up in PBTA and TCGA data: (`Translation_Start_Site`, `Nonstop_Mutation` or `Splice_Site`)

Both notebooks are exploratory. I will store them in their own folder in the`snv-callers` module. I think both would be retired pretty quickly since I don't see a use for these after we do a quick exploration. 

#### What input data are required for this analysis?
`snv_db_sqlite` and `tcga_snv_db.sqlite` that are based on the latest versions of snv consensus data. 

#### How long do you expect is needed to complete the analysis? Will it be a multi-step analysis?
It will be two PRs

#### Who will complete the analysis (please add a GitHub handle here if relevant)?
@cansavvy 

#### What relevant scientific literature relates to this analysis?
https://jitc.bmj.com/content/8/1/e000147#DC by the *Friends of Cancer Research TMB Harmonization Project*.

**Comment by jashapiro** [comment]
This sounds great. I would also suggest comparing results from these analyses to those that come in as part of #725

**Comment by cansavvy** [comment]
With #741 being merged, this is wrapped up.
