### ISSUE TITLE
Planned Data Release: V17

### ISSUE THREAD

**Issue by baileyckelly** [AlexsLemonade/OpenPBTA-analysis#732]
What data file(s) does this issue pertain to?
pbta-histologies.tsv

What release are you using?
V15/V16

Put your question or report your issue here.
Update histologies file to include additional information per tickets:

was planned for v16:
~#607~
~#610~
#637
#509
#608
#245
new:
#631 LGAT subtyping
#623 EWS subtyping
Who is going to work on this:
@baileyckelly

**Comment by baileyckelly** [comment]
Note: This release will ONLY contain histology file changes

**Comment by jharenza** [comment]
@baileyckelly @allisonheath - can we add an estimated timeframe for this on the ticket? Thanks :)

**Comment by jharenza** [comment]
@jaclyn-taroni, since #743 was merged, would you like us to add these results to the `pbta-histologies.tsv` file for V17 release? If yes, should we use corrected or uncorrected results?

**Comment by jaclyn-taroni** [comment]
I suppose my preference would be to use uncorrected, but that opinion is not strongly held. 

Can we get a time frame for this? There are items listed here (#610) that have not been completed. There are outstanding things like #665 that have not been addressed, which could inform the results that were initially included in #631. If we complete #667, we can use whatever is in [`molecular-subtyping-pathology`](https://github.com/AlexsLemonade/OpenPBTA-analysis/tree/9efbddf883ca0fe5805fb1cc1cc27eefcfb9ac72/analyses/molecular-subtyping-pathology), which compiles all the subtyping results, as input into the histologies file and may give us an opportunity to address #735 if that's something we'd like to do.

I also know (but I didn't find this documented - apologies if I missed something) there are changes to `broad_histology` coming that may impact the subtyping modules. 

What order should these items be addressed in? Should we include anything that's ready now and deal with the `broad_histology` change + anything outstanding that I mentioned above at the same time -> V18?

**Comment by jharenza** [comment]
#608 is blocked, so that will be added to V17

**Comment by kgaonkar6** [comment]
I ran the molecular-subtyping-pathology ( last run on July 2nd  ) module for v17 release which contains subtyping results compiled from the following modules and pathology updates:
molecular-subtyping-EWS
molecular-subtyping-HGG
molecular-subtyping-LGAT
molecular-subtyping-embryonal

**Comment by cansavvy** [comment]
I've realized the TCGA consensus and tmb files have never been added to the data release and it would be ideal to keep these tracked.

These files need to be added (they get created by the `run_caller_consensus_analysis-tcga.sh` script and printed out into snv-callers/results/consensus`.

```
tcga-snv-consensus-snv.maf.tsv.gz
tcga-snv-mutation-tmb-all.tsv
tcga-snv-mutation-tmb-coding.tsv
```
Here's a zip file that contains all three of those files: 
[tcga-consensus-09-03-2020.zip](https://github.com/AlexsLemonade/OpenPBTA-analysis/files/5169738/tcga-consensus-09-03-2020.zip)

**Comment by jharenza** [comment]
thanks @cansavvy - I just let @yuankunzhu know!

**Comment by yuankunzhu** [comment]
thanks. will include those files.

**Comment by jharenza** [comment]
@jaclyn-taroni we are shooting for a PR for Tuesday, Sep 8 for this!

**Comment by cansavvy** [comment]
[pbta-snv-mutation-tmb-coding.tsv.zip](https://github.com/AlexsLemonade/OpenPBTA-analysis/files/5211455/pbta-snv-mutation-tmb-coding.tsv.zip)

Here is the most up to date version of the tmb for pbta given the changes done with #727 and #728

**Comment by jharenza** [comment]
@cansavvy to confirm - is this replacing `pbta-snv-consensus-mutation-tmb-coding.tsv` or an addition?

**Comment by jaclyn-taroni** [comment]
This is a replacement for that file.

**Comment by jharenza** [comment]
ok thanks! i will rename to match :)
