### ISSUE TITLE
Cancer Predisposition data issues

### ISSUE THREAD

**Issue by baileyckelly** [AlexsLemonade/OpenPBTA-analysis#733]
#### What data file(s) does this issue pertain to?
histologies file -> cancer_predispositions column

#### What release are you using?
v16/v15

#### Put your question or report your issue here.
I am working on automating & refreshing this value in the histologies file. I found that the data has some issues....
Current Rules:

1. "None Documented" is a real selection value available on the input form via multi-checkbox input.
2. There is data missing where nothing was selected on the input form.  The current rule in the histologies file sets these patients' who have missing values in cancer_predisposition to "None Documented" - which may not necessarily be true.
3. There are also patients who have "None Documented" selected in addition to accurate values. So a patient could have "None Documented" and "NF-1" checkboxes selected. The current histologies file removes the "None Documented" Value in this case.

After discussing internally with our data collection team, we feel that we need to review the medical records for subjects that fall into categories 2 & 3. However, that will likely take some time and I know we are trying to get a release out.

We have a few options (open to others as well - but this is just off the top of my head).

Option 1: When I refresh the data, I can use the existing rules that the past histologies file have used which are:

- If a patient has blank values in cancer_predisposition - set to None Documented
- If a patient has multiple, conflicting cancer_predispositions selected, remove the "None Documented" value.

Option 2: I could modify the rules to the following

- If a patient has blank values in cancer_predisposition - set to "Not Reported"
- If a patient has conflicting values, leave them all.

Option 3: We could wait to release v17 until the data entry team reviews all the questionable values which would ensure that the data is 100% accurate. This, however, will take some time. (Working on timeline estimates now.)

Thoughts?

**Comment by jaclyn-taroni** [comment]
To the best of my knowledge, there is no analysis that utilizes the `cancer_predisposition` information (a quick search of the code base seems to agree with that).

**Comment by jaclyn-taroni** [comment]
👍  yep, sounds good to me, thanks!

**Comment by yuankunzhu** [comment]
> To the best of my knowledge, there is no analysis that utilizes the `cancer_predisposition` information (a quick search of the code base seems to agree with that).


Thanks, that was my impression too. I think at moment the clinical data team's share understanding is option 1 and 2 is easier and quicker to implement, while option 3 sounds right but will take longer time. So for this new release we will take option 1?

**Comment by baileyckelly** [comment]
I think we will take option 2 @yuankunzhu

**Comment by yuankunzhu** [comment]
yes, just saw that. sorry, i guess we were all replying at the same time 😅, my webpage didn't refresh in time. 

let's take option 2.

**Comment by baileyckelly** [comment]
Thanks everyone! Can i close this now? or do I close when I put the PR out with the release?

**Comment by jaclyn-taroni** [comment]
I would wait until the release PR gets merged, so we have it for reference when we review any documentation - this seems like a limitation we may want to note here: https://github.com/AlexsLemonade/OpenPBTA-analysis/blob/master/doc/data-formats.md#data-caveats and maybe in the table in this section of the manuscript: https://github.com/AlexsLemonade/OpenPBTA-manuscript/blob/master/content/03.methods.md#who-classification-of-disease-types (under `Definition` maybe?)

**Comment by jharenza** [comment]
fixed with #764
