### ISSUE TITLE
Consensus CNV calls for gene level 

### ISSUE THREAD

**Issue by kgaonkar6** [AlexsLemonade/OpenPBTA-analysis#734]
#### What release are you using?

data/release-v16-20200320/consensus_seg_annotated_cn_autosomes.tsv.gz

#### Put a link to the relevant section of the [OpenPBTA-manuscript](https://github.com/AlexsLemonade/OpenPBTA-manuscript/) here.
https://github.com/AlexsLemonade/OpenPBTA-manuscript/blob/master/content/03.methods.md#somatic-copy-number-variant-calling-wgs-samples-only

#### Put your question or report your issue here.
I was hoping for some clarification on the consensus copy number output and annotated gene level focal_cn calls. While looking at the file consensus_seg_annotated_cn_autosomes.tsv.gz I saw a lot of genes can have multiple copy number calls. For example:

```
consensus_cnv[which(consensus_cnv$biospecimen_id=="BS_8SYN7GXG"& consensus_cnv$gene_symbol== "CERS3"),]
```

biospecimen_id | status    |    copy_number | ploidy | ensembl       |  gene_symbol  | cytoband
--- | --- | --- | --- | --- | --- | ---
BS_8SYN7GXG  |  amplification      |    45    |  2 |  ENSG00000154227 | CERS3  |     15q26.3 
BS_8SYN7GXG  |  loss                  |  1      |2 | ENSG00000154227 | CERS3     |  15q26.3 

I have 2 questions: 
 - if we need to create a Gene (rows) X Sample (column) type matrix should we use the max or the minimum copy_number or would you suggest using a different file (from gistic ? I looked at TP53 copy numbers between gistic and the consensus_seg_annotated_cn_autosomes.tsv.gz and there seem to be a lot more TP53 loss in consensus_seg_annotated_cn_autosomes.tsv.gz compared to gistic )

- is it possible to have 2 copy number status per gene? I just assumed there would be 1 call per gene in a sample like in gistic output files

**Comment by jashapiro** [comment]
A gene can certainly have segments  that are duplicated as well as other segments with loss, particularly for large genes.We did not want to make a judgement about whether a small loss was more or less important than a large gain, etc., as that could be quite application specific. (Losing a small exon might be inconsequential, or have a very important effect! A duplication of an exon to a location where it is not expressed might not have any effect.) 

In cases where this comes up, there are a few different approaches you can take. One is to filter by frequency: if many samples have gains, but only one has a loss, you are probably safe to only look at the gains. In more complex situations, it probably makes sense to go back to the segment information in `pbta-cnv-consensus.seg.gz` for coordinates of the particular loss or gain and to characterize the losses and gains at the exon level, or even more discretely.

**Comment by kgaonkar6** [comment]
Makes sense thanks for the clarification. Characterizing the losses and gains at the exon does sound like a good strategy. I guess `consensus_seg_annotated_cn_autosomes.tsv.gz` is also actually doing an overlap of consensus segments with exons region right but the output only has the gene_symbol ? https://github.com/AlexsLemonade/OpenPBTA-analysis/blob/9b44bf1c186b3126b16dbe5b87756b3eae3feec2/analyses/focal-cn-file-preparation/04-prepare-cn-file.R#L55

When I captured the tx_exon regions from the `overlaps` variable in the script above it does look like your mentioned as an example that only few exon regions seem to have the loss and majority have amplifications. 

biospecimen_id | status | copy_number | ploidy | ensembl | region | tx_exon | gene_symbol | cytoband
 -- | -- | -- | -- | -- | -- | -- | -- | --
BS_8SYN7GXG | gain | 45 | 2 | ENSG00000154227 | chr15:97169357-100544234 | chr15:100400395-100402865:- | CERS3 | 15q26.3
28470 | BS_8SYN7GXG | gain | 45 | 2 | ENSG00000154227 | chr15:97169357-100544234 | chr15:100402511-100402865:- | CERS3 | 15q26.3
28471 | BS_8SYN7GXG | gain | 45 | 2 | ENSG00000154227 | chr15:97169357-100544234 | chr15:100455893-100456046:- | CERS3 | 15q26.3
28472 | BS_8SYN7GXG | gain | 45 | 2 | ENSG00000154227 | chr15:97169357-100544234 | chr15:100469378-100469484:- | CERS3 | 15q26.3
28473 | BS_8SYN7GXG | gain | 45 | 2 | ENSG00000154227 | chr15:97169357-100544234 | chr15:100472924-100473052:- | CERS3 | 15q26.3
28474 | BS_8SYN7GXG | gain | 45 | 2 | ENSG00000154227 | chr15:97169357-100544234 | chr15:100475837-100476178:- | CERS3 | 15q26.3
28475 | BS_8SYN7GXG | gain | 45 | 2 | ENSG00000154227 | chr15:97169357-100544234 | chr15:100476086-100476178:- | CERS3 | 15q26.3
28476 | BS_8SYN7GXG | gain | 45 | 2 | ENSG00000154227 | chr15:97169357-100544234 | chr15:100479428-100479478:- | CERS3 | 15q26.3
28477 | BS_8SYN7GXG | gain | 45 | 2 | ENSG00000154227 | chr15:97169357-100544234 | chr15:100479428-100479496:- | CERS3 | 15q26.3
28478 | BS_8SYN7GXG | gain | 45 | 2 | ENSG00000154227 | chr15:97169357-100544234 | chr15:100479456-100479478:- | CERS3 | 15q26.3
28479 | BS_8SYN7GXG | gain | 45 | 2 | ENSG00000154227 | chr15:97169357-100544234 | chr15:100479989-100480046:- | CERS3 | 15q26.3
28480 | BS_8SYN7GXG | gain | 45 | 2 | ENSG00000154227 | chr15:97169357-100544234 | chr15:100484550-100484668:- | CERS3 | 15q26.3
28481 | BS_8SYN7GXG | gain | 45 | 2 | ENSG00000154227 | chr15:97169357-100544234 | chr15:100490817-100490931:- | CERS3 | 15q26.3
28482 | BS_8SYN7GXG | gain | 45 | 2 | ENSG00000154227 | chr15:97169357-100544234 | chr15:100500248-100500504:- | CERS3 | 15q26.3
28483 | BS_8SYN7GXG | gain | 45 | 2 | ENSG00000154227 | chr15:97169357-100544234 | chr15:100501677-100501850:- | CERS3 | 15q26.3
28484 | BS_8SYN7GXG | gain | 45 | 2 | ENSG00000154227 | chr15:97169357-100544234 | chr15:100501804-100501850:- | CERS3 | 15q26.3
28485 | BS_8SYN7GXG | gain | 45 | 2 | ENSG00000154227 | chr15:97169357-100544234 | chr15:100503710-100503848:- | CERS3 | 15q26.3
28486 | BS_8SYN7GXG | gain | 45 | 2 | ENSG00000154227 | chr15:97169357-100544234 | chr15:100521667-100521756:- | CERS3 | 15q26.3
28487 | BS_8SYN7GXG | gain | 45 | 2 | ENSG00000154227 | chr15:97169357-100544234 | chr15:100528813-100529075:- | CERS3 | 15q26.3
28488 | BS_8SYN7GXG | gain | 45 | 2 | ENSG00000154227 | chr15:97169357-100544234 | chr15:100528813-100529265:- | CERS3 | 15q26.3
28489 | BS_8SYN7GXG | gain | 45 | 2 | ENSG00000154227 | chr15:97169357-100544234 | chr15:100544124-100544271:- | CERS3 | 15q26.3
28490 | BS_8SYN7GXG | gain | 45 | 2 | ENSG00000154227 | chr15:97169357-100544234 | chr15:100544124-100544279:- | CERS3 | 15q26.3
28491 | BS_8SYN7GXG | gain | 45 | 2 | ENSG00000154227 | chr15:97169357-100544234 | chr15:100544216-100544293:- | CERS3 | 15q26.3
28492 | BS_8SYN7GXG | gain | 45 | 2 | ENSG00000154227 | chr15:97169357-100544234 | chr15:100544216-100544413:- | CERS3 | 15q26.3
28635 | BS_8SYN7GXG | loss | 1 | 2 | ENSG00000154227 | chr15:100544652-101744010 | chr15:100544651-100544720:- | CERS3 | 15q26.3
28636 | BS_8SYN7GXG | loss | 1 | 2 | ENSG00000154227 | chr15:100544652-101744010 | chr15:100544903-100544995:- | CERS3 | 15q26.3

**Comment by kgaonkar6** [comment]
Thanks @jashapiro  , I'll close this ticket.
