### ISSUE TITLE
molecular_subtype is different for the same sample with different experimental_strategy 

### ISSUE THREAD

**Issue by yuankunzhu** [AlexsLemonade/OpenPBTA-analysis#735]
#### What data file(s) does this issue pertain to?
- pbta-histologies.tsv
- pbta-snv-consensus-mutation.maf.tsv.gz

#### What release are you using?
v16

#### Put your question or report your issue here.
looks like when comparing the `molecular_subtype` for the same sample with different `experimental_strategy`, some of them have different values. a full list with more details below:

Kids_First_Participant_ID |  cohort_participant_id | Kids_First_Biospecimen_ID | molecular_subtype | experimental_strategy | tumor_descriptor
-- | -- | -- | -- | -- | --
PT_NK8A49X5 | P-06 | BS_1MME7FBS | DMG, H3 K28 | WGS | Initial CNS   Tumor
PT_NK8A49X5 | P-06 | BS_6DT506HY | HGG, H3 wildtype | WXS | Initial CNS Tumor
PT_NK8A49X5 | P-06 | BS_AHAXPFG3 | DMG, H3 K28 | WGS | Progressive |  
PT_NK8A49X5 | P-06 | BS_GKXD33YH | DMG, H3 K28 | WXS | Progressive |  
PT_NK8A49X5 | P-06 | BS_HEJ72V3F | DMG, H3 K28 | WGS | Progressive |  
PT_QA9WJ679 | P-08 | BS_7PF3C1P7 | DMG, H3 K28 | WGS | Initial CNS Tumor
PT_QA9WJ679 | P-08 | BS_AEEKJ1QK | HGG, H3 wildtype | WXS | Initial CNS Tumor
PT_WGVEF96B | P-09 | BS_TQ0J7WJQ | DMG, H3 K28 | WGS | Initial CNS Tumor
PT_WGVEF96B | P-09 | BS_TYFD8ZMG | HGG, H3 wildtype | WXS | Initial CNS Tumor
PT_G16VK7FR | P-37 | BS_JDZX545X | HGG, H3 wildtype | WGS | Initial CNS Tumor
PT_G16VK7FR | P-37 | BS_2HDEZFTW | DMG, H3 K28 | WXS | Initial CNS Tumor

all the `molecular_subtype` differences for the cases above are driven by the histone mutation status, further investigation turns out the mutation differences was likely introdcued durning the snv consensus merging process. 

the current snv consensus processs is a result based on 3 out of 3, intersection of all callers method. 
https://github.com/AlexsLemonade/OpenPBTA-analysis/blob/9b44bf1c186b3126b16dbe5b87756b3eae3feec2/analyses/snv-callers/scripts/02-merge_callers.R#L131-L136

looks like for all the cases above, they are with similar situation that, only 2 callers called the histones for one experimental_strategy while all 3 called the same mutation for another. for example, patient `PT_G16VK7FR`, only strelka2, mutect2 called K28 for its WGS data while all 3 callers detected K28 from its WES data. 

The PNOC003 team has noticed this issue, and decided for now, they will use the "non-wildtype" mutation status from either WGS or WES to override the wildtype status for the same sample. I don't know if we should take the same approach for OpenPBTA or we should consider to update the consensus method to be a "2 out of 3" selection method, which is close to the original D3b's method, which is a 2 out of 4 consensus (including vardict). In addtion to that, a 3 out of 3, intersection all callers' method might be too stringent which could end up with lower sensitivity where a 2 out of 3/4 method could balance both sensitivity and specificity in theory.

**Comment by jaclyn-taroni** [comment]
Another idea would be to deal with the specific issue you bring up in [`molecular-subtyping-pathology`](https://github.com/AlexsLemonade/OpenPBTA-analysis/tree/master/analyses/molecular-subtyping-pathology), which is the module that compiles the results from all the subtyping model and incorporates pathology feedback (functionally these are "different cases that crop up") as I described earlier.

**Comment by jharenza** [comment]
> Another idea would be to deal with the specific issue you bring up in [`molecular-subtyping-pathology`](https://github.com/AlexsLemonade/OpenPBTA-analysis/tree/master/analyses/molecular-subtyping-pathology), which is the module that compiles the results from all the subtyping model and incorporates pathology feedback (functionally these are "different cases that crop up" as I described earlier).

I think if we have this data from the pathology reports, it makes sense to include in the module described above. @jainpayal022 and @aadamk, is this something you would be willing to pull out and double review? If so, we can release that as a file or add it to a ticket (since it is a small number of samples).

cc @yuankunzhu

**Comment by jharenza** [comment]
@kgaonkar6 is checking to make sure this is resolved with the #750 histologies file

**Comment by kgaonkar6** [comment]
All bs_ids from the above participant_ids now have the same subtyping from the clinical/pathology feedback module.

  | Kids_First_Participant_ID | broad_histology | molecular_subtype | Kids_First_Biospecimen_ID | count
-- | -- | -- | -- | -- | --
1 | PT_G16VK7FR | Diffuse astrocytic and oligodendroglial tumor | DMG, H3 K28 | BS_XGDPK33A, BS_2HDEZFTW | 2
2 | PT_NK8A49X5 | Diffuse astrocytic and oligodendroglial tumor | DMG, H3 K28 | BS_1MME7FBS, BS_HEJ72V3F, BS_AHAXPFG3, BS_YDEVMD24, BS_6DT506HY, BS_1N7MQZGR, BS_GKXD33YH | 7
3 | PT_QA9WJ679 | Diffuse astrocytic and oligodendroglial tumor | DMG, H3 K28 | BS_7PF3C1P7, BS_G3NN392N, BS_AEEKJ1QK | 3
4 | PT_WGVEF96B | Diffuse astrocytic and oligodendroglial tumor | DMG, H3 K28 | BS_TQ0J7WJQ, BS_NB9XXBW6, BS_TYFD8ZMG | 3

Closing , it's fixed
