### ISSUE TITLE
Updated analysis: fusion_filtering bash script paths

### ISSUE THREAD

**Issue by sjspielman** [AlexsLemonade/OpenPBTA-analysis#737]
#### What analysis module should be updated and why?
The [`fusion_filtering/run_fusion_merged.sh`](https://github.com/AlexsLemonade/OpenPBTA-analysis/blob/master/analyses/fusion_filtering/run_fusion_merged.sh) bash script to run the full analysis pipeline should run from the path where it lives. Instead, the file assumes that it is being run from the top-level directory of the OpenPBTA project.

#### What changes need to be made? Please provide enough detail for another participant to make the update.

The script should be modified (and circle config, dockerfile accordingly as needed) to run from its directory.
 
#### What input data should be used? Which data were used in the version being updated?

N/A

#### When do you expect the revised analysis will be completed?

~1 week

#### Who will complete the updated analysis?

@sjspielman

**Comment by jaclyn-taroni** [comment]
Closed via #744
