### ISSUE TITLE
Updated analysis: medulloblastoma consensus subtypes

### ISSUE THREAD

**Issue by jharenza** [AlexsLemonade/OpenPBTA-analysis#747]
#### What analysis module should be updated and why?
#742 via <s>#738</s> #743

#### What changes need to be made? Please provide enough detail for another participant to make the update.
Will need to be updated once #746 goes in

#### What input data should be used? Which data were used in the version being updated?
RNA-Seq collapsed tables
File to be released in #746 

#### When do you expect the revised analysis will be completed?
unsure

#### Who will complete the updated analysis?
probably @komalsrathi

**Comment by komalsrathi** [comment]
@jharenza I think it should be PR https://github.com/AlexsLemonade/OpenPBTA-analysis/pull/743 instead of https://github.com/AlexsLemonade/OpenPBTA-analysis/pull/738. That's where I am using the expected subtypes to compare the classifiers with the pathology report.

**Comment by jharenza** [comment]
> @jharenza I think it should be PR #743 instead of #738. That's where I am using the expected subtypes to compare the classifiers with the pathology report.

updated, thanks!

**Comment by jharenza** [comment]
@komalsrathi - will you use the new file below as input for the classifier accuracy assessment? Thank you! 

[openPBTA-mb-pathology-subtypes.csv](https://github.com/AlexsLemonade/OpenPBTA-analysis/files/6321093/openPBTA-mb-pathology-subtypes.csv)

**Comment by komalsrathi** [comment]
@jharenza can you assign this to me? I never see these tickets unless they are assigned (only get notified and then I have to search for it).

**Comment by jharenza** [comment]
> @jharenza can you assign this to me? I never see these tickets unless they are assigned (only get notified and then I have to search for it).

done!

**Comment by komalsrathi** [comment]
> @komalsrathi - will you use the new file below as input for the classifier accuracy assessment? Thank you!
> 
> [openPBTA-mb-pathology-subtypes.csv](https://github.com/AlexsLemonade/OpenPBTA-analysis/files/6321093/openPBTA-mb-pathology-subtypes.csv)

@jharenza This file does not contain two columns that we have in the current input file:
`Kids_First_Biospecimen_ID` and `other_molecular_findings`. These are also added in the output files. If you can update the csv file, it would be easy to incorporate. I don't want to make any local changes to this file on my end as I am seeing this was referenced in other tickets as well. Thanks!

**Comment by jharenza** [comment]
Added BS_ID but removed `other_molecular_findings` to keep this lite for the release.
[openPBTA-mb-pathology-subtypes.csv](https://github.com/AlexsLemonade/OpenPBTA-analysis/files/6338682/openPBTA-mb-pathology-subtypes.csv)

**Comment by jharenza** [comment]
Closed with #1019
