### ISSUE TITLE
Add total, stranded RNA-Seq for 8 samples

### ISSUE THREAD

**Issue by jharenza** [AlexsLemonade/OpenPBTA-analysis#749]
#### What data file(s) does this issue pertain to?
pbta-star-log-final.tar.gz
pbta-star-log-manifest.tsv
pbta-mend-qc-manifest.tsv
pbta-mend-qc-results.tar.gz
pbta-isoform-counts-rsem-expected_count.polya.rds
pbta-isoform-counts-rsem-expected_count.stranded.rds
pbta-isoform-expression-rsem-tpm.polya.rds
pbta-isoform-expression-rsem-tpm.stranded.rds
pbta-fusion-arriba.tsv.gz
pbta-fusion-putative-oncogenic.tsv
pbta-fusion-recurrently-fused-genes-byhistology.tsv
pbta-fusion-recurrently-fused-genes-bysample.tsv
pbta-fusion-starfusion.tsv.gz
pbta-gene-counts-rsem-expected_count.polya.rds
pbta-gene-counts-rsem-expected_count.stranded.rds
pbta-gene-expression-kallisto.polya.rds
pbta-gene-expression-kallisto.stranded.rds
pbta-gene-expression-rsem-fpkm-collapsed.polya.rds
pbta-gene-expression-rsem-fpkm-collapsed.stranded.rds
pbta-gene-expression-rsem-fpkm.polya.rds
pbta-gene-expression-rsem-fpkm.stranded.rds
pbta-gene-expression-rsem-tpm.polya.rds
pbta-gene-expression-rsem-tpm.stranded.rds

#### What release are you using?

V16

#### Put a link to the relevant section of the [OpenPBTA-manuscript](https://github.com/AlexsLemonade/OpenPBTA-manuscript/) here.
NA

#### Put your question or report your issue here.
For a few samples in which polyA RNA-Seq was performed, new RNA was rRNA-depleted and sequenced as total, stranded and we will process and release these.

**Comment by jharenza** [comment]
For tracking:

**PNOC samples:**
BS_FXJY0MNH
BS_KABQQA0T
BS_D7XRFE0R
**CBTN samples:**
BS_SHJA4MR0
BS_HE0WJRW6
BS_8QB4S4VA
BS_FN07P04C
BS_SB12W1XT

**Comment by jaclyn-taroni** [comment]
Included in v18 release (#857)
