### ISSUE TITLE
Planned Release: V18

### ISSUE THREAD

**Issue by jharenza** [AlexsLemonade/OpenPBTA-analysis#750]
#### What data file(s) does this issue pertain to?
`pbta-histologies.tsv`
all RNA-Seq files

#### What release are you using?

V17

#### Put a link to the relevant section of the [OpenPBTA-manuscript](https://github.com/AlexsLemonade/OpenPBTA-manuscript/) here.
NA

#### Put your question or report your issue here.
Some future updates to include:
Add 8 RNA-Seq samples #749:
- [x] pbta-star-log-final.tar.gz
- [x] pbta-star-log-manifest.tsv
- [x] pbta-mend-qc-manifest.tsv
- [x] pbta-mend-qc-results.tar.gz
- [x] pbta-isoform-counts-rsem-expected_count.stranded.rds
- [x] pbta-isoform-expression-rsem-tpm.stranded.rds
- [x] pbta-fusion-arriba.tsv.gz
- [x] pbta-fusion-putative-oncogenic.tsv
- [x] pbta-fusion-recurrently-fused-genes-byhistology.tsv
- [x] pbta-fusion-recurrently-fused-genes-bysample.tsv
- [x] pbta-fusion-starfusion.tsv.gz
- [x] pbta-gene-counts-rsem-expected_count.stranded.rds
- [x] pbta-gene-expression-kallisto.stranded.rds
- [x] pbta-gene-expression-rsem-fpkm-collapsed.stranded.rds
- [x] pbta-gene-expression-rsem-fpkm.stranded.rds
- [x] pbta-gene-expression-rsem-tpm.stranded.rds
- [x] independent-specimens.rnaseq.primary-plus-stranded.tsv
- [x] fusion_summary_lgat_foi.tsv
- [x] md5sum.txt
 
- [ ] Add new medulloblastoma subtype pathology results file #746
- [ ] pbta-histologies.tsv refresh (V18 or maybe V19, post rework of subtyping modules post #732 to use `pathology_diagnosis` and `free_text_dx` due to being stuck in a loop for #748) 
- [x] Add `Extent of Tumor Resection` to pbta-histologies.tsv cc @adamcresnick and @baileyckelly

**Comment by jaclyn-taroni** [comment]
We're going to need to update the following files, because the `tumor_descriptor` field is changing in v17:

```
independent-specimens.wgs.primary-plus.tsv
independent-specimens.wgs.primary.tsv
independent-specimens.wgswxs.primary-plus.tsv
independent-specimens.wgswxs.primary.tsv
```

Regenerating those files is tracked in #767.

**Comment by jaclyn-taroni** [comment]
`pbta-fusion-recurrent-fusion-byhistology.tsv` will also need to be updated because of the `tumor_descriptor` change - tracked in #769.

**Comment by jharenza** [comment]
@jaclyn-taroni we are going to aim to release all RNA files listed here, plus the independent specimens files

For `pbta-histologies.tsv`, we will not have the new rules for broad/short histology/integrated dx because several subtyping modules are ongoing. We will add subtypes based on whatever subtyping modules have been merged by Friday/Monday.

cc @kgaonkar6
