### ISSUE TITLE
Updated analysis: pathology subtyping to include PNOC003 histone mutations from report data

### ISSUE THREAD

**Issue by jharenza** [AlexsLemonade/OpenPBTA-analysis#751]
#### What analysis module should be updated and why?
[pathology subtyping
](https://github.com/AlexsLemonade/OpenPBTA-analysis/tree/master/analyses/molecular-subtyping-pathology)

#### What changes need to be made? Please provide enough detail for another participant to make the update.
We will add histone mutations:  **H3F3A K28M, HIST1H3B K28M, HIST1H3C K28M, HIST2H3C K28M, H3F3A.G35R** from pathology (or clinical?) reports of PNOC003 trial patient samples. In some cases, as noted in #735, subtyping was different because of mutations missed during consensus calling. However, this information should be available in clinical and/or pathology reports, so we can add.

#### What input data should be used? Which data were used in the version being updated?
This particular subtyping is not currently a part of pathology subtyping, so it would be added based on a doubly-reviewed input file or table provided by someone at D3b.

**UPDATE 2020-10-05** 
Below is a double-reviewed (by Cassie Kline and myself) table of histone mutations found in the specified patient tumor per the TGEN genomic reports. Technically, these do not come from pathology, but from the clinical trial reports, so @jaclyn-taroni, we can either keep these in `pathology-subtyping` and broaden the module to something like `clinician-subtyping-review` or create a new module for this specific subtyping based on clinical trial reporting. Thoughts?

Kids_First_Participant_ID | H3 Status | tumor_descriptor
-- | -- | --
PT_M23Q0DC3 | H3F3A K28M | Initial CNS Tumor
PT_9GKVQ9QS | H3F3A K28M | Initial CNS Tumor
PT_KBFM551M | H3 WT | Initial CNS Tumor
PT_KBFM551M | no report | Progressive   Disease Post-Mortem
PT_V1HNAC2Q | H3F3A K28M | Initial CNS Tumor
PT_NK8A49X5 | H3F3A K28M | Initial CNS Tumor
PT_NK8A49X5 | H3F3A K28M | Progressive
PT_KZ56XHJT | H3F3A K28M | Initial CNS Tumor
PT_KZ56XHJT | H3F3A K28M | Progressive
PT_KZ56XHJT | no report | Progressive   Disease Post-Mortem
PT_QA9WJ679 | H3F3A K28M | Initial CNS Tumor
PT_WGVEF96B | H3F3A K28M | Initial CNS Tumor
PT_HGM20MW7 | H3F3A K28M | Initial CNS Tumor
PT_0MXPTTM3 | H3 WT | Initial CNS Tumor
PT_M9XXJ4GR | H3F3A K28M | Initial CNS Tumor
PT_KTRJ8TFY | H3F3A K28M | Initial CNS Tumor
PT_KTRJ8TFY | no report | Progressive   Disease Post-Mortem
PT_1E3E6GMF | H3F3A K28M | Initial CNS Tumor
PT_VPEMAQBN | HIST1H3B K28M | Initial CNS Tumor
PT_7P6J57H3 | H3F3A K28M | Initial CNS Tumor
PT_C5FKRB1P | H3 WT | Initial CNS Tumor
PT_CSKHQB16 | HIST1H3B K28M | Initial CNS Tumor
PT_1AAYYGGY | H3F3A K28M | Initial CNS Tumor
PT_NWYSD53S | H3F3A K28M | Initial CNS Tumor
PT_8P368R5B | No report | Initial CNS Tumor
PT_C9YDTZPA | H3F3A K28M | Initial CNS Tumor
PT_KAQMYFYB | H3F3A K28M | Initial CNS Tumor
PT_Y74CVASJ | H3F3A K28M | Initial CNS Tumor
PT_W5GP3F6B | H3F3A K28M | Initial CNS Tumor
PT_A06JR0E5 | H3F3A K28M | Initial CNS Tumor
PT_EN2RN5Y1 | H3F3A K28M | Initial CNS Tumor
PT_DMAF1J4A | H3F3A K28M | Initial CNS Tumor
PT_RYMG3M91 | H3F3A K28M | Initial CNS Tumor
PT_RE6AXQM1 | H3F3A K28M | Initial CNS Tumor
PT_G16VK7FR | HIST1H3B K28M | Initial CNS Tumor
PT_1YQH5NSH | H3F3A K28M | Initial CNS Tumor

#### When do you expect the revised analysis will be completed?
not sure yet

#### Who will complete the updated analysis?
not sure yet

@jaclyn-taroni this is now ready

**Comment by jaclyn-taroni** [comment]
Closed via #800
