### ISSUE TITLE
Updated analysis: embryonal subtyping to use pathology diagnosis

### ISSUE THREAD

**Issue by jharenza** [AlexsLemonade/OpenPBTA-analysis#752]
#### What analysis module should be updated and why?
https://github.com/AlexsLemonade/OpenPBTA-analysis/tree/master/analyses/molecular-subtyping-embryonal

#### What changes need to be made? Please provide enough detail for another participant to make the update.
Currently, this module uses `broad_histology` to search for the subset of samples to be subtyped. However, with the rework of rules to determine `broad_histology` post `integrated_diagnosis` (#748), we should rework this module to search for samples using `pathology_diagnosis` and the new field for free text pathology diagnosis, which will be present in `pbta-histologies.tsv in #732. 

#### What input data should be used? Which data were used in the version being updated?
`pbta-histologies.tsv` from V17 instead of from V16

#### When do you expect the revised analysis will be completed?
unsure

#### Who will complete the updated analysis?
unsure

**Comment by cbethell** [comment]
I can work on this issue this sprint!

**Comment by jharenza** [comment]
Hi @cbethell and @jaclyn-taroni! After consulting with Cassie Kline, the below list should be used in embryonal subytyping:

**pathology_diagnosis**
Neuroblastoma (see note)
Supratentorial or Spinal Cord PNET

**pathology_free_text_diagnosis**
embryonal tumor with multilayer rosettes, ros (who grade iv)
embryonal tumor, nos, congenital type
ependymoblastoma
medullooepithelioma


NOTE:
- It looks like we may have to update the CNS NBL logic to ensure we are capturing only `CNS Neuroblastomas` and not peripheral NBL. For instance, if `pathology_diagnosis` == `CNS Neuroblastoma & primary_site != Other locations NOS & pathology_free_text_diagnosis does not contain "peripheral"`, then we can consider them as CNS region NBLs and they can proceed to subtyping. The two tumors we currently have subtypes as `CNS NB-FOXR2` fit this, but if any are added in the future, we will want to be sure that we aren't subtyping NBLs that are non-CNS.
