### ISSUE TITLE
Updated analysis: LGAT subtyping to use pathology diagnosis

### ISSUE THREAD

**Issue by jharenza** [AlexsLemonade/OpenPBTA-analysis#753]
#### What analysis module should be updated and why?
https://github.com/AlexsLemonade/OpenPBTA-analysis/tree/master/analyses/molecular-subtyping-LGAT

#### What changes need to be made? Please provide enough detail for another participant to make the update.
Currently, this module uses `short_histology` to search for the subset of samples to be subtyped. However, with the rework of rules to determine `short_histology` post `integrated_diagnosis` (#748), we should rework this module to search for samples using `pathology_diagnosis` and the new field for `pathology_free_text_diagnosis`, which will be present in `pbta-histologies.tsv in #732. 

Since the `pathology_diagnosis` field is somewhat unharmonized and can consist of mixed diagnoses, I started by creating a [table](https://docs.google.com/spreadsheets/d/1fDXt_YODcSAWDvyI5ISBVhUCu4b5-TFCVWMOwiPeMwk/edit?usp=sharing) of those diagnoses, their 2016 WHO `broad_histology`, and the subtyping module in which these tumors would be subtyped, if at all. I have some questions for Cassie Kline (a clinician at CHOP) who will review so that we can be sure about how to set rules for collecting the proper diagnoses for each module.

If `pathology_diagnosis == Not Reported | Other`, then we should search the `pathology_free_text_diagnosis` for tumors which might fit the subtyping module. Eg: `BS_69VS8PS1` now has  `pathology_diagnosis == Other`, but `pathology_free_text_diagnosis == embryonal tumor with multilayer rosettes, ros (who grade iv)`, therefore, we would want to capture that sample in the embryonal subtyping module.

#### What input data should be used? Which data were used in the version being updated?
`pbta-histologies.tsv` from V17 instead of from V16

#### When do you expect the revised analysis will be completed?
unsure

#### Who will complete the updated analysis?
unsure

**Comment by cansavvy** [comment]
I can work on this issue.

**Comment by cansavvy** [comment]
Based on the comment above, 
> we should rework this module to search for samples using pathology_diagnosis and the new field for free text pathology diagnosis, 

It seems like both `pathology_diagnosis` and `pathology_free_text_diagnosis` should be used for subsetting? But it's unclear to me how to use both or how `pathology_free_text_diagnosis` should be used. I filed an issue on the manuscript repo about this: https://github.com/AlexsLemonade/OpenPBTA-manuscript/issues/123

**Comment by jharenza** [comment]
@cansavvy let me update this ticket to clarify! Also responded in the manuscript issue :).

**Comment by cansavvy** [comment]
More specifically, if biospecimens of particular `pathology_free_text_diagnosis` categories should sometimes be added to the `pathology_diagnosis` definitions, _when_ should this happen? But also _how_ should this happen: which are considered equivalent (As a person who has very little knowledge regarding these diagnoses meanings). 

For example, how do I know which values in `pathology_free_text_diagnosis` I should consider equivalent to `LGAT` and I should use to "add in" more samples to the subtyping? 

When I only look at the 255 LGAT `Kids_First_Biospecimen`s based on `pathology_diagnosis`, there are 80 unique values for `pathology_free_text_diagnosis` in this group.  A lot of these seem to include similar terms, but often have differences in spaces, punctuation. 

Does it make more sense to just use `pathology_diagnosis` categories in this case? I'm not sure how to parse out the values in `pathology_free_text_diagnosis`.

**Comment by jharenza** [comment]
@cansavvy we would use `pathology_diagnosis` and only search in `pathology_free_text_diagnosis` if any of the `Other` or `Not Reported` have diagnoses resembling LGAT. It doesn't look that way to me right now, but awaiting Cassie Kline's confirmation on this (edited in the original ticket above). We also may have an edit of moving `gangliogliomas` to LGAT. So for now, maybe we should block this until we have the definite criteria.

**Comment by jharenza** [comment]
Hi @cansavvy and @jaclyn-taroni! After consulting with Cassie, she thinks it makes sense to add to this module:

**pathology_diagnosis**: ==
Ganglioglioma
Ganglioglioma;Low-grade glioma/astrocytoma (WHO grade I/II)
Low-grade glioma/astrocytoma (WHO grade I/II)
Low-grade glioma/astrocytoma (WHO grade I/II);Other

There were no LGG in the tumors diagnosed as `Other` as of right now.

NOTES:
- Ganglioglioma also shows up with `Dysembryoplastic neuroepithelial tumor (DNET);Dysplasia/Gliosis;Ganglioglioma` and `Dysembryoplastic neuroepithelial tumor (DNET);Ganglioglioma` and these are classified as `neuronal and mixed neuronal-glial tumor`, so we **_do not_** want to include those.
- `Subependymal Giant Cell Astrocytoma (SEGA)` was previously in LGAT, but that was my mistake and it should actually be in `other astrocytic tumor` as a broad histology, so we will not expect to capture those in this module.
- There was a suggestion to update this module to include additional subtypes, but I will file an additional comment later with some background biology for this.

**Comment by jaclyn-taroni** [comment]
Thanks for the update! I'm going to remove the `blocked` label. 

> There was a suggestion to update this module to include additional subtypes, but I will file an additional comment later with some background biology for this.

You 100% could have meant new issue here, but to clarify - I would file a new issue to be addressed after this change has been addressed.

**Comment by jaclyn-taroni** [comment]
I'm going to pick up this issue!
