### ISSUE TITLE
Updated analysis: HGG subtyping to use pathology diagnosis

### ISSUE THREAD

**Issue by jharenza** [AlexsLemonade/OpenPBTA-analysis#754]
#### What analysis module should be updated and why?
https://github.com/AlexsLemonade/OpenPBTA-analysis/tree/master/analyses/molecular-subtyping-HGG

#### What changes need to be made? Please provide enough detail for another participant to make the update.
Currently, this module uses `short_histology` to search for the subset of samples to be subtyped. However, with the rework of rules to determine `short_histology` post `integrated_diagnosis` (#748), we should rework this module to search for samples using `pathology_diagnosis` and the new field for free text pathology diagnosis, which will be present in `pbta-histologies.tsv in #732. 

#### What input data should be used? Which data were used in the version being updated?
pbta-histologies.tsv from V17 instead of from V16

#### When do you expect the revised analysis will be completed?
unsure

#### Who will complete the updated analysis?
unsure

**Comment by jaclyn-taroni** [comment]
In v17, `glioma_brain_region` is being changed to `CNS_region`. `glioma_brain_region` is used in the `07-HGG-molecular-subtyping-combine-table.Rmd` notebook:

https://github.com/AlexsLemonade/OpenPBTA-analysis/blob/43e13134d3e9a6a5e0a126a63f68797c4ecb9b34/analyses/molecular-subtyping-HGG/07-HGG-molecular-subtyping-combine-table.Rmd#L246

When this is revised as detailed above, this minor change should also be made.

**Comment by jaclyn-taroni** [comment]
This step got commented out in https://github.com/AlexsLemonade/OpenPBTA-analysis/pull/764/commits/2335db8cc46cafa2c392bede58f4bc93a1ae485f. We'll need to uncomment that step when this gets addressed.

**Comment by jaclyn-taroni** [comment]
I'm going to pick this issue up.

**Comment by jharenza** [comment]
Hi @jaclyn-taroni! After consulting with Cassie Kline, the below list **_can_** be used in HGG subtyping:

**pathology_diagnosis**
Anaplastic Astrocytoma
Brainstem glioma- Diffuse intrinsic pontine glioma
Diffuse midline glioma, H3K27M mutant, WHO grade IV
Glioblastoma
High Grade Glial Neoplasma
High Grade Glioma
High-grade glioma/astrocytoma (WHO grade III/IV)
Infiltrating Dipg

**pathology_free_text_diagnosis**
dipg

but, we would also be missing high-grade samples that are listed as:
Diffuse Astrocytoma
Infiltrating Diffuse Astrocytoma

The reason these are not harmonized is because they are coming from the PNOC003 trial and the diagnosis terms have not yet been harmonized. There is an ongoing effort for this to happen going forward, but the terms may not change retrospectively for this closed trial.

That being said, I think for now, it is easiest to select from:
**pathology_diagnosis** (CBTTC samples)
High-grade glioma/astrocytoma (WHO grade III/IV)
Brainstem glioma- Diffuse intrinsic pontine glioma

OR 
cohort == "PNOC003"

and I think that should capture all of the samples you need.

**Comment by jaclyn-taroni** [comment]
Okay thanks, will implement on the open PR (#786)!
