### ISSUE TITLE
Updated analysis: MB subtyping to use pathology diagnosis

### ISSUE THREAD

**Issue by jharenza** [AlexsLemonade/OpenPBTA-analysis#756]
#### What analysis module should be updated and why?
https://github.com/AlexsLemonade/OpenPBTA-analysis/tree/master/analyses/molecular-subtyping-MB

#### What changes need to be made? Please provide enough detail for another participant to make the update.
Currently, this module uses `integrated_diagnosis` to search for the subset of samples to be subtyped. However, with the rework of rules to determine  `integrated_diagnosis` post molecular subtyping (#748), we should rework this module to search for samples using `pathology_diagnosis` and the new field for free text pathology diagnosis, which will be present in `pbta-histologies.tsv in #732. 

#### What input data should be used? Which data were used in the version being updated?
pbta-histologies.tsv from V17 instead of from V16

#### When do you expect the revised analysis will be completed?
unsure

#### Who will complete the updated analysis?
unsure

**Comment by jaclyn-taroni** [comment]
@cansavvy since #753 is apparently blocked, why don't we have you plan to pick up this issue? I've filed #786 (HGG) which it may be helpful to have a look at for inspiration re: first look at the `pathology_diagnosis` and `pathology_free_text_diagnosis`.

**Comment by cansavvy** [comment]
Sounds good! I'll take a look at this today!

**Comment by cansavvy** [comment]
I'll push a small notebook that summarizes this, but I did some poking and MB substyping seems to be a bit more straightforward than some of the other histologies: 

- Looks like all samples that have `short_histology` and `integrated_diagnosis` as `Medulloblastoma` also have `pathology_diagnosis` as `Medulloblastoma`. 
- Most but not all of these samples have `medulloblastoma` some place in `pathology_free_text_diagnosis`, but a couple have `PNET`. 
- There are no samples currently classified as `short_histology == "Other"` that have `medulloblastoma` as a part of `pathology_free_text_diagnosis`

**Comment by jaclyn-taroni** [comment]
Closed via #787
