### ISSUE TITLE
Updated analysis: medulloblastoma subtyping

### ISSUE THREAD

**Issue by jharenza** [AlexsLemonade/OpenPBTA-analysis#759]
#### What analysis module should be updated and why?
https://github.com/AlexsLemonade/OpenPBTA-analysis/tree/master/analyses/molecular-subtyping-MB per #758 

#### What changes need to be made? Please provide enough detail for another participant to make the update.
Implement logic for when two RNA specimens from the same event do not both have consensus with each other per #758 

#### What input data should be used? Which data were used in the version being updated?
uncorrected expression [here](https://github.com/AlexsLemonade/OpenPBTA-analysis/tree/master/analyses/molecular-subtyping-MB/input) 

#### When do you expect the revised analysis will be completed?
mid next week

#### Who will complete the updated analysis?
@komalsrathi

**Comment by komalsrathi** [comment]
Closing via https://github.com/AlexsLemonade/OpenPBTA-analysis/pull/760
