### ISSUE TITLE
[Figures] Unified ggplot2 theme

### ISSUE THREAD

**Issue by jaclyn-taroni** [AlexsLemonade/OpenPBTA-analysis#761]
We have unified color palettes included in [`figures`](https://github.com/AlexsLemonade/OpenPBTA-analysis/tree/b17171a0d3dc0dcf8a09331fb7153687df0a520b/figures), but we do not have a recommendation for a unified plot theme. For example, the [transcriptomic overview figure](https://github.com/AlexsLemonade/OpenPBTA-analysis/blob/b17171a0d3dc0dcf8a09331fb7153687df0a520b/figures/pngs/transcriptomic-overview.png) uses `theme_bw()` for the scatter plot in the first panel, where the [co-occurrence plot](https://github.com/AlexsLemonade/OpenPBTA-analysis/blob/b17171a0d3dc0dcf8a09331fb7153687df0a520b/figures/pngs/mutation_cooccurrence_figure.png) uses what I perceive to be `theme_classic()` in panel A.

We should decide on and document recommendations in [`figures/README.md`](https://github.com/AlexsLemonade/OpenPBTA-analysis/blob/b17171a0d3dc0dcf8a09331fb7153687df0a520b/figures/README.md). If we come up with a custom theme, some place like `figures/theme` might be a good spot for it. 

This is not to say that every figure needs the exact same theme, but some general recommendations about grids, etc. would be helpful.

**Comment by cansavvy** [comment]
I think any plots I have made, have used `theme_classic()` because I'm generally partial to it, for no particular reason. 

But in my opinion we should generally not have grids or a gray background (and that is accomplished with `theme_classic()`).

**Comment by jharenza** [comment]
How about `ggtheme = theme_pubr())` from `library(ggpubr)`: https://rpkgs.datanovia.com/ggpubr/ - follows the classic theme and has built in stat options when needed - agree with @cansavvy about no grids or greys for a cleaner look :)

**Comment by sjspielman** [comment]
We use `ggpubr::theme_pubr()` [as described](https://github.com/AlexsLemonade/OpenPBTA-analysis/blob/master/figures/README.md#overall-figure-theme).
