### ISSUE TITLE
[Figures] Color palettes for molecular subtypes

### ISSUE THREAD

**Issue by jaclyn-taroni** [AlexsLemonade/OpenPBTA-analysis#762]
Related to https://github.com/AlexsLemonade/OpenPBTA-analysis/issues/627 in my opinion.

One of the panels in the telomerase activity figure that is being added in https://github.com/AlexsLemonade/OpenPBTA-analysis/pull/736 is a comparison between medulloblastoma subtypes. We do not currently have color palettes for any category that pertains to disease labels outside of short histology. If we are going to consistently display molecular subtypes across figures, we should come up with a unified color palette. 

Given that it was challenging to come up with a palette that accommodated all of the short histology labels, it may also be appropriate to talk about how plots that show molecular subtypes should be in their own panel. I have less strong feelings about this specific recommendation.

**Comment by sjspielman** [comment]
Taken care of with updated palettes described in #1174 and #1176.
