### ISSUE TITLE
Updated analysis: Sort molecular subtyping tables for better diffs

### ISSUE THREAD

**Issue by jaclyn-taroni** [AlexsLemonade/OpenPBTA-analysis#770]
#### What analysis module should be updated and why?

Any (non-deprecated) molecular subtyping table that doesn't explicitly sort the output table, likely all of these:

```
molecular-subtyping-ATRT
molecular-subtyping-chordoma
molecular-subtyping-embryonal
molecular-subtyping-EPN
molecular-subtyping-EWS
molecular-subtyping-HGG
molecular-subtyping-LGAT
molecular-subtyping-pathology
```

Should be updated such that the output is sorted by identifiers (probably `Kids_First_Participant_ID` and `sample_id`) so it will easier to tell what's changed via the diff when we make post-v17 release changes. First brought up in the context of the MB module: https://github.com/AlexsLemonade/OpenPBTA-analysis/pull/760/files#r485623021

#### What changes need to be made? Please provide enough detail for another participant to make the update.

Add `dplyr::arrange(Kids_First_Participant_ID, sample_id)` to a step before writing the table that contains the molecular subtype labels to file. 

For example,  add the `arrange()` step in this code block: https://github.com/AlexsLemonade/OpenPBTA-analysis/blob/43e13134d3e9a6a5e0a126a63f68797c4ecb9b34/analyses/molecular-subtyping-HGG/07-HGG-molecular-subtyping-combine-table.Rmd#L524

To get a sorted `analyses/molecular-subtyping-HGG/results/HGG_molecular_subtype.tsv`.

Note that `molecular-subtyping-EPN` is in Python, but there will need to be an equivalent step.

#### When do you expect the revised analysis will be completed?

If this goes smoothly, I estimate this will take ~1-2 days. This should be addressed _prior to any other molecular subtyping issues_, so this should happen this week.

#### Who will complete the updated analysis?

Likely someone from the CCDL.

**Comment by jaclyn-taroni** [comment]
We're going to plan to 1) use the v16 data (so wait to merge #764) and 2) spread these modules out across the CCDL team to make this go faster. @cbethell @cansavvy @jashapiro  if you pick up a module, can you comment about which one you're working on? If you're picking up a module, be sure to hard refresh just in case the most recent comment hasn't shown up!

**Comment by jashapiro** [comment]
STarting at the top- I will do `molecular-subtyping-ATRT`

**Comment by jaclyn-taroni** [comment]
I will do `molecular-subtyping-chordoma`!

**Comment by jashapiro** [comment]
molecular-subtyping-ATRT done (#771)
Doing `molecular-subtyping-embryonal` next

**Comment by jashapiro** [comment]
`molecular-subtyping-embryonal` done (#772).
Moving on to `molecular-subtyping-EPN`

**Comment by jashapiro** [comment]
Did `molecular-subtyping-EPN` (#773)

**Comment by cbethell** [comment]
I can do `molecular-subtyping-EWS`!

**Comment by jashapiro** [comment]
Starting `molecular-subtyping-HGG`

**Comment by cbethell** [comment]
`molecular-subtyping-EWS` done (#774)
Will do `molecular-subtyping-HGG` next

**Comment by jaclyn-taroni** [comment]
`molecular-subtyping-chordoma` is filed (#775) 
Will move on to `molecular-subtyping-LGAT` this afternoon!

**Comment by jashapiro** [comment]
I'm starting on pathology, but will only file a draft, as it depends on other modules.

**Comment by cbethell** [comment]
`molecular-subtyping-HGG` is filed (#777) 👍
