### ISSUE TITLE
Updated analysis: Overhaul molecular subtyping results compilation step in molecular-subtyping-pathology

### ISSUE THREAD

**Issue by jaclyn-taroni** [AlexsLemonade/OpenPBTA-analysis#784]
#### What analysis module should be updated and why?

The [`molecular-subtyping-pathology`](https://github.com/AlexsLemonade/OpenPBTA-analysis/blob/master/analyses/molecular-subtyping-pathology) module compiles the results from other  molecular subtyping modules in the notebook `analyses/molecular-subtyping-pathology/01-compile-subtyping-results.Rmd`. 

With the updates in v17 (#748), the molecular subtyping modules are upstream of the `broad_histology`, `short_histology` and `integrated_diagnosis` fields and the code in the modules are being altered to use `pathology_diagnosis`. Put slightly more visually (and simplifying the relationship between the downstream fields):

`pathology_diagnosis` ---molecular subtyping in the repo---> `integrated_diagnosis`, `broad_histology`, and `short_histology`.

#### What changes need to be made? Please provide enough detail for another participant to make the update.

Two changes to `analyses/molecular-subtyping-pathology/01-compile-subtyping-results.Rmd` should be considered:

1. There are two modules (`molecular-subtyping-embryonal` and `molecular-subtyping-HGG`) that involve a step where all samples are checked for molecular alterations as part of inclusion criteria and as a result, these modules will not rely on `pathology_diagnosis` alone. It is possible, then, that a sample could end up with two subtype labels from two different modules: one on the basis of `pathology_diagnosis` alone and the one based on the molecular alteration inclusion step that has typically been deemed the more appropriate label once we go back to pathology. If a sample has two labels, we should prefer the one from `molecular-subtyping-embryonal` and `molecular-subtyping-HGG` in this step.

2. With the exception of the EWS results, we join the `integrated_diagnosis`, `short_histology`, `broad_histology`, and `Notes` from the histology file included in the data release `release-v15-20200228` that was prior to the feedback we received from pathology. We can either skip the inclusion of these columns or instead add the `integrated_diagnosis`, `short_histology`, and `broad_histology` columns on the basis of `pathology_diagnosis` and `molecular_subtype`. _Note that it's entirely not clear that this notebook is the right place for this or if we should add it at the end of each individual module._

#### What input data should be used? Which data were used in the version being updated?

The subtyping files in `master` should be used. As mentioned above, this notebook currently uses `release-v15-20200228`.

#### When do you expect the revised analysis will be completed?

This is blocked by #752, #753, #754, #755, and #756.

#### Who will complete the updated analysis?

Likely someone from the CCDL.

**Comment by kgaonkar6** [comment]
I'm commenting out module (molecular-subtyping-pathology) from CI as per [comment](https://github.com/AlexsLemonade/OpenPBTA-analysis/pull/815#issuecomment-710460745) since that code is  expected to change (for example the changes in molecular-subtyping-EWS  output as per #804 , is breaking CI at molecular-subtyping-pathology step becuase the format of the file has changed)

**Comment by jharenza** [comment]
>With the exception of the EWS results, we join the integrated_diagnosis, short_histology, broad_histology, and Notes from the histology file included in the data release release-v15-20200228 that was prior to the feedback we received from pathology. We can either skip the inclusion of these columns or instead add the integrated_diagnosis, short_histology, and broad_histology columns on the basis of pathology_diagnosis and molecular_subtype. Note that it's entirely not clear that this notebook is the right place for this or if we should add it at the end of each individual module.

Since we plan to have #748 as a separate module, we will omit addition of `integrated_diagnosis`, `short_histology`, and `broad_histology` columns within this PR.

**Comment by jharenza** [comment]
> I wanted to add a scenario that needs to be checked/updated other than the issues explained in 1) Two modules (molecular-subtyping-embryonal and molecular-subtyping-HGG) that involve a step where all samples are checked for molecular alterations coping from #824 .
> 
> 1. Here compiled_df is https://github.com/AlexsLemonade/OpenPBTA-analysis/blob/master/analyses/molecular-subtyping-pathology/results/compiled_molecular_subtypes_with_clinical_pathology_feedback.tsv this sample_id 7316-2255 is part of LGAT subtyping since it has path_dx== "Ganglioglioma" and HGG subtyping since it has H3 K28M.
> 
> compiled_df[which(compiled_df$sample_id %in% c("7316-2255")),] %>% left_join(cohort_plot_labels[,c(colnames(compiled_df),"pathology_diagnosis")]) %>% as.data.frame()
> Joining, by = c("Kids_First_Participant_ID", "sample_id", "Kids_First_Biospecimen_ID", "molecular_subtype", "integrated_diagnosis", "short_histology", "broad_histology", "Notes", "tumor_descriptor")
> Kids_First_Participant_ID sample_id Kids_First_Biospecimen_ID molecular_subtype
> 1 PT_6Q0NPVP3 7316-2255 BS_5JM573JC DMG, H3 K28
> 2 PT_6Q0NPVP3 7316-2255 BS_E5H6CFYT DMG, H3 K28
> 3 PT_6Q0NPVP3 7316-2255 BS_5JM573JC LGG, BRAF wildtype
> 4 PT_6Q0NPVP3 7316-2255 BS_E5H6CFYT LGG, BRAF wildtype
> integrated_diagnosis short_histology broad_histology
> 1 Diffuse midline glioma HGAT Diffuse astrocytic and oligodendroglial tumor
> 2 Diffuse midline glioma HGAT Diffuse astrocytic and oligodendroglial tumor
> 3 Diffuse midline glioma HGAT Diffuse astrocytic and oligodendroglial tumor
> 4 Diffuse midline glioma HGAT Diffuse astrocytic and oligodendroglial tumor
> Notes tumor_descriptor pathology_diagnosis
> 1 Updated via OpenPBTA subtyping Initial CNS Tumor Ganglioglioma
> 2 Updated via OpenPBTA subtyping Initial CNS Tumor Ganglioglioma
> 3 Updated via OpenPBTA subtyping Initial CNS Tumor Ganglioglioma
> 4 Updated via OpenPBTA subtyping Initial CNS Tumor Ganglioglioma

To update, HGG/LGG double subtyping assignments will no longer be an issue with #851

**Comment by jharenza** [comment]
closed with #854
