### ISSUE TITLE
Updated analysis: fusion filtering

### ISSUE THREAD

**Issue by kgaonkar6** [AlexsLemonade/OpenPBTA-analysis#789]
#### What analysis module should be updated and why?
fusion_filtering needs some filtering value updates. 

With the cutoff of 10 we were able to get ~96% sensitivity for PPTC (100 read length ) data.  However, when we tested TCGA data which has (50-75 read length) the cutoff of 10 wasn't sufficient (~70% sensitivity) but at 100 we get about ~96% sensitivity (percentage overlap to what is previously published for these samples)
<img width="633" alt="Screen Shot 2020-09-11 at 2 30 06 PM" src="https://user-images.githubusercontent.com/34580719/92960363-7ddb6700-f43b-11ea-988d-b830cbf52a39.png">

So we believe we should change the cutoff to 100 to capture all read length datasets , tagging @jharenza.

We also want to remove `ConjoinG` from artifact filtering since we believe these are true fusions between neighboring genes forming completely novel proteins in some cases. https://metasystems.riken.jp/conjoing/index

#### What changes need to be made? Please provide enough detail for another participant to make the update.
 - update to `default=100`
https://github.com/AlexsLemonade/OpenPBTA-analysis/blob/9e1996ad486aa1cf20bc4fa172b3f99620c0faee/analyses/fusion_filtering/02-fusion-filtering.R#L51 

 - update to `artifact_filter="GTEx_Recurrent|DGD_PARALOGS|Normal|BodyMap"`
https://github.com/AlexsLemonade/OpenPBTA-analysis/blob/9e1996ad486aa1cf20bc4fa172b3f99620c0faee/analyses/fusion_filtering/run_fusion_merged.sh#L31

#### What input data should be used? Which data were used in the version being updated?
pbta-fusion-arriba.tsv.gz
pbta-fusion-starfusion.tsv.gz

#### When do you expect the revised analysis will be completed?
1 day

#### Who will complete the updated analysis?
@kgaonkar6

**Comment by jaclyn-taroni** [comment]
Closed via #791
