### ISSUE TITLE
Updated analysis: independent samples list for RNA-seq

### ISSUE THREAD

**Issue by jharenza** [AlexsLemonade/OpenPBTA-analysis#795]
#### What analysis module should be updated and why?
[Independent samples](https://github.com/AlexsLemonade/OpenPBTA-analysis/tree/master/analyses/independent-samples)

The current analysis creates files of independent (de-deplicated) samples as follows:
- Primary specimens only with whole genome sequence (WGS)
- Primary and secondary specimens with WGS
- Primary specimens only with either WGS or whole exome sequence (WXS)
- Primary and secondary specimens with WGS or WXS

However, there is no independent specimen RNA list and upon a quick check of the v17 data, it looks like we have 52 `Initial CNS Tumor` + `Progressive | Progressive Progressive Disease Post-Mortem | Recurrence` pairs (excluding cell lines). Currently, the only RNA-Seq module that utilizes an independent RNA-Seq specimen list is [fusion filtering](https://github.com/AlexsLemonade/OpenPBTA-analysis/tree/master/analyses/fusion_filtering) as below.

**RNAseq sample matched by `sample_id` to `independent-specimens.wgswxs.primary.tsv`**
https://github.com/AlexsLemonade/OpenPBTA-analysis/blob/ed6552df1f7b233ee7eece71b364ca561ca459a2/analyses/fusion_filtering/06-recurrent-fusions-per-histology.R#L46-L53

**and if an RNA-Seq sample, but no DNA sample exists**
https://github.com/AlexsLemonade/OpenPBTA-analysis/blob/ed6552df1f7b233ee7eece71b364ca561ca459a2/analyses/fusion_filtering/06-recurrent-fusions-per-histology.R#L59-L73

I think it follows that we should update other RNA-Seq only modules which create summaries by a grouping variable to utilize independent RNA-Seq lists and avoid counting duplicate specimens in analyses:
- [gene-set-enrichment-analysis](https://github.com/AlexsLemonade/OpenPBTA-analysis/tree/master/analyses/gene-set-enrichment-analysis)
- [immune-deconv](https://github.com/AlexsLemonade/OpenPBTA-analysis/tree/master/analyses/immune-deconv)
- [telomerase-activity-prediction](https://github.com/AlexsLemonade/OpenPBTA-analysis/tree/master/analyses/telomerase-activity-prediction)

If I am understanding correctly, the above modules are using all samples (primary and other) in grouped analyses by histology. I think we should separate these into primary only +/- relapse (Progressive | Progressive Progressive Disease Post-Mortem | Recurrence).

In addition, with #750, we will be adding data for 8 new stranded RNA-Seq samples (table below), 7 of which have polyA RNA-Seq data currently within OpenPBTA and we should discuss how to handle these when we create independent specimen lists. Do we default to stranded? Do we perform some comparisons first, then choose? cc @jaclyn-taroni @cgreene @jashapiro for discussion

| Kids_First_Participant_ID | cohort_participant_id | Kids_First_Biospecimen_ID_polyA | Kids_First_Biospecimen_ID_stranded | sample_id | aliquot_id_new | composition       |
|---------------------------|-----------------------|---------------------------------|------------------------------------|-----------|----------------|-------------------|
| PT_JT9HH7M6               | C15990                | BS_HWGWYCY7                     | BS_HE0WJRW6                        | 7316-1455 | 994695         | Solid Tissue      |
| PT_Z4BF2NSB               | C34809                | BS_X0XXN9BK                     | BS_SHJA4MR0                        | 7316-161  | 994696         | Solid Tissue      |
| PT_X7HC5YCY               | C42066                | BS_W4H1D4Y6                     | BS_FN07P04C                        | 7316-255  | 994697         | Solid Tissue      |
| PT_8VRZRZ7R               | C113775               | BS_QKT3TJVK                     |        BS_8QB4S4VA                 | 7316-536  | 994694         | Solid Tissue      |
| PT_3AWKWXEV               | C28290                | BS_BYCX6VK1                     | BS_SB12W1XT                        | 7316-85   | 994693         | Solid Tissue      |
| PT_8P368R5B               | C3080658              | NA                              | BS_FXJY0MNH                        | A15247    | A15266         | Solid Tissue      |
| PT_W5GP3F6B               | C3092712              | BS_7WM3MNZ0                     | BS_KABQQA0T                        | A16915    | A16919         | Solid Tissue      |
| PT_RYMG3M91               | C3093450              | BS_68KX6A42                     | BS_D7XRFE0R                        | A18777    | A18808         | Solid Tissue      |
| PT_3AWKWXEV               | C28290                | BS_QYPHA40N                     |                                    | 7316-85   |                | Derived Cell Line |
| PT_3AWKWXEV               | C28290                | BS_59ZJWJTF                     |                                    | 7316-85   |                | Derived Cell Line |

#### What changes need to be made? Please provide enough detail for another participant to make the update.
We should create the following lists within this module, possibly modeled after the code above from the fusion filtering module:
- Primary specimens only with RNA-Seq
- Primary and other specimens with RNA-Seq
- Secondary (Progressive | Progressive Progressive Disease Post-Mortem | Recurrence) specimens with RNA-Seq -> this could be utilized as a "relapse" type list. Thoughts, @jaclyn-taroni @jashapiro @cgreene?

#### What input data should be used? Which data were used in the version being updated?
v17 pbta-histologies.tsv, plus the table above to enable concurrent file release and updated fusion filtering for #750 

#### When do you expect the revised analysis will be completed?
1 week

#### Who will complete the updated analysis?
@kgaonkar6

**Comment by jashapiro** [comment]
I think there are a few different things mentioned here that are important. We will probably want to separate out a few of them into different issues, as I think there is the potential to conflate solutions if we keep them together. I will try to lay out my thoughts below.

1. The issue of multiply counting samples from the same individual is a real one, and we should be careful in analyses where it might come up. However, the solution we used for DNA may not be applicable for RNA. For DNA, combining genotype data is somewhat fraught, as genotype is largely binary (mutation or no), so we went with the simple solution of picking one. (If we had multiple samples for each individual, we could potentially implement something where we took the intersection of calls, but with varying sample sizes, we would end up with very different false positive/false negative rates depending on samples). 

    RNA though, is potentially quite different. Taking average expression across multiple samples is generally fine, so we would probably want to do that in most cases, rather than simply picking one sample. If we are not doing that currently in places where we should, then I would think we should implement averaging or a model that expressly accounts for multiple samples, rather than picking a single sample after expression analysis.

    The correct solution is likely to vary by module, so we should probably have separate issues for each module on how to handle multiple RNA samples.

2. We do not have a general handling of primary vs. recurrence samples. We do not have many non-primary samples overall, and very few where there are both: https://github.com/AlexsLemonade/OpenPBTA-analysis/issues/16#issuecomment-549360497 This should definitely be kept in mind for individual analyses as well. 

3. As to #750, where we have polyA and stranded data, we generally prefer stranded, as that covers far more samples. As far as I am aware, we never combine these two types of data, I do not see this coming up as an issue.

**Comment by jaclyn-taroni** [comment]
> The correct solution is likely to vary by module, so we should probably have separate issues for each module on how to handle multiple RNA samples.

I agree - I think the modules explicitly mentioned above ([`gene-set-enrichment-analysis`](https://github.com/AlexsLemonade/OpenPBTA-analysis/tree/master/analyses/gene-set-enrichment-analysis), [`immune-deconv`](https://github.com/AlexsLemonade/OpenPBTA-analysis/tree/master/analyses/immune-deconv), [`telomerase-activity-prediction`](https://github.com/AlexsLemonade/OpenPBTA-analysis/tree/master/analyses/telomerase-activity-prediction)) are likely to have different requirements or approaches compared to the _motivating example_, [`fusion_filtering`](https://github.com/AlexsLemonade/OpenPBTA-analysis/tree/master/analyses/fusion_filtering), which is closer to the mutation data in that it is largely binary when it comes to _counting recurrent fusions_.

**Comment by jharenza** [comment]
Thanks for the comments @jashapiro! 

>RNA though, is potentially quite different. Taking average expression across multiple samples is generally fine, so we would probably want to do that in most cases, rather than simply picking one sample. If we are not doing that currently in places where we should, then I would think we should implement averaging or a model that expressly accounts for multiple samples, rather than picking a single sample after expression analysis.

Good idea!

> 3. As to #750, where we have polyA and stranded data, we generally prefer stranded, as that covers far more samples. As far as I am aware, we never combine these two types of data, I do not see this coming up as an issue.

This came up because in the fusion filtering module, we do use both polyA and stranded samples, and also had to be sure we were not double counting when looking at recurrent fusions, as @jaclyn-taroni also mentioned. Based on the preference for stranded (I agree), we can create the sample list using that logic for the 8 new samples incoming with #750. cc @kgaonkar6  

I agree, we should separate the issues for updating analyses. So for now, maybe it makes sense to just create the list below? 

```
Primary and other specimens with RNA-Seq
```

**Comment by jaclyn-taroni** [comment]
> I agree, we should separate the issues for updating analyses. So for now, maybe it makes sense to just create the list below? 
> 
> ```
> Primary and other specimens with RNA-Seq
> ```

Sounds reasonable! Does this impact what's in #797?

**Comment by kgaonkar6** [comment]
#797 right now has options for primary only and primary_plus (primary and others if primary sample is not available) , I tried to make it similar to the dna selection.

**Comment by jharenza** [comment]
closed via #797
