### ISSUE TITLE
Updated analysis: molecular-subtyping-HGG ; NA in HGAT samples molecular subtype

### ISSUE THREAD

**Issue by kgaonkar6** [AlexsLemonade/OpenPBTA-analysis#801]
#### What analysis module should be updated and why?
molecular-subtyping-HGG

From discussion with @jharenza  we found that within HGAT short histology samples a subset of samples are `NA` in molecular subtype column 
[not-subtyped_list.txt](https://github.com/AlexsLemonade/OpenPBTA-analysis/files/5371693/not-subtyped_list.txt)
These should be have value = "HGG, To be classified" similar to LGAT molecular subtyping values.

#### What changes need to be made? Please provide enough detail for another participant to make the update.

The 48 samples here the only RNA-Seq (Solid Tissue) HGG samples that have `NA` so if we do a full_join instead of left_join here we will be able to add these RNA-Seq samples only in the module
https://github.com/kgaonkar6/OpenPBTA-analysis/blob/6f5dfc76d5d463f1a2a2d43d0824ccf038c4e185/analyses/molecular-subtyping-HGG/07-HGG-molecular-subtyping-combine-table.Rmd#L280-L286

and then in a later chunk 
https://github.com/AlexsLemonade/OpenPBTA-analysis/blob/1cf06fb0a4b4294ee60b81c795a34dab39bbbe3c/analyses/molecular-subtyping-HGG/07-HGG-molecular-subtyping-combine-table.Rmd#L508-L519

I think changes will be: 
 - `replace_na(list(molecular_subtype = "HGG, H3 wildtype"))` into sample_ids *with* Kids_First_Biospecimen_DNA 
 - `replace_na(list(molecular_subtype = "HGG,To be classified "))` into sample_ids *without* Kids_First_Biospecimen_DNA

#### What input data should be used? Which data were used in the version being updated?
pbta-snv-consensus-mutation.maf.tsv.gz
analyses/focal-cn-preparation/results/cnvkit_annotated_cn_autosomes.tsv.gz
pbta-fusion-putative-oncogenic.tsv
pbta-cnv-consensus-gistic.zip
pbta-gene-expression-rsem-fpkm-collapsed.stranded.rds
pbta-gene-expression-rsem-fpkm-collapsed.polya.rds

#### When do you expect the revised analysis will be completed?
1 day

#### Who will complete the updated analysis?
@kgaonkar6

**Comment by jaclyn-taroni** [comment]
Closed via #813
