### ISSUE TITLE
Updated analysis: EWS molecular subtyping

### ISSUE THREAD

**Issue by jharenza** [AlexsLemonade/OpenPBTA-analysis#804]
#### What analysis module should be updated and why?
[molecular-subtyping-EWS](https://github.com/AlexsLemonade/OpenPBTA-analysis/tree/master/analyses/molecular-subtyping-EWS)

Currently, this module currently recodes `integrated_diagnosis` and `short_histology`, but I think we should update this module in preparation for #748.
 
#### What changes need to be made? Please provide enough detail for another participant to make the update.
1. Pull all samples with hallmark EWS fusions
2. Match RNA `sample_id` with DNA `sample_id`
3. Add `EWS` to `molecular_subtype` for the specimens in 2. --> this will enable updating of `integrated_diagnosis`, `broad_histology`, and `short_histology` with #748 

We can remove the `CNS EFT-CIC` bit of code since this deals with recoding `integrated_diagnosis`.

#### What input data should be used? Which data were used in the version being updated?
`fusion_summary_ewings_foi.tsv`
`pbta-histologies.tsv`

#### When do you expect the revised analysis will be completed?
2-3 days

#### Who will complete the updated analysis?
@kgaonkar6

**Comment by jaclyn-taroni** [comment]
Closed via #815
