### ISSUE TITLE
Updated analysis: HGG subtyping to remove BRAF and include TP53

### ISSUE THREAD

**Issue by jharenza** [AlexsLemonade/OpenPBTA-analysis#807]
#### What analysis module should be updated and why?
[molecular-subtyping-HGG](https://github.com/AlexsLemonade/OpenPBTA-analysis/tree/master/analyses/molecular-subtyping-HGG)

1. Per discussion with @adamcresnick, we should remove the _BRAF_ V600E subtyping from HGG and replace with _TP53_ subtypes for HGG, as _TP53_ is the top co-occurring gene with H3 mutations in DMGs. Neither are currently in WHO, but the latter may be able to inform clinical decision making. 
2. We should remove LGG samples which contain histone mutations during the initial search for samples with histone mutations, since there have been recent reports of LGG with these mutations. (See literature below).

#### What changes need to be made? Please provide enough detail for another participant to make the update.
Step 1 - cleanup
- Remove the _BRAF_ V600E subtypes - This is being done in #856 
- <s>Remove LGG tumor samples which have histone mutations.</s> - This is being done in #851 

Step 2 - annotate as _TP53_ altered if: 
- There are two alterations (SNV+SNV, CNV+SNV)
- There is one alteration + cancer_predispositions == "Li-Fraumeni syndrome"
- There are no TP53 alterations, but cancer_predispositions == "Li-Fraumeni syndrome" **_and_** _TP53_ classifier score for matched RNA-Seq > 0.5
- There are one of _TP53_ activating mutations R273C and R248W (see literature below)

Step 3 - assess and potentially annotate as _TP53_ altered if:
- There is an SNV  **or** Focal CNV loss **_and_** _TP53_ classifier score for matched RNA-Seq > 0.5
- There is an SNV **or** Focal CNV gain **_and_** _TP53_ classifier score for matched RNA-Seq < 0.5 (indicating activating mutation) **_and_** _TP53_ expression is high

#### What input data should be used? Which data were used in the version being updated?
```
pbta-snv-consensus-mutation.maf.tsv.gz
https://github.com/AlexsLemonade/OpenPBTA-analysis/blob/master/analyses/tp53_nf1_score/results/pbta-gene-expression-rsem-fpkm-collapsed.stranded_classifier_scores.tsv
https://github.com/AlexsLemonade/OpenPBTA-analysis/blob/master/analyses/tp53_nf1_score/results/pbta-gene-expression-rsem-fpkm-collapsed.polya_classifier_scores.tsv
```
#### When do you expect the revised analysis will be completed?
2-4 days

#### Who will complete the updated analysis?
@kgaonkar6 

#### Relevant literature
[Tectal Low-Grade Glioma with H3 K27M Mutation](https://www.sciencedirect.com/science/article/abs/pii/S1878875020312134)
[Pediatric low-grade glioma in the era of molecular diagnostics
](https://actaneurocomms.biomedcentral.com/articles/10.1186/s40478-020-00902-z)
[p53 gain-of-function cancer mutants induce genetic instability by inactivating ATM
](https://pubmed.ncbi.nlm.nih.gov/17417627/) 
[Mutants TP53 p.R273H and p.R273C but not p.R273G enhance cancer cell malignancy](https://pubmed.ncbi.nlm.nih.gov/24677579/)

**Comment by jharenza** [comment]
@kgaonkar6 - I imagine a table of lesions consisting of the TP53 SNV, TP53 classifier score, TP53 FPKM, TP53 loss, TP53 gain

**Comment by kgaonkar6** [comment]
In #837 the TP53 annotation PR, we are missing annotation corresponding to Step3 from this PR:

>Step 3 - assess and potentially annotate as TP53 altered if:
>
>There is an SNV or Focal CNV loss and TP53 classifier score for matched RNA-Seq > 0.5
>There is an SNV or Focal CNV gain and TP53 classifier score for matched RNA-Seq < 0.5 (indicating activating mutation) >and TP53 expression is high


is this specific to HGG samples? 

If not I can add these conditions to the annotation criteria in #837 since I think we wanted the exact annotation from #837 to be added to the samples in HGG here , right? @jharenza.

**Comment by kgaonkar6** [comment]
This seems to be completed now, ok from @jharenza to close?

**Comment by jharenza** [comment]
yes!
