### ISSUE TITLE
Proposed Analysis: molecularly subtype craniopharyngiomas

### ISSUE THREAD

**Issue by jharenza** [AlexsLemonade/OpenPBTA-analysis#810]
#### What are the scientific goals of the analysis?
molecularly subtype craniopharyngiomas into adamantinomatous or papillary

#### What methods do you plan to use to accomplish the scientific goals?
1. Select all samples in which `pathology_diagnosis` == `Craniopharyngioma`
2. Create defining lesions table similar to [the one in the HGG subtyping module](https://github.com/AlexsLemonade/OpenPBTA-analysis/blob/master/analyses/molecular-subtyping-HGG/results/HGG_defining_lesions.tsv) to contain sample IDs, age, _CTNNB1_ and _BRAF_ mutations noted below.
3. Assign subtypes as either **CRANIO, ADAM** or **CRANIO, PAP**: ([example](https://github.com/AlexsLemonade/OpenPBTA-analysis/blob/master/analyses/molecular-subtyping-HGG/results/HGG_molecular_subtype.tsv)) based on defining lesions and check ages make sense.
4. If no defining lesion is present, annotate subtype as **CRANIO, To be classified**

**CRANIO, ADAM**
- Contains SNV in exon 3 of _CTNNB1_ (first, identify coordinates of exon 3 of this gene and then make sure the lesion falls within them)
- Tumor occurs mostly in childhood or young adolescence (0-39 years), but can be seen in adults

**CRANIO, PAP**
- Contains _BRAF_ V600E mutation
- Tumor occurs exclusively in adults

#### What input data are required for this analysis?
```
pbta-histologies.tsv
pbta-snv-consensus-mutation.maf.tsv.gz
```

#### How long do you expect is needed to complete the analysis? Will it be a multi-step analysis?
0.5 day

#### Who will complete the analysis (please add a GitHub handle here if relevant)?
@kgaonkar6 

#### What relevant scientific literature relates to this analysis?
[Exome sequencing identifies BRAF mutations in papillary craniopharyngiomas
](https://pubmed.ncbi.nlm.nih.gov/24413733/)
[Craniopharyngiomas of Adamantinomatous Type Harbor β-Catenin Gene Mutations
](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC1850925/)

**Comment by jharenza** [comment]
@dmiller15 will work on this issue

**Comment by dmiller15** [comment]
Initial PR has been created.

**Comment by jaclyn-taroni** [comment]
Reading through #820, I believe that this was closed by this pull request.
