### ISSUE TITLE
Improve documentation for analyses/copy_number_consensus_call/results/uncalled_samples.tsv in module README

### ISSUE THREAD

**Issue by jharenza** [AlexsLemonade/OpenPBTA-analysis#817]
#### What data file(s) does this issue pertain to?
pbta-cnv-consensus.seg.gz 

#### What release are you using?

v17; consensus cnv looks to be last created using v14 data

#### Put a link to the relevant section of the [OpenPBTA-manuscript](https://github.com/AlexsLemonade/OpenPBTA-manuscript/) here.
NA

#### Put your question or report your issue here.
BS_JC8YV5V9 has CNV changes present in all three CNV files (`pbta-cnv-cnvkit.seg.gz`, `pbta-cnv-controlfreec.tsv.gz`, `pbta-sv-manta.tsv.gz`), but is not contained within `pbta-cnv-consensus.seg.gz`. It is also listed as present in [`uncalled_samples.tsv`](https://github.com/AlexsLemonade/OpenPBTA-analysis/blob/master/analyses/copy_number_consensus_call/results/uncalled_samples.tsv), but I cannot find a description of what this file means in the README of the analysis. Are these the samples on which consensus was not performed because they did not have all 3 CNV files present or the samples which did not have consensus among the files? In the `uncalled_samples.tsv` file, BS_JC8YV5V9 is listed as having results from cnvkit and freec, but not manta. I think this sample should be found in consensus, unless the 3 callers had none. Additionally, would it be possible to add documentation to explain the `uncalled_samples.tsv`? Thanks! 

cc @fingerfen and @jashapiro

**Comment by jashapiro** [comment]
`uncalled_samples.tsv` is a table of the samples that fail step 2 of the pipeline described here: https://github.com/AlexsLemonade/OpenPBTA-analysis/blob/master/analyses/copy_number_consensus_call/README.md#consensus-cnv-creation

This should be added to the readme.

**Comment by jharenza** [comment]
> `uncalled_samples.tsv` is a table of the samples that fail step 2 of the pipeline described here: https://github.com/AlexsLemonade/OpenPBTA-analysis/blob/master/analyses/copy_number_consensus_call/README.md#consensus-cnv-creation
> 
> This should be added to the readme.

Thanks @jashapiro! cc @kennethchenlab

**Comment by jaclyn-taroni** [comment]
I am going to assign @jashapiro and update the title (and labels) of the issue to reflect that this is a documentation change.
