### ISSUE TITLE
Updated analysis: survival_analysis_HGG_DMG

### ISSUE THREAD

**Issue by kgaonkar6** [AlexsLemonade/OpenPBTA-analysis#827]
#### What analysis module should be updated and why?

survival-analysis/survival-analysis_HGG_DMG.Rmd needs to be updated so that we don't need to use broad_composition in any module in OpenPBTA. 
`broad_composition` is based on integrated_diagnosis so we do not want to use it in any analysis modules.

#### What changes need to be made? Please provide enough detail for another participant to make the update.
change:
```
 broad_composition == “tumor” 
```

to 
```
composition == "Solid Tissue"
```

#### What input data should be used? Which data were used in the version being updated?
pbta-histologies.tsv
independent-specimens.wgswxs.primary.tsv

#### When do you expect the revised analysis will be completed?
1/2 day

#### Who will complete the updated analysis?
@kgaonkar6

**Comment by jharenza** [comment]
closed with #828
