### ISSUE TITLE
Corrupt link for data description

### ISSUE THREAD

**Issue by rgalvin516** [AlexsLemonade/OpenPBTA-analysis#831]
Hello,

Thank you for the invaluable work compiled here. I am interested in looking at the data description file for more information about the individual gene expression files, but the link to this file on the following page appears corrupt:

https://github.com/AlexsLemonade/OpenPBTA-analysis/blob/master/doc/data-formats.md

The specific link:
https://github.com/AlexsLemonade/OpenPBTA-analysis/blob/master/doc/data-description.md

**Comment by cgreene** [comment]
Quick guess that actual link is here: https://github.com/AlexsLemonade/OpenPBTA-analysis/blob/master/doc/data-files-description.md

If that's it, we'd welcome a quick PR that fixes things :)

**Comment by rgalvin516** [comment]
That is exactly what I was looking for; thanks again and happy to throw you a softball!

**Comment by cgreene** [comment]
I filed #833 to fix this - thanks for reporting it! :)
