### ISSUE TITLE
Updated File and Documentation : Fusion gene and fusion reference lists

### ISSUE THREAD

**Issue by kgaonkar6** [AlexsLemonade/OpenPBTA-analysis#832]
#### What analysis module should be updated and why?
fusion_filtering : the files currently have rownames which causes issues reading the file as discussed in the [thread](https://github.com/AlexsLemonade/OpenPBTA-analysis/pull/830#discussion_r518758733)

Screenshot from @cansavvy 
https://user-images.githubusercontent.com/23458084/98376682-d8dfa380-2011-11eb-8202-8c031c6736d6.png

#### What changes need to be made? Please provide enough detail for another participant to make the update.
Remove the row.names while saving the file , save with write_tsv()

#### What input data should be used? Which data were used in the version being updated?
https://gist.github.com/kgaonkar6/02b3fbcfeeddfa282a1cdf4803704794

#### When do you expect the revised analysis will be completed?
1/2 day

#### Who will complete the updated analysis?
@kgaonkar6

**Comment by jharenza** [comment]
updated via #836
