### ISSUE TITLE
Updated analysis: MB - add "To be classified" to non-subtyped samples

### ISSUE THREAD

**Issue by jharenza** [AlexsLemonade/OpenPBTA-analysis#852]
#### What analysis module should be updated and why?
[MB subtyping
](https://github.com/AlexsLemonade/OpenPBTA-analysis/tree/master/analyses/molecular-subtyping-MB)

#### What changes need to be made? Please provide enough detail for another participant to make the update.
If the sample is not classified, assign the subtype, "MB, To be classified" to align with other modules.

#### What input data should be used? Which data were used in the version being updated?
RNA-Seq collapsed matrices

#### When do you expect the revised analysis will be completed?
?

#### Who will complete the updated analysis?
@komalsrathi - let me know if you can get to this this week, or else @kgaonkar6 or I can update.

**Comment by komalsrathi** [comment]
sure I can take this on.

**Comment by komalsrathi** [comment]
I don't have permission to close this but this can be closed as it was resolved.

**Comment by jharenza** [comment]
closed via #855
