### ISSUE TITLE
Updated analysis: remove BRAF from HGG subtyping

### ISSUE THREAD

**Issue by jharenza** [AlexsLemonade/OpenPBTA-analysis#853]
#### What analysis module should be updated and why?
HGG subtyping 

#### What changes need to be made? Please provide enough detail for another participant to make the update.
Step 1a from [this issue](https://github.com/AlexsLemonade/OpenPBTA-analysis/issues/807) (Remove BRAF from subtyping) should be done before #784  

#### What input data should be used? Which data were used in the version being updated?
```
pbta-snv-consensus-mutation.maf.tsv.gz
```

#### When do you expect the revised analysis will be completed?
tuesday 11/24

#### Who will complete the updated analysis?
@kgaonkar6

**Comment by kgaonkar6** [comment]
closed with #856
