### ISSUE TITLE
Updated analysis: Ependymoma add WGS only samples to subtyping 

### ISSUE THREAD

**Issue by kgaonkar6** [AlexsLemonade/OpenPBTA-analysis#859]
#### What analysis module should be updated and why?
WGS only epndymoma samples are being missed out from the subtyping.

#### What changes need to be made? Please provide enough detail for another participant to make the update.

Mainly from this section it seems only participant ids which have RNA are chosen  to subset WGS samples as well
https://github.com/AlexsLemonade/OpenPBTA-analysis/blob/0a6e54370399e7df632059957186a631b381d23b/analyses/molecular-subtyping-EPN/01-make_notebook_RNAandDNA.py#L49

4 WGS only samples which get missed out because of the participant_id selection :
https://github.com/AlexsLemonade/OpenPBTA-analysis/blob/0a6e54370399e7df632059957186a631b381d23b/analyses/molecular-subtyping-EPN/01-make_notebook_RNAandDNA.py#L53

In addition, since there will be NA's in the RNA bs id column if we remove the above selection, this snippet will also need to be updated 
https://github.com/AlexsLemonade/OpenPBTA-analysis/blob/0a6e54370399e7df632059957186a631b381d23b/analyses/molecular-subtyping-EPN/02_ependymoma_generate_all_data.py#L113-L118

#### What input data should be used? Which data were used in the version being updated?
pbta-gene-expression-rsem-fpkm-collapsed.stranded.rds
pbta-cnv-consensus-gistic.zip
analyses/chromosomal-instability/breakpoint-data/union_of_breaks_densities.tsv
analyses/fusion-summary/results/fusion_summary_ependymoma_foi.tsv
analyses/gene-set-enrichment-analysis/results/gsva_scores_stranded.tsv

#### When do you expect the revised analysis will be completed?
~1 day

#### Who will complete the updated analysis?
@kgaonkar6

**Comment by jaclyn-taroni** [comment]
Closed via #860
