### ISSUE TITLE
Updated analysis: RNA summary files and base histology subtyping update for v18

### ISSUE THREAD

**Issue by kgaonkar6** [AlexsLemonade/OpenPBTA-analysis#861]
#### What analysis module should be updated and why?

**RNA-seq summary files generation modules part of download or used in subtyping**
| Module |  Reason |Brief Description | output
|--------|----------|--------|------
| [`collapse-rnaseq`](https://github.com/AlexsLemonade/OpenPBTA-analysis/tree/master/analyses/collapse-rnaseq) | adding 8 samples #749 and used in subtyping  | Collapses RSEM FPKM matrices such that gene symbols are de-duplicated. | `results/pbta-gene-expression-rsem-fpkm-collapsed.polya.rds` (included in data download; too large for tracking via GitHub) <br> `results/pbta-gene-expression-rsem-fpkm-collapsed.stranded.rds` (included in data download; too large for tracking via GitHub)
| [`fusion_filtering`](https://github.com/AlexsLemonade/OpenPBTA-analysis/tree/master/analyses/fusion_filtering) | adding 8 samples #749 and used in subtyping  | Standardizes, filters, and prioritizes fusion calls updated in #808 and #830 | `results/pbta-fusion-putative-oncogenic.tsv`(included in data download) <br> `results/pbta-fusion-recurrent-fusion-byhistology.tsv` (included in data download) <br> `results/pbta-fusion-recurrent-fusion-bysample.tsv` (included in data download) <br> `results/fusion_summary_lgat_foi.tsv` (included in data download)
| [`fusion-summary`](https://github.com/AlexsLemonade/OpenPBTA-analysis/tree/master/analyses/fusion-summary)| adding 8 samples #749 and used in subtyping  | Generate summary tables from fusion files updated in  #812 and #816 and #821 and [comment](https://github.com/AlexsLemonade/OpenPBTA-analysis/issues/750#issuecomment-691529675) | `results/fusion_summary_embryonal_foi.tsv` (included in data download) <br> `results/fusion_summary_ependymoma_foi.tsv` (included in data download) <br> `results/fusion_summary_ewings_foi.tsv`
| [`gene-set-enrichment-analysis`](https://github.com/AlexsLemonade/OpenPBTA-analysis/tree/master/analyses/gene-set-enrichment-analysis) |  adding 8 samples #749 and used in subtyping  | Updated gene set enrichment analysis with appropriate RNA-seq expression data | `results/gsva_scores_stranded.tsv` <br> `results/gsva_scores_polya.tsv` <br> for stranded, polya expression data respectively
| [`independent-samples`](https://github.com/AlexsLemonade/OpenPBTA-analysis/tree/master/analyses/independent-samples) | adding 8 samples #749 and used in subtyping  | Generates independent specimen lists for WGS/WXS samples updated in  #795 and #797 and [comment](https://github.com/AlexsLemonade/OpenPBTA-analysis/issues/750#issuecomment-691526896)| `results/independent-specimens.wgs.primary.tsv` (included in data download) <br> `results/independent-specimens.wgs.primary-plus.tsv` (included in data download) <br> `results/independent-specimens.wgswxs.primary.tsv` (included in data download) <br> `results/independent-specimens.wgswxs.primary-plus.tsv` (included in data download) <br> `results/independent-specimens.rnaseq.primary-plus-stranded.tsv`(included in data download) <br> `results/independent-specimens.rnaseq.primary-plus-polya.tsv` (included in data download)
| [`transcriptomic-dimension-reduction`](https://github.com/AlexsLemonade/OpenPBTA-analysis/tree/master/analyses/transcriptomic-dimension-reduction)| adding 8 samples #749 used in subtyping | Dimension reduction and visualization of RNA-seq data  | N/A

**Subtyping modules** 
| Module |  Reason |Brief Description | output
|--------|----------|--------|------
| [`molecular-subtyping-CRANIO`](https://github.com/AlexsLemonade/OpenPBTA-analysis/tree/master/analyses/molecular-subtyping-CRANIO) | to add subtyping to base histology  | Molecular subtyping of craniopharyngiomas samples  | `results/CRANIO_molecular_subtype.tsv`
| [`molecular-subtyping-EPN`](https://github.com/AlexsLemonade/OpenPBTA-analysis/tree/master/analyses/molecular-subtyping-EPN) | to add subtyping to base histology  | Molecular subtyping of ependymoma tumors | `results/EPN_all_data_withsubgroup.tsv`
| [`molecular-subtyping-EWS`](https://github.com/AlexsLemonade/OpenPBTA-analysis/tree/master/analyses/molecular-subtyping-EWS) | to add subtyping to base histology | Reclassification of tumors based on the presence of defining fusions for Ewing Sarcoma per | `results/EWS_samples.tsv`
| [`molecular-subtyping-HGG`](https://github.com/AlexsLemonade/OpenPBTA-analysis/tree/master/analyses/molecular-subtyping-HGG) | to add subtyping to base histology  | Molecular subtyping of high-grade glioma samples | `results/HGG_molecular_subtype.tsv`
| [`molecular-subtyping-LGAT`](https://github.com/AlexsLemonade/OpenPBTA-analysis/tree/master/analyses/molecular-subtyping-LGAT)| to add subtyping to base histology | Molecular subtyping of Low-grade astrocytic tumor samples  | `results/lgat_subtyping.tsv`
| [`molecular-subtyping-MB`](https://github.com/AlexsLemonade/OpenPBTA-analysis/tree/master/analyses/molecular-subtyping-MB) | to add subtyping to base histology  | Molecular classification of Medulloblastoma subtypes | `results/MB_molecular_subtype.tsv` <br> `results/MB_batchcorrected_molecular_subtype.tsv` <br> for uncorrected and batch-corrected input matrix
| [`molecular-subtyping-embryonal`](https://github.com/AlexsLemonade/OpenPBTA-analysis/tree/master/analyses/molecular-subtyping-embryonal) | to add subtyping to base histology | Molecular subtyping of non-medulloblastoma, non-ATRT embryonal tumors | `results/embryonal_tumor_molecular_subtypes.tsv`
| [`molecular-subtyping-neurocytoma`](https://github.com/AlexsLemonade/OpenPBTA-analysis/tree/master/analyses/molecular-subtyping-neurocytoma) | to add subtyping to base histology | Molecular subtyping of Neurocytoma samples | `results/neurocytoma_subtyping.tsv`
| [`molecular-subtyping-pathology`](https://github.com/AlexsLemonade/OpenPBTA-analysis/tree/master/analyses/molecular-subtyping-pathology) | to add subtyping to base histology  | Compile output from other molecular subtyping modules and incorporate pathology feedback  | `results/compiled_molecular_subtyping_with_pathology_feedback.tsv`
| [`molecular-subtyping-integrate`](https://github.com/AlexsLemonade/OpenPBTA-analysis/tree/master/analyses/molecular-subtyping-integrate) |  to add subtyping to base histology | Add molecular subtype information to base histology | `results/pbta-histologies.tsv`

#### What changes need to be made? Please provide enough detail for another participant to make the update.
8 new samples were added, as of v18 we only obtain a QC-ed base histology which we will add combined subtyping from molecular-subtyping-pathology

#### What input data should be used? Which data were used in the version being updated?
Any stranded RNA-Seq data 
All inputs needed for subtyping

#### When do you expect the revised analysis will be completed?
~ 1 week

#### Who will complete the updated analysis?
@kgaonkar6

**Comment by jaclyn-taroni** [comment]
v18 is out, closing this!
