### ISSUE TITLE
v18 breaks: Interaction plots failing -- tried using `broad_histology` 

### ISSUE THREAD

**Issue by cansavvy** [AlexsLemonade/OpenPBTA-analysis#880]
#### What analysis module should be updated and why?

With v18 data, interaction plots is broken. 
See the discussion on https://github.com/AlexsLemonade/OpenPBTA-analysis/pull/876#issuecomment-749730138

#### What changes need to be made? Please provide enough detail for another participant to make the update.

It was proposed that changing these scripts to plot `broad_histology` instead of using `integrated_diagnosis` as they do now might fix this problem. 

I tried to implement this by replacing instances of `integrated_diagnosis` with `broad_histology` and re-running with the full data set but it gave the same error -- something about the `comb()` function within `coocurrence()` custom function. 

```
Error in combn(genes, m = 2) : n < m
Calls: coocurrence -> t -> combn
Execution halted
```

Here's the circle CI run where this error was initially found if you'd like to see more: https://app.circleci.com/pipelines/github/AlexsLemonade/OpenPBTA-analysis/4722/workflows/27d03a80-9cfe-415d-ad7f-f941c5ac8307/jobs/5260

#### What input data should be used? Which data were used in the version being updated?

v18 data

#### When do you expect the revised analysis will be completed?

Not sure

#### Who will complete the updated analysis?
Someone who is more familiar with `interaction-plots` ideally.

**Comment by cansavvy** [comment]
I think #889 and #627 might help resolve some issues related to this.

**Comment by cbethell** [comment]
The interaction plots script hard codes which categories to look at, so #889 will need to be tackled before this issue can be tackled as we will need the most accurate `broad_histology` categories for hard coding.

**Comment by jaclyn-taroni** [comment]
I'm going to close this in favor of #910 because I think that's the strategy we should pursue. I will note on that issue that the module also needs to be added back to CI (uncommented out).
