### ISSUE TITLE
v18 breaks: color palettes need updating for the `short_histology` changes. 

### ISSUE THREAD

**Issue by cansavvy** [AlexsLemonade/OpenPBTA-analysis#882]
#### What analysis module should be updated and why?

I think the changes in `short_histology` for v18 `pbta-histologies.tsv` means the color key is out of date. 

There's at least `Melanocytoma` that is not covered by the current `figures/palettes/histology_color_palette.tsv`. But while we are at it, we should check for any other `short_histology` labels that are new and not covered by the color key. Or remove any `short_histology` groups that are no longer in the dataset and are obsolete. 

#### What changes need to be made? Please provide enough detail for another participant to make the update.

`figures/palettes/histology_color_palette.tsv` needs updating so all categories in the v18 pbta-histologies.tsv short_histology are covered. 

If this is done, I suspect the errors we see with these modules should be resolved:
- Chromosomal instability breakpoints
- CN Status heatmap
- Oncoprint plotting

After the color palette is updated, these modules and any other modules that use this `histology_color_palette.tsv` should be re-run and their plots re-pushed to GitHub. 

This error on chromosomal instability is what initially led to this: 
```
Quitting from lines 262-278 (02a-plot-chr-instability-heatmaps.Rmd) 
Error in col2rgb(colors, alpha = TRUE) : 
  invalid color name 'Melanocytoma'
Calls: <Anonymous> ... do.call -> <Anonymous> -> ColorMapping -> t -> col2rgb
```

Here's the link to the full Circle CI error for Chromosomal instability: 
https://app.circleci.com/pipelines/github/AlexsLemonade/OpenPBTA-analysis/4723/workflows/7cfcbf40-cb39-4e3c-981d-9e981ca23b1e/jobs/5261

Here's the link to Oncoprint plotting's error in Circle CI: 
https://app.circleci.com/pipelines/github/AlexsLemonade/OpenPBTA-analysis/4725/workflows/e3e1a7b7-7217-4a1b-9c19-f905e26150e9/jobs/5263

Because of these errors I automatically skipped CN status heatmap since it should also have broken (so i have no link for CN status heatmap). 

I originally documented this on this PR: https://github.com/AlexsLemonade/OpenPBTA-analysis/pull/876

#### What input data should be used? Which data were used in the version being updated?

v18 pbta-histologies.tsv

#### When do you expect the revised analysis will be completed?
Not sure

#### Who will complete the updated analysis?
This *should* be a relatively straightforward fix (if it works).

**Comment by cansavvy** [comment]
Here's the new `short_histology` groups that don't have colors in `histology_color_palette.tsv`. Some of these seem like they are probably more appropriately labeled as groups that already exist. Like is `EPN` the same as `Ependymoma`? 

```
1  Arteriovenous malformation      <NA>
2                   Cavernoma      <NA>
3                     CNS RMS      <NA>
4                        Cyst      <NA>
5                    Epilepsy      <NA>
6                         EPN      <NA>
7                     Fibroma      <NA>
8          Fibromixoid lesion      <NA>
9              Ganglioneuroma      <NA>
10            Germ cell tumor      <NA>
11                  Hamartoma      <NA>
12                        JXG      <NA>
13        Lymphoid infiltrate      <NA>
14               Melanocytoma      <NA>
15       Meningioangiomatosis      <NA>
16                 Metastases      <NA>
17      Myofibroblastic tumor      <NA>
18  Myxoid spindle cell tumor      <NA>
19              Neuroblastoma      <NA>
20                Neurocytoma      <NA>
21              Osteoblastoma      <NA>
22                Perineuroma      <NA>
23               Prolactinoma      <NA>
24            Reactive tissue      <NA>
25              Rosai-dorfman      <NA>
26                    Sarcoma      <NA>
27                       SEGA      <NA>
28            Xanthogranuloma      <NA>
29                       NA's      <NA>
```

**Comment by cansavvy** [comment]
There's more discussion about these new `short_histology` groups here: https://github.com/AlexsLemonade/OpenPBTA-analysis/pull/870#issuecomment-749745542

**Comment by cansavvy** [comment]
Ahh, actually https://github.com/AlexsLemonade/OpenPBTA-analysis/issues/627 should inform us about this.

**Comment by jharenza** [comment]
> But n=2 will be harder to track in heatmaps, particularly when things like `EPN` and `Ependymoma` seem like they are the same category to me? (see above comment [#882 (comment)](https://github.com/AlexsLemonade/OpenPBTA-analysis/issues/882#issuecomment-750407882))

This was an error introduced in the new histologies file (#889) and we will keep only `Ependymoma` once this is updated. cc @kgaonkar6

**Comment by jaclyn-taroni** [comment]
Subsumed by #898 in my opinion (See: https://github.com/AlexsLemonade/OpenPBTA-analysis/issues/898#issuecomment-761696785)
