### ISSUE TITLE
v18 breaks: Comparative RNA-seq has some errors

### ISSUE THREAD

**Issue by cansavvy** [AlexsLemonade/OpenPBTA-analysis#883]
#### What analysis module should be updated and why?

With the v18 data changes `analyses/comparative-RNASeq-analysis/01-correlation-matrix.py` is throwing some errors. 

My suspicion is that `pbta-mend-qc-results.tar.gz` is not up to date with the new samples. 
```
^@^@Loading sample matrix ../../data/pbta-gene-expression-rsem-tpm.polya.rds
Traceback (most recent call last):
  File "analyses/comparative-RNASeq-analysis/01-correlation-matrix.py", line 231, in <module>
    main()
  File "analyses/comparative-RNASeq-analysis/01-correlation-matrix.py", line 218, in main
    verbose=args.verbose)
  File "analyses/comparative-RNASeq-analysis/01-correlation-matrix.py", line 74, in filter_samples
    qc_status = get_qc_status(mend_results_path, mend_manifest_path)
  File "analyses/comparative-RNASeq-analysis/01-correlation-matrix.py", line 43, in get_qc_status
    filename_map = { i.name : extract_sample_qc_status(mend_tgz.extractfile(i), i.name) for i in qc_files }
  File "analyses/comparative-RNASeq-analysis/01-correlation-matrix.py", line 43, in <dictcomp>
    filename_map = { i.name : extract_sample_qc_status(mend_tgz.extractfile(i), i.name) for i in qc_files }
  File "analyses/comparative-RNASeq-analysis/01-correlation-matrix.py", line 30, in extract_sample_qc_status
    status = qc_file_handle.readlines()[1][-5:-1].decode("utf-8")
IndexError: list index out of range
```

It is unclear to me what is causing this error. I suspect it's related to the 8 added samples or the RNA independent specimen edits. Or that some input file it is taking is not updated correctly. 

Circle CI error is here: https://app.circleci.com/pipelines/github/AlexsLemonade/OpenPBTA-analysis/4724/workflows/c15e9c0f-c38a-454b-a6a8-9bbf92ece9b4/jobs/5262

Note that I (maybe prematurely?) Commented out (aka did not test) the following two Comparative RNA-seq Circle CI tests because it seemed they were dependent on each other.

It appears that the RNA-seq composition module is also dependent on some output files from this module, so it has also failed and will need some re-running after this is fixed: 

Here's RNA-seq composition's error. 
https://app.circleci.com/pipelines/github/AlexsLemonade/OpenPBTA-analysis/4728/workflows/b02573a3-258a-495b-a796-ec3af1b72f21/jobs/5266

It can't find the file `bam_umend_qc.tsv` which comes from Comparative RNA-seq it looks like. 

#### What changes need to be made? Please provide enough detail for another participant to make the update.

More investigation is needed. I am admittedly not much help on this one. 

#### What input data should be used? Which data were used in the version being updated?

v18 data

#### When do you expect the revised analysis will be completed?

Not sure

#### Who will complete the updated analysis?

Someone who is more familiar with the Comparative RNA-seq analyses.

**Comment by jashapiro** [comment]
I don't think this is really blocked by #890. Fixing #890 would have fixed it, but we also fixed it by looking at the manifest file and only pulling files from there, rather than all of the files.

**Comment by jashapiro** [comment]
I'm wrong. This should be a blocker. Or at least a documented/explained change.

**Comment by jaclyn-taroni** [comment]
This is now closed.
