### ISSUE TITLE
Updated analysis: CI v18 histology subset file

### ISSUE THREAD

**Issue by kgaonkar6** [AlexsLemonade/OpenPBTA-analysis#887]
#### What analysis module should be updated and why?

~~BLOCKED~~
#879 pbta-histologies.tsv needs to be updated by running #869 and #870 

Additionally since I’ve updated histology file with the new broad/short/harm_dx for pathology_dx== “Other” samples in #870 that also needs to be updated before file is updated to s3 bucket . 

So now for v18 pbta-histologies.tsv the process is:
<img width="567" alt="Screen Shot 2020-12-24 at 3 21 27 PM" src="https://user-images.githubusercontent.com/34580719/103105428-c63e1f80-45fb-11eb-8548-28bcba0b2dba.png">

These changes were added because the "Other" samples needed more consistent short/broad histology values to be easier to plot. As discussed in #870 more specifically the https://github.com/AlexsLemonade/OpenPBTA-analysis/pull/870#pullrequestreview-557885877 has the google sheet that was used to update the broad/short histology terms for "Other" samples to be more consistent.

#### What changes need to be made? Please provide enough detail for another participant to make the update.
Use v18 histology file from s3 to generate CI subset file.

#### What input data should be used? Which data were used in the version being updated?
pbta-histologies.tsv

#### Who will complete the updated analysis?
requesting @cansavvy to add the update, thanks!

**Comment by cansavvy** [comment]
The pbta-histologies.tsv and md5sum.txt files have been updated on S3 for Circle CI testing purposes: https://github.com/AlexsLemonade/OpenPBTA-analysis/pull/888#issuecomment-754746049 I think this issue can be closed.
