### ISSUE TITLE
pbta-mend-qc-results.tar.gz format has changed, and contains extraneous files and attributes

### ISSUE THREAD

**Issue by jashapiro** [AlexsLemonade/OpenPBTA-analysis#890]
#### What data file(s) does this issue pertain to?

`pbta-mend-qc-results.tar.gz`

#### What release are you using?

v18

#### Put your question or report your issue here.

The `pbta-mend-qc-results.tar.gz` file appears to have been created on a Mac, resulting in the inclusion of some hidden files and attributes that are not widely supported.

Most notably, it includes the following hidden file, which broke a script (see #883):
`pbta-mend-qc-results/._b9c39140-5dd2-495c-889d-8cd3499cf504.bam_umend_qc.tsv`

The script will be fixed to make it more robust, but others using the files may also encounter unexpected results, including  warnings like the following when decompressing the archive in the docker image for this project: 

```
tar: Ignoring unknown extended header keyword 'SCHILY.dev'
tar: Ignoring unknown extended header keyword 'SCHILY.ino'
tar: Ignoring unknown extended header keyword 'SCHILY.nlink'
tar: Ignoring unknown extended header keyword 'LIBARCHIVE.creationtime'
```

**Comment by jharenza** [comment]
Hi @jashapiro. Both @kgaonkar6 and I un-tarred on our computers, but do not see any hidden files. Do you think this is happening via CI (is there a new CI file for this) or specific to the docker environment?

**Comment by jashapiro** [comment]
Yes, kind of. The hidden file is something related to extended attributes that get merged back in with the file when it is uncompressed on a Mac. So the errors/warnings will show up on any linux machine, including the docker image. It also shows up when a program uses the tar file while leaving it compressed, as some scripts do.

**Comment by jharenza** [comment]
Ah, gotcha. Just wanted to be sure we didn't have to update that in the data download.

**Comment by jashapiro** [comment]
> Ah, gotcha. Just wanted to be sure we didn't have to update that in the data download.

Ideally, we would. But I don't think it blocks v18.

**Comment by jashapiro** [comment]
The problem is more significant than I had first thought. In addition to the extraneous files, the internal format of the file has in fact changed, and this is breaking the script that uses it. In v17, the contents of the tar file are flat: each file is separately stored, with no folder enclosing them. In v18, the files are enclosed in a `pbta-mend-qc-results` folder. 

Because of the way these are accessed, this breaks the scripts in #883. While it is possible to make the scripts partially robust to this, a change like this is not really desirable, unless there was a particular justification behind it. I would suggest remaking this file for V18 to keep the previous format, and doing so on a linux machine (or in the docker image) to prevent the extraneous attributes mentioned earlier. 

V17 (bare files)
```
>>> [f.name for f in mend_tgz17.getmembers()[:10]]
['004383d0-9f9f-431d-8684-288805a86e37.bam_umend_qc.tsv', '004383d0-9f9f-431d-8684-288805a86e37.readDist.txt', '006835f8-8268-4e3d-97f8-67ca83761d4c.bam_umend_qc.tsv', '006835f8-8268-4e3d-97f8-67ca83761d4c.readDist.txt', '00cbefa4-e79c-47cb-831d-de48268b14e1.bam_umend_qc.tsv', '00cbefa4-e79c-47cb-831d-de48268b14e1.readDist.txt', '00df43b3-15e5-4975-81af-cb775d663cc7.bam_umend_qc.tsv', '00df43b3-15e5-4975-81af-cb775d663cc7.readDist.txt', '0231e385-162c-43d0-8c7d-882d1ea8a7ef.bam_umend_qc.tsv', '0231e385-162c-43d0-8c7d-882d1ea8a7ef.readDist.txt']
```

V18 (enclosed)
```
>>> [f.name for f in mend_tgz18.getmembers()[:10]]
['pbta-mend-qc-results', 'pbta-mend-qc-results/5dbe7818-a57b-40ca-ad27-64b4f09a1ed6.bam_umend_qc.tsv', 'pbta-mend-qc-results/e763ef5e-dd73-4405-86d7-49149cef4cd8.bam_umend_qc.tsv', 'pbta-mend-qc-results/8afb3b33-a305-4297-9b32-a439a805690f.bam_umend_qc.tsv', 'pbta-mend-qc-results/57536f83-4e6e-4d5b-8b50-c5f1e2c379ec.bam_umend_qc.tsv', 'pbta-mend-qc-results/24056635-a801-4b2a-acb7-c96dd14d0a23.bam_umend_qc.tsv', 'pbta-mend-qc-results/259e8003-ad23-4871-96fa-e2234c2b8467.readDist.txt', 'pbta-mend-qc-results/aff2c49e-05d6-4e8c-82e9-4edc079fc71f.bam_umend_qc.tsv', 'pbta-mend-qc-results/a9184a64-c684-4a5e-8aa5-527cd9fac79d.readDist.txt', 'pbta-mend-qc-results/49b95468-3c49-4f5b-b26c-58bdaf38d94a.bam_umend_qc.tsv']
```

**Comment by jharenza** [comment]
Ahh, ok - let me see if @migbro can recreate this for V18, since he made the V17 tarball.

**Comment by migbro** [comment]
Hmmm, it's been a while. Can you remind me where the source data is? Is it the same as first first mend qc run? Has anything actually changed since v17 for those files? I could just grab the v17 one and replace v18 one with it.

**Comment by jharenza** [comment]
There were 8 new samples added and the source data to be added to the v17 files are [here](https://github.com/d3b-center/bixu-tracker/issues/767#issuecomment-702283564).

**Comment by migbro** [comment]
Thanks for that! I've created the new archives in the v18 release. I took the v17 release and added the 3 new PNOC and 5 new CBTN files to the old archive. Please let me know if it looks correct. I also updated the manifest file.

**Comment by jharenza** [comment]
thanks @migbro! @jashapiro these are updated in the v18 release - will you test please?

**Comment by jashapiro** [comment]
Thank you @migbro and @jharenza. I am testing the files locally, and all seems well!

@cansavvy Can you update these two files (and the md5 checksum) in CI?

**Comment by cansavvy** [comment]
> @cansavvy Can you update these two files (and the md5 checksum) in CI?

Will do. Thanks.

**Comment by cansavvy** [comment]
These files and the CI md5sum.txt are updated in the S3 testing CI bucket.

**Comment by jashapiro** [comment]
This is fixed both in v18 and in CI. Closing.
