### ISSUE TITLE
Rerun "PBTA histologies" PR code once they are all merged or reexamine results

### ISSUE THREAD

**Issue by jaclyn-taroni** [AlexsLemonade/OpenPBTA-analysis#891]
In the interest of getting the following pull requests through: 

#863 
#864 
#865 
#866 
#868 
#869 
#870 

I am fixing merge conflicts by accepting the changes in `master` – which will be the changes in the earlier (but presumably more recently updated wrt to files with conflicts) pull requests – without critically examining the changes in results files. Once all of these have been approved and merged, we should create a new branch, rerun all of those steps, and examine the diffs for unexpected changes. Since I understand that these pull requests are _upstream_ of the v18 release, we should do this before we merge #867.

Tagging @kgaonkar6 and @jharenza who are more familiar with the code and results in those pull requests.

**Comment by kgaonkar6** [comment]
I just wanted to confirm that when we re-run the "PBTA histologies" PRs mentioned above using the new base histology file fixing #899,  the `pbta-histologies.tsv` created will be used for v18 release #857, right?

**Comment by jharenza** [comment]
Yes!

**Comment by jaclyn-taroni** [comment]
Closed via #896 - is that correct @kgaonkar6 ?

**Comment by kgaonkar6** [comment]
Yes!! 🎉
