### ISSUE TITLE
Make mapping histology groups for plotting -- Part 1 creating the table

### ISSUE THREAD

**Issue by cansavvy** [AlexsLemonade/OpenPBTA-analysis#897]
#### Background:

From https://github.com/AlexsLemonade/OpenPBTA-analysis/issues/627#issuecomment-754813774: 

> I'm going to suggest that we create a **high level histology** list that we can then use for figures. This does not need to be recorded in `pbta_histologies.tsv` but can be a separate table that we keep in the repo directly that serves as a dictionary to map `harmonized_diagnosis` and/or `broad_histology` to some subset of plotable categories. For color reasons, we should strive to have this set of categories be on the order of 10-15 labels.
> 
> At the moment, `broad_histology` has about 24 categories, but many of these only have a few samples, so it would seem likely these could be combined with others for plotting.
> 

To start working on a method to address #627, we need to first create a mapping from harmonized_diagnosis and/or broad_histology to larger groups -- as mentioned in the quote, we ideally want this to narrow down to 10-15 labels that can be used for large summary figures like those of Chromosomal instability breakpoints and CN Status heatmap and Oncoprint plotting. 

This mapping TSV file will be used in all relevant plotting modules and probably end up making `histology_color_palette.tsv` obsolete. 

#### Steps toward creating a mapping TSV table

Step 1) Create a mapping TSV notebook 

I think this mapping should take place in a Rmd that would live in the `/figures` folder and would use whatever the latest data release's pbta-histologies.tsv to create a separate TSV table that contains these columns for mapping. 

- `Kids_First_Biospecimen` 
- `broad_histology` 
-  `summary_group`   - a reasonable name that would be used on the plots themselves as labels 
- `hex_code` - a hex code that can be used as the color for plotting. 

This notebook's main function will be creating this `summary_group` and will ideally send out easy to interpret warnings for when a histology group from `pbta-histologies.tsv` is either missing but expected. 

`summary_group` will probably be created by 
1) Evaluate how many samples there are per `broad_histology` group.
2) Recode larger `summary_group`s based on their `broad_histology` groups. 

Step 2) We'll need someone with domain expert knowledge to check the groupings and make sure they are reasonable. 

Step 3) figures/README.md#color-palette-usage will need updating

Step 4) Implement the resulting mapping TSV file in all relevant modules and probably retiring `histology_color_palette.tsv`. This part is tracked separately here: #898 

#### What input data are required for this analysis?

`pbta-histologies.tsv`

#### How long do you expect is needed to complete the analysis? Will it be a multi-step analysis?
This first part (except for maybe the domain expert check over part) should be able to be completed this week. 

#### Who will complete the analysis (please add a GitHub handle here if relevant)?

@cansavvy

**Comment by jharenza** [comment]
Thanks for taking this on @cansavvy ! I can review.
