### ISSUE TITLE
Updated analysis: Use `harmonized_diagnosis` in HGG subtyping

### ISSUE THREAD

**Issue by cbethell** [AlexsLemonade/OpenPBTA-analysis#901]
#### What analysis module should be updated and why?

`molecular-subtyping-HGG` should be updated as part of #877.

#### What changes need to be made? Please provide enough detail for another participant to make the update.

As noted in the [comment on 877](https://github.com/AlexsLemonade/OpenPBTA-analysis/issues/877#issuecomment-759796037):

We may want to add `harmonized_diagnosis` rather than replace `integrated_diagnosis` and the following location in the HGG subtyping module.

| Script                                           | Location                                |
|-----------------------|---------------------------------------------------------|
| `molecular-subtyping-HGG/00-HGG-select-pathology-dx.Rmd`       | https://github.com/AlexsLemonade/OpenPBTA-analysis/blob/53c1f7c8534d32da98c20f8e9136899e7dfcce92/analyses/molecular-subtyping-HGG/00-HGG-select-pathology-dx.Rmd#L130 |

This line selects `integrated_diagnosis` as one of the columns to include the final object, therefore this notebook does not look to be _dependent_ upon `integrated_diagnosis`. That said, I believe we would want to add `harmonized_diagnosis` (no absolute need to re-run).

#### What input data should be used? Which data were used in the version being updated?

v18 data is currently used in this notebook (related: #900)

#### When do you expect the revised analysis will be completed?

not more than ~ 1/2 day (potential pitfalls are not obvious)

#### Who will complete the updated analysis?

TBD

**Comment by jaclyn-taroni** [comment]
Good call filing this because #900 wasn't decided yet and we wouldn't want it to get lost! Because I feel fairly sure about the direction noted in https://github.com/AlexsLemonade/OpenPBTA-analysis/issues/900#issuecomment-761687503, I don't think this will be necessary and I am going to close this issue.
