### ISSUE TITLE
Revert LGAT subtyping module 00 notebook to use v17

### ISSUE THREAD

**Issue by cbethell** [AlexsLemonade/OpenPBTA-analysis#902]
#### Background:

Upon digging into #877, it was found that the [`molecular-subtyping-LGAT/00-LGAT-select-pathology-dx.Rmd`](https://github.com/AlexsLemonade/OpenPBTA-analysis/blob/master/analyses/molecular-subtyping-LGAT/00-LGAT-select-pathology-dx.Rmd) file was updated to use v18 files ([line 33](https://github.com/AlexsLemonade/OpenPBTA-analysis/blob/7792a969784e5da6df52b02e23b05b9617c65bb8/analyses/molecular-subtyping-LGAT/00-LGAT-select-pathology-dx.Rmd#L33)) in merged PR #869.

However, the module's `README.md` file currently reads as follows:

_"This does not run the 00-LGAT-select-pathology-dx notebook, as that is intended to be run once and tied to a specific release (release-v17-20200908)"_

#### Suggested Next Steps

The solution we decide on for the HGG subtyping module issue #900, should most likely be propagated here.

Again please feel free to weigh in!

**Comment by jaclyn-taroni** [comment]
Changed title to reflect option 2 on #900 - see that issue for more context!
