### ISSUE TITLE
Updated analysis: Use `harmonized_diagnosis` in LGAT subtyping

### ISSUE THREAD

**Issue by cbethell** [AlexsLemonade/OpenPBTA-analysis#903]
#### What analysis module should be updated and why?

`molecular-subtyping-LGAT` should be updated as part of #877.

#### What changes need to be made? Please provide enough detail for another participant to make the update.

As noted in the [comment on 877](https://github.com/AlexsLemonade/OpenPBTA-analysis/issues/877#issuecomment-759796037):

We may want to add `harmonized_diagnosis` rather than replace `integrated_diagnosis` and the following location in the LGAT subtyping module.

| Script                                           | Location                                |
|-----------------------|---------------------------------------------------------|
| `molecular-subtyping-LGAT/00-LGAT-select-pathology-dx.Rmd`      | https://github.com/AlexsLemonade/OpenPBTA-analysis/blob/53c1f7c8534d32da98c20f8e9136899e7dfcce92/analyses/molecular-subtyping-LGAT/00-LGAT-select-pathology-dx.Rmd#L121 |

This line selects `integrated_diagnosis` as one of the columns to include the final object, therefore this notebook does not look to be _dependent_ upon `integrated_diagnosis`. That said, I believe we would want to add `harmonized_diagnosis` (no absolute need to re-run).

We will also want to ensure that the comments/documentation are still accurate and up to date i.e. https://github.com/AlexsLemonade/OpenPBTA-analysis/blob/7792a969784e5da6df52b02e23b05b9617c65bb8/analyses/molecular-subtyping-LGAT/00-LGAT-select-pathology-dx.Rmd#L15

#### What input data should be used? Which data were used in the version being updated?

v18 data is currently used in this notebook (related: #902)

#### When do you expect the revised analysis will be completed?

not more than ~ 1/2 day (potential pitfalls are not obvious)

#### Who will complete the updated analysis?

TBD

**Comment by jaclyn-taroni** [comment]
The implementation of #902 means we will be using an earlier file that does not contain `harmonized_diagnosis`. Closing this issue.
