### ISSUE TITLE
Revert MB subtyping module 00 notebook to use v17

### ISSUE THREAD

**Issue by cbethell** [AlexsLemonade/OpenPBTA-analysis#906]
#### Background:

It was found that the [`molecular-subtyping-MB/00-MB-select-pathology-dx.Rmd`](https://github.com/AlexsLemonade/OpenPBTA-analysis/blob/master/analyses/molecular-subtyping-MB/00-mb-select-pathology-dx.Rmd) file was updated to use v18 files ([line 34](https://github.com/AlexsLemonade/OpenPBTA-analysis/blob/7792a969784e5da6df52b02e23b05b9617c65bb8/analyses/molecular-subtyping-MB/00-mb-select-pathology-dx.Rmd#L34)) in merged PR #869.

However, the module's `README.md` file currently reads as follows:

_"This Rmd checks the alignment of Medulloblastoma labels across fields: pathology_diagnosis, integrated_diagnosis, and short_histology. It is tied to a specific release (release-v17-20200908)."_

If/when the `README.md` is updated, the comment at line 18 may also need to be updated:
https://github.com/AlexsLemonade/OpenPBTA-analysis/blob/7792a969784e5da6df52b02e23b05b9617c65bb8/analyses/molecular-subtyping-MB/00-mb-select-pathology-dx.Rmd#L18

#### Suggested Next Steps

The solution we decide on for the HGG subtyping module issue #900 and the LGAT subtyping module issue #902, should most likely be propagated here.

**Comment by jaclyn-taroni** [comment]
Changed title to reflect option 2 on #900 - see that issue for more context!
