### ISSUE TITLE
Updated analysis: Use `harmonized_diagnosis` in MB subtyping

### ISSUE THREAD

**Issue by cbethell** [AlexsLemonade/OpenPBTA-analysis#907]
#### What analysis module should be updated and why?

`molecular-subtyping-MB` should be updated as part of #877.

#### What changes need to be made? Please provide enough detail for another participant to make the update.

As noted in the [comment on 877](https://github.com/AlexsLemonade/OpenPBTA-analysis/issues/877#issuecomment-759796037):

`integrated_diagnosis` in the line below is being used to filter to values = "Medulloblastoma" in `00-mb-select-pathology-dx.Rmd`, therefore we will likely want to replace it here with `harmonized_diagnosis` and re-run the notebook and/or module.

| Script                                           | Location                                |
|-----------------------|---------------------------------------------------------|
| `molecular-subtyping-MB/00-mb-select-pathology-dx.Rmd`             | https://github.com/AlexsLemonade/OpenPBTA-analysis/blob/53c1f7c8534d32da98c20f8e9136899e7dfcce92/analyses/molecular-subtyping-MB/00-mb-select-pathology-dx.Rmd#L58 |

Note that I linked the main instance where `integrated_diagnosis` should be replaced with `harmonized_diagnosis` above, however, there are other instances/comments throughout the notebook where this change will need to be propagated.

#### What input data should be used? Which data were used in the version being updated?

v18 data is currently used in this notebook (related: #906)

#### When do you expect the revised analysis will be completed?

~ 1 day (potential pitfalls are not obvious)

#### Who will complete the updated analysis?

TBD

**Comment by jaclyn-taroni** [comment]
The implementation of #906 means we will be using an earlier file that does not contain `harmonized_diagnosis`. Closing this issue.
