### ISSUE TITLE
Updated analysis: Use `harmonized_diagnosis` in interaction plots module

### ISSUE THREAD

**Issue by cbethell** [AlexsLemonade/OpenPBTA-analysis#910]
#### What analysis module should be updated and why?

`interaction-plots` should be updated as part of #877.

#### What changes need to be made? Please provide enough detail for another participant to make the update.

As noted in the [comment on 877](https://github.com/AlexsLemonade/OpenPBTA-analysis/issues/877#issuecomment-759796037):

The main instances of `integrated_diagnosis` that need to be replaced with `harmonized_diagnosis` are linked below (noting that there are three individual scripts/notebooks that will need to be updated in this module).
Although only the main instances (instances that would affect the output) are linked below, changes should be propagated throughout each of the scripts/notebooks (including comments, file names, etc.) and the notebooks and/or module should be re-run.

| Script                                           | Location                                |
|-----------------------|---------------------------------------------------------|
| `interaction-plots/scripts/01-disease-specimen-lists.R`    | https://github.com/AlexsLemonade/OpenPBTA-analysis/blob/ab673df68e4f10124f58463dbeb87ea4f800f9d5/analyses/interaction-plots/scripts/01-disease-specimen-lists.R#L67 <br> https://github.com/AlexsLemonade/OpenPBTA-analysis/blob/ab673df68e4f10124f58463dbeb87ea4f800f9d5/analyses/interaction-plots/scripts/01-disease-specimen-lists.R#L91 |
| `interaction-plots/scripts/02-process_mutations.R` | https://github.com/AlexsLemonade/OpenPBTA-analysis/blob/ab673df68e4f10124f58463dbeb87ea4f800f9d5/analyses/interaction-plots/scripts/02-process_mutations.R#L336 |
| `interaction-plots/scripts/03-plot_interactions.R`   | https://github.com/AlexsLemonade/OpenPBTA-analysis/blob/ab673df68e4f10124f58463dbeb87ea4f800f9d5/analyses/interaction-plots/scripts/03-plot_interactions.R#L133 <br> If/when the other notebooks noted above in the `interaction-plots` module, the comment here should also be updated |

#### What input data should be used? Which data were used in the version being updated?

It appears that the results in this module are from a run with v15 data (merged PRs #595 and #639).
`interaction-plots/01-create-interaction-plots.sh` was updated in merged PR #764 but appears that it was not re-ran.

We will still want to remember to re-run this module with the v18 data when making the updates mentioned above.

#### When do you expect the revised analysis will be completed?

~ 1 day (potential pitfalls are not obvious)

#### Who will complete the updated analysis?

TBD

**Comment by jaclyn-taroni** [comment]
This module is currently commented out in CI because v18 introduced a breaking change. When this is addressed, we need to make sure it gets run in CI again!
