### ISSUE TITLE
Updated analysis: Update LGAT subtyping script 02

### ISSUE THREAD

**Issue by jharenza** [AlexsLemonade/OpenPBTA-analysis#923]
#### What analysis module should be updated and why?
[LGAT subtyping](https://github.com/AlexsLemonade/OpenPBTA-analysis/tree/master/analyses/molecular-subtyping-LGAT)

#### What changes need to be made? Please provide enough detail for another participant to make the update.
I realized when attempting to add #905 that the old LGAT subtyping results file (`../molecular-subtyping-LGAT/results/lgat_subtyping.tsv`) does not exist, but also that the updated LGAT module was not assessing BRAF and other kinase fusions in the way in which we want according to what was done for #665. See #830. So sorry, @kgaonkar6 - I missed this when I reviewed!

The BRAF and kinase fusions should simply be pulled from this [analysis](https://github.com/AlexsLemonade/OpenPBTA-analysis/tree/master/analyses/fusion-summary) in which we assessed kinase domain and reciprocality. 

#### What input data should be used? Which data were used in the version being updated?
See above, V18

#### When do you expect the revised analysis will be completed?
next week

#### Who will complete the updated analysis?
@kgaonkar6

**Comment by kgaonkar6** [comment]
We are using the file directly from fusion-summary , just formatting to the subtype specific columns:

https://github.com/AlexsLemonade/OpenPBTA-analysis/blob/0ed49b68a62462d2c96495ffea1bdadd5b4ff835/analyses/molecular-subtyping-LGAT/02-subset-fusion-files-LGAT.Rmd#L48-L81

columnname | description | values
-- | -- | --
KIAA_BRAF_fus | contains KIAA1549-BRAF fusion | "Yes" fusion exists, "No" fusion is absent
MAPK_fus | contains non-canonical BRAF fusion other than KIAA1549-BRAF; contains RAF1 fusion | "Yes" fusion exists, "No" fusion is absent
RTK_fus | harbors a fusion in ALK, ROS1, NTRK1, NTRK2,NTRK3 or PDGFR | "Yes" fusion exists, "No" fusion is absent
FGFR_fus | harbors FGFR1-TACC1 or other FGFR1 or FGFR2 fusion | "Yes" fusion exists, "No" fusion is absent
MYB_fus | harbors either a MYB-QKI fusion or other MYB or MYBL1 fusion | "Yes" fusion exists, "No" fusion is absent

I am working on creating ../molecular-subtyping-LGAT/results/lgat_subtyping.tsv for #905 and to complete the LGAT analysis, not sure what I've missed for the fusion analysis in 02 script. Can you explain?

**Comment by jharenza** [comment]
Ah, false alarm. I missed that part when I went back through to check! I think we are good!
