### ISSUE TITLE
symlinks instructions in README

### ISSUE THREAD

**Issue by jharenza** [AlexsLemonade/OpenPBTA-analysis#94]
#### File(s)

_What data file(s) does this issue pertain to?_

#### Release

_What release are you using?_

#### Link to [OpenPBTA-manuscript](https://github.com/AlexsLemonade/OpenPBTA-manuscript/)

_Put a link to the relevant section of the OpenPBTA manuscript here._

#### Question/issue

_Put your question or report your issue here._
We had some confusions about how to use symlinks with R, and the R.utils package installed with the docker should have been able to read symlinks, but was unable to (with #92), so `file.path` had to be used instead. May be good to add some of the detail around use of symlinks for specific types of files with R to the README.

**Comment by jaclyn-taroni** [comment]
For my reference, this is the specific commit: https://github.com/AlexsLemonade/OpenPBTA-analysis/pull/92/commits/777fa8d5f08a1643e4464eba783cc1361d994960

**Comment by jharenza** [comment]
I think we can close this, as this was resolved in the comments of the commit above.
