### ISSUE TITLE
Updated analysis: chordoma subtyping to use pathology diagnosis

### ISSUE THREAD

**Issue by jharenza** [AlexsLemonade/OpenPBTA-analysis#941]
#### What analysis module should be updated and why?
chordoma subtyping

#### What changes need to be made? Please provide enough detail for another participant to make the update.
Along with #608, we also need to switch from using `short_histology` to using `pathology_diagnosis`. Thanks to @baileyckelly's eagle 👀 , it was brought to my attention that some of the samples in this module are not actually chordomas, but choroid plexus tumors, and this was my bad when assigning `short_histology` early on. This is fixed in the current release, but will decrease our N here.

| Kids_First_Participant_ID | Kids_First_Biospecimen_ID_DNA | Kids_First_Biospecimen_ID_RNA | pathology_diagnosis      | sample_id |
|---------------------------|-------------------------------|-------------------------------|--------------------------|-----------|
| PT_F1086Z0A               | BS_P4D8Y3S8                   | BS_BWZTMWTM                   | Chordoma                 | 7316-1101 |
| PT_HFQNKP5X               | BS_YB07VF1X                   | BS_9GN1QA3Q                   | Chordoma                 | 7316-2935 |
| PT_HFQNKP5X               | BS_EJ9JKM1C                   | BS_6F49F7WH                   | Chordoma                 | 7316-3295 |
| PT_WTMSD2WB               | BS_67PX06P3                   | BS_JTBM5TSE                   | Chordoma                 | 7316-3632 |
| PT_HFQNKP5X               | BS_DBDXCXT5                   | BS_5B6XZ7YP                   | Chordoma                 | 7316-4062 |
| PT_HFQNKP5X               | BS_GFM6EA61                   | BS_FBJ516WW                   | Chordoma                 | 7316-921  |
| PT_3WA7SBQ6               | BS_0VRSD9V3                   | BS_HN8DE43A                   | Choroid plexus carcinoma | 7316-2248 |
| PT_41BCPB7R               | BS_64HCD9K3                   | NA                            | Choroid plexus carcinoma | 7316-406  |
| PT_7TRGHZBK               | BS_W36RZSFA                   | BS_XEVMEYFS                   | Choroid plexus carcinoma | 7316-431  |
| PT_YZ8A8A36               | BS_GSVCN2XC                   | BS_59FR1NC2                   | Choroid plexus carcinoma | 7316-723  |

#### What input data should be used? Which data were used in the version being updated?
V18

#### When do you expect the revised analysis will be completed?
next week

#### Who will complete the updated analysis?
@kgaonkar6 or @jharenza

**Comment by jharenza** [comment]
When going to inspect one of the samples, I just realized that the `Kids_First_Biospecimen_ID_DNA` and `Kids_First_Biospecimen_ID_RNA` column labels are swapped, so we also have to update this.

https://github.com/AlexsLemonade/OpenPBTA-analysis/blob/ce57f8c58e09724a72df99dea9ca75c31975f178/analyses/molecular-subtyping-chordoma/01-Subtype-chordoma.Rmd#L176-L182

**Comment by kgaonkar6** [comment]
I've updated the code to address the above 2 issues. While reviewing changes I also looked at SMARCB1 loss do we want to keep samples with 2 copies as `loss` as well?
<img width="1189" alt="Screen Shot 2021-02-16 at 11 08 29 AM" src="https://user-images.githubusercontent.com/34580719/108089390-89b10200-7047-11eb-8317-740496ac553f.png">

**Comment by jharenza** [comment]
Thanks @kgaonkar6 - hmm, yes, keep since the N was small and we reviewed them all. Will you add copy number as well as tumor ploidy to the final output file here and in #608 , we will add the molecular subtype based on the path review.

**Comment by jharenza** [comment]
completed with #944
