### ISSUE TITLE
duplicate RNA-Seq BS_ID in clinical file

### ISSUE THREAD

**Issue by jharenza** [AlexsLemonade/OpenPBTA-analysis#95]
#### File(s)

_What data file(s) does this issue pertain to?_

#### Release
V2/V3

_What release are you using?_

#### Link to [OpenPBTA-manuscript](https://github.com/AlexsLemonade/OpenPBTA-manuscript/)

_Put a link to the relevant section of the OpenPBTA manuscript here._

#### Question/issue

_Put your question or report your issue here._
`BS_6DCSD5Y6` is duplicated for its RNA-Seq entry in the clinical file RNA-Seq and this is due to two different ages at diagnosis. Will look into which is correct - we may have a discrepancy between KF DRC and Pedcbio portal. Will also fix this with V4. cc: @yuankunzhu

**Comment by jharenza** [comment]
Age of `2955` was correct. Will update this file in V4 and also add units of days to the age column.

**Comment by cgreene** [comment]
Nice detective work! 👍

**Comment by jharenza** [comment]
updated in #101
