### ISSUE TITLE
Docker installing `units` failures

### ISSUE THREAD

**Issue by cansavvy** [AlexsLemonade/OpenPBTA-analysis#952]
### Summary

When Docker builds in the data download step, sometimes a package called `units` fails to install: 

https://app.circleci.com/pipelines/github/AlexsLemonade/OpenPBTA-analysis/5116/workflows/ece6709e-1c0d-4cb8-be7b-9051f956d722/jobs/5714
```
configure: error: in `/tmp/RtmpHpJSHz/R.INSTALL326563bcd8f/units':
configure: error: 
--------------------------------------------------------------------------------
  Configuration failed because libudunits2.so was not found. Try installing:
    * deb: libudunits2-dev (Debian, Ubuntu, ...)
    * rpm: udunits2-devel (Fedora, EPEL, ...)
    * brew: udunits (OSX)
  If udunits2 is already installed in a non-standard location, use:
    --configure-args='--with-udunits2-lib=/usr/local/lib'
  if the library was not found, and/or:
    --configure-args='--with-udunits2-include=/usr/include/udunits2'
  if the header was not found, replacing paths with appropriate values.
  You can alternatively set UDUNITS2_INCLUDE and UDUNITS2_LIBS manually.
--------------------------------------------------------------------------------

See `config.log' for more details
ERROR: configuration failed for package ‘units’
* removing ‘/usr/local/lib/R/site-library/units’
Error in install.packages(opts$PACKAGES, repos = c(bioc_repos, getOption("repos"))) : 
  (converted from warning) installation of package ‘units’ had non-zero exit status
```

I haven't looked into this much yet, but it might be solved by installing `libudunits2-dev` before getting to the R installations.

**Comment by cansavvy** [comment]
`libudunits2-dev` is supposedly already installed: https://github.com/AlexsLemonade/OpenPBTA-analysis/blob/2c1f5faf1f5687fa40b9b30fa6442798bd38557d/Dockerfile#L23 and there was no error or warning about that install failing. Hmm...

**Comment by jaclyn-taroni** [comment]
Here's the status of my investigation:

- When we build the Docker image in CI using the `--no-cache` option (#976), it builds just fine: https://app.circleci.com/pipelines/github/AlexsLemonade/OpenPBTA-analysis/5186/workflows/e8e74608-512f-41a1-87bb-6f890a723a57/jobs/5792
- Similarly, there's no problem building locally with `--no-cache`.
- Recent pull requests have not seen the same intermittent failure. Using #961 as an example, it always passes: https://app.circleci.com/pipelines/github/AlexsLemonade/OpenPBTA-analysis?branch=pull%2F961 In particular, there was an instance where the cache was not used (probably got a new machine!) and there was no problem: https://app.circleci.com/pipelines/github/AlexsLemonade/OpenPBTA-analysis/5162/workflows/af2b50cd-690a-49a5-b809-0365e7269825/jobs/5767. We see success in other PRs, too: https://app.circleci.com/pipelines/github/AlexsLemonade/OpenPBTA-analysis/5178/workflows/2a306bf5-8815-435d-8ae0-628493e5f3c2/jobs/5783

I am going to close this (and #957!) for now, as building "from scratch" is fine and that is better than the alternative – the image _only builds_ when the layer installing `libudunits2-dev` is cached – in my opinion. We can always reopen if this crops back up.
