### ISSUE TITLE
Confirm values of gene count data provided

### ISSUE THREAD

**Issue by ajlee21** [AlexsLemonade/OpenPBTA-analysis#958]
#### What data file(s) does this issue pertain to?

pbta-gene-counts-rsem-expected_count.polya.rds
pbta-gene-counts-rsem-expected_count.stranded.rds

#### What release are you using?

release-v18-20201123

#### Put your question or report your issue here.

I would like to run DESeq2 to compare the expression of samples with matched selection strategies (polyA vs ribo-depleted). 

I wonder if the raw RSEM files are available anywhere in order to use tximport to then pass into DESeq? Or are these count rds files outputs from tximport? I believe these are estimated counts from RSEM based on this script, but I wanted to double check: https://github.com/AlexsLemonade/OpenPBTA-analysis/blob/master/analyses/collapse-rnaseq/00-create-rsem-files.R

Thank you again for your help!

**Comment by jharenza** [comment]
Hi @ajlee21 - these are merges of the raw files with the `gene_id` being a combination of `ensembl_id` and `gene_symbol` and the script you refer to does the merge, so you can use these files. Another good resource is the [data-files-description.md](https://github.com/AlexsLemonade/OpenPBTA-analysis/blob/master/doc/data-files-description.md) file, which describes each data file in our releases. These are annotated as `PBTA data files`, which are usually the raw files derived from the upstream analysis workflow. :)

**Comment by ajlee21** [comment]
This is amazing documentation! Thank you for clarifying this!

**Comment by jaclyn-taroni** [comment]
Just to add that you might look into [`DESeqDataSetFromMatrix()`](https://www.rdocumentation.org/packages/DESeq2/versions/1.12.3/topics/DESeqDataSet-class) for your use case.

**Comment by ajlee21** [comment]
Thanks! I'm still fairly new to RNA-seq world. This question came but because I noticed that the estimated counts obtained from RSEM aren't integers, which makes sense, but the documentation I've been reading has been suggesting to use tximport to summarize the RSEM data and then using `DESeqDataSetFromTximport`. I wasn't sure if I could round the estimated counts from RSEM and use `DESeqDataSetFromMatrix()` as you're suggesting. It sounds like you can, but its not _ideal_. And I wasn't clear on how to use tximport with the merged data, which prompted by question.  

Thank you for following up

**Comment by jashapiro** [comment]
> `DESeqDataSetFromTximport`. I wasn't sure if I could round the estimated counts from RSEM and use `DESeqDataSetFromMatrix()`

Im pretty sure that all the `DESeqDataSet` functions end up rounding (see below for the start of `DESeqDataSetFromTximport`). Not quite sure why they complain when the import is from a matrix specifically. Maybe just to make the user a bit more careful.

```
> DESeq2::DESeqDataSetFromTximport
function (txi, colData, design, ...) 
{
    counts <- round(txi$counts)
   ...
```

**Comment by ajlee21** [comment]
Interesting... Good to know. Thank you

Thank you all for being so helpful and responsive! <3
