### ISSUE TITLE
Low number of matched participant identifiers

### ISSUE THREAD

**Issue by jaclyn-taroni** [AlexsLemonade/OpenPBTA-analysis#96]
#### File(s)

All files

#### Release

`release-v3-20190829`

#### Question/issue

I was attempting to increase the number of matched participants in the subset file to 100 over on #91. I map the biospecimen IDs in each file to the participant IDs: https://github.com/AlexsLemonade/OpenPBTA-analysis/blob/6b47032c4c227ec11e4d076c296c2c921ac5a527/analyses/create-subset-files/01-create_subset_files.Rmd#L208

I find 91 participants in all files https://github.com/AlexsLemonade/OpenPBTA-analysis/blob/6b47032c4c227ec11e4d076c296c2c921ac5a527/analyses/create-subset-files/01-create_subset_files.Rmd#L236

Here are the number of mapped participant ids for each file:
```R
> lapply(participant_id_list, length)
$cnvkit
[1] 939

$controlfreec
[1] 941

$arriba
[1] 1029

$starfusion
[1] 720

$kallisto
[1] 1029

$rsem
[1] 944

$mutect2
[1] 973

$strelka2
[1] 973

$manta
[1] 940

$lumpy
[1] 147
```

I feel like the number of participants in all was higher in release v2 but I don't remember off the top of my head. Alternatively, this strategy for finding matched participants should be changed.

**Comment by jharenza** [comment]
Hmm, it looks like lumpy numbers are low - should be on par with Manta.  Also, from V2, looks like the total N participants in both clinical files is 943. I think the kallisto results you have there are N biospecimens, not patients.

**Comment by jaclyn-taroni** [comment]
Those numbers are for V3, I think the issue is duplicates in the mapping
```R
> head(participant_id_list$kallisto)
[1] "PT_00G007DM" "PT_00G007DM" "PT_01MZ62KG" "PT_02J5CWN5" "PT_02J5CWN5" "PT_02MVZZSW"
> length(unique(participant_id_list$kallisto))
[1] 898
```

**Comment by jaclyn-taroni** [comment]
Adding a `unique` to the mapping step
```R
participant_id_list <- lapply(
  sample_id_list,
  function(sample_ids) {
    participant_ids <- histologies_df %>%
      dplyr::filter(Kids_First_Biospecimen_ID %in% sample_ids) %>% 
      dplyr::pull(Kids_First_Participant_ID)
    unique(participant_ids)
  }
)
```
I get:
```R
> lapply(participant_id_list, length)
$cnvkit
[1] 798

$controlfreec
[1] 798

$arriba
[1] 898

$starfusion
[1] 649

$kallisto
[1] 898

$rsem
[1] 826

$mutect2
[1] 814

$strelka2
[1] 814

$manta
[1] 797

$lumpy
[1] 141
```

**Comment by jharenza** [comment]
I think that looks better - we will look into that lumpy file - seems like we are missing data.

**Comment by jharenza** [comment]
@jaclyn-taroni fyi, if you want to exclude LUMPY for now - https://github.com/AlexsLemonade/OpenPBTA-analysis/issues/97

**Comment by jaclyn-taroni** [comment]
This was resolved in data release v4.
