### ISSUE TITLE
Time to progression in addition to time to death? 

### ISSUE THREAD

**Issue by rgalvin516** [AlexsLemonade/OpenPBTA-analysis#963]
#### What data file(s) does this issue pertain to?
pbta-histologies
#### What release are you using?
<v18>
#### Put a link to the relevant section of the [OpenPBTA-manuscript] here.
N/A

#### Put your question or report your issue here.
I am curious if it would be possible to obtain time to progression for each patient ID? I ask because time to death is not a useful metric for pediatric low-grade tumors, where overall survival is usually excellent but progression free survival can be poor. In the subset of data I am working with, only 1 patient with a low-grade tumor had a death event. When investigating some predictor of interest that is present in both high- and low-grade samples, a cox regression analysis will always be insignificant for the predictor of interest when adjusting for tumor grade since the only deaths are in high-grade samples. Therefore, knowing time to progression could help researchers identify clinically meaningful predictors. May I put in another plug to inquire if overall survival days can be obtained/updated for samples with NA values?

Thank you much for the work and effort with this important project

**Comment by jharenza** [comment]
Hi @rgalvin516! Thanks so much for your interest in the data and for your suggestion. I have a few questions which will help us determine how we can calculate this and add it to the V19 release for you. As long as we define the rules for the calculation, I think we can do this.

1) Is time to progression defined as time to any adverse event (progression, relapse, other?)?

2) In the case of multiple events, would you define time to progression as time to the _first_ event?

Thanks!

Cc @baileyckelly

**Comment by rgalvin516** [comment]
Hello,

Thanks for the quick response and willingness to look into this! 

1) In considering various adverse events (besides death), I think progression/recurrence of the primary diagnosis would be most useful. Potential con-founders include pseudo-progression and radiation necrosis, but it may not be possible to know this knowledge with precision. Second malignancy is another adverse event but couldn't be analyzed thoroughly without knowing treatment exposures

2) I agree with using time to the first event 

Thanks again

**Comment by jharenza** [comment]
Hi @rgalvin516 - it turns out we do have this calculated and can add it with our V19 release #867, which I expect should come out within the next month. It will be our last before manuscript submission, so just wrapping up a few PRs from which files will be derived and added to that release.

**Comment by jharenza** [comment]
This has been added with #1026
