### ISSUE TITLE
Updated analysis: molecular subtyping integrate

### ISSUE THREAD

**Issue by jharenza** [AlexsLemonade/OpenPBTA-analysis#967]
#### What analysis module should be updated and why?
molecular-subtyping-integrate

#### What changes need to be made? Please provide enough detail for another participant to make the update.
Add additional logic to map some of the `pathology_free_text_diagnosis` terms to be included within the final `harmonized_diagnosis` and/or `integrated_diagnosis`, if one exists. For example, we do not subtype meningiomas, but they have histological/clinical subtypes in the WHO (see table below), and we usually capture this information in `pathology_free_text_diagnosis`. We would like to propagate this to the final `harmonized_diagnosis`. 

| pathology_diagnosis | pathology_free_text_diagnosis    | broad_histology | short_histology | harmonized_diagnosis              | checked |
|---------------------|----------------------------------|-----------------|-----------------|-----------------------------------|---------|
| Meningioma          | contains "atypical"              | Meningioma      | Meningioma      | Atypical meningioma               | yes     |
| Meningioma          | contains "anaplastic"            | Meningioma      | Meningioma      | Anaplastic (malignant) meningioma | yes     |
| Meningioma          | contains "clear cell meningioma" | Meningioma      | Meningioma      | Clear cell meningioma             | yes     |
| Meningioma          | contains "meningothelial"        | Meningioma      | Meningioma      | Meningothelial meningioma         | yes     |

#### What input data should be used? Which data were used in the version being updated?
I will provide a table of which values should be mapped and what the resulting diagnosis should be. 

#### When do you expect the revised analysis will be completed?
1-2 weeks

#### Who will complete the updated analysis?
@jharenza for file and @kgaonkar6 for analysis

**Comment by jharenza** [comment]
@jaclyn-taroni and @kgaonkar6 - I finished up this file after discussion with a clinician and pathologists. The file is located [here](https://docs.google.com/spreadsheets/d/1fDXt_YODcSAWDvyI5ISBVhUCu4b5-TFCVWMOwiPeMwk/edit#gid=1210552782), but I wanted some advice/discussion around how to integrate the `rules_by_free_text` tab. Here, I am adding the above meningioma information, which should be straightforward, because the `harmonized_diagnosis` will be exactly as is in the spreadsheet. However, it becomes a bit tricky if any of the samples have previously been subtyped. For those which have been subtyped and are listed here, for ex:

| pathology_diagnosis                           | subtyping module | pathology_free_text_diagnosis | broad_histology            | short_histology | harmonized_diagnosis           |
|-----------------------------------------------|------------------|-------------------------------|----------------------------|-----------------|--------------------------------|
| Low-grade glioma/astrocytoma (WHO grade I/II) | LGAT             | contains "fibrillary"         | Low grade astrocytic tumor | LGAT            | Diffuse fibrillary astrocytoma |

What we will really want the integrated and harmonized diagnoses to say will be `Diffuse fibrillary astrocytoma, alteration`  for example, `Diffuse fibrillary astrocytoma, MYB`. So, should I separate out the file for those which are subtyped or is this enough to pull those for separate logic?

**Comment by jaclyn-taroni** [comment]
Are you able to distill the rules for what ends up in `harmonized_diagnosis` when subtyping has occurred into a sentence or two? (What the final field should be, etc.) And will it be the same across subtyping modules?

**Comment by jharenza** [comment]
> Are you able to distill the rules for what ends up in `harmonized_diagnosis` when subtyping has occurred into a sentence or two? (What the final field should be, etc.) And will it be the same across subtyping modules?

I was thinking about how best to do this. This is not going to be the same across subtyping modules. 

The only two histologies that have been subtyped that I have us updating using `pathology_free_text_diagnosis` are Craniopharyngioma and LGAT, so I wonder if this is better to add to the subtyping modules themselves?

Then, that would leave anything not subtyped to be taken care of here.

**Comment by jaclyn-taroni** [comment]
> I was thinking about how best to do this. This is not going to be the same across subtyping modules.
> 
> The only two histologies that have been subtyped that I have us updating using `pathology_free_text_diagnosis` are Craniopharyngioma and LGAT, so I wonder if this is better to add to the subtyping modules themselves?
> 
> Then, that would leave anything not subtyped to be taken care of here.

What about adding steps, potentially divided up by subtype, to `molecular-subtyping-pathology`, which appears to be upstream of `molecular-subtyping-integrate`?  The point being that `molecular-subtyping-pathology` would then capture all of the pathology- or clinical-related changes or additions to our subtyping process. We'd have to change the docs (e.g., `README.md`) in that module to be more general, but that's fine. 

If you agree, the next move is to split up into issues with instructions by subtype/diagnosis (e.g., Craniopharyngioma, LGAT, Meningioma) so we're set up for pull requests that are manageable in scope & close this. If those issues have very descriptive titles, even better!

**Comment by jharenza** [comment]
> If you agree, the next move is to split up into issues with instructions by subtype/diagnosis (e.g., Craniopharyngioma, LGAT, Meningioma) so we're set up for pull requests that are manageable in scope & close this. If those issues have very descriptive titles, even better!

Sure - will do!

**Comment by jharenza** [comment]
closing since I created individual tickets
