### ISSUE TITLE
Updated analysis: Add oncoprints by `broad_histology` + update consensus maf to use hotspot consensus maf

### ISSUE THREAD

**Issue by jharenza** [AlexsLemonade/OpenPBTA-analysis#968]
#### What analysis module should be updated and why?
oncoprint-landscape

#### What changes need to be made? Please provide enough detail for another participant to make the update.
- Add oncoprints by `broad_histology` in panel form for easier viewing. 

#### What input data should be used? Which data were used in the version being updated?
- Use histology-specific gene lists per #969 
- Update consensus maf to use hotspot consensus maf

#### When do you expect the revised analysis will be completed?
?

#### Who will complete the updated analysis?
someone from CCDL

**Comment by jharenza** [comment]
@cbethell I saw you added a PR as I was writing this! 

In looking at the `independent-specimens.wgswxs.primary.tsv` file being used for the oncoprint, I started thinking of how we want to create panels for this plot since we have such a spread for N per histology (below)

broad_histology | Freq
-- | --
Low-grade astrocytic tumor | 227
Embryonal tumor | 132
Diffuse astrocytic and oligodendroglial   tumor | 80
Ependymal tumor | 60
Benign tumor | 33
Tumors of sellar region | 30
Neuronal and mixed neuronal-glial tumor | 25
Tumor of cranial and paraspinal nerves | 20
Meningioma | 17
Mesenchymal non-meningothelial tumor | 15
Pre-cancerous lesion | 12
Germ cell tumor | 8
Choroid plexus tumor | 7
Histiocytic tumor | 6
Tumor of pineal region | 4
Metastatic tumors | 3
Other astrocytic tumor | 2
Lymphoma | 1
Melanocytic tumor | 1
Non-CNS tumor | 1
Non-tumor | 1
Other tumor | 1

It may look best if we create plots for the following 4 broad histologies and combine all of the others into `Other CNS` while keeping their `broad_histology` labels. 
Low-grade astrocytic tumor
Embryonal tumor
Diffuse astrocytic and oligodendroglial tumor
Ependymal tumor

I am also thinking we may want to remove benign tumor, pre-cancerous lesion, non-CNS tumor, and non-tumor as well, but I will confirm this latter point tonight with @adamcresnick when we meet.

**Comment by cbethell** [comment]
> It may look best if we create plots for the following 4 broad histologies and combine all of the others into `Other CNS` while keeping their `broad_histology` labels.
> Low-grade astrocytic tumor
> Embryonal tumor
> Diffuse astrocytic and oligodendroglial tumor
> Ependymal tumor

Sounds good to me @jharenza! I'll work on implementing this over in that draft PR 👍 

> I am also thinking we may want to remove benign tumor, pre-cancerous lesion, non-CNS tumor, and non-tumor as well, but I will confirm this latter point tonight with @adamcresnick when we meet.

And I'll keep an eye out for your update on this point!

**Comment by jharenza** [comment]
I also wanted to note that the legend has `Normal` as a value for `display_group`, but I don't think that should be the case.

**Comment by jharenza** [comment]
>I am also thinking we may want to remove benign tumor, pre-cancerous lesion, non-CNS tumor, and non-tumor as well, but I will confirm this latter point tonight with @adamcresnick when we meet.

I wasn't able to meet with him, but let's go ahead and remove these.

**Comment by jaclyn-taroni** [comment]
Closing in favor of #1004 and #1005
