### ISSUE TITLE
Updated analysis: add recurrent fusions to oncoplot goi list

### ISSUE THREAD

**Issue by jharenza** [AlexsLemonade/OpenPBTA-analysis#977]
#### What analysis module should be updated and why?
oncoprint-landscape

#### What changes need to be made? Please provide enough detail for another participant to make the update.
Per discussion [here](https://github.com/AlexsLemonade/OpenPBTA-analysis/pull/975#issuecomment-811286554), I noticed that since we have recurrent SNVs and CNVs in our GOI lists, then it might follow that we add recurrent fusions or fused genes, which can be found in this [results folder](https://github.com/AlexsLemonade/OpenPBTA-analysis/tree/master/analyses/fusion_filtering/results). Since the recurrent fusion analysis was done per histology, and there are not very many, we could simply add [these genes](https://github.com/AlexsLemonade/OpenPBTA-analysis/blob/master/analyses/fusion_filtering/results/pbta-fusion-recurrently-fused-genes-byhistology.tsv) to our `goi` list. I can add a separate ticket for that since this is also beyond the initial ticket.

#### What input data should be used? Which data were used in the version being updated?
v18
[these genes](https://github.com/AlexsLemonade/OpenPBTA-analysis/blob/master/analyses/fusion_filtering/results/pbta-fusion-recurrently-fused-genes-byhistology.tsv)

#### When do you expect the revised analysis will be completed?
1 week

#### Who will complete the updated analysis?
@cbethell ?

**Comment by cbethell** [comment]
@jharenza, after taking another a look at this issue and #969, I now have the question of whether or not these issues will overlap. 

If the broad histology specific goi lists will be curated as noted in #969, should we go ahead and wait to include those lists? Will those lists include recurrent fusions or fused genes? Or should these recurrent fusions perhaps be added to the lists from #969 rather than the current goi lists we implement in this module?

**Comment by jharenza** [comment]
hmm, I think if we deprecate the full oncoprint, then this issue would no longer be valid and the genes with fusions (not fusions themselves) will be included within the gene list for #969 - is the plan to remove the full oncoprint?

**Comment by cbethell** [comment]
> hmm, I think if we deprecate the full oncoprint, then this issue would no longer be valid and the genes with fusions (not fusions themselves) will be included within the gene list for #969 - is the plan to remove the full oncoprint?

Good question @jharenza, I do not feel strongly about removing/retaining the full oncoprint. However, if we do retain the full oncoprint, would we also retain the current complete goi list (which we would add the genes with fusions to) or should we also update the goi list for the full oncoprint in accordance with #969, perhaps by compiling the histology goi lists?

**Comment by jaclyn-taroni** [comment]
I think our limited time is better spent on dropping the full oncoprint, with the understanding that we should not alter the code in a manner that makes it difficult to plot the full oncoprint, and focusing on #969 and #1004. Closing this.
