### ISSUE TITLE
Updated analysis: HGG subtyping sample selection on harmonized path_dx and path_free_text_dx

### ISSUE THREAD

**Issue by kgaonkar6** [AlexsLemonade/OpenPBTA-analysis#986]
#### What analysis module should be updated and why?
HGG subtyping module could be updated to use only the harmonized path_dx and path_free_txt_dx for selection across all samples.

#### What changes need to be made? Please provide enough detail for another participant to make the update.
In v18 the pathology diagnosis for all HGG samples was fully harmonized so will not need the hard code cohort based filtering here:

https://github.com/AlexsLemonade/OpenPBTA-analysis/blob/6bdd22b504016e09df0d2801d79c34ddd6d83026/analyses/molecular-subtyping-HGG/02-HGG-molecular-subtyping-subset-files.R#L143-L146

All PNOC003 samples have pathology_diagnosis == "Brainstem glioma- Diffuse intrinsic pontine glioma"  now.

#### What input data should be used? Which data were used in the version being updated?
pbta-histologies.tsv ; v18

#### When do you expect the revised analysis will be completed?
~1/2 day

#### Who will complete the updated analysis?
@kgaonkar6

**Comment by jharenza** [comment]
closed with #1021
