### ISSUE TITLE
Updated analysis: molecular subtyping LGAT: remove non LGG tumors

### ISSUE THREAD

**Issue by jharenza** [AlexsLemonade/OpenPBTA-analysis#995]
#### What analysis module should be updated and why?
molecular subtyping LGAT - after review of `pathology_free_text_diagnosis` contents with Cassie Kline, it was decided that we should remove a few samples from the LGAT module, as they belong within the `broad_histology` of `neuronal and mixed neuronal-glial tumors`

#### What changes need to be made? Please provide enough detail for another participant to make the update.
Remove the following samples with keywords in `pathology_free_text_diagnosis` from the LGAT subtyping module

pathology_diagnosis | subtyping module | pathology_free_text_diagnosis | broad_histology
-- | -- | -- | --
Low-grade glioma/astrocytoma (WHO grade I/II) | NA, remove from LGAT module | contains "desmoplastic infantile astrocytoma" | Neuronal and mixed neuronal-glial tumor
Low-grade glioma/astrocytoma (WHO grade I/II) | NA, remove from LGAT module | diffuse leptomeningeal glioneuronal tumor | Neuronal and mixed neuronal-glial tumor
Low-grade glioma/astrocytoma (WHO grade I/II) | NA, remove from LGAT module | contains "glioneuronal" | Neuronal and mixed neuronal-glial tumor
Low-grade glioma/astrocytoma (WHO grade I/II) | NA, remove from LGAT module | rosette forming glioneuronal tumor | Neuronal and mixed neuronal-glial tumor

#### What input data should be used? Which data were used in the version being updated?
`pbta-histologies.tsv`

#### When do you expect the revised analysis will be completed?
this week

#### Who will complete the updated analysis?
@kgaonkar6 or @jharenza

**Comment by jaclyn-taroni** [comment]
I'm assigning myself to this, as I assigned myself to #996 and they are related.

**Comment by jaclyn-taroni** [comment]
@jharenza what should I do in this case, where these samples would be included because `pathology_diagnosis == "Ganglioglioma"` but also excluded because `pathology_free_text_diagnosis` contains "glioneuronal"

```
# A tibble: 2 x 5
  Kids_First_Biospecimen_ID sample_id experimental_strategy pathology_diagnosis pathology_free_text_diagnosis                     
  <chr>                     <chr>     <chr>                 <chr>               <chr>                                             
1 BS_7N0B2CY1               7316-1985 RNA-Seq               Ganglioglioma       low grade glial-glioneuronal lesion. ganglioglioma
2 BS_B6KCJF2B               7316-1985 WGS                   Ganglioglioma       low grade glial-glioneuronal lesion. ganglioglioma
```

<details>
  <summary> Steps to reproduce </summary>
  
```R
library(tidyverse)
histologies_df <- readr::read_tsv(file.path("data", "pbta-histologies-base.tsv"))

histologies_df %>%
  filter(str_detect(str_to_lower(pathology_free_text_diagnosis), "glioneuronal"),
         str_detect(str_to_lower(pathology_diagnosis), "ganglioglioma")) %>%
  select(Kids_First_Biospecimen_ID,
         sample_id,
         experimental_strategy,
         pathology_diagnosis,
         pathology_free_text_diagnosis)

```
</details>

**Comment by jharenza** [comment]
For these cases, even though `Ganglioglioma` are glial-neuronal tumors, Cassie Kline had asked us to subtype them with the LGGs, but as a part of that subtyping, when we add the `short_histology`, they should be `Ganglioglioma` instead of LGAT, and should have `Ganglioglioma` as the prefix for `integrated_diagnosis` - I may have to check the latter.

**Comment by jharenza** [comment]
yes
