### ISSUE TITLE
Updated analysis: molecular subtyping pathology - JXG

### ISSUE THREAD

**Issue by jharenza** [AlexsLemonade/OpenPBTA-analysis#998]
#### What analysis module should be updated and why?
As outlined in #967, we would like to integrate some of the information in `pathology_free_text` diagnosis to the `integrated_diagnosis` or `harmonized_diagnosis`. For this ticket, we will further subtype `Other` tumors to `Juvenile xanthogranuloma` per the [WHO 2016 CNS subtypes](https://link.springer.com/content/pdf/10.1007/s00401-016-1545-1.pdf) based on information gathered from the pathology reports.

The following samples will be annotated here:
```
> v18 %>%
+   filter(grepl("xanthogranuloma|jxg", pathology_free_text_diagnosis)) %>%
+   select(pathology_free_text_diagnosis) %>%
+   distinct()
# A tibble: 2 x 1
  pathology_free_text_diagnosis           
  <chr>                                   
1 non- langerhans histiocytosis (jxg- cns)
2 xanthogranuloma 
```

#### What changes need to be made? Please provide enough detail for another participant to make the update.
If `pathology_diagnosis == Other` and `pathology_free_text_diagnosis` contains the below terms, then annotate as below:

pathology_diagnosis | subtyping module | pathology_free_text_diagnosis | broad_histology | short_histology | harmonized_diagnosis
-- | -- | -- | -- | -- | --
Other | NA | if contains "xanthogranuloma" or "jxg" | Histiocytic tumor | JXG | Juvenile xanthogranuloma

#### What input data should be used? Which data were used in the version being updated?
`pbta-histologies.tsv`

#### When do you expect the revised analysis will be completed?
this week?

#### Who will complete the updated analysis?
@kgaonkar6 or @jharenza

**Comment by kgaonkar6** [comment]
closed via #1056
