### ISSUE TITLE
Updated analysis: molecular subtyping pathology - lymphoma

### ISSUE THREAD

**Issue by jharenza** [AlexsLemonade/OpenPBTA-analysis#999]
#### What analysis module should be updated and why?
As outlined in #967, we would like to integrate some of the information in `pathology_free_text` diagnosis to the `integrated_diagnosis` or `harmonized_diagnosis`. For this ticket, we will further subtype `
` tumors to `CNS Burkitt's lymphoma` per the [WHO 2016 CNS subtypes](https://link.springer.com/content/pdf/10.1007/s00401-016-1545-1.pdf) based on information gathered from the pathology reports.

The below sample will be updated:
```
> v18 %>%
+   filter(pathology_diagnosis == "Primary CNS lymphoma") %>%
+   select(Kids_First_Biospecimen_ID, sample_id, pathology_free_text_diagnosis) %>%
+   distinct()
# A tibble: 2 x 3
  Kids_First_Biospecimen_ID sample_id pathology_free_text_diagnosis
  <chr>                     <chr>     <chr>                        
1 BS_0ZR4XA69               7316-1855 burkitt's lymphoma           
2 BS_1607397Q               7316-1855 burkitt's lymphoma           
```
#### What changes need to be made? Please provide enough detail for another participant to make the update.
If `pathology_diagnosis == Primary CNS lymphoma` and `pathology_free_text_diagnosis == burkitt's lymphoma` , update as below:

pathology_diagnosis | subtyping module | pathology_free_text_diagnosis | broad_histology | short_histology | harmonized_diagnosis
-- | -- | -- | -- | -- | --
Primary CNS lymphoma | NA | burkitt's lymphoma | Lymphoma | CNS lymphoma | CNS Burkitt's lymphoma

#### What input data should be used? Which data were used in the version being updated?
`pbta-histologies.tsv`

#### When do you expect the revised analysis will be completed?
this week?

#### Who will complete the updated analysis?
@kgaonkar6 or @jharenza

**Comment by kgaonkar6** [comment]
closed via #1057
